### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by yyzybb537** [gperftools/gperftools#1000]
The gperftools is very hard to build. I try many times, and also missing some symbols.
can you support CMake or vcpkg?

**Comment by alk** [comment]
I need more details. What OS? If you're building on unix system from source tarballs, it is should be just matter of ./configure && make

As for cmake and other option I personally don't have any plans for them.

**Comment by yyzybb537** [comment]
os： ubuntu16.04
$ ./configure CXXFLAGS='-fPIC' --enable-libunwind -enable-frame-pointers && make

I'd installed libunwind before.

Error info：
/bin/bash ./libtool  --tag=CXX   --mode=link g++ -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation  -fno-omit-frame-pointer  -fno-builtin -fPIC -pthread   -o debugallocation_test src/tests/debugallocation_test-debugallocation_test.o libtcmalloc_debug.la -lpthread
libtool: link: g++ -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -fsized-deallocation -fno-omit-frame-pointer -fno-builtin -fPIC -pthread -o .libs/debugallocation_test src/tests/debugallocation_test-debugallocation_test.o  ./.libs/libtcmalloc_debug.so -lpthread -pthread
./.libs/libtcmalloc_debug.so: undefined reference to `_ULx86_64_init_local'
./.libs/libtcmalloc_debug.so: undefined reference to `_Ux86_64_getcontext'
./.libs/libtcmalloc_debug.so: undefined reference to `_ULx86_64_get_reg'
./.libs/libtcmalloc_debug.so: undefined reference to `_ULx86_64_step'
collect2: error: ld returned 1 exit status
Makefile:3824: recipe for target 'debugallocation_test' failed
make: *** [debugallocation_test] Error 1

**Comment by alk** [comment]
Looks like you've installed libunwind in some non-standard path perhaps and then didn't use right flags to feed it to configure/make. Looks like CPPFLAGS are set correctly, not but LDFLAGS.

Comments on issue #528 should help you
