### ISSUE TITLE
How to call MallocExtension::instance()->ReleaseFreeMemory() from gdb?

### ISSUE THREAD

**Issue by pangqingyuan1991** [gperftools/gperftools#1003]
Hi,
My C (not C++) code is linked with -ltcmalloc with gcc(not g++) and it succeed. 
I want to call MallocExtension::instance()->ReleaseFreeMemory() from gdb, anyone know how to do it?

THanks!!

**Comment by alk** [comment]
Consider calling C version. See malloc_extension_c.h
