### ISSUE TITLE
Build error "msync not declared" on ubuntu trusty, when building on virtual box guest->host filesystem

### ISSUE THREAD

**Issue by pwinston** [gperftools/gperftools#1008]
I'm trying to compile gperftools-2.7 under ubuntu trusty. Under Vagrant on a mac.  When I configure gperftools-2.7 it confirms libunwind is installed, which I installed first.

But make in gperftools-2.7 gives these errors:
`src/heap-checker.cc: In static member function ‘static void HeapLeakChecker::IgnoreLiveObjectsLocked(const char*, const char*)’:
src/heap-checker.cc:1436:52: error: ‘MS_ASYNC’ was not declared in this scope
         if (msync(const_cast<char*>(object), size, MS_ASYNC) != 0) {
                                                    ^
src/heap-checker.cc:1436:60: error: ‘msync’ was not declared in this scope
         if (msync(const_cast<char*>(object), size, MS_ASYNC) != 0) {`

Am I missing a pre-requisite here?

**Comment by PpvAlx** [comment]
I have the same error on Ubuntu 18.04.1 LTS.

**Comment by alk** [comment]
I also tried docker thing for 18.04. I need someone to attach config.log to try to figure out what happened.

**Comment by alk** [comment]
Fresh VM of ubuntu trusty also has no issues building gperftools 2.7. I need more details about your setup.

**Comment by edhemphill** [comment]
ok - my tests are on Ubuntu 18.04 LTS Desktop...  I'll try to capture a configure.log later this week.

**Comment by edhemphill** [comment]
Here is a config.log of the issue. With gperftools 2.7 release.

This was specifically a vanilla install of Ubuntu 18.04.1 LTS 64-bit on VirtualBox. Only `build-essential` was installed after install.

[config.log](https://github.com/gperftools/gperftools/files/2711591/config.log)
[dpkg-l.log](https://github.com/gperftools/gperftools/files/2711597/dpkg-l.log)

**Comment by alk** [comment]
error code 6 is failing of mmap of file that is smaller than mapping length. Can you also give output of /proc/mounts and echo $HOME ? I think we should still get rid of testing mmap, but I would like to understand what is happening here.

**Comment by alk** [comment]
Great. This explains "breakage". You're building from directory mounted via vboxsf. I guess it is virtual box thingy that propagates host FS to guest. And apparently it does so in broken, or at least unexpected way.

I am not 100% sure about broken. autoconf code that checks for working mmap is arguably doing it wrong too. It creates files smaller than page size and tries to mmap entire first page. Apparently vboxfs doesn't like it. And I am not sure if it is correctly not liking it.

Anyways, I'll get rid of mmap testing

**Comment by edhemphill** [comment]
OK - totally get that @alk . `vboxsf` just has too many issue. Just as you wrote this I switched this box to using a NFS share from the guest.  Thanks for following up. Hopefully this helps others.

**Comment by alk** [comment]
Merged a fix.
