### ISSUE TITLE
'PT_NIP' was not declared - linux ppc64le

### ISSUE THREAD

**Issue by omron93** [gperftools/gperftools#1009]
Hi,
I'm building gperftools on linux ppc64le machine and I'm getting errors like this

```
src/stacktrace_powerpc-linux-inl.h:188:62: error: 'PT_NIP' was not declared in this scope
         result[n] = (void*) sigframe->uc.uc_mcontext.gp_regs[PT_NIP];
                                                              ^~~~~~
src/stacktrace_powerpc-linux-inl.h:188:62: note: suggested alternative: 'PT_NUM'
         result[n] = (void*) sigframe->uc.uc_mcontext.gp_regs[PT_NIP];
                                                              ^~~~~~
                                                              PT_NUM
```

It was working some time ago, but something changed. I'm trying to figure out what's wrong, but can't find how `PT_NIP` is defined in gperftools - how is `/usr/include/linux/ptrace.h` included? @alk Could you help please?

> gcc 8.1.1
> kernel-headers 4.17.0
> glibc-headers 2.27

**Comment by alk** [comment]
I am not not a ppc person. What version of gperftools is that? Can you pinpoint this problem to any specific change in gperftools ?

**Comment by omron93** [comment]
> What version of gperftools is that?

2.5 (it's bundled in mongodb database). I've tested it also with 2.6.3 and I working on ppc64le. So I guess this issue can be closed as it works in latest version.

> I almost sure it is related to https://sourceware.org/bugzilla/show_bug.cgi?id=21457 . We cleanup lot of architecture headers for GLIBC 2.27 which added a lot of identifiers not reserved by POSIX (such as PT_NIP). It means to get the old register definition for mcontext_t you will need to use build with _DEFAULT_SOURCE (_BSD_SOURCE || _SVID_SOURCE on GLBC prior of 2.24) or include the kernel header.

@zatrazz Thanks for the information and workaround! I wasn't able to find what is causing it...

**Comment by omron93** [comment]
> It means to get the old register definition for mcontext_t you will need to use build with _DEFAULT_SOURCE (_BSD_SOURCE || _SVID_SOURCE on GLBC prior of 2.24) or include the kernel header.

@zatrazz I probably get it wrong. So `_DEFAULT_SOURCE` has to be used when building glibc? (I thought that it concerns building gperftools)
