### ISSUE TITLE
Reg: Provision to get to know who used the corrupted memory before crash!

### ISSUE THREAD

**Issue by bkannadassan** [gperftools/gperftools#1011]
Hi All!

   I would like to know is it possible to track last 100/200 allocs and frees before crash ?. I tried writing a backtrace function inside the tc memory allocation module and it went into a loop. I could later see that backtrace does malloc and thats the reason it went into a loop. I know heapprofiler does a lot, but I don't want it that heavy. Since this runs for 2-3 days and then we observe corruption issue.

rgds
Balaji Kamal Kannadassan

**Comment by alk** [comment]
You're free to do whatever you want in malloc hooks. That is how heap checker is integrated to malloc. As for libc's backtrace, yes it mallocs. One way to handle it is by setting thread local variable indicating you're already inside your malloc hook.
