### ISSUE TITLE
PROFILE: interrupts/evictions/bytes = 0/0/64

### ISSUE THREAD

**Issue by stevenagy** [gperftools/gperftools#1012]
Hi,

I'm attempting to use gperftools' CPU profiler on a couple binaries. I was getting seemingly no profiling data, and after reading some posts here mentioning here that it may be due to the binary executing too quickly for any profiling to actually be done (e.g. `pprof --text binary prof` produces nothing), I added a call to `sleep(10)` in my target binary. This didn't help either. 

I'm asking here to inquire if there might be any other issues going on. I also cannot profile unless I use the `LD_PRELOAD` method described (adding `-lprofiler` to the compiler flags doesn't do anything, it seems).

Any ideas?

**Comment by ChasenYang** [comment]
The sampling time of the tool is 10ms, and the result can be correctly analyzed only when the processing time of the program is more than 10ms.

I
----
example:
$ time ./main
PROFILE: interrupts/evictions/bytes = 0/0/64

real    0m0.006s
user    0m0.001s
sys     0m0.005s
----
time ./main
PROFILE: interrupts/evictions/bytes = 0/0/64

real    0m0.006s
user    0m0.001s
sys     0m0.005s
----
pprof --text main pprof.log 
Using local file main.
Using local file pprof.log.
Removing killpg from all stack traces.
Total: 4 samples
       2  50.0%  50.0%        3  75.0% std::__unguarded_partition
       1  25.0%  75.0%        1  25.0% __gnu_cxx::__normal_iterator::base
       1  25.0% 100.0%        1  25.0% __gnu_cxx::__normal_iterator::operator*
       0   0.0% 100.0%        4 100.0% __libc_start_main
       0   0.0% 100.0%        4 100.0% main
       0   0.0% 100.0%        1  25.0% std::__final_insertion_sort
       0   0.0% 100.0%        3  75.0% std::__introsort_loop
       0   0.0% 100.0%        1  25.0% std::__unguarded_insertion_sort
       0   0.0% 100.0%        4 100.0% std::sort

**Comment by Cybroxtu** [comment]
My program runs for about 2 minutes, still get `PROFILE: interrupts/evictions/bytes = 0/0/64`...
But after add strace to monitor syscall, weirdly it begin to sample `PROFILE: interrupts/evictions/bytes = 150/3/9240`
Have no idea why...

**Comment by alk** [comment]
Closing then.
