### ISSUE TITLE
when Function execution time is too short, gperf can't detected

### ISSUE THREAD

**Issue by yeyichao** [gperftools/gperftools#1014]
I start a thread A in my main function after ProfilerStart, main join the thread A ,in thread A  just do one thing ,call function B and sleep 1 second then finished. function B is like for(int i = 0; i < 1000000; i++ ) ; return; I found use 1000000,gperf can detected, however ,when I usr less than 1000000, such as 100000, gperf can't detected. I use gettimeofday to Calculation the function B's execution time, 1000000 is about 0.005us, 100000 is about 0.002us.
so I want to know What preconditions are needed for gperf?

**Comment by yeyichao** [comment]
I have a mistake, not 0.005us but 0.005s

**Comment by alk** [comment]
You should read on up on how sampling profilers work. I am not able to suggest good place though.

In few words, the program is interrupted every few milliseconds and stack trace is captured. The idea is code running more often will be interrupted proportionally more often. So by aggregating stack traces we'll see hot parts etc.

So more you run, more samples you get, and more precise your profile becomes. I would say you need at least 1000 samples to see anything.

By default gperftools cpu profiler is using 100hz profiling frequency. I.e. every 10 ms of cpu time. So you should run your code at least 10 seconds. It is possible to raise profiling frequency (see docs), but note that it comes with increased profiling overhead.
