### ISSUE TITLE
How to clear thread cache freelists

### ISSUE THREAD

**Issue by obones** [gperftools/gperftools#1020]
Hello,

I have a program here, on Windows x64, that had performance issues with multi-threaded memory allocation and TCMalloc helped to greatly improve the situation.
From times to times, that same program uses a third party library that creates short lived threads at regular and frequent intervals. This worked well with the default memory allocator, but now that we use TCMalloc, we see a steady increase in system memory consumption. That increase can bring a computer to its knees if we let the program run overnight.

I used the `MallocExtension::GetStats` method to get a quick dump of the situation on a 3 minutes run, and have found the following:

```
------------------------------------------------
MALLOC:          76840 (    0.1 MiB) Bytes in use by application
MALLOC: +       827392 (    0.8 MiB) Bytes in page heap freelist
MALLOC: +       215096 (    0.2 MiB) Bytes in central cache freelist
MALLOC: +            0 (    0.0 MiB) Bytes in transfer cache freelist
MALLOC: +      2026400 (    1.9 MiB) Bytes in thread cache freelists
MALLOC: +      2752512 (    2.6 MiB) Bytes in malloc metadata
MALLOC:   ------------
MALLOC: =      5898240 (    5.6 MiB) Actual memory used (physical + swap)
MALLOC: +            0 (    0.0 MiB) Bytes released to OS (aka unmapped)
MALLOC:   ------------
MALLOC: =      5898240 (    5.6 MiB) Virtual address space used
MALLOC:
MALLOC:            165              Spans in use
MALLOC:             55              Thread heaps in use
MALLOC:           8192              Tcmalloc page size
------------------------------------------------
Call ReleaseFreeMemory() to release freelist memory to the OS (via madvise()).
Bytes released to the OS take up virtual address space but no physical memory.
```

This is shortly after starting using the third party library, and if I leave it running, the bytes in thread cache free lists keeps on growing:

```
MALLOC: +      3787776 (    3.6 MiB) Bytes in thread cache freelists
MALLOC:            101              Thread heaps in use
```

then again later on:
```
MALLOC: +     13970016 (   13.3 MiB) Bytes in thread cache freelists
MALLOC:            360              Thread heaps in use
```

So clearly, the increase in memory usage comes from the thread cache freelists. As suggested by the report, I called ``ReleaseFreeMemory`` but it does not change anything, the report returned by  ``GetStats`` still gives the same values.
It's as if TCMalloc does not see that the threads are dead and so decides not to release the memory associated to them. 

I understand that creating such short lived threads is not really clever, but having that third party library changed to use a thread pool will prove to be quite difficult.

This is why I'm wondering if there is something that I could do to make TCMalloc release the memory for threads that are dead, either immediately when they die, or at regular intervals via a method call.

Thanks for your help.

**Comment by obones** [comment]
Ok, this should be done automatically when the thread dies, and it works just fine in the 32 bits version.
I have found where in the `port.cc` file this is setup, I'm investigating and will send a pull request when I'm done.

**Comment by obones** [comment]
There you go:
https://github.com/gperftools/gperftools/pull/1022

Basically, the x64 PE loader is looking for callbacks in the const section which tcmalloc was not doing.

**Comment by alk** [comment]
I assume your commit fixes the problem?

**Comment by obones** [comment]
Yes, this fixes the issue, I have been using it in production since I made the pull request. 
Thanks for having merged it.
