### ISSUE TITLE
Why is the default kPageShift 13 is it ok to modify ?

### ISSUE THREAD

**Issue by bkannadassan** [gperftools/gperftools#1023]
#if defined(TCMALLOC_32K_PAGES)
static const size_t kPageShift  = 15;
#elif defined(TCMALLOC_64K_PAGES)
static const size_t kPageShift  = 16;
#else
static const size_t kPageShift  = 13;
#endif

For 32 and 64k understand 15/16. In my system pagesize is 4k so here we have default as 13 which is 8k is this because we can't support arrays mapping to pageid for >>12 ?. I would like to understand so is their no relation between what pagesize system supports to whats chosen ?. If so does making 15/16 I can get better performance ?. Btw I see that we use this shift to find the pageID, so since in my system 4k is the pagesize will 2 page fall into a single Span ?. 

$206 = {start = 18419, length = 1, next = 0x8029380, prev = 0x80250f0, objects = 0x8fe6fc0, refcount = 37, sizeclass = 10, location = 0, sample = 0}
(gdb) p (void **)0x8fe6fc0
$207 = (void **) 0x8fe6fc0
(gdb) p *$207
$208 = (void *) 0x8fe7050
(gdb) p (void **)$208
$209 = (void **) 0x8fe7050
(gdb) p *$209
$210 = (void *) 0x8fe70e0
(gdb) p tcmalloc::ThreadCache::threadlocal_data_.fast_path_heap.list_[10]
$211 = {list_ = 0x8fe7710, length_ = 12, lowater_ = 8, max_length_ = 128, length_overages_ = 1, size_ = 144}
(gdb) p /x 144
$212 = 0x90
(gdb) p /x 144 + 0x6fc0
$213 = 0x7050

Reason for asking above is I see we are having in span objects adjacent linked. If its going to be 2 page chunk will their be an impact on sorting and inserting while freeing ?. Can you clarify on how this is done so that it will help us to know the impact.

rgds
Balaji Kamal Kannadassan

**Comment by alk** [comment]
Those are logical pages. They're independent from hardware page size. Yes it is possible to modify this at compile time.

This is workload-dependent. Larger pages are typically little faster, but cause a little more fragmentation.

Closing since I think I answered your question.
