### ISSUE TITLE
Aggressive decommit now disabled by default

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [gperftools/gperftools#1025]
Hi,

In a commit from 2016 you decided to revert by default the aggressive decommit mode, the commit message mentions that this improves some tensorflows benchmarks. It still possible to define an environment variable or to set it in C/C++ through malloc extensions to enable it again.

First, do we know (with the current implementation, which apparently changed in 2016) in which case aggressive decommit is indeed slowing down performances (is it when I use a lot of small objects ? when do I a lot of big frees ? in some other kind of scenarios) ?

Our experience with our own Amadeus specific business processes is that we consume a lot more memory per process with and without aggressive decommit with exactly the same code (1GB vs 4GB in one specific workload, 1GB vs 2GB in another, 200MB vs 1.5GB in yet another different workload) while on the other side we couldn't see real performance degradation. So knowing exactly when this is useful would allow people to choose or not to enable it.

In our case, it looks like most if not all of our usages of tcmalloc would benefit from aggressive decommit (with a lot less consumed resident memory) without the drawback of being noticeably slower, so would you consider having a configure-time flag that would allow to switch the default behavior once and for all without having to modify all user programs/user environment ?

Cheers,
Romain

**Comment by alk** [comment]
Correct. Default is off now. Some workloads do see performance drop from aggressive decommit. And yes, I'll accept patch for build- or configure-time switch.

**Comment by alk** [comment]
As for which workloads get slower, well, I don't have good answer for you. Those the exercise freeing pages into page heap is kind obvious but not helpful answer. I cannot say more specific.

**Comment by HolyWu** [comment]
This issue could be closed since https://github.com/gperftools/gperftools/commit/5574c87e39ee592c909cb48245c1d91e90ddaf4d.
