### ISSUE TITLE
Why use heap_lock.TryLock() at HeapProfilerDumpSignal rather than SpinLockHolder?

### ISSUE THREAD

**Issue by wuttqq** [gperftools/gperftools#1040]
when i use HeapProfilerDumpSignal to dump heap.
Sometimes i can not get heap log by HeapProfilerDumpSignal.
Is it by design?

**Comment by alk** [comment]
This is because thread handling the signal might have the lock. This entire HeapProfilerDumpSignal thingy is somewhat inherently unsafe. And TryLock is how it avoids deadlocking.
