### ISSUE TITLE
why core in FetchFromSpans when calling protobuf  ParseFromString(gperftools-2.0)

### ISSUE THREAD

**Issue by wuzhiguocarter** [gperftools/gperftools#1041]
Here are bt of my coredump file
#0  tcmalloc::CentralFreeList::FetchFromSpans (this=this@entry=0x17e2b00 <tcmalloc::Static::central_cache_+4864>) at src/central_freelist.cc:298
#1  0x0000000000bce5b9 in tcmalloc::CentralFreeList::FetchFromSpansSafe (this=this@entry=0x17e2b00 <tcmalloc::Static::central_cache_+4864>) at src/central_freelist.cc:283
#2  0x0000000000bce643 in tcmalloc::CentralFreeList::RemoveRange (this=0x17e2b00 <tcmalloc::Static::central_cache_+4864>, start=start@entry=0x7f8dfa924ad0, 
    end=end@entry=0x7f8dfa924ad8, N=32) at src/central_freelist.cc:263
#3  0x0000000000bd0983 in tcmalloc::ThreadCache::FetchFromCentralCache (this=this@entry=0xfdb252780, cl=<optimized out>, byte_size=48) at src/thread_cache.cc:162
#4  0x00000000010e24d8 in Allocate (cl=<optimized out>, size=<optimized out>, this=0xfdb252780) at src/thread_cache.h:341
#5  do_malloc (size=<optimized out>) at src/tcmalloc.cc:1068
#6  cpp_alloc (nothrow=false, size=40) at src/tcmalloc.cc:1354
#7  tc_new (size=40) at src/tcmalloc.cc:1530
#8  0x000000000090ce1a in google::protobuf::internal::GenericTypeHandler<route_feature::LinkFreqStruct>::New() ()

**Comment by alk** [comment]
That happens when your app has memory management bugs. Like double free or dangling pointer writes, etc. Consider debugging it using asan/msan/valgrind etc.
