### ISSUE TITLE
How to use tc_malloc partially? 

### ISSUE THREAD

**Issue by fun2199** [gperftools/gperftools#1045]
Platform:  Visual Studio 2010.  
Purpose:  My program(exe) uses several DLLs. I just want one DLL to use tc_malloc . 

Test :
1.  DLL :  add  "libtcmalloc_minimal.lib" /INCLUDE:"__tcmalloc" .    and this DLL output a function to test whether tc_malloc is working.
void func()
{
  for (size_t i = 1; i < COUNT; ++i)
  {
    int * pInt = (int*)malloc(i * sizeof(int));
    free(pInt);
  }
}
2. EXE:  load the DLL through LoadLibrary(),  get address of  func() and run it (It is sure the tc_malloc is working). 
Then the problem comes when I free the DLL through FreeLibrary() which is a  access violation in exe (0xC0000005).  It seems failed to recover the original fn contents, as it get lost in this function. 
       BOOL rv = ((BOOL (WINAPI *)(HMODULE))function_info_[kFreeLibrary].origstub_fn)(hLibModule);

Is there a way to Unpatch ?

**Comment by alk** [comment]
There is no way to unpatch. But there is way to disable patching entirely. Latest git code now has build option that overrides allocation functions. You'll need to link this kind of code statically to your dll and you'll be done.

**Comment by fun2199** [comment]
It sounds much more convenient to disable patching entirely in WIN32_OVERRIDE_ALLOCATORS mode. 
Thank you very much for your answering.

**Comment by fun2199** [comment]
> There is no way to unpatch. But there is way to disable patching entirely. Latest git code now has build option that overrides allocation functions. You'll need to link this kind of code statically to your dll and you'll be done.

It sounds much more convenient to disable patching entirely in WIN32_OVERRIDE_ALLOCATORS mode.
Thank you very much for your answering.

**Comment by alk** [comment]
Not sure what you're referring to, but WIN32_OVERRIDE_ALLOCATORS is exactly mode that isn't patching anything.

**Comment by fun2199** [comment]
>  " Latest git code now has build option that overrides allocation functions. You'll need to link this kind of code statically to your dll and you'll be done. "

Do you mean there is way to replace specific allocation function ?  Such as the allocation functions in one of my DLLs ? 
And which kind of code should I link to my dll ?

**Comment by weiqiangguo** [comment]
hi @fun2199, I have also encountered the same problem. how do you solve this problem

**Comment by obones** [comment]
Maybe you could have a look at this issue: https://github.com/gperftools/gperftools/issues/1078

**Comment by alk** [comment]
Most recent visual studio solution that we ship contains Release-Override config that should do it.
