### ISSUE TITLE
How to enable heap profiler in a running process?

### ISSUE THREAD

**Issue by wakakalu** [gperftools/gperftools#1047]
Hi,
I started a process several days ago. At the beginning, it seems normal. But after running for several days, it's memory grows larger and larger and I suspect there is memory leak in it.

I used LD_PRELOAD environment variable to load tcmalloc when starting my program but I didn't set HEAPPROFILE environment variable so I cannot inspect the memory allocation now.  If I set the HEAPPROFILE and restart my process, the memory of the process will return to normal size.

Is there any way to enable the heap profiler of a running process?

Thanks!

**Comment by alk** [comment]
This is fundamental limitation of heap checker & profiler implementation. Closing as won't fix.
