### ISSUE TITLE
heap profiler shows no memory usage

### ISSUE THREAD

**Issue by tst-basilhuffman** [gperftools/gperftools#1061]
When running the heap profiler (c++ application) and checking the data with pprof, all the function/method calls are displayed.  However, the memory usage (columns 1 & 4) show 0.0.  Percentages are shown in columns 2,3,5 but I am unsure of how these percentages are calculated and what they mean in the context of 0.0MB memory usage.

**Comment by alk** [comment]
We're not supporting (perl-based) pprof version that is included with gperftools. Please use modern pprof implementation from github.com/google/pprof
