### ISSUE TITLE
Memory in central cache freelist not release back to os

### ISSUE THREAD

**Issue by dl239** [gperftools/gperftools#1062]
memory in central cache freelist not release back to os
<img width="577" alt="wx20181022-183259 2x" src="https://user-images.githubusercontent.com/6183996/47288553-2ce4de80-d629-11e8-87ec-0edd21c7913a.png">
How to release them back to os

My version is 2.5

**Comment by alk** [comment]
Yes, memory in central free list is not possible to return back to kernel. If you can describe your workloads a bit more, maybe I will be able to advice some ways to reduce impact.

Please reopen with more details. Closing as won't fix as such slab-ful memory management is "conscious design choice" behind tcmalloc (and jemalloc too).

**Comment by hsepeng** [comment]
we suffer the same problems of huge central cache freelist not release back to os @alk , is there a solution to shrink it down?

**Comment by jh244212647** [comment]
we have same problems, huge central cache not release to os, @alk . is there a solution?
