### ISSUE TITLE
cpu profiler doesn't work correctly in multi-thread programming.

### ISSUE THREAD

**Issue by flame4** [gperftools/gperftools#1063]
Hi, My os is centos7 and i test gperftools using std::thread in c++11, but the result is confused!

My program:

#include <google/profiler.h>
#include <thread>
#include <vector>
#include <iostream>
#include <unistd.h>
#include <mutex>
std::mutex m;
void t(int id) {
    ProfilerRegisterThread();
    ProfilerStart("test.prof"); // test.prof is the name of profile file
    for(int i = 0; i < 1000; ++i){}
    m.lock();
    std::cout << "i'm thread " << id << std::endl;
    m.unlock();
    ProfilerStop();
}

void test() {
    std::vector<std::thread> pool;
    for(int i = 0; i < 10; ++i) {
        pool.push_back(std::thread(t, i));
    }
    for(int i = 0; i < 10; ++i) {
        pool[i].join();
    }
    sleep(2);
}

int main() {
    test();
    return 0;
}

And use cmake to compiler it.
CMAKE:

cmake_minimum_required(VERSION 2.8)

project (testperf)

SET(CMAKE_CXX_FLAGS_DEBUG "-W -Wextra -fPIC -lpthread -std=c++11 -O0 -g -gstabs+")
MESSAGE(STATUS "CMAKE_BUILD_FLAGS is ${CMAKE_CXX_FLAGS_DEBUG}")

ADD_EXECUTABLE(testperf test.cpp)

INCLUDE_DIRECTORIES(MY LIBUNWIND PATH)
INCLUDE_DIRECTORIES(MT GPERFTOOLS PATH) #unwind gperftools-2.0

FIND_LIBRARY(PTHREAD_LIB NAMES pthread PATHS "/usr/lib64")
MESSAGE(STATUS "Library path PTHREAD_LIB is " ${PTHREAD_LIB})
FIND_LIBRARY(UNWIND_LIB NAMES unwind PATHS MY LIBUNWIND PATH)
MESSAGE(STATUS "Library path UNWIND_LIB is " ${UNWIND_LIB})
FIND_LIBRARY(PROFILER_LIB NAMES profiler PATHS MY GPERFTOOLS PATH)
MESSAGE(STATUS "Library path PROFILER_LIB is " ${PROFILER_LIB})

TARGET_LINK_LIBRARIES(testperf ${PTHREAD_LIB})
TARGET_LINK_LIBRARIES(testperf ${UNWIND_LIB})
TARGET_LINK_LIBRARIES(testperf ${PROFILER_LIB})

SET(EXECUTABLE_OUTPUT_PATH ${PROJECT_BINARY_DIR}/bin)

it can compile and run. 
At the same time, i set  CPUPROFILE="/tmp/prof.out". 

After run the binary, i get a /tmp/prof.out output which is not empty, but only has the tail address information. The binary header is empty!

I don't know why, please help me.

**Comment by alk** [comment]
Your program finishes too quickly. gperftools profiler needs at least several seconds of cpu time to get you profiler of at least some precision. Closing as won't fix.
