### ISSUE TITLE
Tests fails at win10 vs2015 Release-patch x64

### ISSUE THREAD

**Issue by ViktorRoy94** [gperftools/gperftools#1064]
Hi
I built gpertools.sln in Visual Studio 2015 in Release-patch configuration x64 and tried run tests but they all failed with that exception
(Exception thrown at 0x0000000000000000 in current_allocated_bytes_test.exe: 0xC0000005: Access violation executing location 0x0000000000000000.)

I tried debug and found out place where exception showed up:

path_fucntions.cc
string 945
LPVOID WINAPI WindowsInfo::Perftools_HeapAlloc(HANDLE hHeap, DWORD dwFlags,
                                               DWORD_PTR dwBytes) {
  LPVOID result = ((LPVOID (WINAPI *)(HANDLE, DWORD, DWORD_PTR))
                   function_info_[kHeapAlloc].origstub_fn)(
                       hHeap, dwFlags, dwBytes);
  MallocHook::InvokeNewHook(result, dwBytes); <--- Here exception
  return result;
}
string 954

Static link in Release-Override x64 configuration pass all tests easy.

**Comment by alk** [comment]
Hm. Very odd. Nothing like this ever happened on my windows testing VMs or machines. I routinely test with vs2015 thingy too. Perhaps you can disassemble crash place and provide stacktrace ?
