### ISSUE TITLE
getgrouplist() causing the fault for a tcmalloc library linked program. 

### ISSUE THREAD

**Issue by RanjitKumarReddy** [gperftools/gperftools#1065]
Hi,

While using the tcmalloc with a simple c program which calls  getgrouplist() function,  causing the SEGV.

Is this existing issue?

In the core dump, i found that its trying to free a tcmalloc created memory using glibc free instead of tcmalloc free. Am i missing something here? Because my program working fine when i didn;t use the getgrouplist().

```
(gdb) bt
#0  0x00007ffff76d56c5 in raise () from /lib64/libc.so.6
#1  0x00007ffff76d6ca1 in abort () from /lib64/libc.so.6
#2  0x00007ffff771612f in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff771b948 in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff77209bc in free () from /lib64/libc.so.6
#5  0x00007ffff6b1cac8 in init () from /lib64/libnsl.so.1
#6  0x00007ffff6b1cc4b in _nsl_default_nss () from /lib64/libnsl.so.1
#7  0x00007ffff6d2aefe in _nss_compat_initgroups_dyn () from /lib64/libnss_compat.so.2
#8  0x00007ffff7747d58 in internal_getgrouplist () from /lib64/libc.so.6
#9  0x00007ffff7747ffd in getgrouplist () from /lib64/libc.so.6
#10 0x0000000000400a58 in main (argc=3, argv=0x7fffffffde28) at getgrouplist.c:37
```

Thank you,
Ranjit

**Comment by RanjitKumarReddy** [comment]
http://man7.org/linux/man-pages/man3/getgrouplist.3.html

I've used the example program mentioned in above man page. In case if you want to reproduce.

**Comment by RanjitKumarReddy** [comment]
After digging little deeper, i've found that the allocated memory is created by libc.

Function: _IO_getdelim

```
ssize_t
_IO_getdelim (char **lineptr, size_t *n, int delimiter, FILE *fp)
{
--

  if (*lineptr == NULL || *n == 0)
    {
      ***n = 120;
      *lineptr = (char *) malloc (*n);**
      if (*lineptr == NULL)

---
}

weak_alias (_IO_getdelim, __getdelim)
weak_alias (_IO_getdelim, getdelim)
```

**Comment by alk** [comment]
This looks like it could be bug in your libc. Both malloc and free should be used from gperftools. What are exact versions used ?

Can you please post sample program that causes crash ?
