### ISSUE TITLE
when my server destory, tcmalloc lead to crash

### ISSUE THREAD

**Issue by AzureSky2013** [gperftools/gperftools#1070]
@alk 
i need your help!!
#0  tcmalloc::SLL_PopRange (end=<synthetic pointer>, start=<synthetic pointer>, N=30, head=0x2d89c80) at ../src/linked_list.h:88
#1  tcmalloc::ThreadCache::FreeList::PopRange (end=<synthetic pointer>, start=<synthetic pointer>, N=30, this=0x2d89c80) at ../src/thread_cache.h:238
#2  tcmalloc::ThreadCache::ReleaseToCentralCache (this=this@entry=0x2d89c40, src=src@entry=0x2d89c80, cl=cl@entry=2, N=30) at ../src/thread_cache.cc:206
#3  0x0000000001f90438 in tcmalloc::ThreadCache::Scavenge (this=0x2d89c40) at ../src/thread_cache.cc:224
#4  0x00000000017259f1 in __gnu_cxx::new_allocator<MapGridLite>::deallocate (this=0x150f2348, __p=0x15100000) at /usr/include/c++/6.1.0/ext/new_allocator.h:110
#5  0x0000000001723b28 in std::allocator_traits<std::allocator<MapGridLite> >::deallocate (__a=..., __p=0x15100000, __n=36) at /usr/include/c++/6.1.0/bits/alloc_traits.h:442
#6  0x0000000001721f53 in std::_Vector_base<MapGridLite, std::allocator<MapGridLite> >::_M_deallocate (this=0x150f2348, __p=0x15100000, __n=36) at /usr/include/c++/6.1.0/bits/stl_vector.h:178
#7  0x000000000172780d in std::_Vector_base<MapGridLite, std::allocator<MapGridLite> >::~_Vector_base (this=0x150f2348, __in_chrg=<optimized out>) at /usr/include/c++/6.1.0/bits/stl_vector.h:160
#8  0x0000000001726730 in std::vector<MapGridLite, std::allocator<MapGridLite> >::~vector (this=0x150f2348, __in_chrg=<optimized out>) at /usr/include/c++/6.1.0/bits/stl_vector.h:427
#9  0x00000000017252be in std::_Destroy<std::vector<MapGridLite, std::allocator<MapGridLite> > > (__pointer=0x150f2348) at /usr/include/c++/6.1.0/bits/stl_construct.h:93
#10 0x0000000001723382 in std::_Destroy_aux<false>::__destroy<std::vector<MapGridLite, std::allocator<MapGridLite> >*> (__first=0x150f2348, __last=0x150f2600) at /usr/include/c++/6.1.0/bits/stl_construct.h:103
#11 0x000000000172174c in std::_Destroy<std::vector<MapGridLite, std::allocator<MapGridLite> >*> (__first=0x150f2300, __last=0x150f2600) at /usr/include/c++/6.1.0/bits/stl_construct.h:126
#12 0x000000000171fc09 in std::_Destroy<std::vector<MapGridLite, std::allocator<MapGridLite> >*, std::vector<MapGridLite, std::allocator<MapGridLite> > > (__first=0x150f2300, __last=0x150f2600)
    at /usr/include/c++/6.1.0/bits/stl_construct.h:151
#13 0x000000000171e9ee in std::vector<std::vector<MapGridLite, std::allocator<MapGridLite> >, std::allocator<std::vector<MapGridLite, std::allocator<MapGridLite> > > >::~vector (this=0x15058628, __in_chrg=<optimized out>)
    at /usr/include/c++/6.1.0/bits/stl_vector.h:426
#14 0x000000000171596d in MapBaseLite::~MapBaseLite (this=0x15058620, __in_chrg=<optimized out>) at /data/source/fengshen/trunk/src/sGame/ai/lite/MapBaseLite.cpp:38
#15 0x00000000017159ab in MapBaseLite::~MapBaseLite (this=0x15058620, __in_chrg=<optimized out>) at /data/source/fengshen/trunk/src/sGame/ai/lite/MapBaseLite.cpp:50
#16 0x000000000171df0f in MapBaseLite::release (this=0x15058620) at /data/source/fengshen/trunk/src/sGame/ai/lite/MapBaseLite.h:30
#17 0x000000000171212d in MapManagerLite::~MapManagerLite (this=0xde3bb00, __in_chrg=<optimized out>) at /data/source/fengshen/trunk/src/sGame/ai/lite/MapManagerLite.cpp:19
#18 0x0000000001786a7c in MapManagerLite::release (this=0xde3bb00) at /data/source/fengshen/trunk/src/sGame/ai/lite/MapManagerLite.h:28
#19 0x00000000017859c7 in AIService::destroy (this=0x4a110e0) at /data/source/fengshen/trunk/src/sGame/ai/AIService.cpp:25
#20 0x00000000017858e7 in AIService::~AIService (this=0x4a110e0, __in_chrg=<optimized out>) at /data/source/fengshen/trunk/src/sGame/ai/AIService.cpp:19
#21 0x0000000001785945 in AIService::~AIService (this=0x4a110e0, __in_chrg=<optimized out>) at /data/source/fengshen/trunk/src/sGame/ai/AIService.cpp:20
#22 0x000000000102c6d1 in AIService::release (this=0x4a110e0) at /data/source/fengshen/trunk/src/sGame/ai/AIService.h:34
#23 0x000000000101b63d in __MyServer::destroy (this=0x3650500) at /data/source/fengshen/trunk/src/sGame/MyServer.cpp:200
#24 0x000000000101e5f6 in daemon_end () at /data/source/fengshen/trunk/src/sGame/MyServer.cpp:605
#25 0x000000000101e87f in main () at /data/source/fengshen/trunk/src/sGame/MyServer.cpp:645

operating system
centos x86-64 6.5 
myserver static link all libs, such as libevent, libcurl, libstdc++, and so on, and mulit-thread application  
and i followed INSTALL and README to compile all libraries with -fno-omit-frame-pointer except libstdc++,   
how to resolve this problem?  compiling the gcc with -fno-omit-frame-pointer can fix it?

**Comment by AzureSky2013** [comment]
it never crash without using tcmalloc, after using tcmalloc, it will crash by 5% probility!

**Comment by foreverhui** [comment]
> it never crash without using tcmalloc, after using tcmalloc, it will crash by 5% probility!


I encountered the same problem, did you solve it？my program never crash without using tcmalloc, after using tcmalloc, it will crash.

**Comment by alk** [comment]
Crashes like that are normally bugs in a program. Things like double free or writing to freed memory. It may work ~fine in other mallocs or not. And some bugs could also crash other mallocs and not tcmalloc, it will depend on numerous factors. But by default bugs like that we ignore since we just have to assume it is bugs in program. If however you're able to prove that we somehow messed up tcmalloc itself, then please let us know.
