### ISSUE TITLE
unable to build profiler on power (ppc64le) with gcc-7

### ISSUE THREAD

**Issue by clnperez** [gperftools/gperftools#1074]
Trying to compile with ppc64le works fine if I'm using a debian-based distro. On fedora, though, I get this from the configure output:

`checking how to access the program counter from a struct ucontext... configure: WARNING: Could not find the PC.  Will not try to compile libprofiler... `

I set up two f28 containers (ppc64le and x86_64), each with the same installed packages, to compare the configure output between the two architectures. Everything in the output is identical up until that point, so I am stuck. Any suggestions?

**Comment by clnperez** [comment]
I updated the title of this. I hit it on Ubuntu 18.04, but don't on 16.04 -- so I think it's a compiler problem.

**Comment by laboger** [comment]
Adding @tuliom
