### ISSUE TITLE
Running the CPU profiler on an iPhone

### ISSUE THREAD

**Issue by michaeleisel** [gperftools/gperftools#1075]
In the instructions, it says to run the executable using `pprof` to do CPU profiling. However, due to iOS sandbox restrictions, I can't do this on a real iPhone (I have no control over the command to execute the program and I can't use functions like `execv`). How can I work around this and do CPU profiling?

**Comment by alk** [comment]
it might be possible to get profile data to your workstation and then point pprof tool (from github.com/google/pprof to profile and binary). There might be some tweaks necessary to give it right binutils (I haven no idea how apples does things), but it should be possible in principle.

Note, I am not actually sure if libprofiler actually works on ios.
