### ISSUE TITLE
heap profiler slow in arm cpu 

### ISSUE THREAD

**Issue by chwma** [gperftools/gperftools#1077]
**Platform**: arm64 Cortex-A57
**Operating** System: linux
**free memory**: 1G
**all memroy**: 4G

don't heap profiler:
  begin time: Sun Nov 18 22:56:11 UTC 2018
  end time:    Sun Nov 18 22:56:18 UTC 2018
  cost: 7s

do heap profiler:
  begin time: Sun Nov 18 22:39:01 UTC 2018
  end time:    Sun Nov 18 22:48:53 UTC 2018
  cost: 532s

Why is the difference so big?

**Comment by alk** [comment]
Heap profiler is just inherently very slow. Won't be fixed. Sorry.
