### ISSUE TITLE
The link to a google newsgroup post inside windows\config.h is unreachable

### ISSUE THREAD

**Issue by obones** [gperftools/gperftools#1078]
When building for Windows, one can control the results via the config.h file.
Inside that file, there is this comment: 
https://github.com/gperftools/gperftools/blob/e9ab4c53041ac62feefbbb076d326e9a77dd1567/src/windows/config.h#L24

However, the associated link is unreachable to many which does not allow understanding what needs to be done.
I believe I found a solution and posted it on the stackoverflow question that mentioned that same comment:
https://stackoverflow.com/questions/39577554/safest-way-to-link-googles-tcmalloc-lib/54201847#54201847

If someone in the dev team has access to the original newsgroup post, would it be possible to change the comment to include the entire original text?
If not, could at least someone confirm the findings I reported at SO?

Thanks

**Comment by alk** [comment]
I did ask internally at some point without any effect. I think we can assume this is gone forever.

But the good news is that recent code now contains configuration 'Release-Override' that does mostly same.
