### ISSUE TITLE
OS X (Mojave) only display address when using pprof

### ISSUE THREAD

**Issue by PhoebeWangintw** [gperftools/gperftools#1086]
Hi,
I'm currently using the [latest version](https://github.com/gperftools/gperftools/commit/9e5b1628737c67b4587f937164572774592978c4) of gperftools installed from GitHub. However, when using pprof, I only get the output with address, which looks like this:
```bash
Total: 3 samples
       2  66.7%  66.7%        2  66.7% 0x000000010fe3cee9
       1  33.3% 100.0%        1  33.3% 0x00007fff691b5c09
       0   0.0% 100.0%        2  66.7% 0x000000010fe3cf30
       0   0.0% 100.0%        2  66.7% 0x000000010fe3cf72
       0   0.0% 100.0%        1  33.3% 0x000000010fe3d007
       0   0.0% 100.0%        2  66.7% 0x00007fd241402ac7
       0   0.0% 100.0%        3 100.0% 0x00007fff691c9ed8
       0   0.0% 100.0%        3 100.0% __mh_execute_header
```

I compiled and executed my file like this:
```bash
$ g++ test.cpp -lprofiler
$ ./a.out
$ pprof -text ./a.out my.prof > output.txt
```
I googled this problem everywhere, but I couldn't find a good solution.
I would greatly appreciate if someone could help me. Thank you!

**Comment by alk** [comment]
We're not supporting (perf version of) pprof that is included with gperftools. Take modern golang implementation at github.com/google/pprof.

Closing as won't fix.
