### ISSUE TITLE
SIGPROF cause zeromq recv() raise EINTR

### ISSUE THREAD

**Issue by Crystal8** [gperftools/gperftools#1089]
I came across a problem, when I ran gperftools with ProfilerStart() and ProfilerStop() in my project, which using  zeromq. It would throw "EINTR" when zmq::recv() receives the SIGPROF signal in it's progress. So I tried to block SIGPROF in every threads except the main thread. It came out that the cpu-profiler would not profile the other threads info. Do I miss something ?
@alk

**Comment by alk** [comment]
Any syscall is expected to return EINTR from time to time and user space code is supposed to always deal with it. So in this case there is nothing gperftools can do. Closing as won't fix. zmq thingy should be fixed to deal with EINTR.
