### ISSUE TITLE
segfault on LuaJIT2

### ISSUE THREAD

**Issue by chipitsine** [gperftools/gperftools#1090]
hello,

it is "known" that google perf tools break LuaJIT2
at least openresty developers say so: https://github.com/openresty/lua-nginx-module/issues/1487

any idea why that happens ?

**Comment by alk** [comment]
In call stack in the ticket mentioned above, it is obvious that libgcc-based backtrace capturing is used. Which is not actually safe to use from signal handlers. It is good enough for heap profiler and such, but not cpu profiler. You're likely to have better results with libunwind. Just make sure libunwind is installed before you run configure.
