### ISSUE TITLE
Using Tcmalloc in MPI program cause Reduce or AllReduce operation can't Complete 

### ISSUE THREAD

**Issue by LoveSiGua** [gperftools/gperftools#1093]
A very strange problem showed up today in my MPI program.

If I use Tcmalloc in my MPI program , a simplified code is like:

#define LENGTH=1000000
double * data = (double *)malloc(LENGTH* sizeof(double));
MPI_Allreduce(MPI_IN_PLACE，&data[0], LENGTH,MPI_SUM, MPI_COMM_WORLD);

the Allreduce operation can't proceed if the LENGTH>4096。

if my MPI program don’t use Tcmalloc，then it will proceed like usual。I don‘t know what happened， can anybody give me some advice？

**Comment by alk** [comment]
Sorry, unable to advise about your specific case. If there is bug in tcmalloc we'll need more detailed info or a way to reproduce.
