### ISSUE TITLE
TCmalloc DeadLock between func InsertRange() and RemoveRange()

### ISSUE THREAD

**Issue by leonwu327** [gperftools/gperftools#1094]
#0  0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
#1  0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
#2  0x00007f333cb5a492 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
#3  0x00007f333cb5d2a7 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int) () from /lib64/libtcmalloc.so.4

#0  0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
#1  0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
#2  0x00007f333cb5a492 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
#3  0x00007f333cb5d2a7 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int) () from /lib64/libtcmalloc.so.4

#0  0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
#1  0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
#2  0x00007f333cb59fdc in tcmalloc::CentralFreeList::InsertRange(void*, void*, int) () from /lib64/libtcmalloc.so.4
#3  0x00007f333cb5d460 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) () from /lib64/libtcmalloc.so.4
#4  0x00007f333cb5d81c in tcmalloc::ThreadCache::ListTooLong(tcmalloc::ThreadCache::FreeList*, unsigned int) () from /lib64/libtcmalloc.so.4

#0  0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
#1  0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
#2  0x00007f333cb59fdc in tcmalloc::CentralFreeList::InsertRange(void*, void*, int) () from /lib64/libtcmalloc.so.4
#3  0x00007f333cb5d460 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) () from /lib64/libtcmalloc.so.4
#4  0x00007f333cb5d81c in tcmalloc::ThreadCache::ListTooLong(tcmalloc::ThreadCache::FreeList*, unsigned int) () from /lib64/libtcmalloc.so.4

#0  0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
#1  0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
#2  0x00007f333cb59fdc in tcmalloc::CentralFreeList::InsertRange(void*, void*, int) () from /lib64/libtcmalloc.so.4
#3  0x00007f333cb5d460 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) () from /lib64/libtcmalloc.so.4
#4  0x00007f333cb5d798 in tcmalloc::ThreadCache::Scavenge() () from /lib64/libtcmalloc.so.4

#0  0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
#1  0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
#2  0x00007f333cb5a492 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
#3  0x00007f333cb5d2a7 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int) () from /lib64/libtcmalloc.so.4
#4  0x00007f3331df63b2 in ceph::BackTrace::print (this=this@entry=0x7f330658f8e0, out=...) at /usr/src/debug/ceph-12.2.7-809-g56cc656/src/common/BackTrace.cc:39
#5  0x000055eccb1ad74d in handle_fatal_signal (signum=11) at /usr/src/debug/ceph-12.2.7-809-g56cc656/src/global/signal_handler.cc:119
#6  <signal handler called>
#7  0x00007f333cb5a05d in tcmalloc::CentralFreeList::FetchFromOneSpans(int, void**, void**) () from /lib64/libtcmalloc.so.4
#8  0x00007f333cb5a31a in tcmalloc::CentralFreeList::FetchFromOneSpansSafe(int, void**, void**) () from /lib64/libtcmalloc.so.4
#9  0x00007f333cb5a3d0 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
#10 0x00007f333cb5d2a7 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int) () from /lib64/libtcmalloc.so.4

#0  0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
#1  0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
#2  0x00007f333cb59fdc in tcmalloc::CentralFreeList::InsertRange(void*, void*, int) () from /lib64/libtcmalloc.so.4
#3  0x00007f333cb5d460 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) () from /lib64/libtcmalloc.so.4
#4  0x00007f333cb5d798 in tcmalloc::ThreadCache::Scavenge() () from /lib64/libtcmalloc.so.4

#0  0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
#1  0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
#2  0x00007f333cb59fdc in tcmalloc::CentralFreeList::InsertRange(void*, void*, int) () from /lib64/libtcmalloc.so.4
#3  0x00007f333cb5d460 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) () from /lib64/libtcmalloc.so.4
#4  0x00007f333cb5d798 in tcmalloc::ThreadCache::Scavenge() () from /lib64/libtcmalloc.so.4

**Comment by alk** [comment]
This is not exactly deadlock. More interesting thing.

So this thread is the one "deadlocked" with itself.

#0 0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
#1 0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
#2 0x00007f333cb5a492 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
#3 0x00007f333cb5d2a7 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int) () from /lib64/libtcmalloc.so.4
#4 0x00007f3331df63b2 in ceph::BackTrace::print (this=this@entry=0x7f330658f8e0, out=...) at /usr/src/debug/ceph-12.2.7-809-g56cc656/src/common/BackTrace.cc:39
#5 0x000055eccb1ad74d in handle_fatal_signal (signum=11) at /usr/src/debug/ceph-12.2.7-809-g56cc656/src/global/signal_handler.cc:119
#6 
#7 0x00007f333cb5a05d in tcmalloc::CentralFreeList::FetchFromOneSpans(int, void**, void**) () from /lib64/libtcmalloc.so.4
#8 0x00007f333cb5a31a in tcmalloc::CentralFreeList::FetchFromOneSpansSafe(int, void**, void**) () from /lib64/libtcmalloc.so.4
#9 0x00007f333cb5a3d0 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
#10 0x00007f333cb5d2a7 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int) () from /lib64/libtcmalloc.so.4

So there is segfault (signal 11) and then fatal signal handler happens to run while thread owns malloc lock. Signal handler then tries to run some backtrace printing stuff, but doing so calls malloc (which is not safe to call from signal handler). And this is exactly what bites this program.

I.e. that signal handler is calling non-async-signal-safe functions.

Closing as this is not a malloc bug.

**Comment by hjwsm1989** [comment]
> #0 0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
> #1 0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
> #2 0x00007f333cb5a492 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
> #3 0x00007f333cb5d2a7 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int) () from /lib64/libtcmalloc.so.4
> 
> #0 0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
> #1 0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
> #2 0x00007f333cb5a492 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
> #3 0x00007f333cb5d2a7 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int) () from /lib64/libtcmalloc.so.4
> 
> #0 0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
> #1 0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
> #2 0x00007f333cb59fdc in tcmalloc::CentralFreeList::InsertRange(void*, void*, int) () from /lib64/libtcmalloc.so.4
> #3 0x00007f333cb5d460 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) () from /lib64/libtcmalloc.so.4
> #4 0x00007f333cb5d81c in tcmalloc::ThreadCache::ListTooLong(tcmalloc::ThreadCache::FreeList*, unsigned int) () from /lib64/libtcmalloc.so.4
> 
> #0 0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
> #1 0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
> #2 0x00007f333cb59fdc in tcmalloc::CentralFreeList::InsertRange(void*, void*, int) () from /lib64/libtcmalloc.so.4
> #3 0x00007f333cb5d460 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) () from /lib64/libtcmalloc.so.4
> #4 0x00007f333cb5d81c in tcmalloc::ThreadCache::ListTooLong(tcmalloc::ThreadCache::FreeList*, unsigned int) () from /lib64/libtcmalloc.so.4
> 
> #0 0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
> #1 0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
> #2 0x00007f333cb59fdc in tcmalloc::CentralFreeList::InsertRange(void*, void*, int) () from /lib64/libtcmalloc.so.4
> #3 0x00007f333cb5d460 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) () from /lib64/libtcmalloc.so.4
> #4 0x00007f333cb5d798 in tcmalloc::ThreadCache::Scavenge() () from /lib64/libtcmalloc.so.4
> 
> #0 0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
> #1 0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
> #2 0x00007f333cb5a492 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
> #3 0x00007f333cb5d2a7 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int) () from /lib64/libtcmalloc.so.4
> #4 0x00007f3331df63b2 in ceph::BackTrace::print (this=this@entry=0x7f330658f8e0, out=...) at /usr/src/debug/ceph-12.2.7-809-g56cc656/src/common/BackTrace.cc:39
> #5 0x000055eccb1ad74d in handle_fatal_signal (signum=11) at /usr/src/debug/ceph-12.2.7-809-g56cc656/src/global/signal_handler.cc:119
> #6
> #7 0x00007f333cb5a05d in tcmalloc::CentralFreeList::FetchFromOneSpans(int, void**, void**) () from /lib64/libtcmalloc.so.4
> #8 0x00007f333cb5a31a in tcmalloc::CentralFreeList::FetchFromOneSpansSafe(int, void**, void**) () from /lib64/libtcmalloc.so.4
> #9 0x00007f333cb5a3d0 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
> #10 0x00007f333cb5d2a7 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int) () from /lib64/libtcmalloc.so.4
> 
> #0 0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
> #1 0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
> #2 0x00007f333cb59fdc in tcmalloc::CentralFreeList::InsertRange(void*, void*, int) () from /lib64/libtcmalloc.so.4
> #3 0x00007f333cb5d460 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) () from /lib64/libtcmalloc.so.4
> #4 0x00007f333cb5d798 in tcmalloc::ThreadCache::Scavenge() () from /lib64/libtcmalloc.so.4
> 
> #0 0x00007f333cb69b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
> #1 0x00007f333cb69a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
> #2 0x00007f333cb59fdc in tcmalloc::CentralFreeList::InsertRange(void*, void*, int) () from /lib64/libtcmalloc.so.4
> #3 0x00007f333cb5d460 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) () from /lib64/libtcmalloc.so.4
> #4 0x00007f333cb5d798 in tcmalloc::ThreadCache::Scavenge() () from /lib64/libtcmalloc.so.4

Hi, do you have resolved this problem? As i searched the ceph source code, it remains unchanged.
