### ISSUE TITLE
Build error on Centos 7

### ISSUE THREAD

**Issue by jaeseok-park** [gperftools/gperftools#1101]
Hi.
I tried to build gperftools on CentOS 7.6.
But, it failed with the below error:
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -DNO_TCMALLOC_SAMPLES -pthread -DNDEBUG -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -DNO_FRAME_POINTER -g -O2 -MT src/libtcmalloc_minimal_la-tcmalloc.lo -MD -MP -MF src/.deps/libtcmalloc_minimal_la-tcmalloc.Tpo -c src/tcmalloc.cc  -fPIC -DPIC -o src/.libs/libtcmalloc_minimal_la-tcmalloc.o
In file included from src/tcmalloc.cc:94:0:
./src/gperftools/tcmalloc.h:137:5: error: token "@" is not valid in preprocessor expressions
 #if @ac_cv_have_std_align_val_t@ && __cplusplus >= 201703L
```
My g++ version is v4.8.5, and I have tested to build it with g++ v8.2.1, but the same error.

I know that gperftools is tested on CentOS 5.5. But, I hope to use it on my system.

Could anyone advise me, please?

**Comment by alk** [comment]
This looks like some issue with autoconf. Can you post exact commands ? (Are you building from git or source tarball) Also please post full contents of config.log, so that we can debug.

**Comment by jaeseok-park** [comment]
I'm sorry for late response.
I solved this issue.
When I met it, I just run `./configure` and `make` and it failed. I didn't know I should run `./autogen.sh` before running `./configure`.
```
./autogen.sh
./configure
make
```
I have built it successfully with the above instructions.
Thank you.
