### ISSUE TITLE
Project cannot start after centos7 installation

### ISSUE THREAD

**Issue by yanwencheng** [gperftools/gperftools#1103]
Project cannot start after centos7 installation

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f96ef0f1874, pid=5123, tid=0x00007f96d3a0f700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libunwind.so.7+0x6874]  access_mem+0x24
#
# Core dump written. Default location: /yunku/core or core.5123
#
# An error report file with more information is saved as:
# /yunku/hs_err_pid5123.log
#
# Compiler replay data is saved as:
# /yunku/replay_pid5123.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by alk** [comment]
That looks like crash in libunwind. Consider reporting it over there.

What exactly you're running? Is that malloc or profiler? In any case you can switch it to frame pointer base unwinding and then switch JVM to generate frame pointers: -XX:+PreserveFramePointer.

gperftools can be either built without libunwind, or switched to frame pointers by passing environment variable TCMALLOC_STACKTRACE_METHOD=x86.

**Comment by runzhiwang** [comment]
@alk Hi, I got the same crash when analyse the memory of java program via "LD_PRELOAD=/xx/libtcmalloc.so". How can I use gperftools without libunwind ?

**Comment by hnwyllmm** [comment]
use libtcmalloc_minimal.so instead of libtcmalloc.so without libunwind.so


mdbbm%ldd ./libtcmalloc_minimal.so.4.1.2 
        linux-vdso.so.1 =>  (0x00007ffd7a78f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f011ecdf000)
        libstdc++.so.6 => /data02/settlegrp/mdbbm/gcc-5.2.0_home/lib/../lib64/libstdc++.so.6 (0x00007f011e951000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f011e6cd000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f011e339000)
        libgcc_s.so.1 => /data02/settlegrp/mdbbm/gcc-5.2.0_home/lib/../lib64/libgcc_s.so.1 (0x00007f011e122000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003727000000)




At 2019-09-09 21:29:27, "runzhiwang" <notifications@github.com> wrote:


@alk Hi, I got the same crash when analyse the memory of java program via "LD_PRELOAD=/xx/libtcmalloc.so". How can I use gperftools without libunwind ?

**Comment by runzhiwang** [comment]
@hnwyllmm I use libtcmalloc_minimal.so, but could not get the memory heap in HEAPPROFILE. Is there anything wrong with my operations ?
1. wget https://github.com/gperftools/gperftools/releases/download/gperftools-2.5/gperftools-2.5.tar.gz
2. tar -zxvf gperftools-2.5.tar.gz 
3. cd gperftools-2.5
4. ./configure --enable-minimal
5. make&& make install
6. 
export LD_PRELOAD=/gperftools-2.5/.libs/libtcmalloc_minimal.so
export HEAPPROFILE=/gperftools-2.5/tmp/gzip
7. java -jar xxx.jar
8. Did not find any gzip_xxx.heap in /tmp.

**Comment by hnwyllmm** [comment]
Sorry, you cannot use profile tools with minimal.so

**Comment by dongming** [comment]
same problem
