### ISSUE TITLE
dead_lock when exit my process

### ISSUE THREAD

**Issue by tencentjerry** [gperftools/gperftools#1109]
![image](https://user-images.githubusercontent.com/7704680/56451886-815ee180-6360-11e9-8f5a-c812915408e4.png)

after fork ，then create multithread， when exit(by catching signal)， it cause deadlock

**Comment by alk** [comment]
BTW posting screen shots is a bit unnice. Not sure why you're doing this.

I don't see anything about tcmalloc data that your provided. Can you please add more details so that it is clear how tcmalloc affects this?
