### ISSUE TITLE
Issue with TCmalloc when used with Huge page C++

### ISSUE THREAD

**Issue by beingdhruv08** [gperftools/gperftools#1112]
I am trying to use tcmalloc library with huge pages in my system.  I am using gcc version 5.4.0  to build. Our system also starts a child process by forking the process. This child process is only used for logging. The parent process writes(along with other stuff) into shared memory and the child process(logger) reads from it and dumps it into file. We use boost library functions to create shared memory. Our current boost version is 1.58.0

While starting of program my code is crashing at random places. Mostly I am getting segfaults in our parallel logger.

I am using this flag TCMALLOC_MEMFS_MALLOC_PATH=/dev/hugepages/  for use pages. We have a setup our system to  have default 1Gb huge page size. Our tcmalloc version is 4.2.6
Below are two gdb traces which shows error coming at different places in code. 

**GDB STACK TRACE - 1**
(gdb) bt
#0  0x00007f672e58b79d in tc_malloc () from /usr/lib/libtcmalloc.so.4
#1  0x00007f672d95b1d5 in __GI__IO_file_doallocate (fp=0x16e6640) at filedoalloc.c:127
#2  0x00007f672d969594 in __GI__IO_doallocbuf (fp=fp@entry=0x16e6640) at genops.c:398
#3  0x00007f672d9688f8 in _IO_new_file_overflow (f=0x16e6640, ch=-1) at fileops.c:820
#4  0x00007f672d96728d in _IO_new_file_xsputn (f=0x16e6640, data=0x7f672f1e8c20 <str>, n=1) at fileops.c:1331
#5  0x00007f672d95c7bb in __GI__IO_fwrite (buf=0x7f672f1e8c20 <str>, size=1, count=1, fp=0x16e6640) at iofwrite.c:39
#6  0x00007f672ee62cb4 in Log_write::parseAndLogLine(char*, int, int) () from /strategies/in105/bin/bin.20190513/libBase.so
#7  0x00007f672ee650f8 in Log_write::start_log(int, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) ()
   from /strategies/in105/bin/bin.20190513/libBase.so
#8  0x0000000000410b48 in eye_init(int, char**) ()
#9  0x0000000000409f43 in main ()

**GDB STACK TRACE - 1**
(gdb) bt
#0  0x00007fa45fbf20b3 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned long, int) () from /usr/lib/libtcmalloc.so.4
#1  0x00007fa45fbf216b in tcmalloc::ThreadCache::ListTooLong(tcmalloc::ThreadCache::FreeList*, unsigned long) () from /usr/lib/libtcmalloc.so.4
#2  0x00007fa45fc04818 in tc_deletearray () from /usr/lib/libtcmalloc.so.4
#3  0x000000000040f06b in eye_init(int, char**) ()
#4  0x0000000000409f37 in main ()

**Comment by alk** [comment]
Could this be caused by MAP_SHARED for memfs thingy? I.e. #1139 ? (if so fix is inside that ticket)
