### ISSUE TITLE
HEAPCHECK=normal doesn't find leaks in a leaking program on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [gperftools/gperftools#1113]
Testcase leak.c:
```
#include <stdlib.h>

main() {
  malloc(100000000);
}
```

Compile:
> cc -g -o leak leak.c

Run:
> $ HEAPCHECK=normal LD_PRELOAD=/usr/local/lib/libtcmalloc.so ./leak

FreeBSD 12 amd64

**Comment by zhangyiru** [comment]
try HEAPCHECK=draconian

**Comment by alk** [comment]
heap checker only works on linux.

**Comment by yurivict** [comment]
> heap checker only works on linux.

Why?
What limits it such that it can't work on FreeBSD?

**Comment by alk** [comment]
Several reasons.

a) we never had heap checker unittest passing on anywhere other than linux (and then only x86 and maybe ppc).

b) one of reasons is lack of threadlister facility support. Which was and is Linux-only (and does semi-crazy things with clone and ptrace)

c) lack of ptrace support to grab registers and stack pointer (we support linux and plenty of architectures). Yes occasionally, it could find you something even on bsd, but "occasionally" doesn't count.

d) we're overwhelmed with existing amount of support work. No chance to gain BSD support. And even if someone contributes, not much hope being able to maintain.

e) heap leak checker isn't entirely most cleanest code. And isn't entirely right too (e.g. #540 and I can name more)

f) asan/msan/lsan now exist and have well funded, competent teams supporting them

Thus not only I made decision to stop pretending that heap checker is not Linux-only. But I am also going to call it's support best effort & deprecated. With eye towards eventually dropping it.
