### ISSUE TITLE
Fails to dump profiles for child processes

### ISSUE THREAD

**Issue by yurivict** [gperftools/gperftools#1116]
My process spawns some child processes. I run the top process with perftools and get this:

```
HEAPPROFILE=my-google-profile-pid$$ LD_PRELOAD=/usr/local/lib/libtcmalloc.so ./myexe
<...skipped...>
running test: mmtf ... OK
running test: calc-nwchem ... Starting tracking the heap
Starting tracking the heap
Dumping heap profile to my-google-profile-pid10044_10048.0001.heap (Exiting, 8 kB in use)
Failed dumping heap profile to my-google-profile-pid10044_10048.0001.heap
Starting tracking the heap
Starting tracking the heap
Dumping heap profile to my-google-profile-pid10044_10060.0001.heap (Exiting, 8 kB in use)
Failed dumping heap profile to my-google-profile-pid10044_10060.0001.heap
Starting tracking the heap
Starting tracking the heap
Dumping heap profile to my-google-profile-pid10044_10072.0001.heap (Exiting, 8 kB in use)
Failed dumping heap profile to my-google-profile-pid10044_10072.0001.heap
Starting tracking the heap
Starting tracking the heap
Dumping heap profile to my-google-profile-pid10044_10084.0001.heap (Exiting, 8 kB in use)
Failed dumping heap profile to my-google-profile-pid10044_10084.0001.heap
OK (in 8 sec)
All 13 tests succeeded (in 15 secs)
-- ChemWiz is finishing at Thu May 23 15:15:55 2019
-- ran for 15 second(s) (wallclock) --
Dumping heap profile to my-google-profile-pid10044.0008.heap (Exiting, 5 MB in use)
```

It doesn't give any reason why it fails dumping child profiles.

```google-perftools-2.7``` on FreeBSD 12, installed from the port.

There are two problems:
1. It doesn't print the reason of the failure
2. The failure itself needs to be fixed

**Comment by Rekklesjjs** [comment]
Hello,may I ask that have you fixed this problem?I met this problem too.

**Comment by yurivict** [comment]
@Rekklesjjs 
I don't recall seeing this problem fixed.
But a lot of time has passed since.

**Comment by Rekklesjjs** [comment]
> @Rekklesjjs I don't recall seeing this problem fixed. But a lot of time has passed since.

Ok,I got it.Thank you.

**Comment by alk** [comment]
Reading original post again and looking at the code it looks like the only plausible possibility (short of exotic stuff a-la selinux or sandboxing facilities) is that current directly isn't writable by whatever child runs as. So likely something in your setup. I've added commit that will print errno so we can understand better, hopefully.

Closing for now as usual, but please reopen when you get more details.
