### ISSUE TITLE
unable to compile with -fsanitize=address

### ISSUE THREAD

**Issue by fulara** [gperftools/gperftools#1120]
compiler: clang 7.0
version: gperftools 2.7
os: centos7
i am able to compile package without -fsanitize flag.
However when trying to compile gperftools 2.7 with below flags i am getting compilation errors.

```
export CXXFLAGS='-fsanitize=address'
export LDFLAGS=$CXXFLAGS
...
src/base/low_level_alloc.cc:363:25: error: use of undeclared identifier 'munmap'
        munmap_result = munmap(region, size);
```
and few other ones.

this is one of lines how my compilation line looks like:
```
/var/build/psi/fulara/clean/conan-gperftools/clang/bin/clang++ -DHAVE_CONFIG_H -I. -I./src -I./src -D_GLIBCXX_USE_CXX11_ABI=1 -DNDEBUG -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -fsized-deallocation -faligned-new -DNO_FRAME_POINTER -m64 -g -fPIC -stdlib=libstdc++ -std=c++17 -fsanitize=address -MT src/base/libtcmalloc_internal_la-low_level_alloc.lo -MD -MP -MF src/base/.deps/libtcmalloc_internal_la-low_level_alloc.Tpo -c src/base/low_level_alloc.cc  -fPIC -DPIC -o src/base/.libs/libtcmalloc_internal_la-low_level_alloc.o
```
not 100% sure if this is the exact line thats failing.

Is this just a case that this is unavailable with -fsanitize?
I am trying to build whole tree of dependency with -fsanitize flag.

**Comment by alk** [comment]
why are you trying to compile tcmalloc itself with sanitizer? As for this specific failure it looks like HAVE_MMAP isn't defined. So perhaps something happened at configure phase. Please post config.log

**Comment by fulara** [comment]
I was trying to compile my entire stack with sanitizer, to make sure all the libs are covered.
I ended up not doing it for the tcmalloc if I recall correctly.

Closing as I no longer have that setup and the need to compile this.
