### ISSUE TITLE
bad_alloc, with any allocator, with CPUPROFILE set and the profiler enabled

### ISSUE THREAD

**Issue by adamnovak** [gperftools/gperftools#1124]
I have a program that I am working on that, on startup, needs to load something like 90 GB of data into memory.

If I'm running the libprofiler profiler, this process results in a `std::bad_alloc` being thrown. This is in turn interpreted by my code as invalid input data, since it made the load process throw an exception.

```
ubuntu@ip-172-31-21-67:~/vg$ LD_PRELOAD=lib/libprofiler.so CPUPROFILE=slow.prof vg gaffe -p -x ~/graphs/whole_genome_graph/whole_genome.xg -m ~/graphs/whole_genome_graph/whole_genome.min -H ~/indexes/all_full.gbwt -d ~/graphs/whole_genome_graph/whole_genome.dist -G real_250_200000.gam -t32 --discard
Loading XG index /home/ubuntu/graphs/whole_genome_graph/whole_genome.xg
terminate called after throwing an instance of 'vg::XGFormatError'
  what():  XG input data not in XG version 10 format (std::bad_alloc)
ERROR: Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_97vog9/stacktrace.txt
PROFILE: interrupts/evictions/bytes = 4416/2623/434032
```

When profiling is off, the program runs fine, even if libprofiler is loaded.

```
ubuntu@ip-172-31-21-67:~/vg$ LD_PRELOAD=lib/libprofiler.so vg gaffe -p -x ~/graphs/whole_genome_graph/whole_genome.xg -m ~/graphs/whole_genome_graph/whole_genome.min -H ~/indexes/all_full.gbwt -d ~/graphs/whole_genome_graph/whole_genome.dist -G real_250_200000.gam -t32 --discard
Loading XG index /home/ubuntu/graphs/whole_genome_graph/whole_genome.xg
Loading GBWT index /home/ubuntu/indexes/all_full.gbwt
Loading minimizer index /home/ubuntu/graphs/whole_genome_graph/whole_genome.min
Loading distance index /home/ubuntu/graphs/whole_genome_graph/whole_genome.dist
Initializing MinimizerMapper
--hit-cap 10
--hard-hit-cap 300
--score-fraction 0.6
--max-extensions 48
--max-alignments 8
--no-chaining 0
--max-multipmaps 1
--distance-limit 1000
--xdrop 0
warning:[GSSWAligner::maximum_mapping_quality_exact]: Max score of 0 is the padding score; changing to -21
Mapped 200000 reads across 32 threads in 140.312 seconds.
Mapping speed: 44.5435 reads per second per thread
```

Currently I'm seeing this issue with jemalloc used as the program's malloc, but I also see it with tcmalloc (using the combined tcmalloc/profiler library) and with the system allocator.

Is libprofiler replacing my allocator with its own, worse allocator when I turn on profiling? How do I get it to not do that? I specifically want to profile my application with the allocator I am going to be using in production, and moreover whatever the profiler is doing to the allocator is not working correctly.

Am I running into some known limitation of the profiler?

I have tested gperftools 855b3800064db49af823b85a54be269923eb6f4d and fe62a0baab87ba3abca12f4a621532bf67c9a7d2; both exhibit the problem.

**Comment by alk** [comment]
Thanks for reporting this and apologies for delay.

Your case is perplexing. cpu profiler should not be affecting memory usage of the program in any significant way. Profiler's own data takes about 10 megs total.

So not sure what is happening.

Could your crash be say symptom of some other issue? For example if there are some unbounded queuing involved and say if some thread(s) could get stuck (say if something happens with backtrace capturing facility which is known in various configurations to have a problem sometimes)

**Comment by alk** [comment]
In order to debug this, have memory allocator crash on exceeding memory and have it dump core. And then in core (yes, 90 gigs of core will be painful) you will see backtraces of all threads.

**Comment by adamnovak** [comment]
> have memory allocator crash on exceeding memory and have it dump core

Would this be just making sure `std::bad_alloc` is not caught and that core dumps are on? Or would this involve doing something special to the allocator to change its behavior? Although I tried a few different allocators I don't actually control the code in any of them.

I don't *think* this was threading-related; it happens in my single-thread initialization code, where I load in all the data before branching out into many threads to run my analysis. Though I suppose it could still be some kind of conflict between `libprofiler` and OpenMP, since I think the OpenMP worker threads still *exist* at this point, just in an idle state since we aren't in a parallel section.

How interested are you in getting this reproduced/getting the stacktraces from all involved threads? I don't think I have the dataset or code revision I reported this from, and we're fairly happy now using `perf` and Callgrind for profiling, so making `libprofiler` work might be a bit of an orphaned project on my side.

**Comment by alk** [comment]
Yes, not catching std::bad_alloc should abort and dump core, assuming cores are enabled. As how important it is, well, sure I am keen to study this case. But I am in no position to ask you to do lots of work you don't want to. So if can do one more run with whatever dataset/use-case is convenient for, you and that has chance of causing this, please do.
