### ISSUE TITLE
autogen failed on ubuntu 16.04

### ISSUE THREAD

**Issue by legendtang** [gperftools/gperftools#1125]
When I run `./autogen.sh` on ubuntu 16.04 with libtool installed,

it gives me:

```
configure.ac:165: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
Makefile.am:141: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:141:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:141:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:141:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:141:   its definition is in aclocal's search path.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by thegrb93** [comment]
Same issue with redhat. Related https://github.com/google/googletest/issues/236

**Comment by thegrb93** [comment]
Solution might be to install libtool. sudo apt-get install libtool

**Comment by legendtang** [comment]
> Solution might be to install libtool. sudo apt-get install libtool . Since I don't have install privileges I can't test this, but maybe it'll be fixed for you.

I have `libtool` installed and can still reproduce the issue

**Comment by thegrb93** [comment]
Did you just install it? Might want to try running aclocal again to refresh.

**Comment by legendtang** [comment]
> Did you just install it? Might want to try running aclocal again to refresh if so.

It is preinstalled on my machine. I have tried your method a long time ago but no luck.

**Comment by thegrb93** [comment]
Just a thought. On Monday I'll be installing prebuilt binaries instead of building so probably won't be able to figure out what's wrong.

**Comment by alk** [comment]
looks like indeed libtool is missing. But note that you can always just graph .tar.gz from downloads. As usual with autotools project, source tar ball already has right configure that doesn't need libtool or anything fancy available.
