### ISSUE TITLE
glibc pthread mmap calls are not hooked; break HEAP_PROFILE_MMAP (was: Inconsistent tracking mmap usage)

### ISSUE THREAD

**Issue by theidexisted** [gperftools/gperftools#1128]
I am profiling a process starting up process's memory usage. Which creates about 1500 threads so it use much memory in `pthread_create`, which will call `mmap` internal.

First time, I profile the process with these environment variables, the profile shows that the leaf node in the graph is `pthread_create`, which consumes 3 GB memory(When compared with the thread number and the VIRT memory cost, we can see that this value is correct).
```bash
HEAP_PROFILE_ONLY_MMAP=1 HEAPPROFILE=x HEAPPROFILESIGNAL=30 HEAP_PROFILE_ALLOCATION_INTERVAL=0 HEAP_PROFILE_INUSE_INTERVAL=0 ./a.out
```

The second time, with these environment variables, only 500 MB memory usage is captured, which is the same value shows from tcmalloc's stats function, it seems that the mmap profile doesn't work.
```
HEAP_PROFILE_MMAP=1 HEAPPROFILE=x HEAPPROFILESIGNAL=30 HEAP_PROFILE_ALLOCATION_INTERVAL=0 HEAP_PROFILE_INUSE_INTERVAL=0 ./a.out
```

From the [document](https://gperftools.github.io/gperftools/heapprofile.html) we can see that it's fine to profile both mmap and malloc at the same time, is this a bug in my case?

- gperftools version: 2.7
- os version: RHEL 7.0
- gcc version: 4.8.5

**Comment by alk** [comment]
deduping this to #1010
