### ISSUE TITLE
How to enable "TCMALLOC_PAGE_FENCE" on windows port？

### ISSUE THREAD

**Issue by Cecil-Huang** [gperftools/gperftools#1129]
I  just download master code to my Windows 10 64bit and build/test it in VS2017, everything is ok so far. 
The next step is to enable "TCMALLOC_PAGE_FENCE" and find my memory problem but it was found that debugallocation.cc is not included in windows project.
Could you please help me how to use "TCMALLOC_PAGE_FENCE" in windows?

**Comment by alk** [comment]
We don't support debugallocator on windows. Consider simply using asan.
