### ISSUE TITLE
what's the diff between tcmalloc and tcmalloc-minimal?

### ISSUE THREAD

**Issue by bulletdb-cn** [gperftools/gperftools#1131]
which one should I use?

**Comment by salami738** [comment]
See: http://goog-perftools.sourceforge.net/doc/tcmalloc.html

> If you'd rather link in a version of TCMalloc that does not include the heap profiler and checker 
> (perhaps to reduce binary size for a static binary), you can link in libtcmalloc_minimal instead.

**Comment by bulletdb-cn** [comment]
Thank you!
