### ISSUE TITLE
potential trouble when arm64 hardware page size is 64k (was: maybe memory leak on ceph?)

### ISSUE THREAD

**Issue by qqqil** [gperftools/gperftools#1135]
When the pagesize of the system is 64k, the pagesize of tcmalloc is 8k. After running for a while, the memory useage by the process(ceph-osd) would continue to grow until the process restarts.
but when the pagesize of tcmalloc was 64k, the process's (ceph-osd) memory usage was low and would not grow.  
OS:centos-7.6 aarch64 
os-PAGESIZE:64K
ceph version:14.2.1    

heap stats log: 
ceph tell osd.0 heap stats
osd.0 tcmalloc heap stats:------------------------------------------------
MALLOC:   384500815376 (366688.6 MiB) Bytes in use by application
MALLOC: +   1530109952 ( 1459.2 MiB) Bytes in page heap freelist
MALLOC: +    135975624 (  129.7 MiB) Bytes in central cache freelist
MALLOC: +      8006656 (    7.6 MiB) Bytes in transfer cache freelist
MALLOC: +     26774312 (   25.5 MiB) Bytes in thread cache freelists
MALLOC: +   1612447744 ( 1537.8 MiB) Bytes in malloc metadata
MALLOC:   ------------
MALLOC: = 387814129664 (369848.4 MiB) Actual memory used (physical + swap)
MALLOC: +            0 (    0.0 MiB) Bytes released to OS (aka unmapped)
MALLOC:   ------------
MALLOC: = 387814129664 (369848.4 MiB) Virtual address space used
MALLOC:
MALLOC:       24418024              Spans in use
MALLOC:             39              Thread heaps in use
MALLOC:           8192              Tcmalloc page size
Call ReleaseFreeMemory() to release freelist memory to the OS (via madvise()).
Bytes released to the OS take up virtual address space but no physical memory.

**Comment by alk** [comment]
Yes, mismatch between malloc's idea of page size and OS page size could cause trouble. Try building with bigger malloc page size.

Also stats above indicate that, yes malloc was unable to return page heap to kernel, but this is "only" 1.5 gigs, where "in use by app" is 366 gigs. So there seem to be something beyond just malloc.

**Comment by xhuacmer** [comment]
@alk hello, could you where the page size set of tcmalloc is in the gperftools source code? Thanks!

**Comment by alk** [comment]
here https://github.com/gperftools/gperftools/blob/master/src/common.h#L76 and here: https://github.com/gperftools/gperftools/blob/master/configure.ac#L123

**Comment by xhuacmer** [comment]
@alk Thanks！Oh, I miss the common.h file.

**Comment by alk** [comment]
So I got my proposed commit "in". We should now be robust. There is one detail though. Since we'll be effectively forcing tcmalloc logical page size up to 64k, it means some workloads will see higher internal fragmentation. But up-side is we'll be able to return memory back to kernel.
