### ISSUE TITLE
VS2017 X64  Static symbol issues

### ISSUE THREAD

**Issue by xspeed1989** [gperftools/gperftools#1136]
1>libucrt.lib(recalloc.obj) : error LNK2005: _recalloc libtcmalloc_minimal.lib(override_functions.obj)  1>libucrt.lib(msize.obj) : error LNK2005: _msizelibtcmalloc_minimal.lib(override_functions.obj) 

verison:2.7

**Comment by HolyWu** [comment]
There is a pending PR https://github.com/gperftools/gperftools/pull/1100 which fixes this issue.  Until then, you can modify the relevant lines yourself.

**Comment by xspeed1989** [comment]
> There is a pending PR #1100 which fixes this issue. Until then, you can modify the relevant lines yourself.

ok ,thanks
the pr is working

**Comment by HolyWu** [comment]
@xspeed1989 Remember to close the issue if it's resolved.

**Comment by xspeed1989** [comment]
@HolyWu tcmalloc_minimal_unittest 
libtcmalloc_minimal.lib(override_functions.obj) : error LNK2005: _msize  libucrt.lib(msize.obj)

**Comment by HolyWu** [comment]
Apparently we need to override `_msize_base` function as well. Do the same thing in https://github.com/gperftools/gperftools/pull/1099/commits/a6d9dae2d21b4de5d0882b3fd1424d394b1e5a4e.

**Comment by xspeed1989** [comment]
@HolyWu  ok. it's work fine!
