### ISSUE TITLE
Initial reserved memory for tcmalloc doesn't come from HugePages ?

### ISSUE THREAD

**Issue by alokkataria** [gperftools/gperftools#1140]
I wrote a simple program that does a bunch of mallocs / frees. Running this program with the following environment variable TCMALLOC_MEMFS_MALLOC_PATH=/dev/hugepages/tcmalloc makes sure that any mmaps that tcmalloc does, the memory is gotten from the Hugepage pool. But besides these mmaps tcmalloc seems to preserve about 1MB of memory at the program start. That memory is not backed by hugepages though.

I have tried setting the generic.heap_size to '0', to ensure this pre-reservation goes away, but that doesn't seem to have any effect ? 
MallocExtension::instance()->SetNumericProperty("generic.heap_size", 2);

Have also tried calling MallocExtension::instance()->ReleaseFreeMemory(); before any of my allocations happen, but still doesn't help release this first pre-reserved 1MB

Is there a way to ensure that either this pre-reserved memory too comes from hugepage pool or a way to not have any preservation at all ?

**Comment by alokkataria** [comment]
@alk can you please shed some light here ?

**Comment by alk** [comment]
No, there is no way. Currently or planned. But in practical uses of this feature at Google, those few megs of early memory seems harmless. If you have evidence that this is somehow harmful, please elaborate. It might be possible to do something.

Closing for now, but feel free to reopen if you have more to say.
