### ISSUE TITLE
cputype (16777228) does not match previous archive members cputype (16777223)

### ISSUE THREAD

**Issue by shuaiqiao168** [gperftools/gperftools#1142]
I try build tcmalloc on iOS, but come cross a error:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/liblogging.a(dynamic_annotations.o) cputype (16777228) does not match previous archive members cputype (16777223) (all members must match)
make: *** [liblogging.la] Error 1

Anyone can help me?
my makefile configuration:
CC = xcrun -sdk iphoneos clang -arch arm64
CCDEPMODE = depmode=gcc3
CFLAGS = -Wall -arch arm64 -fembed-bitcode -fno-common

**Comment by alk** [comment]
We don't support iOS, sorry.

In this case something might be wrong with your make bits. I suspect some files are built with for-host (e.g. x86-64) and some are for-target, but I won't be able to look at this.

**Comment by shuaiqiao168** [comment]
Thanks a lot!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aliaksey Kandratsenka (aka Aliaksei Kandratsenka)"<notifications@github.com&gt;; 
发送时间: 2020年2月10日(星期一) 下午2:27
收件人: "gperftools/gperftools"<gperftools@noreply.github.com&gt;; 
抄送: "我来乔@"<774035889@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gperftools/gperftools] cputype (16777228) does not match previous archive members cputype (16777223) (#1142)




Closed #1142.
 
&mdash;
