### ISSUE TITLE
gperftools and libunwind cause project crash 

### ISSUE THREAD

**Issue by runzhiwang** [gperftools/gperftools#1144]
![image](https://user-images.githubusercontent.com/51938049/64658204-41aca980-d469-11e9-9df4-a9e163799c28.png)
@alk Hi, I got the crash when use gperftools and libunwind to analyse the memory of java program via "LD_PRELOAD=/.../libtcmalloc.so" .  When I disable libunwind by "./configure --prefix=... --enable-shared=no --enable-frame-pointers --disable-libunwind", and make && make install, but the libtcmalloc.so would not be generated, so LD_PRELOAD cannot be set to /.../libtcmalloc.so, and gperftools cannot work.

Environment: Red Hat 4.8.5-36, x86_64, gperftools 2.7, libunwind 0.99-alpha

**Comment by alk** [comment]
You did --enable-shared=no which asked ./configure to only build static library. Thus no .so produced.

Also note that profiling java programs should be done with some other means. gperftools is not for java.
