### ISSUE TITLE
2.7: gperftools is not LTO ready

### ISSUE THREAD

**Issue by kloczek** [gperftools/gperftools#1146]
When gperftools i build with LTO optimisation build fails in linking
<pre>cp -p ./src/tests/maybe_threads_unittest.sh maybe_threads_unittest.sh
/bin/sh ./libtool  --tag=CXX   --mode=link g++ -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation -faligned-new  -DNO_FRAME_POINTER -fno-builtin -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -pthread  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -flto-partition=none -fuse-linker-plugin -o memalign_unittest src/tests/memalign_unittest-memalign_unittest.o src/tests/memalign_unittest-testutil.o libtcmalloc_minimal.la -lpthread 
libtool: link: g++ -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -fsized-deallocation -faligned-new -DNO_FRAME_POINTER -fno-builtin -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -pthread -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -flto-partition=none -fuse-linker-plugin -o .libs/memalign_unittest src/tests/memalign_unittest-memalign_unittest.o src/tests/memalign_unittest-testutil.o  ./.libs/libtcmalloc_minimal.so -lpthread -pthread
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/libstdc++.so: undefined reference to `pthread_create&apos;
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/libstdc++.so: undefined reference to `pthread_join&apos;
collect2: error: ld returned 1 exit status
make: *** [Makefile:4150: memalign_unittest] Error 1
</pre>

**Comment by alk** [comment]
Hi. Thanks for report. If you can give me test program or specific ./configure flags that cause this I'll be happy to look.

**Comment by kloczek** [comment]
I'm injecting LTO settimgs by adding set of env variables before executing configure
```
$ rpm -E %set_build_flags

        export CFLAGS="${CFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none}";
        export CXXFLAGS="${CXXFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none}";
        export FFLAGS="${FFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules -flto=auto -flto-partition=none}";
        export FCFLAGS="${FCFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules -flto=auto -flto-partition=none}";
        export LDFLAGS="${LDFLAGS:--Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin}";
        export AR="/usr/bin/gcc-ar" RANLIB="/usr/bin/gcc-ranlib" NM="/usr/bin/gcc-nm";
        export CC="gcc" CXX="g++"
```
You can reduce above to:
```
$ rpm -E %set_build_flags

        export CFLAGS="${CFLAGS:  -flto=auto -flto-partition=none}";
        export CXXFLAGS="${CXXFLAGS:  -flto=auto -flto-partition=none}";
        export LDFLAGS="${LDFLAGS:  -flto=auto -flto-partition=none -fuse-linker-plugin}";
        export AR="/usr/bin/gcc-ar" RANLIB="/usr/bin/gcc-ranlib" NM="/usr/bin/gcc-nm";
        export CC="gcc" CXX="g++"
```
Just tested 2.7.90 and this time it fails a bit diffetent.

**Comment by alk** [comment]
yes, indeed LTO flags are making tests fail.

$ ./autogen.sh && ./configure CXXFLAGS='-flto=auto -flto-partition=none -ggdb3' CFLAGS='-flto=auto -flto-partition=none -ggdb3' LDFLAGS='-flto=auto -flto-partition=none -fuse-linker-plugin' && make -j8 tcmalloc_minimal_unittest && ./tcmalloc_minimal_unittest

**Comment by alk** [comment]
I take it back. Failing to reproduce now.

Even with fedora and the following Dockerfile:

```
FROM fedora:latest

RUN yes | yum install git g++ libunwind-devel make autoconf automake libtool

RUN cd && git clone https://github.com/gperftools/gperftools

ENV CFLAGS="-flto=auto -flto-partition=none"
ENV CXXFLAGS="-flto=auto -flto-partition=none"
ENV LDFLAGS="-flto=auto -flto-partition=none -fuse-linker-plugin"
ENV AR="/usr/bin/gcc-ar"
ENV RANLIB="/usr/bin/gcc-ranlib" NM="/usr/bin/gcc-nm"
ENV CC="gcc" CXX="g++"

RUN cd ~/gperftools && ./autogen.sh && ./configure && make -j8

RUN cd ~/gperftools && make -j check
```

I assume is #1145 is basically same issue very likely. But in order to help you I really need some way to reproduce. Would take us ages for me to get enough information by asking you.

**Comment by kloczek** [comment]
> I assume is #1145 is basically same issue very likely. But in order to help you I really need some way to reproduce. Would take us ages for me to get enough information by asking you.

Nope. Linking issues are completely different thing.
In this case it is not possible even to link binaries because missing symbols.

PS. If you need any other details (like call traces in case core dumping in case of #1145) or want me to to perform some diagnostics please juzt tell me.

**Comment by alk** [comment]
Ok lets close this one at least until #1145 is understood.
