### ISSUE TITLE
Benchmark report

### ISSUE THREAD

**Issue by EmuraDaisuke** [gperftools/gperftools#1150]
Hello tcmalloc!

I am [KanameShiki](https://github.com/EmuraDaisuke/MemoryAllocator.KanameShiki).
Same memory allocator as you.

I hope that various ideas will merge to create a better memory allocator.
I believe it will benefit all people who use computers.

**Comment by alk** [comment]
Hello to you too. Can you elaborate what exactly are you proposing ?
