### ISSUE TITLE
improve heap recording data structure

### ISSUE THREAD

**Issue by romange** [gperftools/gperftools#1151]
heap profiler has huge contention on multi-cores systems.

When heap profiler is enabled it immediately consumes most of the CPU bandwidth on linux x64 systems with tcmalloc process utilizing 16 cores or more. Upon inspection I verified that the bottleneck is the `sys_futex` system call. I am attaching the callgraph that proves it. I do not think it's realistic to build a scalable heap recorder with critical section wrapping the whole record call. It will always cause a huge contention on multi-core systems. I suggest to convert RecordAlloc call to non-blocking. It can probably be achieved by either using lock-free data structure or by making it thread local and then merge into a final log during the dump phase. 

![Screenshot from 2019-10-20 22-59-07](https://user-images.githubusercontent.com/3674760/67165469-f5b92280-f38d-11e9-8b1c-e967ded359aa.png)

**Comment by alk** [comment]
heap checker and heap profiler are not designed for production use. Inside Google, heap checker is still used, usually for tests, but heap profiler is completely gone. They have nicer heap allocation profiler: https://github.com/google/tcmalloc/blob/master/tcmalloc/malloc_extension.h#L65, which I would like us to have too, but don't have throughput to port.

I thinking wont-fix this ticket. Heap checker is dead horse basically, and much harder to maintain then rest of code too.

**Comment by romange** [comment]
Ok, fair enough. Is that nicer profiler open-sourced?

**Comment by alk** [comment]
Yes, it should be part of that google tcmalloc fork. I suspect big part of usability problem with it, is malloc extension will give you "Profile" instance and it'll be up to you to serialize it for pprof. Do file ticket over there if that is indeed the case.

**Comment by ckennelly** [comment]
I maintain https://github.com/google/tcmalloc.

We have an internal library for doing the conversion that @alk mentions from `Profile` to something understandable for pprof, but it would be very natural to eventually include.

**Comment by alk** [comment]
Closing as won't fix. Do consider either adopting "abseil" version of tcmalloc and either bugging them about this Profile thing or doing it yourself. Or consider just porting modern heap profiling.

I.e. real problem that you have is that existing heap profiler actually records every single allocation. That is extremely expensive. What google's version does is, it uses sampling to only track small subset of allocations (which is basically free to track both in cpu and ram terms). And this gives you in theory less precise but in practice pretty okay profile of "where bytes are allocated in my program".
