### ISSUE TITLE
how to use HEAPCHECK

### ISSUE THREAD

**Issue by boyxiaolong** [gperftools/gperftools#1152]
I have read the doc,,such as my code is:

`#include <stdlib.h>
int main() {
    const int array_count = 1024;
    int* p = new int[array_count];
    return 0;
}`

and compile with:

`g++ t1.cc -ltcmalloc -g -pthread -o ltest`

then run it :

`HEAPCHECK=normal ./ltest`

the output just

`WARNING: Perftools heap leak checker is active -- Performance may suffer
Have memory regions w/o callers: might report false leaks
No leaks found for check "_main_" (but no 100% guarantee that there aren't any): found 13 reachable heap objects of 4646 bytes`

the tool can't find the memory leak, is it normal? and how to find the heapleak file? where is it?

**Comment by stefvanvlierberghe** [comment]
Why would p be a memory leak ? 
*p it is still reachable by p !

If you allocate p a second time (creating a leak) you get what you expect:

cat try.c++
#include <stdlib.h>
int main() { const int array_count = 1024; int* p = new int[array_count]; p = new int[array_count]; return 0; }

WARNING: Perftools heap leak checker is active -- Performance may suffer
Have memory regions w/o callers: might report false leaks
Leak check _main_ detected leaks of 4096 bytes in 1 objects
The 1 largest leaks:
*** WARNING: Cannot convert addresses to symbols in output below.
*** Reason: Cannot find 'pprof' (is PPROF_PATH set correctly?)
*** If you cannot fix this, try running pprof directly.
Leak of 4096 bytes in 1 objects allocated from:
	@ 400666 
	@ 7ffff6bfb545 
	@ 400589

**Comment by alk** [comment]
In general, do prefer leak or address sanitizer to heap checker. What stefan wrote above looks like plausible reason. It could have found p's address on stack.
