### ISSUE TITLE
No function names in cpu profiling output, OSX

### ISSUE THREAD

**Issue by MaxCarlson** [gperftools/gperftools#1156]
I'm having the exact same problem in #589 & #899 .

My program is built with the flags below
```
clang++
"-std=c++17",
"-g",
"-O2",
"...includes...",
"...cpp files...",
"-o",
"~/cpp/hmiss/hmiss",
"/usr/local/Cellar/gperftools/2.7/lib/libprofiler.dylib",
```

I'm enabling and running CPU profiling with the following line,
`DYLD_FALLBACK_LIBRARY_PATH=/opt/local/lib CPUPROFILE=hmiss.prof ./hmiss`

After running the profiling I run pprof and get the following output.
```
s979258ca% pprof --text ./hmiss hmiss.prof                              
Using local file ./hmiss.
Using local file hmiss.prof.
Total: 444 samples
     154  34.7%  34.7%      154  34.7% 0x0000000105c4ad65
      49  11.0%  45.7%       49  11.0% 0x0000000105c6708a
      40   9.0%  54.7%       40   9.0% 0x0000000105c4a385
      37   8.3%  63.1%       37   8.3% 0x0000000105c4a391
      30   6.8%  69.8%       30   6.8% 0x0000000105c4a37a
      10   2.3%  72.1%       10   2.3% 0x00007fff63f409da
      ...
       0   0.0% 100.0%        2   0.5% _NC3__enddef
       0   0.0% 100.0%        2   0.5% _NC3_inq_var_fill
       0   0.0% 100.0%      366  82.4% __mh_execute_header
       0   0.0% 100.0%        2   0.5% _ex__leavedef
       0   0.0% 100.0%        2   0.5% _ex_put_block
       0   0.0% 100.0%        2   0.5% _ex_put_block_param
       0   0.0% 100.0%        2   0.5% _ex_put_block_params
       0   0.0% 100.0%        2   0.5% _nc_enddef
       0   0.0% 100.0%        2   0.5% _ncio_move
       0   0.0% 100.0%        2   0.5% _posixio_open
```

Weirdly, I'm getting function names for linked libraries, just not my program.
I've seen people include the -lprofiler flag in the build process, but it doesn't change anything for me.
Is there something else I need to do here to get the function names in the profiling data?

Thanks for any help,
Max

**Comment by l1526789512** [comment]
I got the same problem. Can anyone give some help? Thanks.

**Comment by alk** [comment]
Please try using golang pprof tool. More more feature-ful and is actually supported. Then report whatever issues you find there. gperftools-bundled (perl-based) pprof is dead horse basically.
