### ISSUE TITLE
Windows: tcmalloc issue with _aligned_malloc 

### ISSUE THREAD

**Issue by alex-176** [gperftools/gperftools#1157]
my app is using tcmalloc (it significantly boosted the performance of our app - thanks)
I'm trying to use openvino library.  MLKDNNplugin.dll (that is causing the issue is a part of openvino) is using xbyak library where the issue actually occurs.

xbyak library uses a combination of _aligned_malloc and VirtualProtect to allocate an aligned memory and set it to RWE mode.
After several successful allocations (it is always a pair of _aligned_malloc and VirtualProtect), VirtualProtect fails with ERROR_INVALID_ADDRESS error (code 487 (0x1E7) - Attempt to access invalid address).
both disabling tcmalloc and replacing _aligned_malloc with VirtualAlloc resolve the issue.

Is there a proper way to resolve the issue?
Is there a way to prevent tcmalloc from handling _aligned_malloc?

---
Windows 10 x64, visual C++2015, release x64

**Comment by alk** [comment]
Thanks for report.

Well "preventing" _aligned_malloc is asking for trouble, your library/application will use free() to free this memory, so if it is not handled by tcmalloc it may cause trouble.

If you can provide small program that demonstrates the issue, I'll have a look at fixing it (assuming it is some bug in malloc that we're not aware of yet).

**Comment by wisealex2** [comment]
All my experiments were with intel's open vino library (particularly MKL). it is very easy to reproduce with open vino but for sure it is not a small codebase.
if MKL based sample can work for you - it will be relatively easy to prepare a sample with the issue.
if it is too big - i am not sure if i can find enough time in the nearest future to prepare a small example.

**Comment by alk** [comment]
If can reproduce the problem in, say, 15 minutes, that is good enough.

**Comment by alk** [comment]
So tcmalloc actually does **not** override _aligned_malloc on windows. Here is my guess what happens. On windows they use _aligned_malloc (on unixes I am guessing that use_mmap thingy is usually defined and they use mmap). I described the possible issue there: https://github.com/herumi/xbyak/issues/174

Closing optimistically assuming "it is it". Please, do reopen if there is really bug in tcmalloc.
