### ISSUE TITLE
windows mingw gcc8.1:Unable to patch because function is too short

### ISSUE THREAD

**Issue by taodm** [gperftools/gperftools#1158]
I complied gpreftools by mingw( i686-8.1.0-release-posix-dwarf-rt_v6-rev0)
when run test, I got "Unable to patch because function is too short"
code is preamble_patcher_with_stub.cc line 174
    } else if (IT_RETURN == instruction_type) {
      SIDESTEP_ASSERT(false &&
                      "Unable to patch because function is too short");
      return SIDESTEP_FUNCTION_TOO_SMALL;

**Comment by alk** [comment]
Yes, seeing this too. Consistently. I am testing on x86-64 so it appears to affect 64-bit case too. Not sure what we can do though. And how come visual studio runtimes don't hit this case (is that msvscrt versus ucrt something case?)

**Comment by alk** [comment]
DeDuping this onto earlier issue #667
