### ISSUE TITLE
tc_delete_nothrow vs tc_free: alias between functions of incompatible types

### ISSUE THREAD

**Issue by CunningBaldrick** [gperftools/gperftools#1162]
Building gperftools 2.7 with gcc 8.3.1 on Ubuntu 19.10, I get this warning:

.../src/tcmalloc.cc:1996:36: warning: 'void tc_delete_nothrow(void*, const std::nothrow_t&)' alias between functions of incompatible types 'void(void*, const std::nothrow_t&)' and 'void(void*)' [-Wattribute-alias]
 extern "C" PERFTOOLS_DLL_DECL void tc_delete_nothrow(void* p, const std::nothrow_t&) PERFTOOLS_NOTHROW
                                    ^~~~~~~~~~~~~~~~~
.../src/tcmalloc.cc:1893:6: note: aliased declaration here
 void tc_free(void* ptr) PERFTOOLS_NOTHROW {
      ^~~~~~~

And indeed they do seem to be incompatible.  Probably a tc_free_nothrow routine should be introduced and used as the alias (it would just call tc_free and ignore the extra argument).  If that sounds right to you I can whip up a patch.

**Comment by alk** [comment]
Thanks for bug report. Actually master should have the fix. And I'll be making release somewhat soon.

**Comment by DuncanSands** [comment]
I see the same with 2.7.90.  Was that release supposed to contain the fix?

**Comment by alk** [comment]
Yes, 2.7.90 should not have this warning. Please open fresh ticket if you still see the issue (with as much details as possible).
