### ISSUE TITLE
list to nullptr

### ISSUE THREAD

**Issue by Yarkin** [gperftools/gperftools#1164]
#0  SLL_Next (t=0x0) at src/linked_list.h:45
#1  SLL_PopRange (end=<synthetic pointer>, start=<synthetic pointer>, N=32, head=0x48b4aa0) at src/linked_list.h:88
#2  PopRange (end=<synthetic pointer>, start=<synthetic pointer>, N=32, this=0x48b4aa0) at src/thread_cache.h:238
#3  tcmalloc::ThreadCache::ReleaseToCentralCache (this=this@entry=0x48b49c0, src=src@entry=0x48b4aa0, cl=<optimized out>, N=N@entry=32) at src/thread_cache.cc:206 

f 0 is nullptr, but reinterpret_cast to void *

**Comment by alk** [comment]
Thanks for bug report. But such reports are 100% of the times indicate some bug in your program. Such as something corrupting freelists in tcmalloc.

Closing (as usual in such cases), but if you have small program that demonstrates actual bug in tcmalloc, please reopen.
