### ISSUE TITLE
What is the status of the project?

### ISSUE THREAD

**Issue by acmorrow** [gperftools/gperftools#1169]
This has been on my mind for a while, but I've been reluctant to raise the issue. As someone who has at various times maintained open source software, I know it can be a pretty thankless exercise, and sometimes other things just take priority.

However, I'm becoming rather concerned about the status of this project:

- It has been almost 2 years since the last stable release and there are no newer release candidates
- It has been almost 1 year since the most recent commit to master.
- Most new opened issues seem to gather no replies.
- The most recent PR with a non-clabot reply seems to also be about a year ago.

I know there had been discussions that a major update to the project was coming, to bring it more into line with the internal Google implementation. Maybe that has stalled, or just taking longer than expected? Anyway, I think it would be very helpful if some background on why activity in the project seems to have dramatically slowed could be provided by the current maintainers. Ideally, an update on the roadmap would be helpful too.

To reiterate, I really do appreciate the hard work the maintainers have put in on this project and I hate to complain. But the project I work on currently relies on tcmalloc, and if the future of this project is somehow in doubt, I'd rather know that sooner than later so I can plan accordingly.

**Comment by alk** [comment]
Thanks for pinging. And just at interesting time.

Project is alive. It is just I was not able to give it much attention in last few months.

Note that Google fork was open sourced just last Friday. github.com/google/tcmalloc. They'll probably blog about it in day or two.

You're free to move your dependence over there, but I don't think it'll work for everyone, and I have no idea if it'll work for you or not.

So gperftools will live. I won't be able to port some nice features from google fork, definitely not any time soon. But I do plan to perform at least simple maintenance in gperftools. (And any help would be useful btw)

**Comment by acmorrow** [comment]
Thanks @alk - I opened an issue on google/tcmalloc (see https://github.com/google/tcmalloc/issues/2) with a laundry list of questions about the relationship between the projects. Definitely interested in learning more, and *very* excited about the percpu work.

**Comment by acmorrow** [comment]
I guess also, more focused on this project, I guess I'd like to know whether it is going to be in more of a maintenance mode with most effort going towards google/tcmalloc, or whether this project continues under active development? Is the hope that google/tcmalloc will become primary once it starts issuing stable releases of some form? Should users of this repo be planning to jump to the other in the near term?

**Comment by alk** [comment]
I wish answer to this could be trivial, but it is not. And believe me I thought about this quite a bit.

Officially those 2 projects are unrelated. They share some common ancestry. Some name confusion will definitely keep happening too. And some people (e.g. me) contribute to both. That is all that relates them in some way.

Thing is google tcmalloc seems to be more like exposing of internal code, than attempt to offer useful malloc that will meet diverse needs and will last. A bunch of bits amputated. No intention as far as I know to offer stable ABI. No intention to support wider range of OSes. Things like that. None super-bad, but they add up.

So I do intend to keep maintaining gperftools in a way that keeps it good thing to use. I don't have throughput to copy all the best features. And as you can see I don't always have throughput to keep up with (mostly janitorial) requests on issues.

And in general for my own work, I often do it first in google's copy and then port to gperftools. Like was with fast path work back in 2016. And it will likely happen with tracing (coming soon I promise). But this "lag" isn't such a bad thing actually. For example, I am really starting to think for example that we don't really need percpu stuff at all.
