### ISSUE TITLE
CPU profiler outputs empty  .prof file on arm

### ISSUE THREAD

**Issue by tsukurudesktop** [gperftools/gperftools#1171]
Hello, I tried cross-compiling gperftools on a x86_64 machine for arm using 

./configure --enable-frame-pointers --build=x86_64-linux --host=arm-linux CXX=arm-cortexa8-linux-gnueabihf-g++ CC=arm-cortexa8-linux-gnueabihf-gcc

and then compiled my application with gcc -fno-omit-frame-pointers. However, when running the application on arm with CPU profiling turned on, I always get an empty .prof file. 
Anyone know how to solve this problem?

**Comment by tsukurudesktop** [comment]
The issue is solved by enable libunwind feature when compiling. The latest libunwind 1.4 is used instead of libunwind-0.99 because 0.99 failed when being cross-compilied. With 1.4 “emergency malloc” cannot work but setting UNW_ARM_UNWIND_METHOD=4 let profiler works properly.

However in the result the call graph always dropped the call relations of some functions, leading to some single nodes which were not connected.

**Comment by staycalmstayfoolish** [comment]
hello, dear tsukurudesktop
I was also working on some projects with ARMV8 which needed gperftools as a profiler tool. And I used your configure command referred above. However, would you please tell me how to enable the libunwind? Besides, is there any detailed documents about gperftools so that I can configure or install the gperftools according to the docs?

**Comment by tsukurudesktop** [comment]
Just follow the instruction here, https://github.com/gperftools/gperftools/blob/master/INSTALL
To enable libunwind, you need to install the library of libunwind first, and then compile gperftools with a extra flag "--enable-libunwind". Gperftools will then link itself with libunwind. @staycalmstayfoolish

**Comment by lwb4** [comment]
I had the same issue on an armv5 system, but resolved it by setting CPUPROFILESIGNAL=12 and sending kill -12 (pid) to the program to stop & start profiling. Didn't have to mess with libunwind compilation in my case.
