### ISSUE TITLE
Are there any plans to add CMake based build definition?

### ISSUE THREAD

**Issue by georgi-d** [gperftools/gperftools#1174]
CMake has become the de-facto standard build for C++ projects and is widely supported and used with multiple open source projects moving or at least adding CMake build support.

Are there any plans to add CMake based build for gperftools?
My use case is that I need to build gperftoold as part of a larger build which already supports building CMake based sub projects. Due to my toolchain setup where nothing is installed on the host system itself it is a very complicated to setup autotools as a sub project build tool.

Would a poll request adding CMake build be considered for merging?
Thanks

**Comment by alk** [comment]
See https://github.com/gperftools/gperftools/pull/938, but it's not ready it seems. Fails to build anything on my box.

I am not interested switching project entirely to cmake, but I will perform minimal maintenance if somebody contributes (working and good) cmake build.
