### ISSUE TITLE
Regarding glibc backtrace.

### ISSUE THREAD

**Issue by max0x7ba** [gperftools/gperftools#1181]
`glibc` function `backtrace` uses function `_Unwind_Backtrace` to do its job, as you mention. 

By default, `_Unwind_Backtrace` comes from `libgcc_s.so`, unless `-lunwind` is linked. `-lunwind` provides a more accurate version of `_Unwind_Backtrace`, see https://stackoverflow.com/a/60713161/412080 for full details.

**Comment by alk** [comment]
Yes, I am aware. Can you please elaborate what exactly is the issue ?

**Comment by alk** [comment]
Also I would not necessarily call libunwind version "more accurate". It it just different code.

**Comment by max0x7ba** [comment]
In the link I posted the stacktrace addresses do not resolve to functions when `-lunwind` isn't linked.

**Comment by alk** [comment]
I see. But looks like we're conflating 2 not entirely related things. That comment refers to backtrace_symbols. Which is doing 2 things, first capturing stack trace and second symbolizing it. gperftools doesn't use this function. We only capture raw stack trace (with addresses).

As far as I know, there are no major differences in stack unwinding features between libgcc_s and libunwind. They both use same kind of data. And should both produce same backtraces. There are some differences such as bugs, or how they're able to "learn" about which modules are loaded and whether they support capturing stack trace from signal handler (which we use for cpu profiling).

**Comment by max0x7ba** [comment]
> That comment refers to backtrace_symbols. Which is doing 2 things, first capturing stack trace and second symbolizing it.

`backtrace_symbols` only prints an existing stacktrace. It doesn't capture the stacktrace.

**Comment by alk** [comment]
Ah, sure.

So what is that you're trying to report here? What do we need to fix?

**Comment by alk** [comment]
Well I guess your point is backtrace (not from libunwind) is less precise. But your test in that stacktrace is very specific. You can see how difference between libunwind and libgcc is exactly one byte. Most likely what is happening is your test is dealing with fatal exceptions and those "imprecise" cases are exactly 2 functions that are likely fatal and call to something as their last instructions. Which makes "natural" backtrace point one byte past those functions.

For non-fatal cases, we don't need this "-1" trick libunwind.
