### ISSUE TITLE
How to compiler with the ARM cross-toolchain, such as x86_64_aarch64_arm_gnu compiler?

### ISSUE THREAD

**Issue by staycalmstayfoolish** [gperftools/gperftools#1183]
Dear devepolers:
I want to test the C++ code performance with gperftools on a ARMV8 platform such as ARM A53 and I have successfully tried a demo on a x64 linux OS. Thus the question is how can I compile the gperftools source code with x86_64_aarch64_arm_gnu?
Thanks very much and best regards.

**Comment by alk** [comment]
Cross compiling works standard to any autoconf-based project. Just pass --host flag.

**Comment by staycalmstayfoolish** [comment]
Dear alk,
I have tried the --host flag as following:
./configure --prefix=/home/projects/gperftools_setup --host=/home/projects/aarch_64/bin/aarch64-linux-gnu-g++
but it turned out to be invalid which throw an error: machine "aarch64-linux-gnu" not recognized.
Besides, is there any detailed document about the gperftools? Would you please share me a copy of that? Thanks.

**Comment by alk** [comment]
Please consider reading standard instructions on cross compiling with autotools. There are plenty.

Standard way to use is something like ./configure --host=aarch64-linux-gnu

Put bin directory of your cross toolchain to PATH. And also make sure it works standalone. I.e. try to compile hello world or something like that to ensure it works.
