### ISSUE TITLE
tcmalloc::ThreadCache::ReleaseToCentralCache overhead

### ISSUE THREAD

**Issue by CristoferMartins** [gperftools/gperftools#1186]
How i can reduce this overhead?
This is the only things i'm changing in tcmalloc(performance):
```
MallocExtension::instance()->SetNumericProperty("tcmalloc.max_total_thread_cache_bytes", 134217728);
MallocExtension::instance()->SetMemoryReleaseRate(0);
```
My tcmalloc version: gperftools 2.4

Btw this are my ubuntu settings(system wide optimizations) which i did not change:
```
cat /sys/kernel/mm/transparent_hugepage/enabled:
always [madvise] never
cat /sys/kernel/mm/transparent_hugepage/defrag:
[always] madvise never
cat /sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_none:
511
```
Should i set them to this? 

```
/sys/kernel/mm/transparent_hugepage/enabled:
    [always] madvise never

/sys/kernel/mm/transparent_hugepage/defrag:
    always defer [defer+madvise] madvise never`

/sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_none:
    0
```

**Comment by alk** [comment]
max_ptes_none should be set to 0. Anything else is borked. But none of this THP-related stuff is relevant to central cache overhead. If your program sees too much overhead there, the only know you have is giving it bigger per-thread caches. It won't always help though.

**Comment by CristoferMartins** [comment]
@alk thanks for your answer.
There is some info i forget to mention:
MallocExtension::instance()->SetNumericProperty is called in the main thread, the process has 8 threads in total. Another thing i paid attention to is: if i reduce the memory allocation/deallocation calls, the ReleaseToCentralCache overhead gets lower.

**Comment by alk** [comment]
Yes, it is enough to only call set numeric property once in main thread. Another thing that may help your program a bit more is trying bigger tcmalloc logical page size.

I am afraid not much beyond that I can recommend. Consider trying "abseil" tcmalloc that has per-cpu mode and which makes it's free list operations faster. At github.com/google/tcmalloc.
