### ISSUE TITLE
Patch not yet included in Debian experimental repo

### ISSUE THREAD

**Issue by krlmlr** [gperftools/gperftools#1187]
https://github.com/gperftools/gperftools/pull/1175 doesn't seem to be part of the ["experimental" Debian package](https://packages.debian.org/experimental/google-perftools). Also, Homebrew still has gperftools 2.7 in their bottles.

This patch is very important for https://github.com/r-prof/jointprof, part of an R Consortium project. Do you need to do a tag/release, or should I work with package maintainers directly? Thanks!

**Comment by alk** [comment]
I finally cut 2.8 release. So hopefully it'll be soon picked up by debian and other distros.
