### ISSUE TITLE
2.7.90, can't compile page_heap_test (VS2017)

### ISSUE THREAD

**Issue by babylon73** [gperftools/gperftools#1189]
Hi,

page_heap_test does not compile out of the box (unresolved externals), when I add the files into the project (logging.cc, spinlock.ccm spinlock_internal.cc, sysinfo.cc) only two errors left:
_1>page_heap_test.obj : error LNK2019: unresolved external symbol "public: static void __cdecl tcmalloc::Static::InitStaticVars(void)" (?InitStaticVars@Static@tcmalloc@@SAXXZ) referenced in function main
1>page_heap_test.obj : error LNK2001: unresolved external symbol "private: static class SpinLock tcmalloc::Static::pageheap_lock_" (?pageheap_lock_@Static@tcmalloc@@0VSpinLock@@A)_

However, all my attempts to add files with tcmalloc::Static lead to conflicts with libtcmalloc_minimal.

This unit test has been strongly reworked since my last gperftools recent version integration (I was on 2.6.3 until this moment), would be great to have it functional again.

All other projects compile just fine.

Thank you.

**Comment by babylon73** [comment]
Finally, I could compile it, the follwing files are to be adde to the project:

central_freelist.cc
common.cc
logging.cc
span.cc
spinlock.cc
spinlock_internal.cc
static_vars.cc
sysinfo.cc

In this case, page_heap_test compiles. However, it just hangs upon startup (gperftools 2.7.90), I will create a separate issue for that.

**Comment by alk** [comment]
Thanks for bug report. About to submit fix.

**Comment by alk** [comment]
fixed in https://github.com/gperftools/gperftools/commit/e521472f1ac1ecf028e8c922ca4f8741473afd66
