### ISSUE TITLE
2.7.90, page_heap_test hangs.

### ISSUE THREAD

**Issue by babylon73** [gperftools/gperftools#1190]
I'm trying to upgrade to the recent version of gperftools (I was using 2.6.3 before), page_heap_test unit test fails.

First of all, it does not compile out of the box (closed issue #1189), I've overcome this.

Now it just hangs upon startup, here is the call stack:
```
 	[External Code]	
>	[Inline Frame] libtcmalloc_minimal.dll!SpinLock::SpinLoop() Line 79	C++
 	[Inline Frame] libtcmalloc_minimal.dll!SpinLock::SlowLock() Line 122	C++
 	libtcmalloc_minimal.dll!SpinLock::Lock() Line 71	C++
 	[Inline Frame] libtcmalloc_minimal.dll!SpinLockHolder::{ctor}(SpinLock *) Line 133	C++
 	libtcmalloc_minimal.dll!`anonymous namespace'::do_free_pages(tcmalloc::Span * span, void *) Line 1422	C++
 	page_heap_test.exe!main(int argc, char * * argv) Line 202	C++
 	[External Code]	
```
The most interesting part is that OLD page_heap_test from 2.6.3 also hangs with present state of gperftools (I have rolled back the changes in page_heap_test.cc to 2.6.3 and compiled it with 2.7.90 codebase).

Seems like something is actually wrong.

**Comment by alk** [comment]
Thanks for bug report. Lets actually handle it as part of #issue 1190.
