### ISSUE TITLE
Reg: Tracking Memory allocation to dump on crash

### ISSUE THREAD

**Issue by bkannadassan** [gperftools/gperftools#1193]
Hi All,

  We do get core dump on crash with tcmalloc backtrace, but that doesn't help tracking the issue. We are trying to make it more helpful for an application developer when a program crashes. Hence we would like to add a wrapper over the tcmalloc function so that we can introduce some additional memory and track allocations. Here the idea is when the memory is freed we will capture that backtrace as well. So when there is a crash we can identify who last allocated this memory and who freed the same. Any help or pointers on the same ?.

rgds
Balaji Kamal Kannadassan

**Comment by alk** [comment]
tcmalloc's existing debug allocator does that. Also take a look at address sanitizer and similar tools.
