### ISSUE TITLE
close sample but get a huge pagehuge free bytes

### ISSUE THREAD

**Issue by apophise** [gperftools/gperftools#1195]
i set TCMALLOC_SAMPLE_PARAMETER = 0.
and i find tcmalloc.pageheap_free_bytes grow to a big value.
What is the connection between them？

**Comment by alk** [comment]
Those things are completely independent from each other. If pageheap free bytes grows to large value, you might be dealing with some kind of page heap fragmentation, or maybe it is your program that spikes to large amounts of memory in-use at some times.
