### ISSUE TITLE
It still builds failed on alpine linux when using docker

### ISSUE THREAD

**Issue by chenweiyj** [gperftools/gperftools#1198]
I am using alpine 3.11 as the base image. It still builds failed on alpine linux when using docker. 
When the tcmalloc can support alpine linux since it is widely used.

**Comment by alk** [comment]
Happy to help debug this, but need a lot more details. Is there any specific set of steps I can reproduce? (docker might make it simple for you to communicate and for me to try 100% deterministically)

**Comment by alk** [comment]
building with alpine works.

I did this:

```
$ docker run --tty  --interactive alpine sh -c '/bin/sh -i'
```

then inside:

```
$ apk add git g++ libunwind-dev make automake libtool autoconf linux-headers
```

(or clang instead of g++)

```
$ git clone https://github.com/gperftools/gperftools
$  cd gperftools
$ ./autogen.sh
$ ./configure && make -j
```

Some tests fail, but those look like issues with tests.

Please, next time file high quality bug reports.
