### ISSUE TITLE
tcmalloc::ThreadCache::ReleaseToCentralCache

### ISSUE THREAD

**Issue by 396318214** [gperftools/gperftools#1199]
#0  0x00007f5283f94b93 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned long, int) () from ./libtcmalloc.so.4
#1  0x00007f5283f94c4b in tcmalloc::ThreadCache::ListTooLong(tcmalloc::ThreadCache::FreeList*, unsigned long) () from ./libtcmalloc.so.4
#2  0x00007f5283fa35a2 in tc_free () from ./libtcmalloc.so.4
#3  0x0000564a8a6b5aba in std::string::_Rep::_M_dispose (__a=..., this=<optimized out>) at /usr/include/c++/6/bits/basic_string.h:2780
#4  std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (this=0x564a96f01760, __in_chrg=<optimized out>) at /usr/include/c++/6/bits/basic_string.h:3077
#5  ProtoCmd::MsgInfo::SharedDtor (this=this@entry=0x564a8baf13e0) at StatCommand.pb.cc:182

**Comment by alk** [comment]
Thanks for filing ticket, but I cannot do anything with bug reports that don't give me any details of what is supposedly not right. Closing.
