### ISSUE TITLE
how can i check if tcmalloc work with code?

### ISSUE THREAD

**Issue by zengxianhua** [gperftools/gperftools#1200]
Hi, I build libtcmalloc_minimal.a in armv7a and arm64 and link it with my android project,but I don't know whether it works with calling new and delete function?Is there a way to check if it works in my porject with code?

**Comment by alk** [comment]
simplest idea that came to mind is to just put __builtin_trap() somewhere in tc_malloc or something, and then see if program linked with tcmalloc actually crashes there.

**Comment by gezihua123** [comment]
@zengxianhua it works?
