### ISSUE TITLE
Deadlock - pageheap_lock nested call  happened when called GetStackTrace of libgcc on arrch64 platform

### ISSUE THREAD

**Issue by p2donkey** [gperftools/gperftools#1207]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/29086847/89389112-94551b00-d737-11ea-99fd-ff078d02a8f8.png">

we  build our code on centos7.6  / aarch64, run on it.
The process was stucked and the stack is shown in the figure above.
and we check the nested called stack , found the source code below 

> 
#ifdef HAVE_UNWIND_BACKTRACE
#define STACKTRACE_INL_HEADER "stacktrace_libgcc-inl.h"
#define GST_SUFFIX libgcc
#include "stacktrace_impl_setup-inl.h"
#undef GST_SUFFIX
#undef STACKTRACE_INL_HEADER
#define HAVE_GST_libgcc
#endif

// libunwind uses __thread so we check for both libunwind.h and
// __thread support
#if defined(HAVE_LIBUNWIND_H) && defined(HAVE_TLS)
#define STACKTRACE_INL_HEADER "stacktrace_libunwind-inl.h"
#define GST_SUFFIX libunwind

#include "stacktrace_impl_setup-inl.h"
#undef GST_SUFFIX
#undef STACKTRACE_INL_HEADER
#define HAVE_GST_libunwind
#endif // HAVE_LIBUNWIND_H

#if defined(__i386__) || defined(__x86_64__)
#define STACKTRACE_INL_HEADER "stacktrace_x86-inl.h"
#define GST_SUFFIX x86
#include "stacktrace_impl_setup-inl.h"
#undef GST_SUFFIX
#undef STACKTRACE_INL_HEADER
#define HAVE_GST_x86
#endif // i386 || x86_64

#if defined(__ppc__) || defined(__PPC__)
#if defined(__linux__)
#define STACKTRACE_INL_HEADER "stacktrace_powerpc-linux-inl.h"
#else
#define STACKTRACE_INL_HEADER "stacktrace_powerpc-darwin-inl.h"
#endif
#define GST_SUFFIX ppc
#include "stacktrace_impl_setup-inl.h"
#undef GST_SUFFIX
#undef STACKTRACE_INL_HEADER
#define HAVE_GST_ppc
#endif

#if defined(__arm__)
#define STACKTRACE_INL_HEADER "stacktrace_arm-inl.h"
#define GST_SUFFIX arm
#include "stacktrace_impl_setup-inl.h"
#undef GST_SUFFIX
#undef STACKTRACE_INL_HEADER
#define HAVE_GST_arm
#endif

#ifdef TCMALLOC_ENABLE_INSTRUMENT_STACKTRACE
#define STACKTRACE_INL_HEADER "stacktrace_instrument-inl.h"
#define GST_SUFFIX instrument
#include "stacktrace_impl_setup-inl.h"
#undef GST_SUFFIX
#undef STACKTRACE_INL_HEADER
#define HAVE_GST_instrument
#endif
> 

it seems like we can not go into any branch on armv8 platform and change the STACKTRACE_INL_HEADER and then we use stacktrace_libgcc-inl.h, deadlock happened.
our platform is aarch64 not arm. 
configure with 
./configure --enable-frame-pointers --with-pic --enable-emergency-malloc

we also tried with libunwind 1.31 compiled in and configure with --enable-libunwind,  and still stucked with deadlock. 
does it support aarch64 ? and how to resolve the problem?

**Comment by p2donkey** [comment]
https://user-images.githubusercontent.com/29086847/89389112-94551b00-d737-11ea-99fd-ff078d02a8f8.png

**Comment by p2donkey** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/29086847/89389385-ea29c300-d737-11ea-8b1f-e79730eb8b62.png">
the stack

**Comment by alk** [comment]
Hm, I wonder why I haven't yet made it default, but this should be fixable by building gperftools with --enable_emergency_malloc.

**Comment by alk** [comment]
odd, you have it enabled. Can you post your ./config.log and ./config.h ?

**Comment by alk** [comment]
Indeed, I just tested on my own arm64 machine that emergency malloc correctly works in this configuration. So really curious what happens on your machine.
