### ISSUE TITLE
deadlock with libunwind

### ISSUE THREAD

**Issue by zstu-jack** [gperftools/gperftools#1210]
i wonder in which condition the problem would occur.

libunwind version  1.1
gperftools version 2.6
and the program also linked with jemalloc.

![image](https://user-images.githubusercontent.com/23565430/90223960-8f801d80-de41-11ea-8783-99fc69c73306.png)

**Comment by alk** [comment]
problems with dl_iterate_phdr lock have been reported in past. libunwind is indeed not 100% right when they claim supporting working from inside signal handlers. But I also don't see some classic signs where SIGPROF is delivered during call to dl_iterate_phdr or similar by some normal code. Probably other threads' backtraces have something.

In general if your code is not touching this lock (same lock that dl_iterate_phdr is taking), then this should not occur. But AFAIU some exceptions handling code might use those. I would actually consider building libunwind with --disable-cxx-exceptions and --disable-weak-backtrace. I.e. let stock libgcc runtime deal with exceptions.
