### ISSUE TITLE
why heap profiler's memory large then process virtual memory?

### ISSUE THREAD

**Issue by yyzhuxin** [gperftools/gperftools#1213]
This is heap profiler shows 
Total: 156298.8 MB

This is process shows
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
45419 web_ser+  20   0 98.092g 0.094t  15076 S 105.0 77.0   4694:46 xxx

heap profiler shows 156GB，but process only show 98G，is heap profiler right？

**Comment by alk** [comment]
profiler shows total memory allocated. I.e. sum of all sizes ever malloced. Some of them might be freed.
