### ISSUE TITLE
Determining the best suitable or max permissible value for TCMALLOC_HEAP_LIMIT_MB

### ISSUE THREAD

**Issue by sandeepkalekar** [gperftools/gperftools#1215]
Currently I am using tcmalloc on a host with capacity of 32 GB ram
free -m
              total        used        free      shared  buff/cache   available
Mem:          31895        4618       24526         126        2750       26689
Swap:          1023         492         531

I observed following message being dumped 
Dumping heap profile to /tmp/???/???_heap.2467.heap (2506001 MB allocated cumulatively, 2410 MB currently in use)

I have one query and also need one advise  -
1. What is meant by 2506001 MB allocated cumulatively which turn out be 2447.2666015625 GB, when the host with capacity of 32 GB ram?
2. Also please advise for best suitable or maximum permissible value of TCMALLOC_HEAP_LIMIT_MB to avoid OOM

**Comment by alk** [comment]
Cumulatively refers to running sum of all malloced memory. I.e. never subtracting freed memory. That is just one statistics it keeps, and the one it profiles on.

I don't think there is much to do on heap limits here. In general current version of heap profiler is extremely and unnecessarily heavy both in ram and cpu. So some excessive slowness and ram consumption is expected. Are you sure you need heap profiler at all ?

**Comment by sandeepkalekar** [comment]
@alk Thank you helping me understand query regarding cumulatively allocated memory. Please let me how can a dump current memory  used in the log, after subtracting the freed memory, because I think in above case when it says 2410 MB currently in use, the actual memory used differs from the one which is calculated.
Also as a separate query - Can I use TCMALLOC_HEAP_LIMIT_MB to mitigate OS OOM to Tcmalloc OOM when heap profiler is disabled. I have other scheduled daemons which when triggered cause OS to freeze, rather than causing OOM in application which tcmalloc. Please advise if there are any other parameters apart from TCMALLOC_HEAP_LIMIT_MB  which can help me control memory, instead of causing OS to freeze when short of memory.

**Comment by alk** [comment]
No, setting limit is unlikely to help you. Your program will see OOM event and likely die (e.g. c++'s new throws exception).

You may get some physical ram usage reduction if you run in aggressive decommit more. But don't expect this to be large amount.  Enabling decommit mode is possible either via malloc extension API, or via environment variable (TCMALLOC_AGGRESSIVE_DECOMMIT=1) or default can be changed at ./configure time.

**Comment by sandeepkalekar** [comment]
@alk Thank you for sharing environment variable TCMALLOC_AGGRESSIVE_DECOMMIT=1 with me. Right now I have started using TCMALLOC_AGGRESSIVE_DECOMMIT=1. But the system eventually also runs out of swap space (Right now we have set 1 GB swap space).  Can you please suggest if there other things which can be tried.

**Comment by alk** [comment]
I may be able to help, but I'll need to know more details on what you're trying to achieve. Can you elaborate? Why you're running heap profiler on mysqld ?

**Comment by sandeepkalekar** [comment]
@alk Right now I am only setting TCMALLOC_AGGRESSIVE_DECOMMIT=1 (I have not turned on the heap profiler) . Also I have disabled Transparent Huge Pages. I am expecting use of swap space due to larger database as compared to buffer pool. But I am also hoping the swap space to free up when the database is idle which is not happening currently. Currently I see steady memory growth and swap space usage which results in OOM. Can you please help me with this regards?

**Comment by alk** [comment]
Most likely something is badly misconfigured. Such as maybe buffer pool is set too big or some mysql cache.
