### ISSUE TITLE
Question regarding:  dispatch_allocate_full()

### ISSUE THREAD

**Issue by geoffrob345** [gperftools/gperftools#1218]
Hi,

I'm looking at version 2.8

In the file tcmalloc.cc

In the function dispatch_allocate_full()

There are calls to three functions:

- allocate_full_cpp_throw_oom(size);
- allocate_full_cpp_nothrow_oom(size);
- allocate_full_malloc_oom(size);

I can't find where these function are defined, I'm hoping someone can show me.

Thanks and sorry for the "dumb" question.

Geoff

**Comment by alk** [comment]
They are defined by macros. tcmalloc.cc line 1785.
