### ISSUE TITLE
Failed to get backtrace while using heapchecker on ARM platform 

### ISSUE THREAD

**Issue by Umakumar01** [gperftools/gperftools#1219]
am facing the similar issue reported in #841  where heap profiler for ARM doesnt report the exact trace where memory leak is observed rather it shows only leak is observed

the issue is observed on ARM compiler compiled with gcc version 4.8.4 and not in gcc version 6.4 on gperftools version 2.6.1

```
heap profile: 6: 221 [ 6: 221] @ heapprofile
1: 33 [ 1: 33] @
1: 10 [ 1: 10] @
1: 10 [ 1: 10] @
1: 10 [ 1: 10] @
1: 10 [ 1: 10] @
1: 148 [ 1: 148] @

MAPPED_LIBRARIES
```:

any solution is available in gperftools 2.6.1 version

**Comment by alk** [comment]
Both arm environments are aarch64 and linux and same distro? Any case I would start checking your toolchain.
