### ISSUE TITLE
Possible Cross-compiling issue and how should I debug?

### ISSUE THREAD

**Issue by myanowitz** [gperftools/gperftools#1220]
I have an external embedded device:

```

root@gcp-a72:~/bin# uname -a

Linux gcp-a72 4.19.94-g5a23bc00e0 #1 SMP PREEMPT Wed Aug 12 17:54:08 UTC 2020 aarch64 GNU/Linux

```

Whenever I attempt to run something using libtcmalloc, I am getting, before any leak is detected:

```

Thread finding failed with -1 errno=9

Could not find thread stacks. Will likely report false leak positives.

Bus error

```

It runs as expected on Ubuntu 16.04. But whenever, I attempt to cross-compile to this device, I get that error.

 

1) I may not be passing the correct parameters to ./configure, so that maybe where the problem is:

     I am using:

_`./configure CC=/opt/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc CXX=/opt/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ --enable-frame-pointers --host=aarch64-linux-gnu AR=/opt/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-ar -with-sysroot=/opt/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/sysroots/aarch64-linux --with-gnu-ld`_

 

2) What is the proper way to debug (with gdb) this (assuming built correctly in the first step)?

**Comment by alk** [comment]
heap checker is actually not working on aarch64. I am not sure if it is worth fixing, since address sanitizer and similar are much superior.

Closing, but feel free to reopen if you have something to add.
