### ISSUE TITLE
allow custom stacktrace provider

### ISSUE THREAD

**Issue by romange** [gperftools/gperftools#1224]
Hi @alk ,

gperftool already provides customization of stacktrace providers via setenv. Unfortunately, libunwind code immediately crashes on aarch64 (see https://github.com/libunwind/libunwind/issues/68). Even more, gcc based stacktrace provider is using libunwind if it's linked into the binary. Therefore,  gperf profiler works on aarch64 only if it's linked without libunwind dependency.

There is [abseil based](https://github.com/abseil/abseil-cpp/blob/master/absl/debugging/stacktrace.h) stacktrace provider that has a similar signature as the one in gperftools. If we could programmatically set stacktrace provider we could use the one from abseil and not being dependent on a linker configuration of the binary. 

Do you mind if I send a PR that will allow setting stacktrace provider programmatically?

**Comment by alk** [comment]
Yes, that would be useful.

**Comment by romange** [comment]
the crash has been fixed on aarch64, closing.
