### ISSUE TITLE
malloc() sometimes spuriously returns nullptr

### ISSUE THREAD

**Issue by robryk** [gperftools/gperftools#1226]
Me and @veluca93 have found that, upon updating from gperftools-2.7 to gperftools-2.8, allocations started to sometimes return `nullptr` in a cpu- and allocation-heavy multithreaded process. Bisection found that the issue starts at be3da70298bf3d25c7d64655922ab82dd819ec98.

The issue can be reproduced by building https://gitlab.com/wg1/jpeg-xl (for example, according to the instructions in https://gitlab.com/wg1/jpeg-xl/-/blob/master/doc/developing_in_debian.md) and running `./ci.sh fast_benchmark`. The issue manifests itself as nondeterministic assertion failures of one of many assertions that check for non-null returns from malloc. 

If getting any tracing information, or testing patches, might be helpful, please say so.

**Comment by alk** [comment]
Closing as duplicate. BTW I was not able to do this ./ci.sh fast_benchmark thingy. It barks at missing file under build/tools or something.
