### ISSUE TITLE
memory leak in erl_eterm_alloc

### ISSUE THREAD

**Issue by ierasa** [gperftools/gperftools#1230]
Hi,

The switch got crashed due to OOM. We asked them to enable the memory patroller tool to detect the memory leak.
From the memory dump, we could see below back trace not freeing the memory.

Can someone help, 

STK ID : 69660  alloc: 64 bytes; # of allocs: 3747; # of free: 0
 /fabos/lib/libmp.so.1.0(snap_malloc+0xc4) [0x6861bd4]
 /fabos/lib/libmp.so.1.0(malloc+0x54) [0x6860774]
 /usr/confd/lib/libconfd.so(erl_eterm_alloc+0xac) [0x75b00a0]
 /usr/confd/lib/libconfd.so(erl_alloc_eterm+0x2c) [0x75abc40]
 /usr/confd/lib/libconfd.so(erl_mk_uint+0x30) [0x75a96f4]
 /usr/confd/lib/libconfd.so(val_to_term+0x5b0) [0x756caf4]
 /usr/confd/lib/libconfd.so(tag_val_to_term+0x40) [0x756d6a0]
 /usr/confd/lib/libconfd.so(tag_vals_to_termlist+0x80) [0x756d854]
 /usr/confd/lib/libconfd.so(confd_action_reply_values+0xcc) [0x757440c]
 /fabos/lib/libDcm.so(_ZN5DcmNs22ConfdActionpointWorker21DcmdConfdActionFinishEP15confd_user_infoi+0x458) [0xb0b924c]
 /fabos/lib/libDcm.so(_ZN5DcmNs27ConfdInterfaceObjectManager9sa_actionEP15confd_user_infoP7xml_tagP14confd_hkeypathP15confd_tag_valuei+0x398) [0xac5d014]
 /usr/confd/lib/libconfd.so [0x7576ae4]

**Comment by alk** [comment]
I am not sure how this could be related to gperftools. So closing. Reopen with more details if there is somehow relation with gperftools.
