### ISSUE TITLE
Confused on the warning: address $addr is longer than address length $address_length

### ISSUE THREAD

**Issue by Phantomape** [gperftools/gperftools#1234]
Wrote a simple program
```
#include <gperftools/profiler.h>
#include <iostream>

using namespace std;

int main() {
    ProfilerStart("./cpu.prof");
    const int64_t len = 1e9;
    int *arr = new int[len]; // Just ignore the mem leak here
    for (int i = 0; i < 1e9; i++)
        ;
    ProfilerStop();
    return 0;
}
```
And when I start using pprof in interactive mode, I typed ```list main```, which shows up some warnings about some address is longer than address length. I took a closer look at the code and found that 
![image](https://user-images.githubusercontent.com/8809221/100520227-af143980-31d7-11eb-8799-05f6869b99bc.png)
here sets the ```$sep_symbol``` to be _fini. However, some lib may contain symbol like ```fini```, which is causing such warnings. For example: ```objdump -d '/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28' | grep _fini | tail -n 1``` shows ```d6148:	74 26                	je     d6170 <_ZNSt13random_device7_M_finiEv@@GLIBCXX_3.4.18+0x30>```. I wonder if it is by designed?

**Comment by alk** [comment]
perl version of pprof is unsupported. Sorry. Please use golang version from github.com/google/pprof.

Closing as wontfix.
