### ISSUE TITLE
__FRAME_END__: pprof interpretation

### ISSUE THREAD

**Issue by RohanVDeshpande** [gperftools/gperftools#1236]
I am running pprof's heap profiler. I see the following:
`Total: 86.1 MB`
`66.1  76.7%  76.7%     86.1 100.0% __FRAME_END__`
`2.8   3.3%  80.0%      2.8   3.3% std::vector::_M_realloc_insert`
`.....`

What does '\_\_FRAME_END\_\_' mean?

Help would be much appreciated.

**Comment by alk** [comment]
We are using whatever symbol name addr2line will give us. If your compiler or compiler tool toolchain somehow produces such "odd" symbol name infos then we may end up with something like this. I don't really know what __FRAME_END__ is.
