### ISSUE TITLE
memory statistic diff in google heap profiler and real memory use

### ISSUE THREAD

**Issue by zhaozheng09** [gperftools/gperftools#1242]
My python **stablely** use 17GB memory.
`
10705 hadoop-+  20   0 33.453g 0.016t  93024 S 405.1  6.5   4560:23 python main.py
`
but google heap profiler tell:

`Total: 1354.5 MB`
`   282.9  20.9%  20.9%    282.9  20.9% std::string::_M_mutate`
`   180.9  13.4%  34.2%    406.0  30.0% tensorflow::OpKernel::OpKernel`
`   ....`
I'm sure that my `top`is correctly, so I think I have a error usage with google heap profiler

my profiler code : 
`
export LD_PRELOAD="`pwd`/tf_venv/libcudnn/libtcmalloc.so"
HEAPPROFILE=/tmp/test.prof python main.py $*
`
my tcmalloc version:`4.1.0`

**Comment by zhaozheng09** [comment]
Would anyone help me ? please

**Comment by zhaozheng09** [comment]
@alk ♪（＾∀＾●）ﾉｼ （●´∀｀）♪

**Comment by alk** [comment]
Indeed. Another possibility is if those python extensions allocate memory outside of malloc APIs (e.g. mmap directly).

This could be somewhat confirmed by posting /proc/<pid>/smaps

**Comment by zhaozheng09** [comment]
think you, guys~!
