### ISSUE TITLE
gperftools 2.9 `tcmalloc_minimal_unittest` fails on OS X 11.2.1

### ISSUE THREAD

**Issue by Moisan** [gperftools/gperftools#1252]
After compiling gperftools with the following arguments on OS X 11, I get the following error when launching `tcmalloc_minimal_unittest`.

```
./configure --disable-dependency-tracking
make tcmalloc_minimal_unittest
./tcmalloc_minimal_unittest
```

```
src/central_freelist.cc:330] tcmalloc: allocation failed 8192
```

This also matches the failures of [Homebrew CI when trying to build gperftools 2.9](https://github.com/Homebrew/homebrew-core/pull/71698).

**Comment by alk** [comment]
I am not able to reproduce. osex 10.15.7. So at least no something immediately dumb. Need help debugging this. Can you try same under debugger and showing what is backtrace ? Then I would probably need you to show me what sbrk and mmap returns when this fails (which looks like maybe first call to both).

Also this is x86-64 right? (have no idea if osex supports i386).

Also I assume 2.8.1 works ?

Also can you attach config.log and config.h ?

**Comment by Moisan** [comment]
> Also this is x86-64 right?.

Yes this is x86-64.

> Also I assume 2.8.1 works ?

Yes, 2.8.1 does work. 

Here are the [configure.log](https://gist.github.com/Moisan/4d5bbbe4d3dc6e793cf6dec877c9090f) and [configure.ac](https://gist.github.com/Moisan/6974bef3bbe73de64c5436123d9a9f25). The homebrew package uses the `-D_XOPEN_SOURCE` cflags. I tried with and without it, it fails the same way in both cases.

**Comment by alk** [comment]
Thanks. Can you attach strace (or struss or whatever there is on osex that logs syscalls)? Same test just wrap it with strace.

**Comment by alk** [comment]
Is there some kind of patching involved? Asking because I got my hands on latest osx and M1-based machine and it requires some configure tweaks to work, but then it works fine.

I found that:

$ ./configure --enable-stacktrace-via-backtrace

is necessary.

And then forcing this backtracing method is necessary.

$ make tcmalloc_unittest
$ TCMALLOC_STACKTRACE_METHOD=generic TCMALLOC_HEAP_LIMIT_MB=1024 ./tcmalloc_unittest

So definitely something worth a fix, but this seems to be different issue than what you're reporting.

**Comment by alk** [comment]
I pushed couple commits that make OSX pass tcmalloc_unittest out of the box.

**Comment by Moisan** [comment]
Sorry the delay, I confirm that this works for me locally:
```
$ ./configure --enable-stacktrace-via-backtrace
$ make tcmalloc_unittest
$ TCMALLOC_STACKTRACE_METHOD=generic TCMALLOC_HEAP_LIMIT_MB=1024 ./tcmalloc_unittest
```

Also, building from HEAD fixes the issue I had without any of these configure tweaks. If you were to make a release with those changes, we could integrate that directly to the Homebrew package.

**Comment by alk** [comment]
Done. 2.9.1 was just released.
