### ISSUE TITLE
Wrong ASSERT in do_free_with_callback

### ISSUE THREAD

**Issue by DuncanSands** [gperftools/gperftools#1254]
gperftools 2.9.0, GCC 10.2.1, ubuntu bionic, ASSERT enabled.

I saw the following crash on resizing an already large std::string.  The old memory is deallocated:
```
      void
      _M_dispose()
      {
        if (!_M_is_local())
          _M_destroy(_M_allocated_capacity);
      }
```
That calls sized delete with the size of the string (12686) as the size to deallocate, resulting in a call to tc_free_sized with size=12686.

That flies straight past the following odd check in tc_free_sized as 12686 is not a multiple of kPageSize (which is 8192):

```
#ifndef NO_TCMALLOC_SAMPLES
  // if ptr is kPageSize-aligned, then it could be sampled allocation,
  // thus we don't trust hint and just do plain free. It also handles
  // nullptr for us.
  if (PREDICT_FALSE((reinterpret_cast<uintptr_t>(ptr) & (kPageSize-1)) == 0)) {
    tc_free(ptr);
    return;
  }
#else
```

I call the check odd because it seems to think that ''size'' is some kind of tcmalloc internal size, when it could be anything.

Anyway, we reach the call ''do_free_with_callback(ptr, &InvalidFree, true, size)" at the end of tc_free_sized, so we get here:

```
void do_free_with_callback(void* ptr,
                           void (*invalid_free_fn)(void*),
                           bool use_hint, size_t size_hint) {
  ThreadCache* heap = ThreadCache::GetCacheIfPresent();

  const PageID p = reinterpret_cast<uintptr_t>(ptr) >> kPageShift;
  uint32 cl;

#ifndef NO_TCMALLOC_SAMPLES
  // we only pass size hint when ptr is not page aligned. Which
  // implies that it must be very small object.
  ASSERT(!use_hint || size_hint < kPageSize);
  ^ #### THIS FAILS ####
```
We again have an odd check that seems to think that size_hint (12686) is some kind of internal tcmalloc size, rather than something coming straight from whatever ''size'' value was passed to sized delete.  There is no reason why size_hint should be smaller than kPageSize, and indeed it isn't and the ASSERT fires.

**Comment by alk** [comment]
Thanks for detailed bug report. Fixed now.
