### ISSUE TITLE
Unused TCMALLOC_FOR_DEBUGALLOCATION?

### ISSUE THREAD

**Issue by reluctantbugreporter** [gperftools/gperftools#1266]
What is the use of `TCMALLOC_FOR_DEBUGALLOCATION`?

It is defined in both CMakeLists.txt and Makefile.am but I could not find any use of it. It was used last time in version 1.7 and replaced by `TCMALLOC_USING_DEBUGALLOCATION` in version 1.8.

`TCMALLOC_USING_DEBUGALLOCATION` is defined in debugallocation.cc#84 and used in tcmalloc.cc.

**Comment by alk** [comment]
The use is in preventing tcmalloc.cc from installing it's own malloc extensions instance and letting debugallocation to do so instead. As noted in the comments.

```
TCMallocGuard::TCMallocGuard() {
  if (tcmallocguard_refcount++ == 0) {
    ReplaceSystemAlloc();    // defined in libc_override_*.h
    tc_free(tc_malloc(1));
    ThreadCache::InitTSD();
    tc_free(tc_malloc(1));
    // Either we, or debugallocation.cc, or valgrind will control memory
    // management.  We register our extension if we're the winner.
#ifdef TCMALLOC_USING_DEBUGALLOCATION
    // Let debugallocation register its extension.
#else
    if (RunningOnValgrind()) {
      // Let Valgrind uses its own malloc (so don't register our extension).
    } else {
      MallocExtension::Register(new TCMallocImplementation);
    }
#endif
  }
}
```

**Comment by alk** [comment]
Feel free to reopen if you have any specific questions or suggestions left.
