### ISSUE TITLE
what's the mean of Bytes in page heap freelist?

### ISSUE THREAD

**Issue by jyxjrh** [gperftools/gperftools#1268]
My tcmalloc version is 2.7.
the getstats ouput like this:
MALLOC:     6406282016 ( 6109.5 MiB) Bytes in use by application
MALLOC: +  86959882240 (82931.4 MiB) Bytes in page heap freelist
MALLOC: +    398013080 (  379.6 MiB) Bytes in central cache freelist
MALLOC: +     10408448 (    9.9 MiB) Bytes in transfer cache freelist
MALLOC: +    510976072 (  487.3 MiB) Bytes in thread cache freelists
MALLOC: +    130023424 (  124.0 MiB) Bytes in malloc metadata
MALLOC:   ------------
MALLOC: =  94415585280 (90041.7 MiB) Actual memory used (physical + swap)
MALLOC: +     29671424 (   28.3 MiB) Bytes released to OS (aka unmapped)
MALLOC:   ------------
MALLOC: =  94445256704 (90070.0 MiB) Virtual address space used
MALLOC:
MALLOC:         538154              Spans in use
MALLOC:            187              Thread heaps in use
MALLOC:           8192              Tcmalloc page size
------------------------------------------------

the Bytes in page heap freelist is more than physic memory. Is there any memory leak?
thank you!

**Comment by Charles-Xiao** [comment]
Hi, this problem has been solved?

**Comment by joson-cn** [comment]
> Hi, this problem has been solved?

hi，have you slove it 。

**Comment by lszChain** [comment]
Hi，I have the same problem, how did you solve it . Thanks!!!
