### ISSUE TITLE
Test failures on Kubuntu 21.04

### ISSUE THREAD

**Issue by Lastique** [gperftools/gperftools#1272]
After building gperftools 2.9.1 on Kubuntu 21.04 its unit tests fail:

- stacktrace_unittest
- sampling_test.sh
- sampling_debug_test.sh

Here is a full build log, where you will find configure/build options and the failed test logs: 
[build_log.txt](https://github.com/gperftools/gperftools/files/6384156/build_log.txt)
Additionally, I'm attaching a backtrace for stacktrace_unittest as it is failing with SIGABRT: 
[stacktrace_unittest.bt.txt](https://github.com/gperftools/gperftools/files/6384158/stacktrace_unittest.bt.txt)

**Comment by Lastique** [comment]
Apparently, the test failures are caused by the fact that LTO is enabled by default in Kubuntu 21.04. If I disable LTO by adding `export DEB_BUILD_MAINT_OPTIONS = optimize=-lto` to the packaging scripts, the tests succeed.

You might want to explicitly disable LTO in gperftools build scripts, if it is not compatible with the optimization.

**Comment by alk** [comment]
thanks for reporting this and apologies for delay. We should now handle lto. (issue was tests-only)
