### ISSUE TITLE
TCMALLOC_DONT_PREFER_LIBUNWIND should be user settable

### ISSUE THREAD

**Issue by acmorrow** [gperftools/gperftools#1276]
Currently, you can't build gperftools with a user defined `-DTCMALLOC_DONT_PREFER_LIBUNWIND` and `-Wall`, `-Werror` because you will get an error like:

```
error: 'TCMALLOC_DONT_PREFER_LIBUNWIND' macro redefined [-Werror,-Wmacro-redefined]
```

This happens because the definition of `TCMALLOC_DONT_PREFER_LIBUNWIND` is unconditional:

```
// ppc and i386 implementations prefer arch-specific asm implementations.
// arm's asm implementation is broken
#if defined(__i386__) || defined(__ppc__) || defined(__PPC__)
#if !defined(NO_FRAME_POINTER)
#define TCMALLOC_DONT_PREFER_LIBUNWIND
#endif
#endif
```

If this were written as:

```
#ifndef TCMALLOC_DONT_PREFER_LIBUNWIND
// ppc and i386 implementations prefer arch-specific asm implementations.
// arm's asm implementation is broken
#if defined(__i386__) || defined(__ppc__) || defined(__PPC__)
#if !defined(NO_FRAME_POINTER)
#define TCMALLOC_DONT_PREFER_LIBUNWIND
#endif
#endif
#endif
```

Then a user selected setting for this value could be honored.

**Comment by alk** [comment]
Yes, this can be fixed. But why not configure libunwind out instead? Or you want it to be available just in case but not preferred ?

**Comment by alk** [comment]
I have https://github.com/alk/gperftools/commit/f15f26978b1f64c86371a134cd0fe22e12b8490f (which somehow I cannot create as a pull request to this repo) which is basically what you proposed. But lets first answer about "why-s".

**Comment by acmorrow** [comment]
@alk - Correct, basically as you suggested. We would like `libunwind` available as the last resort fallback, should a more performant option not exist. But given the issues in #1277 we never want it to be preferred.

**Comment by alk** [comment]
Fixed now. You should not see warning about duplicate define anymore.
