### ISSUE TITLE
Abnormal packet reading  by libunwind when SSH and tcmalloc are used together

### ISSUE THREAD

**Issue by cjl20062529** [gperftools/gperftools#1283]
In an x86 system, when the memory of tcmalloc is insufficient, the heap extension obtains the current call stack through libunwind. libunwind creates a pipe to check whether the address is valid.

libunwind-1.3.1/src/x86_64/Ginit.c
```
......
static int mem_validate_pipe[2] = {-1, -1};
static inline void
open_pipe (void)
{
  /* ignore errors for closing invalid fd's */
  close (mem_validate_pipe[0]);
  close (mem_validate_pipe[1]);

  pipe2 (mem_validate_pipe, O_CLOEXEC | O_NONBLOCK);
}
```

when we run scp command in linux, the scp process inherits the pipeline that it applies for through tcmalloc to the subprocess ssh, but in the main function of ssh.c, ssh close all fds greater than STDERR_FILENO, libunwind does not know that fd is closed, continue to read, it read away the contents of the ssh process.

in ssh.c：
```
...
#ifndef HAVE_SETPROCTITLE
	/* Prepare for later setproctitle emulation */
	/* Save argv so it isn't clobbered by setproctitle() emulation */
	saved_av = xcalloc(ac + 1, sizeof(*saved_av));
	for (i = 0; i < ac; i++)
		saved_av[i] = xstrdup(av[i]);
	saved_av[i] = NULL;
	compat_init_setproctitle(ac, av);
	av = saved_av;
#endif

	seed_rng();

	/*
	 * Discard other fds that are hanging around. These can cause problem
	 * with backgrounded ssh processes started by ControlPersist.
	 */
	closefrom(STDERR_FILENO + 1); **----> The function close all fds greater than STDERR_FILENO.**
...
    fd = open(xxx) //-------> **reopen a fd, the fd number is the same as the pipe fd in libunwind**
    read(fd, xxx)
```

so, when ssh process read again, it return content that does not meet expectations.
Is there any problem with tcmalloc in this scenario?

**Comment by alk** [comment]
malloc has nothing to do with this.

Also are you sure this description is accurate? Code you list above has O_CLOEXEC when pipe is opened (by libunwind, not us). So I am struggling to see how scp could inherit anything there.

Closing since there is really nothing we have to do with this. But feel free to reopen if you have anything to add (perhaps I misunderstood something).
