### ISSUE TITLE
Memory leak with malloc is not reflected in heapcheck whereas leak via new operator is reflected

### ISSUE THREAD

**Issue by Bhuvaneswari07** [gperftools/gperftools#1286]
I try to check a memory leak using gperftool 2.7.9 ,for this i manually made a leak as int *ptr=(int *)malloc(1000) in a particular api on arm architecture ,but that was not reflected while doing heapcheck .whereas i do the same via "int *p = new int[1000] " using new operator it reflects.
Steps i followed:
1.export LD_PRELOAD=/tmp/aamp/usr/lib/libtcmalloc.so.4:$LD_PRELOAD
2.HEAPCHECK=normal HEAP_CHECK_DUMP_DIRECTORY=/opt/  TCMALLOC_STACKTRACE_METHOD=libgcc <binary >

**Comment by alk** [comment]
heap checker wasn't really functional on arms until very recently. It should now work with latest code.
