### ISSUE TITLE
crosscompile with arm-hisiv400-linux， undefined-reference-to _Unwind_GetIP 

### ISSUE THREAD

**Issue by wuxiangbing** [gperftools/gperftools#1289]
hi, there is some problems  while crosscompile with arm-hisiv400-linux:
I configure with：
./configure --host=arm-hisiv400-linux --prefix=/home/xxx/gperftools LDFLAGS=-L/home/xxx/libunwind/lib CPPFLAGS=-I/home/xxx/libunwind/include

then make it, error occurrs：
libtool: link: arm-hisiv400-linux-g++ -std=gnu++11 -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-result -g -O2 -pthread -o .libs/debugallocation_test src/tests/debugallocation_test-debugallocation_test.o  -L/home/xxx/libunwind/lib ./.libs/libtcmalloc_debug.so /home/xxx/libunwind/lib/libunwind.so -lc -lgcc   ....  /libunwind/lib -Wl,-rpath -Wl,/opt/hisi-linux/x86-arm/arm-hisiv400-linux/bin/../lib/gcc/arm-hisiv400-linux-gnueabi/4.8.3/../../../../arm-hisiv400-linux-gnueabi/lib

 ./.libs/libtcmalloc_debug.so: undefined reference to `_Unwind_GetIP'

how to fixed?

**Comment by Shipley1105** [comment]
I got `Undefined reference to 'RunningOnValgrind' ` while compiling with arm-gcc6.3-linux-uclibceabi

**Comment by Shipley1105** [comment]
> I got `Undefined reference to 'RunningOnValgrind' ` while compiling with arm-gcc6.3-linux-uclibceabi

Here is Solution:
```bash
export CROSS_COMPILE=arm-gcc6.3-linux-uclibceabi-
./configure --prefix=/home/xiepeng1/valgrind-3.19.0/valgrind-install \
--host=arm-gcc6.3-linux-uclibceabi \
CC=${CROSS_COMPILE}gcc \
CPP=${CROSS_COMPILE}cpp \
CXX=${CROSS_COMPILE}g++ \
LD=${CROSS_COMPILE}ld   \
AR=${CROSS_COMPILE}ar
```

**Comment by alk** [comment]
So, first ./configure incantation looks generally right. It is what I'd do. Why it fails at _Unwind_GetIP is really odd. What libunwind do you feed it ? Also perhaps you can attach config.log. Usually debugging configure-time troubles is best to start from this file.
