### ISSUE TITLE
basic CPUPROFILE usage fails on osx (with gperftools installed via brew)

### ISSUE THREAD

**Issue by timotheecour** [gperftools/gperftools#1292]
I tried to follow the steps outlined in (see below links) but nothing worked:

```
brew install gperftools
brew test gperftools # works, sanity check

clang -o /tmp/z01 -lprofiler hello.c
CPUPROFILE=/tmp/prof.out /tmp/z01
pprof /tmp/z01 /tmp/prof.out
```

```
Using local file /tmp/z01.
Using local file /tmp/prof.out.
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/lib/liboah.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/lib/liboah.dylib (No such file or directory)
...
````

likewise with `/usr/local/opt/gcc/bin/gcc-11 -o /tmp/z01 -L/usr/local/Cellar/gperftools/2.9.1/lib -lprofiler -g hello.c`

## links
* https://stackoverflow.com/questions/22623934/how-to-install-gprof-on-os-x
* https://stackoverflow.com/questions/10562280/line-number-in-google-perftools-cpu-profiler-on-macosx?noredirect=1&lq=1
* https://stackoverflow.com/questions/29308174/how-to-profile-from-the-command-line-on-mac-os-x?noredirect=1&lq=1
* https://gperftools.github.io/gperftools/cpuprofile.html

**Comment by jcolafrancesco** [comment]
It seems linked to some libs moved around on recent versions of MAC OS: https://developer.apple.com/forums/thread/655588

Reproduced through an Homebrew install on my side.
Trying to reproduce installing from sources.

**Comment by ThanHenderson** [comment]
Was there ever any luck with this issue?

**Comment by JamesYang007** [comment]
Anyone figure this out?

**Comment by TBurlacu-tud** [comment]
Still an issue

**Comment by yilongdong** [comment]
I've met the question

**Comment by Nijaid** [comment]
Same issue arises with gperftools installed via MacPorts

**Comment by melishua** [comment]
Same issue, could someone please share the solution? thanks!

**Comment by ropmacedo** [comment]
Just to keep this list up and running. I'm also having the same issue with gperftools installed via MacPorts

**Comment by lsk567** [comment]
Same issue here.

**Comment by nav-mohan** [comment]
Same issue here.

**Comment by mttjcksn** [comment]
Same issue!

**Comment by alk** [comment]
it works for me. Few notes:

a) make sure that your program runs at least 10 seconds or to get at least some precision.

b) use pprof from github.com/google/pprof (golang version). But be aware of https://github.com/google/pprof/issues/477

As for brew version of gperftools, since I am not really OSX expert, also do consider checking which verion(s) it is actually giving you.

**Comment by alk** [comment]
E.g. see below. I also tested that whenever graphviz is installed pprof --http thingy works (which is my main mode of interaction with profiles which I highly recommend)

```
alk@hair gperftools % c++ -Wall -O2 -o malloc_bench_std benchmark/malloc_bench.cc benchmark/run_benchmark.c -L.libs -lprofiler
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
alk@hair gperftools % CPUPROFILE=$PWD/pr DYLD_LIBRARY_PATH=.libs ./malloc_bench_std
profiler before init
profiler after init
Trying to randomize freelists...done.
Benchmark: bench_fastpath_throughput                        32.939903 nsec
Benchmark: bench_fastpath_throughput                        38.229328 nsec
Benchmark: bench_fastpath_throughput                        38.182063 nsec
PROFILE: interrupts/evictions/bytes = 1648/595/74568
alk@hair gperftools % pprof --text ./pr
Local symbolization failed for libsystem_kernel.dylib: error reading fat Mach-O file /usr/lib/system/libsystem_kernel.dylib: architecture not found in /usr/lib/system/libsystem_kernel.dylib: arm64
Local symbolization failed for libsystem_malloc.dylib: stat /usr/lib/system/libsystem_malloc.dylib: no such file or directory
Local symbolization failed for libsystem_c.dylib: stat /usr/lib/system/libsystem_c.dylib: no such file or directory
Local symbolization failed for libdyld.dylib: stat /usr/lib/system/libdyld.dylib: no such file or directory
Local symbolization failed for libc++abi.dylib: stat /usr/lib/libc++abi.dylib: no such file or directory
Some binary filenames not available. Symbolization may be incomplete.
Try setting PPROF_BINARY_PATH to the search path for local binaries.
File: liboah.dylib
Type: cpu
Showing nodes accounting for 16.48s, 100% of 16.48s total
Dropped 1 node (cum <= 0.08s)
      flat  flat%   sum%        cum   cum%
    14.11s 85.62% 85.62%     15.09s 91.57%  [libsystem_malloc.dylib]
        1s  6.07% 91.69%         1s  6.07%  [libsystem_kernel.dylib]
     0.44s  2.67% 94.36%      0.44s  2.67%  __ZNSt3__124uniform_int_distributionIlEclINS_26linear_congruential_engineIjLj48271ELj0ELj2147483647EEEEElRT_RKNS1_10param_typeE
     0.37s  2.25% 96.60%      4.19s 25.42%  [libc++abi.dylib]
     0.30s  1.82% 98.42%      7.86s 47.69%  __Z24randomize_one_size_classm
     0.22s  1.33% 99.76%      0.22s  1.33%  __ZL12measure_onceP14internal_benchl.cold.2
     0.04s  0.24%   100%      8.47s 51.40%  __ZL25bench_fastpath_throughputlm
         0     0%   100%      5.58s 33.86%  <unknown>
         0     0%   100%     16.48s   100%  [libdyld.dylib]
         0     0%   100%      7.86s 47.69%  __Z22randomize_size_classesv
         0     0%   100%      8.60s 52.18%  __ZL12measure_onceP14internal_benchl
         0     0%   100%     16.48s   100%  _main
         0     0%   100%      8.62s 52.31%  _report_benchmark
```

**Comment by alk** [comment]
But also, it looks like whatever /proc/<pid>/maps-like output we generate with profile isn't right on OSX. I.e. see those "no such file" messages above. Someone (not me) should consider debugging and fixing it.

Here is pointer(s).  Our profile format (so called legacy, because modern pprof's native format is proto) is described here: https://github.com/gperftools/gperftools/blob/master/docs/cpuprofile-fileformat.html

Part of that is dump of /proc/<pid>/maps. On Linux we just do that. On OSX apparently there is no procfs, so we synthesize it. In this code: https://github.com/gperftools/gperftools/blob/9d44463380716ebad2f8ba13ce8a737f22bb2602/src/base/sysinfo.cc#L749

Something is apparently making it output not entirely right paths, perhaps.

**Comment by Deeperand** [comment]
Still have this issue at March 2024

**Comment by alk** [comment]
We still need someone who likes and knows this OS to help us update pprof to do the right thing.

What I said above above /proc/pid/maps stuff likely isn't entirely accurate. otool also dump 'wrong' paths for dynamic libraries. It doesn't seem something very new (maybe few years new, but it wasn't the case some number of years ago). Looks like for whatever reason apple choose to place those dynamic libraries somewhere else, or hide them who knows.

So I propose, first, someone googles and asks around or somehow else figures out where those files actually are. Perhaps find / incantation might help you find those files. We're talking about what seems like equivalent of libc for osx e.g. /usr/lib/system/libsystem_c.dylib

With that we should be able to figure out how to update github.com/google/pprof to find those files (we can also update our obsolete perl version but maybe not). I can help with the later but I need help with first.

@Deeperand @lsk567 @ropmacedo @mttjcksn @melishua

**Comment by peterhuang621** [comment]
Hi, I'm in the first day to learn gperftools. It seems like gperftools can't work currently on Macos (not fixed it yet?), and the only way to use it is to switch to go version pprof? Maybe I should consider studying it in Linux or Win now? Thank you.

**Comment by alk** [comment]
We're not in "can't work" territory on OSX. There is definitely issues in our support of cpu profiling and so called heap profiling, but they work (for some definition). Malloc bits work (but OSX "features" makes performance advantage mostly moot; malloc/new performance is broken on those OSes).

For sure, you'll get fullest and best experience on GNU/Linux (not windows), but learning by fixing/doing could also be great motivation. If for some reason Apple's systems are your passion, feel free to dive in and contribute.

**Comment by peterhuang621** [comment]
> We're not in "can't work" territory on OSX. There is definitely issues in our support of cpu profiling and so called heap profiling, but they work (for some definition). Malloc bits work (but OSX "features" makes performance advantage mostly moot; malloc/new performance is broken on those OSes).
> 
> For sure, you'll get fullest and best experience on GNU/Linux (not windows), but learning by fixing/doing could also be great motivation. If for some reason Apple's systems are your passion, feel free to dive in and contribute.

Thanks for your prompt reply and suggestions. I get it likes a temporary OSX support issue. I am switching my studies to linux server and all looks fine now. 👍

**Comment by alk** [comment]
So I looked at this some more. Basic usage definitely works. There is issue of failing to symbolize those "system" libraries. And it appears to be some sort of sick intention of OSXers. But all the non-system binaries are symbolized correctly. At least on my test box.

To summarize: those 'can't open file' messages are Apple's intention. Go bug them if you care, but it won't break your profiling workloads too much. Also don't use our pprof version. Use github.com/google/pprof (get it by go install github.com/google/pprof@latest and it'll be at ~/go/bin/pprof). We'll soon stop shipping "our" version entirely.

Reference on the system libraries on osx: https://developer.apple.com/forums/thread/655588?answerId=665804022#665804022 and https://developer.apple.com/forums/thread/715385

**Comment by ZJZ0405** [comment]
> Hi, I'm in the first day to learn gperftools. It seems like gperftools can't work currently on Macos (not fixed it yet?), and the only way to use it is to switch to go version pprof? Maybe I should consider studying it in Linux or Win now? Thank you.
> 嗨，我是学习 gperftools 的第一天。gperftools 目前似乎无法在 Macos 上运行（还没有修复？），使用它的唯一方法是切换到 go 版本 pprof？也许我现在应该考虑在 Linux 或 Win 中学习它？谢谢。

I agree with you. Maybe I should sleep and use linux.
