### ISSUE TITLE
cmake says "Could NOT find Gperftools"

### ISSUE THREAD

**Issue by DecapitatedKneecap** [gperftools/gperftools#1296]
I am trying to build this c++ project:

https://github.com/Restream/reindexer

When I open the folder in CLion, cmake throws this error:

-- Could NOT find Gperftools (missing: GPERFTOOLS_LIBRARIES GPERFTOOLS_INCLUDE_D
IR)

I have also tried building with cmake command line and I get the same error.

I am on Windows 7 x64. CLion support directed me to this readme on your project:

https://github.com/gperftools/gperftools/blob/master/README_windows.txt

Does the fact that I am on Windows have anything to do with this error? I will also add that I am brand new to c++ and know very little about c++ package management. Thanks.

**Comment by alk** [comment]
Sorry for delay. Consider asking reindexer people. It is their cmake thingy appears to be trying and failing.
