### ISSUE TITLE
Do we have plan to support tcmalloc on QNX os?

### ISSUE THREAD

**Issue by MashoujiangPlusAI** [gperftools/gperftools#1301]
Hi,

I am new to gperftools, and investigating the possible of porting tcmalloc on QNX, I am wandering if the project is planing to support QNX platform? or does anyone have the experience on porting to QNX? Appreciate if you have any comment about my question.

Thanks!

**Comment by alk** [comment]
deduping this to #1147 

But also have a look at #805 someone seemingly managed to build it there.

I personally have no plans to contribute anything, but any patches for this os I'll merge.
