### ISSUE TITLE
32-bit int overflow in heap profile

### ISSUE THREAD

**Issue by sporksmith** [gperftools/gperftools#1303]
Originally https://github.com/golang/go/issues/48580, and bounced from https://github.com/google/tcmalloc/issues/100

I'm profiling a long-running program using `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_and_profiler.so.4 HEAPPROFILE=shadow.heap HEAP_PROFILE_TIME_INTERVAL=180`

The initial profiles are parsed fine by `pprof`, but after a point `pprof` refuses to parse any subsequent profiles.

Inspecting the profiles themselves, it looks like a 32-bit integer is overflowing.

First line from the last parseable profile:
```
heap profile: 2237252: 888238604 [2144665071: 188608279238] @ heapprofile
```

And from the first un-parseable profile:
```
heap profile: 2250136: 892383061 [-2147316050: 188867582594] @ heapprofile
```

I've confirmed that editing the files to change the negative number to a positive number allows `pprof` to parse it. It also works if I put a number there too large to be represented by a 32-bit int, suggesting that `pprof` supports a larger integer size.

**Comment by lindsayad** [comment]
I ran into this exact issue today

**Comment by Spongman** [comment]
is that responsible for this nonsense?
![image](https://user-images.githubusercontent.com/1088194/206081228-55b2e1f5-c1fa-4eb6-a308-7fe63f8ff2c1.png)

**Comment by vincentbernat** [comment]
This looks easy to fix:
```patch
diff --git a/src/heap-profile-stats.h b/src/heap-profile-stats.h
index 1e0359a4d7df..7fb4884c4e5b 100644
--- a/src/heap-profile-stats.h
+++ b/src/heap-profile-stats.h
@@ -58,10 +58,10 @@ struct HeapProfileStats {
         alloc_size - free_size == other.alloc_size - other.free_size;
   }

-  int32 allocs;      // Number of allocation calls.
-  int32 frees;       // Number of free calls.
-  int64 alloc_size;  // Total size of all allocated objects so far.
-  int64 free_size;   // Total size of all freed objects so far.
+  uint64 allocs;      // Number of allocation calls.
+  uint64 frees;       // Number of free calls.
+  uint64 alloc_size;  // Total size of all allocated objects so far.
+  uint64 free_size;   // Total size of all freed objects so far.
 };

 // Allocation and deallocation statistics per each stack trace.
diff --git a/src/heap-profile-table.cc b/src/heap-profile-table.cc
index 93d592c3b7fe..938aa19db929 100644
--- a/src/heap-profile-table.cc
+++ b/src/heap-profile-table.cc
@@ -288,7 +288,7 @@ int HeapProfileTable::UnparseBucket(const Bucket& b,
     profile_stats->free_size += b.free_size;
   }
   int printed =
-    snprintf(buf + buflen, bufsize - buflen, "%6d: %8" PRId64 " [%6d: %8" PRId64 "] @%s",
+    snprintf(buf + buflen, bufsize - buflen, "%6" PRIu64 ": %8" PRIu64 " [%6" PRIu64 ": %8" PRIu64 "] @%s",
              b.allocs - b.frees,
              b.alloc_size - b.free_size,
              b.allocs,
```
However, there are other places were the cast are just wrong (cast to `int`, cast to `size_t`).

**Comment by alk** [comment]
Fixed. Thanks.
