### ISSUE TITLE
Cannot analyze the caller of some stl functions

### ISSUE THREAD

**Issue by akemihomura0105** [gperftools/gperftools#1304]
When using HeapProfiler for analysis, some stl functions do not show the caller. The pdf output using pprof is as follows.

Is this phenomenon normal?
![捕获](https://user-images.githubusercontent.com/43955018/135022413-93a5311b-4f88-4f4b-bad5-97000811fd06.PNG)
![捕获1](https://user-images.githubusercontent.com/43955018/135022415-2b75c359-f1fb-412a-9592-d18c04ffa21e.PNG)

**Comment by alk** [comment]
This suggests lack of completely functional stack traces capturing support. Perhaps you're using frame pointers and some STL bits are built without frame pointers. There is nothing that STL bits do that would break our profilers.
