### ISSUE TITLE
coredump when using cpu profile

### ISSUE THREAD

**Issue by cjcanbibi** [gperftools/gperftools#1306]
Use cpu profile in gperftools-2.7 to check cpu load of my process. At first, my prgram link libtcmalloc_mininal.a, libprofiler.a, and libunwind.a, then I starup it. But process coredump at a short running time spot. The coredump message is:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  access_mem (as=<optimized out>, write=0, arg=<optimized out>, val=0x7f8f28fe06b8, addr=7) at x86_64/Ginit.c:164
164     x86_64/Ginit.c: No such file or directory.
[Current thread is 1 (Thread 0x7f8f28fe5700 (LWP 25944))]
(gdb) bt
#0  access_mem (as=<optimized out>, write=0, arg=<optimized out>, val=0x7f8f28fe06b8, addr=7) at x86_64/Ginit.c:164
#1  access_mem (as=<optimized out>, addr=7, val=0x7f8f28fe06b8, write=<optimized out>, arg=<optimized out>)
    at x86_64/Ginit.c:150
#2  0x000055fa32c89060 in dwarf_get (c=0x7f8f28fe0ed0, c=0x7f8f28fe0ed0, val=0x7f8f28fe06b8, loc=...)
    at ../include/tdep/libunwind_i.h:137
#3  apply_reg_state (c=c@entry=0x7f8f28fe0ed0, rs=rs@entry=0x55fa34a76b78 <local_addr_space+29880>)
    at dwarf/Gparser.c:766
#4  0x000055fa32c8952f in _ULx86_64_dwarf_find_save_locs (c=c@entry=0x7f8f28fe0ed0) at dwarf/Gparser.c:849
#5  0x000055fa32c87679 in _ULx86_64_dwarf_step (c=c@entry=0x7f8f28fe0ed0) at dwarf/Gstep.c:35
#6  0x000055fa32c87346 in _ULx86_64_step (cursor=cursor@entry=0x7f8f28fe0ed0) at x86_64/Gstep.c:42
#7  0x000055fa32c85525 in GetStackTraceWithContext_libunwind (result=0x7f8f28fe1348, max_depth=<optimized out>,
    skip_count=<optimized out>, ucp=<optimized out>) at src/stacktrace_libunwind-inl.h:138
#8  0x000055fa32c85c3c in GetStackTraceWithContext (result=result@entry=0x7f8f28fe1348,
    max_depth=max_depth@entry=63, skip_count=skip_count@entry=3, uc=0x7f8f28fe15c0) at src/stacktrace.cc:305
#9  0x000055fa32c82906 in CpuProfiler::prof_handler (signal_ucontext=<optimized out>,
    cpu_profiler=0x55fa34a6b0a0 <CpuProfiler::instance_>, sig=<optimized out>) at src/profiler.cc:359
#10 0x000055fa32c8332b in ProfileHandler::SignalHandler (sig=27, sinfo=0x7f8f28fe16f0, ucontext=0x7f8f28fe15c0)
    at src/profile-handler.cc:530

Anyone know the reasons?

**Comment by alk** [comment]
Unfortunately when stuff crashes in libunwind there is not much we can do. Compilers have in past occasionally produced broken unwind info. So it could be your case.

libunwind may have some bug(s) too.

I cannot think of anything else.

Consider reporting you case to libunwind folk. And/or try different stacktrace capturing method in gperftools. Via TCMALLOC_STACKTRACE_METHOD. Discover supported methods by setting TCMALLOC_STACKTRACE_METHOD_VERBOSE=t.
