### ISSUE TITLE
memleak exceed int range when using heap-checker

### ISSUE THREAD

**Issue by zhangyiru** [gperftools/gperftools#1308]
![image](https://user-images.githubusercontent.com/15630061/137467612-5f49bde2-8bcc-44cc-bb4d-3a409180f0ab.png)

when i use heap-checker, if memleak exceed int range, the result is 0
so i change the type bytes to size_t，please review this commit, thx ~
#1307

**Comment by alk** [comment]
Thanks for the patch. Applied and closing.
