### ISSUE TITLE
stacktrace_unittest aborted in arm

### ISSUE THREAD

**Issue by zhangyiru** [gperftools/gperftools#1309]
./configure && make && make check 

![image-20211018104302015](https://user-images.githubusercontent.com/15630061/137667874-7d8da2e4-957d-456d-a5e6-6fbb65dcc20b.png)

i write a demo to verity whether GetStackTrace return a value that exceed 0，but result is Segmentation fault.
![image](https://user-images.githubusercontent.com/15630061/137667928-3d237181-9f98-4f36-805e-51e7a5308624.png)

glibc-debuginfo and gperftools-debuginfo is installed. but gdb result is this
![image](https://user-images.githubusercontent.com/15630061/137668077-ae74171e-ab03-49ca-85fe-d54287387c13.png)

version:
gperftools-2.81 
kernel 4.14
gcc10.3
glibc2.34

any ideas? thx ~

**Comment by zhangyiru** [comment]
#751 
i use the --enable-stacktrace-via-backtrace flag to configure, but result is same

**Comment by alk** [comment]
This is 32-bit arm right? In any case, ./stacktrace_unittest passes for me on armhf-linux (I tested with modern Debian). Try our latest code. Also diagnose with TCMALLOC_STACKTRACE_METHOD_VERBOSE=t environment variable set.

(Please reopen if you can still reproduce this somehow; I am curious, albeit I do care much less about legacy arm than aarch64 (aka arm64))
