### ISSUE TITLE
Heap Profiler not reporting all resident memory as in-use memory

### ISSUE THREAD

**Issue by eslam-ahmed-khair** [gperftools/gperftools#1311]
Hello,

I have a case where I want to profile the resident memory used by an application at a given point by linking to `-ltcmalloc` and running with the environment variable `HEAPPROFILE`.

However, in a lot of cases whenever the profiler dumps the heap profile and reports the in-use memory, it is often not close the resident memory shown by `htop`. an example would be a program reaching  a resident memory of 370 MB but the profiler only reports 202 MB as in-use and breaks them down, yet it neglects the remaining memory. Can I correct this behavior? as I need the complete breakdown of the allocated live memory.

Any Help would be appreciated,
Thanks

**Comment by Hello71** [comment]
heap profilers measure anonymous memory, i.e. memory allocated with malloc or similar. RSS also includes file-backed memory, such as executable files.
