### ISSUE TITLE
Sidestep interception not working in ARM64

### ISSUE THREAD

**Issue by navch** [gperftools/gperftools#1314]
As there are new instruction set on ARM platform. So side interception won't work. Is this planned to make sidestep work on ARM64 platform? any alternative of this?

**Comment by alk** [comment]
override mode perhaps ? No plans. And I am not sure we can keep maintaining patching thingy at all moving forward. We're only malloc doing this trick on windows. Surely others somehow manage without. Perhaps we do too.
