### ISSUE TITLE
released snapshots differ from their counterpart tags

### ISSUE THREAD

**Issue by romange** [gperftools/gperftools#1321]
Take https://github.com/gperftools/gperftools/releases/download/gperftools-2.9.1/gperftools-2.9.1.tar.gz for example.

It's missing cmake build files while git tag is missing automake files. 

Providing snapshot to demonstrate the difference. Is it intentional?

![Screenshot from 2022-01-15 05-09-26](https://user-images.githubusercontent.com/3674760/149606764-298b2f2f-142f-43a8-9a46-c176785e1e43.png)

**Comment by alk** [comment]
Thanks for pointing this out. Some difference is to be expected, it is how autotools work. But that cmake bits are missing is clearly a mistake.

**Comment by romange** [comment]
@alk  it seems that cmake install build is broken....  It seems that exported libraries are not self-contained with respect to the symbols they are using. See the errors below.

I am configuring gperftools with:
 ```
-DGPERFTOOLS_BUILD_HEAP_PROFILER=OFF  \
-DGPERFTOOLS_BUILD_HEAP_CHECKER=OFF \
                    -DGPERFTOOLS_BUILD_DEBUGALLOC=OFF -DBUILD_TESTING=OFF `
```

 && /usr/lib/ccache/g++ -Wall -Wextra -g -fPIC -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer -Wno-unused-parameter -march=haswell  -std=c++20 -fdiagnostics-color=always -g -fsanitize=address -fsanitize=undefined  base/CMakeFiles/abseil_test.dir/abseil_test.cc.o -o abseil_test  lib/libgtest_main_ext.a  lib/libbase.a  _deps/glog-build/libglogd.a  /usr/lib/x86_64-linux-gnu/libunwind.so  /usr/lib/x86_64-linux-gnu/libunwind-x86_64.so  _deps/gflags-build/libgflags_debug.a  -latomic  -lrt  _deps/abseil_cpp-build/absl/time/libabsl_time.a  _deps/abseil_cpp-build/absl/time/libabsl_civil_time.a  _deps/abseil_cpp-build/absl/time/libabsl_time_zone.a  _deps/abseil_cpp-build/absl/debugging/libabsl_failure_signal_handler.a  _deps/abseil_cpp-build/absl/debugging/libabsl_examine_stack.a  _deps/abseil_cpp-build/absl/debugging/libabsl_symbolize.a  _deps/abseil_cpp-build/absl/strings/libabsl_strings.a  _deps/abseil_cpp-build/absl/strings/libabsl_strings_internal.a  _deps/abseil_cpp-build/absl/numeric/libabsl_int128.a  _deps/abseil_cpp-build/absl/base/libabsl_throw_delegate.a  _deps/abseil_cpp-build/absl/debugging/libabsl_demangle_internal.a  _deps/abseil_cpp-build/absl/base/libabsl_malloc_internal.a  _deps/abseil_cpp-build/absl/base/libabsl_base.a  _deps/abseil_cpp-build/absl/base/libabsl_spinlock_wait.a  -lrt  _deps/abseil_cpp-build/absl/debugging/libabsl_stacktrace.a  _deps/abseil_cpp-build/absl/debugging/libabsl_debugging_internal.a  _deps/abseil_cpp-build/absl/base/libabsl_raw_logging_internal.a  _deps/abseil_cpp-build/absl/base/libabsl_log_severity.a  third_party/libs/xxhash/lib/libxxhash.a  lib/libgmockd.a  lib/libgtestd.a  _deps/benchmark-build/src/libbenchmark.a  -Wl,-Bstatic  -lpfm  -Wl,-Bdynamic  /usr/lib/x86_64-linux-gnu/librt.a  third_party/libs/gperf/lib/libprofiler.a  third_party/libs/gperf/lib/libtcmalloc_minimal.a && :
/usr/bin/ld: third_party/libs/gperf/lib/libprofiler.a(profiler.cc.o): in function `CpuProfiler::Enabled()':
profiler.cc:(.text+0x116): undefined reference to `SpinLock::SlowUnlock()'
/usr/bin/ld: profiler.cc:(.text+0x129): undefined reference to `SpinLock::SlowLock()'
/usr/bin/ld: third_party/libs/gperf/lib/libprofiler.a(profiler.cc.o): in function `CpuProfiler::GetCurrentState(ProfilerState*)':
profiler.cc:(.text+0x17f): undefined reference to `SpinLock::SlowUnlock()'
/usr/bin/ld: profiler.cc:(.text+0x1e1): undefined reference to `SpinLock::SlowLock()'
/usr/bin/ld: third_party/libs/gperf/lib/libprofiler.a(profiler.cc.o): in function `CpuProfiler::Start(char const*, ProfilerOptions const*)':
profiler.cc:(.text+0x2c0): undefined reference to `SpinLock::SlowUnlock()'
/usr/bin/ld: profiler.cc:(.text+0x359): undefined reference to `SpinLock::SlowLock()'
/usr/bin/ld: third_party/libs/gperf/lib/libprofiler.a(profiler.cc.o): in function `CpuProfiler::CpuProfiler()':
profiler.cc:(.text+0x50a): undefined reference to `GetUniquePathFromEnv(char const*, char*)'
/usr/bin/ld: third_party/libs/gperf/lib/libprofiler.a(profiler.cc.o): in function `CpuProfiler::Stop()':
profiler.cc:(.text+0x6c4): undefined reference to `SpinLock::SlowUnlock()'
/usr/bin/ld: profiler.cc:(.text+0x6de): undefined reference to `SpinLock::SlowUnlock()'
/usr/bin/ld: profiler.cc:(.text+0x6f1): undefined reference to `SpinLock::SlowLock()'
/usr/bin/ld: third_party/libs/gperf/lib/libprofiler.a(profiler.cc.o): in function `CpuProfiler::FlushTable()':
profiler.cc:(.text+0x784): undefined reference to `SpinLock::SlowUnlock()'
/usr/bin/ld: profiler.cc:(.text+0x79e): undefined reference to `SpinLock::SlowUnlock()'
/usr/bin/ld: profiler.cc:(.text+0x7b1): undefined reference to `SpinLock::SlowLock()'
/usr/bin/ld: third_party/libs/gperf/lib/libprofiler.a(profiler.cc.o): in function `CpuProfilerSwitch(int)':
profiler.cc:(.text+0x97f): undefined reference to `GetUniquePathFromEnv(char const*, char*)'
/usr/bin/ld: third_party/libs/gperf/lib/libprofiler.a(profiler.cc.o): in function `RAW_LOG(int, char const*, ...)':
profiler.cc:(.text._Z7RAW_LOGiPKcz[_Z7RAW_LOGiPKcz]+0x6b): undefined reference to `FLAG__namespace_do_not_use_directly_use_DECLARE_int32_instead::FLAGS_verbose'
/usr/bin/ld: third_party/libs/gperf/lib/libprofiler.a(profiler.cc.o): in function `CpuProfiler::GetCurrentState(ProfilerState*) [clone .cold]':
profiler.cc:(.text.unlikely+0xe): undefined reference to `SpinLock::SlowUnlock()'
/usr/bin/ld: third_party/libs/gperf/lib/libprofiler.a(profiler.cc.o): in function `CpuProfiler::Start(char const*, ProfilerOptions const*) [clone .cold]':
profiler.cc:(.text.unlikely+0x28): undefined reference to `SpinLock::SlowUnlock()'
/usr/bin/ld: third_party/libs/gperf/lib/libprofiler.a(profiler.cc.o): in function `CpuProfiler::Stop() [clone .cold]':
profiler.cc:(.text.unlikely+0x52): undefined reference to `SpinLock::SlowUnlock()'
```
