### ISSUE TITLE
Profiling after the fork() doesnt work

### ISSUE THREAD

**Issue by MansiJ1111** [gperftools/gperftools#1326]
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
void func1(){
	int i=0;
	while(i<100000){
		++i;
	}
}

void func2(){
	int i=0;
	while(i<200000){
		++i;
	}
}

void func3(){
	for(int i=0;i<1000;++i){
		func1();
		func2();

	}
}
int main(int argc, char *argv[])
{
    printf("PID of parent = %d\n", getpid());
    func3();
   int p;
    p = fork();
    if(p==-1)
    {
        printf("There is an error while calling fork()");
    }
    if(p==0)
    {
    printf("We are in the child process\n");
   
    }
    else
    {
        printf("We are in the parent process");
    }
    return 0;
}

I am trying to profile the above program which forks a child process.Currently using gperftool version 2.1.
The program doesnt call exec().
Is this issued solved now because it is mentioned in the document that this issue will be resolved in perftool 1.2?
If yes,what are the steps to profile the child process?
If no,is there any plan to get this issue solved?

**Comment by alk** [comment]
the thing that was solved is when fork is followed by exec. In your cases what is the outcome that you expect? Thing is your program spends certain amount of cpu time before forking then forks and then both processes die. What kind of profile you want to obtain in this case ?

Closing for now, but please do reopen when you respond.
