### ISSUE TITLE
macOS doesn't generated profiler file

### ISSUE THREAD

**Issue by lucasjinreal** [gperftools/gperftools#1328]
I am running like this:

```
LD_PRELOAD=/usr/local/lib/libprofiler.dylib CPUPROFILE=./main.prof ./main
```

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/21303438/158986283-0c8080a1-6426-44bd-8021-2aed536b6f2d.png">

But the file I needed main.prof doesn't generated.

**Comment by alk** [comment]
ah, this is because osx thingy needs different environment variable. It is DYLD_PRELOAD instead of LD_PRELOAD....
