### ISSUE TITLE
tcmalloc crashes on Windows

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#133]
Originally reported on Google Code with ID 130

```
What steps will reproduce the problem?
1. Get version 1.2 google perftools source
2. Build with vs2005 or vs2008
3. Run any tcmalloc unittest, it will just crash

What is the expected output? What do you see instead?
expect no crash but see crash message:

Unhandled exception at 0x7c958579 in tcmalloc_minimal_unittest.exe: 
0xC0000005: Access violation writing location 0x00030ffc.

What version of the product are you using? On what operating system?
version 1.2 google-perftools build with vs2005 or vs2008 on Windows 
2003/XP.

Please provide any additional information below.

See attatch file, when  PatchMainExecutableLocked() called, the 
PreamblePatcher::ResolveTarget(fn) returnes "operator new[]" instead of
"Perftools_newarray", and then it crashes late at PreamblePatcher::Patch().


```

Reported by `yinyunqiao` on 2009-05-13 14:43:45

<hr>
- _Attachment: google-perftools-crashes.PNG<br>![google-perftools-crashes.PNG](https://storage.googleapis.com/google-code-attachments/gperftools/issue-130/comment-0/google-perftools-crashes.PNG)_

**Comment by pkxpp** [comment]
crush in win7, stack info:
`>	libtcmalloc_minimal.dll!`anonymous namespace'::LibcInfo::PopulateWindowsFn(const `anonymous-namespace'::ModuleEntryCopy & module_entry)  行 536	C++
 	libtcmalloc_minimal.dll!`anonymous namespace'::PatchMainExecutableLocked()  行 648	C++
 	libtcmalloc_minimal.dll!`anonymous namespace'::PatchAllModules()  行 765	C++
 	libtcmalloc_minimal.dll!TCMallocGuard::TCMallocGuard()  行 909 + 0x5 字节	C++
 	libtcmalloc_minimal.dll!`dynamic initializer for 'tcmalloc_initializer''()  行 585 + 0xa 字节	C++
 	msvcr100.dll!6a6a263d() 	
 	libtcmalloc_minimal.dll!_CRT_INIT(void * hDllHandle, unsigned long dwReason, void * lpreserved)  行 284 + 0xf 字节	C
 	libtcmalloc_minimal.dll!__DllMainCRTStartup(void * hDllHandle, unsigned long dwReason, void * lpreserved)  行 506 + 0x8 字节	C
 	libtcmalloc_minimal.dll!_DllMainCRTStartup(void * hDllHandle, unsigned long dwReason, void * lpreserved)  行 476 + 0xe 字节	C
`

**Comment by alk** [comment]
Lets open new ticket with all the details. I am afraid that just stack trace won't be enough to debug this. Would be very nice if you can provide simple test program that reproduces the issue.

**Comment by chrisdoherty4** [comment]
Was a new ticket opened somewhere and can you link it if so?
