### ISSUE TITLE
request for bazel build system support

### ISSUE THREAD

**Issue by xiedeacc** [gperftools/gperftools#1330]
as title

**Comment by alk** [comment]
Thanks for suggestion but I have to reject this. Different people want/prefer different build systems and we already face enough (vs project files, autotools and semi-supported cmake thingy).

For cmake I choose to do best-effort support (without really being proficient with this thingy or willing to support it) and it is causing enough pain for me already. bazel/blaze thingy will be perhaps less bad than cmake, but still effort that I cannot commit to.
