### ISSUE TITLE
libtcmalloc_minimal build fail with vs2019

### ISSUE THREAD

**Issue by alicera** [gperftools/gperftools#1331]
I build libtcmalloc_minimal fail with vs2019.
I right-click the retarget projects and I choose the vc142 to build.Then rebuild.It is still fail.
Because my workspace is vs2019, I build it with vs2019. 

![image](https://user-images.githubusercontent.com/59388989/162112396-07b3f291-9880-4932-9c93-57eecd544001.png)

![image](https://user-images.githubusercontent.com/59388989/162112447-63b64185-ad78-49cc-926f-ce54f588e0ea.png)

**Comment by lennoxho** [comment]
The MSVC IDE should have offered to upgrade the project files

**Comment by alk** [comment]
Indeed. Either install vs2015 platform tools or something (sorry, forgot how it is called), or accept VS offer to upgrade.
