### ISSUE TITLE
Implicit TLS detection in CMakeLists.txt does not account for MSVC

### ISSUE THREAD

**Issue by lennoxho** [gperftools/gperftools#1332]
`__thread` is not supported on MSVC. 
We should add an `elseif(MSVC)` clause that checks for `__declspec(thread)` instead.

https://github.com/gperftools/gperftools/blob/fe85bbdf4cb891a67a8e2109c1c22a33aa958c7e/CMakeLists.txt#L357-L367

**Comment by alk** [comment]
Sure. Go ahead and add, please.

**Comment by lennoxho** [comment]
https://github.com/gperftools/gperftools/pull/1435

**Comment by lennoxho** [comment]
Merged https://github.com/gperftools/gperftools/pull/1439
