### ISSUE TITLE
I wrote a test program, but pprof doesn't have any output

### ISSUE THREAD

**Issue by Yojay97** [gperftools/gperftools#1337]
Below is my simple test program.

#include <iostream>
#include <gperftools/profiler.h>

void test()
{
    std::cout << "test" << std::endl;
}

int sub(int x, int y)
{
    return x + y;
}

int main(int argc, char *argv[])
{
    ProfilerStart("hello.prof");
    test();
    std::cout << "sub = " << sub(3, 6) << std::endl;
    ProfilerStop();

    return 0;
}

After the program finishes running, I use "pprof --text hello hello.prof" to parse the cpu, But only returned the following prompt

Using local file hello.
Using local file hello.prof.

I use the "g++ hello.cpp -o hello -lprofiler" to compile the code.

Thanks.

**Comment by Yojay97** [comment]
fine, maybe my code is too simple........Increase the execution time of the program to solve this problem.But how can i change the sample rate?

**Comment by ForceConstant** [comment]
Try running with the ` LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libprofiler.so CPUPROFILE=hello.prof hello`

**Comment by alk** [comment]
This program is too short. It doesn't have any hope of producing even single sample. Go read about sampling profilers if you doubt me.

Make sure whatever you profile spends at least few seconds to get any precision at all.
