### ISSUE TITLE
why the addr can't parse to function name?

### ISSUE THREAD

**Issue by myseemylife** [gperftools/gperftools#1340]
i use gperftools to detect leaks. 
![image](https://user-images.githubusercontent.com/3964397/171598497-55c38365-2d8e-4cd9-a1d7-986dd9f757d3.png)
the console  info tells me the leaks point addr.so i use add2line tools to tranlate  the source code point where.
i got nothing valid function name but ??!
can i trust the log??
BTW,i cross-compile gperftools to some arm-boards.
any suggestion will help me a lot!!

**Comment by alk** [comment]
it tries to call pprof to symbolize addresses. For this it currently requires "our"/perl version of pprof. Either in PATH or with full path to the binary given in PPROF_PATH. I am hoping to drop this dependency sometime soon but for now this is what we have.
