### ISSUE TITLE
Why am I a missing some symbols in report? Because of function pointers?

### ISSUE THREAD

**Issue by ForceConstant** [gperftools/gperftools#1341]
I am trying to profile a legacy c++ program, and it has lots of threads that are called by function pointers. I am getting some symbols, but not all, and it seems that I am not getting the ones that are being called by a function pointer. For example

```
Dropped 57 nodes (cum <= 0.01s)
      flat  flat%   sum%        cum   cum%
     1.68s 90.78% 90.78%      1.85s   100%  [libc.so.6]
     0.17s  9.09% 99.86%      1.85s   100%  [myapp.out]
         0     0% 99.86%      1.83s 99.04%  /workspace/src/task/u_rttask.h:350
         0     0% 99.86%      0.01s  0.65%  main /workspace/src/main.cpp:187
```

I am using the `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libprofiler.so CPUPROFILESIGNAL=12 CPUPROFILE_FREQUENCY=100000 CPUPROFILE=/workspace/prof.out myapp.out` to start.

**Comment by alk** [comment]
function pointers shouldn't be a problem. Could this be say due to those functions being static and your program not having debug symbols?

In any case we are not supporting pprof anymore. Do test go version at github.com/google/pprof and report any issues there.
