### ISSUE TITLE
tcmalloc heap profiling fails on arm with musl libc

### ISSUE THREAD

**Issue by infn-ke** [gperftools/gperftools#1342]
When I start my binary on arm 32 bits with musl libc it fails immediately with the following error message;

```
/ # HEAPPROFILE=/tmp/heapprof /usr/bin/myapp
Starting tracking the heap
Check failed: new_pages != MAP_FAILED: mmap error
Aborted
/ #
```

What is the initial mmap size? tcmalloc supported on musl?

**Comment by alk** [comment]
gperftool's "heap profiler" is actually very slow and memory hungry thingy. So my guess is we simply ran out of memory and that caused mmap failure.

Anyways, without additional details there is nothing I can add. Closing, but do reopen if you can add something.
