### ISSUE TITLE
How can we install this on Centos 9?

### ISSUE THREAD

**Issue by lebeier** [gperftools/gperftools#1344]
Hi Team,

I am trying to find this package on Centos Stream 9 and unable to do so. Is this supported on the latest Centos 9?

**Comment by alk** [comment]
Same steps as every other autotools-powered free software project. Download .tar.gz, ./configure && make && make install as usual. Have seen INSTALL file ?

(Closing, but please feel free to reopen if you have specific questions and/or if you're able to propose or point out specific omissions in our docs)
