### ISSUE TITLE
Remove x86 support

### ISSUE THREAD

**Issue by DK318** [gperftools/gperftools#1346]
As mentioned [here](https://github.com/gperftools/gperftools/issues/1345#issuecomment-1165155423) e2k is used by evil countries and we don't need to support it. So I think it would be a good solution to remove x86 support because this hardware is in use by the army of many evil countries

**Comment by AsGreyWolf** [comment]
Отчет: прочитал 7 главу LYAH, решил кату "Решить задачу по глюкам"

**Comment by TheTeslak** [comment]
ARM architecture is used by Russian "Baikal" processors. I propose to leave support only RISC-V

**Comment by zamazan4ik** [comment]
RISC-V shall be removed too: https://www.theregister.com/2021/07/15/yadro_riscv/

**Comment by osdeverr** [comment]
I truly believe with my entire heart that the x86 infrastructure, used by evil people all across the world to commit evil and heinous crimes, does not deserve to be supported in this project. As upstanding citizens and simply _people who care_ about injustices and horrors happening in this world, we have a moral obligation to ban x86, x86-64 and everything related to those two from the open source community. Tools of violence never belonged here in the first place, but it's our job to correct history's mistakes by removing them now, even if it was past due ages ago. Down with X86!
#DownWithX86

**Comment by alk** [comment]
Closing as spam/trolling. And blocked all trolls too.
