### ISSUE TITLE
Linking with tcmalloc still causes openat/mmap

### ISSUE THREAD

**Issue by infn-ke** [gperftools/gperftools#1349]
I'm running tcmalloc on arm 32 bits, having compiled against the shared library tcmalloc. Performance is really slow, and stracing on the process shows that it is busy doing openat/fstat/mmap/close. Why is that? If I'm not using LD_PRELOAD, why is tcmalloc repeatedly doing open on the shared library?

```bash
openat(AT_FDCWD, "/usr/lib/libtcmalloc.so.9.10.5", O_RDONLY) = 17
fstat64(17, {st_mode=S_IFREG|0755, st_size=577032, ...}) = 0
mmap2(NULL, 577032, PROT_READ, MAP_PRIVATE, 17, 0) = 0xe4066000
close(17)                               = 0
munmap(0xe4066000, 577032)              = 0
```

**Comment by alk** [comment]
We don't do that. Could be this be something borked with dynamic linker perhaps? Are you saying it does this cycle repeatedly?

**Comment by alk** [comment]
perhaps you can catch this in action with gdb or something? Just put breakpoing on openat for example see backtrace.

**Comment by infn-ke** [comment]
Yes, this happens repeatedly when I'm doing heap checking. Invoked as `HEAPCHECK=normal HEAP_CHECK_DUMP_DIRECTORY=/`

**Comment by infn-ke** [comment]
Yes linking to libunwind. glibc `backtrace` not an option, using musl. What other options are there?

**Comment by alk** [comment]
libgcc has built-in backtracing facility.

```
TCMALLOC_STACKTRACE_METHOD=libgcc TCMALLOC_STACKTRACE_METHOD_VERBOSE=t ./stacktrace_unittest
```

But do note that typical configurations of libunwind interpose libunwind's implementation of required functions. See here for some more details. https://github.com/gperftools/gperftools/wiki/gperftools'-stacktrace-capturing-methods-and-their-issues

**Comment by infn-ke** [comment]
I have a transitive link dependency, is that ok? My binary depends on tcmalloc and then tcmalloc depends on unwind. Or my binary should have an explicit need to both tcmalloc and libunwind?

**Comment by alk** [comment]
No, my point is, if you want to use libgcc's implementation, then you either don't link to libunwind or you configure libunwind to disable c++ exceptions "support".

**Comment by infn-ke** [comment]
> No, my point is, if you want to use libgcc's implementation, then you either don't link to libunwind or you configure libunwind to disable c++ exceptions "support".

Removing libunwind from tcmalloc does resolve the problem with repeated `openat` of tcmalloc. Thanks, appreciated. Any ideas on why that would be happening?

I proceeded without libunwind and instead rely on libgcc unwinding; tcmalloc built with `gperftools_enable_frame_pointers` and my app is built with `-fno-omit-frame-pointer`. Now leak checking works correctly on x86-64. However, when I cross-compile the same thing for arm (also glibc) then the leak checker does not find the leak. tcmalloc should work on arm with libgcc unwinding?

**Comment by alk** [comment]
We didn't have fully supported heap leak checker on arms (any). Now it is fixed. As for this open thingy and libunwind, perhaps consider asking there. Closing (reopen if you still need anything).
