### ISSUE TITLE
cpu profiler: cause my program 'feign death' 

### ISSUE THREAD

**Issue by LightSun** [gperftools/gperftools#1351]
Hello , gperftools is a very good project. I like it. But I met some problem. 
The program is 'feign death' and cpu hold turn to zero.  Now It only can be exit by kill process.
I don't know why and How to fix it. 
But when I run without profiler. It run ok. Can you help me?
 running with 
```
env LD_PRELOAD=libprofiler.so CPUPROFILE=info.prof ./shengxin_test 
//shengxin_test is c++ 

```

**Comment by alk** [comment]
Likely one of the cases described here: https://github.com/gperftools/gperftools/wiki/gperftools'-stacktrace-capturing-methods-and-their-issues

If you post backtraces I'd be able to tell.

But the good news (I'll update wiki page soon-ish) is that if you have gcc 12 or later and glibc 2.35 or later, libgcc backtrace capturing method is 100% perfect. (covers ubuntu 22.04 and later, fedora 36 or later and most recent debian stable; doesn't cover rhel 9 sadly)

Do switch via environment variable TCMALLOC_STACKTRACE_METHOD=libgcc

E.g. like this:

```
$ TCMALLOC_STACKTRACE_METHOD_VERBOSE=t TCMALLOC_STACKTRACE_METHOD=libgcc ./stacktrace_unittest
```

Closing, but do reopen if you can add something.
