### ISSUE TITLE
--disable-cpu-profiler leaves profiler-related files libprofiler.pc and include/google/profiler.h installed

### ISSUE THREAD

**Issue by yurivict** [gperftools/gperftools#1356]
It doesn't make sense to install ```libprofiler.pc``` when ```libprofiler.so``` isn't installed.

Same is with ```include/google/profiler.h```.

It looks like perftools install 2 copies of header files: under ```include/google``` and under ```include/gperftools```.
```--disable-cpu-profiler``` disables ```include/gperftools/profiler.h``` but not ```include/google/profiler.h```.

**Comment by alk** [comment]
Good point. Fixed. Thanks.
