### ISSUE TITLE
Broken on riscv64 architecture: error: Cannot calculate stack trace: will need to write for your environment

### ISSUE THREAD

**Issue by yurivict** [gperftools/gperftools#1359]
```
src/stacktrace.cc:261:2: error: Cannot calculate stack trace: will need to write for your environment
#error Cannot calculate stack trace: will need to write for your environment
 ^
src/stacktrace.cc:304:23: error: use of undeclared identifier 'get_stack_impl'
  return frame_forcer(get_stack_impl->GetStackFramesPtr(result, sizes, max_depth, skip_count));
                      ^
src/stacktrace.cc:314:23: error: use of undeclared identifier 'get_stack_impl'
  return frame_forcer(get_stack_impl->GetStackFramesWithContextPtr(
                      ^
```

The FreeBSD build server for riscv64 architecture sent such fallout message.

Log URL:        http://beefy7.nyi.freebsd.org/data/130releng-riscv64-quarterly/ec58039ced76/logs/google-perftools-2.10_1.log (IPv6 URL)

FreeBSD 13.0

**Comment by alk** [comment]
We now support FreeBSD/riscv via generic_fp stacktrace capturing method. And also libunwind should work too.

Feel free to contribute ucontext integration support here: https://github.com/gperftools/gperftools/blob/972c12f77dfe27253d966a1bb58d10efb79c34c8/src/stacktrace_generic_fp-inl.h#L302

After that ./stacktrace_unittest should be passing. Closing for now (reopen if you can add something).
