### ISSUE TITLE
Broken on armv7 architecture: use of undeclared identifier '_URC_NO_REASON'

### ISSUE THREAD

**Issue by yurivict** [gperftools/gperftools#1360]
```
In file included from src/stacktrace.cc:97:
In file included from ./src/stacktrace_impl_setup-inl.h:51:
./src/stacktrace_libgcc-inl.h:65:12: error: use of undeclared identifier '_URC_NO_REASON'
    return _URC_NO_REASON;
           ^
./src/stacktrace_libgcc-inl.h:73:10: error: use of undeclared identifier '_URC_NO_REASON'
  return _URC_NO_REASON;
         ^
2 errors generated.
```

FreeBSD 13.0

**Comment by alk** [comment]
Well, _Unwind_Backtrace crashes on FreeBSD anyways (will you guys consider unbreaking whatever it is broken on your libthr thingy when we touch anything thread-related early?). So as of today, ./configure simply disables this code on FreeBSD. So won't apply. (But do consider fixing whatever it is not great with the threading thingy)
