### ISSUE TITLE
Debiao 10 / 2.8.1  heap cache lead to OOM

### ISSUE THREAD

**Issue by magicsupery** [gperftools/gperftools#1366]
we make a project with lua(huge small objets in maps), and repalce the malloc system with gperftools 2.8.1 on debian 10, the lua version is lua 5.1.5, gcc version 8.3.0 (Debian 8.3.0-6) 

when the lua process running, i found the process will turn out OOM. Here's my stats

malloc stats ------------------------------------------------
MALLOC:       72021680 (   68.7 MiB) Bytes in use by application
MALLOC: +   7384039424 ( 7042.0 MiB) Bytes in page heap freelist
MALLOC: +     84018240 (   80.1 MiB) Bytes in central cache freelist
MALLOC: +     11031808 (   10.5 MiB) Bytes in transfer cache freelist
MALLOC: +     15552528 (   14.8 MiB) Bytes in thread cache freelists
MALLOC: +     50593792 (   48.2 MiB) Bytes in malloc metadata
MALLOC:   ------------
MALLOC: =   7617257472 ( 7264.4 MiB) Actual memory used (physical + swap)
MALLOC: +    334692352 (  319.2 MiB) Bytes released to OS (aka unmapped)
MALLOC:   ------------
MALLOC: =   7951949824 ( 7583.6 MiB) Virtual address space used
MALLOC:
MALLOC:          36208              Spans in use
MALLOC:             14              Thread heaps in use
MALLOC:           8192              Tcmalloc page size
------------------------------------------------
Call ReleaseFreeMemory() to release freelist memory to the OS (via madvise()).
Bytes released to the OS take up virtual address space but no physical memory.

===============================================

as above, i think maybe the heap cache got some leaks !

why the new span can not use the heap cache??

i read the source coke in page_heap.cc  SearchFreeAndLargeLists

is there some bugs in it leading the result that we can not find the proper span in the free list?

or we have so many "one-page" Span Fragments? so when we need Span that length > 1 will cause a heap grow？

but when i re-reading the stats,  i doubt  68.7 MiB app used will cause fragments in 7042.0 MiB free list?

it really confuse me,  thanks for reply!

**Comment by alk** [comment]
Hard to say from this stats. I am not sure if this stats reflect the issue. Maybe you had some amount of ram which was used and just recently freed.

(Closing as very old. I apologize for not responding earlier. Please reopen if you have more to add)
