### ISSUE TITLE
Add config for setting upper bound of overall thread cache size

### ISSUE THREAD

**Issue by tedyu** [gperftools/gperftools#1367]
Currently `ThreadCache::set_overall_thread_cache_size` uses 1GB as upper bound for the cache size.

As servers have more and more memory, this hard coded limit is low.

We should add a config which allows the cache size to be set higher than 1GB.

**Comment by alk** [comment]
Thanks for suggestion. Feel free to contribute. But also do note that this option is settable at runtime via TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES define.
