### ISSUE TITLE
Any idea how to use with php?

### ISSUE THREAD

**Issue by aario-k24** [gperftools/gperftools#1372]
Anyone used this software for php? If so how?
I compile release version 2.10 using:
```
./autogen.sh
./configure
make -j9
make install
```
I put this in php.ini:
```
extension="memprof.so"
```
And then I run `php` and get:
```
Unable to load dynamic library 'memprof.so'
```
And all around google it seems that no one ever discussed this error on any forums! What does the compile script do? What does it install? How to use this software?

**Comment by alk** [comment]
Sorry, we don't have anything to do with php support. Could it be that you filed ticket in wrong project?
