### ISSUE TITLE
cmake build seemingly lacks 4k pages option (was: Page size 4 kB - how to set?)

### ISSUE THREAD

**Issue by infn-ke** [gperftools/gperftools#1373]
How do I set a page size of 4 kB? I can see there are at least two different build switches that I believe refers to the same thing? 

There is a parameter called `TCMALLOC_PAGE_SIZE_SHIFT`  that seems to allow me to change to 4 kB (shift of 12) 
https://github.com/gperftools/gperftools/blob/master/cmake/config.h.in#L284

The top cmake recipe has a parameter called `gperftools_tcmalloc_pagesize` but that only allows setting a page size down to 8 kB.
https://github.com/gperftools/gperftools/blob/master/CMakeLists.txt#L122

What is the correct way to set 4 kB page size?

**Comment by NTULINUX** [comment]
Well, looking at the Gentoo ebuild, I found:

use largepages && append-cppflags -DTCMALLOC_LARGE_PAGES
use largepages64k && append-cppflags -DTCMALLOC_LARGE_PAGES64K

but doing a `git grep` in the gperftools tree, there is no code relevant to TCMALLOC_LARGE_PAGES except in ChangeLog.old

So I dug through the source code more and found in the INSTALL file:

```
*** TCMALLOC LARGE PAGES: TRADING TIME FOR SPACE

You can set a compiler directive that makes tcmalloc faster, at the
cost of using more space (due to internal fragmentation).

Internally, tcmalloc divides its memory into "pages."  The default
page size is chosen to minimize memory use by reducing fragmentation.
The cost is that keeping track of these pages can cost tcmalloc time.
We've added a new flag to tcmalloc that enables a larger page size.
In general, this will increase the memory needs of applications using
tcmalloc.  However, in many cases it will speed up the applications
as well, particularly if they allocate and free a lot of memory. We've
seen average speedups of 3-5% on Google applications.

To build libtcmalloc with large pages you need to use the
--with-tcmalloc-pagesize=ARG configure flag, e.g.:

   ./configure <other flags> --with-tcmalloc-pagesize=32

The ARG argument can be 4, 8, 16, 32, 64, 128 or 256 which sets the
internal page size to 4K, 8K, 16K, 32K, 64K, 128K and 256K respectively.
The default is 8K.
```

Upon examining the configure.ac file, this `./configure --with-tcmalloc-pagesize=` flag sets the option you found earlier, `TCMALLOC_PAGE_SIZE_SHIFT`


configure.ac:

```
AC_ARG_WITH([tcmalloc-pagesize],
            [AS_HELP_STRING([--with-tcmalloc-pagesize],
                            [Set the tcmalloc internal page size to 4K, 8K, 16K, 32K, 64K, 128K or 256K])],
            [],
            [with_tcmalloc_pagesize=$default_tcmalloc_pagesize])

...

case "$with_tcmalloc_pagesize" in
  4)
       AC_DEFINE(TCMALLOC_PAGE_SIZE_SHIFT, 12);;
  8)
       #Default tcmalloc page size.
       ;;
  16)
       AC_DEFINE(TCMALLOC_PAGE_SIZE_SHIFT, 14);;
  32)
       AC_DEFINE(TCMALLOC_PAGE_SIZE_SHIFT, 15);;
  64)
       AC_DEFINE(TCMALLOC_PAGE_SIZE_SHIFT, 16);;
  128)
       AC_DEFINE(TCMALLOC_PAGE_SIZE_SHIFT, 17);;
  256)
       AC_DEFINE(TCMALLOC_PAGE_SIZE_SHIFT, 18,
                 [Define internal page size for tcmalloc as number of left bitshift]);;
  *)
       AC_MSG_WARN([${with_tcmalloc_pagesize}K size not supported, using default tcmalloc page size.])
esac
```

Your question helped me find a Gentoo bug, they're setting it the wrong way (dead code currently) and the correct method is to actually use `TCMALLOC_PAGE_SIZE_SHIFT` now.

Cheers!

**Comment by alk** [comment]
For cmake stuff, someone please contribute whatever fix necessary. Yes, all you need to to have -DTCMALLOC_PAGE_SIZE_SHIFT set accordingly.
