### ISSUE TITLE
pprof: request: exclude allocations that have since been freed

### ISSUE THREAD

**Issue by Spongman** [gperftools/gperftools#1375]
So, in pprof there's a `--base` argument to exclude allocations that were not made until after a certain point.

I'd like to request a similar argument that allows us to exclude allocations that were not live _after_ a given point.

For example, if I have 3 heap files: `0001.heap`, `0002.heap` and `0003.heap`, I only want to show the memory that was allocated when `0002.heap` was dumped, and _specifically exclude_ those allocations that were freed before `0003.heap` was allocated.

**Comment by alk** [comment]
I am sorry but we're not supporting/improving our perl version of pprof.
