### ISSUE TITLE
failed to build due to std::random_shuffle removed from new C++ standard

### ISSUE THREAD

**Issue by akofer** [gperftools/gperftools#1378]
build error when using -std=c++17 or -std=c++20:
benchmark/malloc_bench.cc:236:8: error: no member named 'random_shuffle' in namespace 'std'

reason:
std::random_shuffle is removed in the new C++ standard.

solution:
as the example here: https://en.cppreference.com/w/cpp/algorithm/random_shuffle

**Comment by alk** [comment]
Thanks. Fixed.
