### ISSUE TITLE
How to modify the TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD

### ISSUE THREAD

**Issue by chentingxi36** [gperftools/gperftools#1381]
I have the trouble in the 'tcmalloc: large alloc 1427832832 bytes == 0xfc94000 @', and don't how to How to modify the TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD in the environment variable

**Comment by alk** [comment]
Well, here is one way (on Linux or other unix-y OS):

TCMALLOC_LARGE_ALLOC_REPORT=1048576 ./my-program

I am sorry, but we don't provide general advise on programming/OS-usage matters unrelated to malloc. Closing.
