### ISSUE TITLE
[windows] PreamblePatcher::Patch() fails from time to time in Release

### ISSUE THREAD

**Issue by babylon73** [gperftools/gperftools#1383]
Hello,

Got the recent state of the code, testing under Win10 x64 with VS2022 (AMD Ryzen Threadripper 2950X CPU, have no idea whether it actually matters though).

From time to time, completely sporadically, all the unit tests that presume patching start to fail (Release config). When it happens, 
PreamblePatcher::Patch() method always fails for the "_expand" function returning the SIDESTEP_FUNCTION_TOO_SMALL error code.

Debug config always works just fine.

It happens completely unpredictably. All unit tests may work flawlessly tens of times, and then, for some mistirious reason, all of them start failing with the symptoms described above.

It happens not just for unit tests - my test application I'm trying to patch works similarly (sometimes patching succeeds and all works just fine, sometimes the application exits via the abort() at the very beginning due to the patching failure).

I have no clue what might be the reason and why the problem is floating, ready to do the extra testing and provide the debug info, any advice on where to start would be highly appreciated.

Thank you.

**Comment by alk** [comment]
Thanks for filing ticket. So I am seemingly unable to reproduce this on my windows test machine. Could be something on your system playing games with whatever dlls shipped with your OS?

I think we can test this if you retry your tests in safe mode.

**Comment by babylon73** [comment]
Hi alk,

Thank you for the response.

You mean - boot Windows in safe mode and then run the unit tests? Any specific instructions on testing procedure in safe mode?

Thank you.

**Comment by alk** [comment]
Just have those .exe built and run. Same way that causes trouble for you
