### ISSUE TITLE
heapprofiler doesn't work well on arm and 64g x86-64

### ISSUE THREAD

**Issue by han-ccc** [gperftools/gperftools#1389]
what condition does heapprofiler works on arm, and x86-64 whose memory large than 32g(i guess) need?  
I can get samples and generat calling diagram on 16g x86-64 centos, but when I run heapprofiler on a arm with 192g memory and a centos with 64g memroy. The pprof just says the report has no sample. I tried gperftool with 2.3 2.5 2.10 version, with or without libunwind 1.5 1.6. 
I compile the program with fno-omit-frame-pointer and -g.
Anyone knows how to make it work, many thanks!!!
bty, could this be related to the heavy use of coroutines or some 32 bit limits？

**Comment by alk** [comment]
Please show output of TCMALLOC_STACKTRACE_METHOD_VERBOSE=t ./stacktrace_unittest

All cases you mention should work.

**Comment by alk** [comment]
Closing for now, but do reopen please if you still observe any issues with latest code.
