### ISSUE TITLE
Does the trampoline insertion code work with Windows 10 1703's parallel DLL loader?

### ISSUE THREAD

**Issue by holenno1** [gperftools/gperftools#1393]
While debugging an intermittent deadlock in our application, I came across those articles
https://blogs.blackberry.com/en/2017/10/windows-10-parallel-loading-breakdown
https://blog.marcocantu.com/blog/2017-june-delphi-packages-creators-update.html

and this stackoverflow post
https://stackoverflow.com/questions/42789199/why-there-are-three-unexpected-worker-threads-when-a-win32-console-application-s

Where I learned starting with Windows 10 version 1703 aka Creator's update, DLLs are now loaded in parallel by default during program startup.

Was the trampoline insertion code in preamble_patcher.cc written with thread safety in mind?

**Comment by alk** [comment]
Thanks for bringing this up. Not sure. Someone with actual windows expertise should investigate.

But from reading your links, it looks like just actual loading and relocations are processed in parallel. When user's initialization code is run (static object constructors etc) it seems it would run sequentially. So then we'd be fine. I think.

**Comment by alk** [comment]
BTW I failed to recall and comment that we actually do all the patchings under spinlock. So we should be safe w.r.t. any parallelisms in DLL loadings.
