### ISSUE TITLE
undefined reference to `HeapLeakChecker::DoIgnoreObject(void const*)

### ISSUE THREAD

**Issue by shentu521** [gperftools/gperftools#1395]
`#应用程序链接静态库
LIB_STATIC_LINK = 	\
					-L$(STATIC_LIB_DIR)  $(LIB)   			\
					-L$(THIRD_PARTY)/sipsdk/build -lnpsipsdk	\
					-L${THIRD_PARTY}/../GmSSL -lgmssl\
					-L${THIRD_PARTY}/resip/lib -ldum -lresip -lrutil -lresipares	\
					 -lresolv -lwebrtc \
					 -lm -ldl -lpthread -lrt -lz \
					-L${THIRD_PARTY}/gpreftools -ltcmalloc_minimal  -lprofiler\
					  -lspinlock -lsysinfo -llogging 	\
					-lmaybe_threads   \`

but link error:

/mnt/hgfs/server2.0/citms_sip_server/thirdparty/centeros-lib//gpreftools/libtcmalloc_minimal.a(malloc_extension.cc.o): In function `MallocExtension* HeapLeakChecker::IgnoreObject<MallocExtension>(MallocExtension*)':
malloc_extension.cc:(.text._ZN15HeapLeakChecker12IgnoreObjectI15MallocExtensionEEPT_S3_[_ZN15HeapLeakChecker12IgnoreObjectI15MallocExtensionEEPT_S3_]+0x14): undefined reference to `HeapLeakChecker::DoIgnoreObject(void const*)'

**Comment by alk** [comment]
There is not enough details in your description. This does look like a common "gotcha" with static libraries that sometimes you need to pass same .a archive twice. But I also see that you're manually linking in some .a in addition to -ltcmalloc_minimal. Those bits (e.g. logging) are so called "convenient arhives". They are not to be used outside of gperftools own build process.

So there is definitely something you're doing wrong, but without more details I cannot help.

Closing right now, but do reopen with details if you have something to add.
