### ISSUE TITLE
HugetlbSysAllocator cannot free huge pages to OS

### ISSUE THREAD

**Issue by ZhiqiangLiu26** [gperftools/gperftools#1397]
HugetlbSysAllocator cannot free huge pages to OS

 When enable tcmalloc with 2M hugepage, in bstore_mempool thread, ceph_heap_release_free_memory() cannot free memory in free lists (page heap freelist, central freelist, thread freelist). Once the heap_size is greater than target_mem, the tuned_mem will continue to be decreased until a very small value. Actually, there are already many memory in free lists which cannot be used by the OSD.

ceph issue: https://tracker.ceph.com/issues/61493, pr: https://github.com/ceph/ceph/pull/51922

It is becacuse tcmalloc releases memory to OS with using `madvise(MADV_FREE)`, which does not seem to free hugepages.

In https://github.com/gperftools/gperftools/issues/1237, the hugepages with memfs allocator has been discussed. Any advise for hugepage with hugetlb ?

**Comment by alk** [comment]
De-duplicating this into #1237.
