### ISSUE TITLE
feat: save prof.out file after calling exit() func.

### ISSUE THREAD

**Issue by Ruth-Seven** [gperftools/gperftools#1404]
I believe that adding another way to save prof.out file is a great idea. Cause some project like server can't activly end their instrument sequence. So Ctrl + C or linux signal which would be caught by SignalHandler is necessary for ending this program. And SingalHandler can cleanly end the program by calling exit().

I just wander whether gperftools can support this feature like [gprof](https://ftp.gnu.org/old-gnu/Manuals/gprof-2.9.1/html_mono/gprof.html#SEC3:~:text=by%20returning%20from%20main%20or%20by%20calling%20exit.)

**Comment by alk** [comment]
Sorry, I didn't get this. Can you please elaborate what is that you need that we lack ?

**Comment by alk** [comment]
Isn't it already the case ? exit() will trigger all the destructors and that includes cpu profiler which will dump the profile as part of that.

**Comment by Ruth-Seven** [comment]
I examine it again later in my mac

**Comment by Ruth-Seven** [comment]
> Isn't it already the case ? exit() will trigger all the destructors and that includes cpu profiler which will dump the profile as part of that.

Yes. Gperftools really save the prof.out after called exit().


`#include <iostream>
#include <execinfo.h>
#include <cxxabi.h>
#include <cstring>

// Function to demangle a single symbol
std::string demangle(char *symbol)
{
    int status;
    char temp[256];
    strcpy(temp, symbol);
    char *p = temp;
    char *endp = p + strlen(temp);
    int timer = 4;
    while (p < endp)
    {
        p = strtok(p, " ");
        if (--timer <= 0)
        {
            printf("degbug::chunks: %s\n", p);
            break;
        }
        p += 1 + strlen(p);
    }
    char *demangledName = abi::__cxa_demangle(p, 0, 0, &status);

    std::string demangledSymbol;
    if (status == 0)
    {
        std::string convertedSymbol = demangledName;
        demangledSymbol = symbol;
        demangledSymbol.replace(p - temp, strlen(p), convertedSymbol);
    }
    else
    {
        // std::cout << "demangle:" << status << std::endl;
        // If demangling fails, return the original symbol
        demangledSymbol = symbol;
    }

    return demangledSymbol;
}

// Function to print the call stack
void printCallStack()
{
    const int maxFrames = 32; // Maximum number of frames to retrieve

    void *callStack[maxFrames];
    int numFrames = backtrace(callStack, maxFrames);
    char **symbols = backtrace_symbols(callStack, numFrames);

    std::cout << "Call Stack:" << std::endl;
    for (int i = 0; i < numFrames; ++i)
    {
        std::string demangledSymbol = demangle(symbols[i]);
        std::cout << demangledSymbol << std::endl;
    }

    free(symbols);
}

// Function to demonstrate call stack printing
void functionC()
{
    printCallStack();
}



void functionB()
{
    functionC();
}

void functionA()
{
    functionB();
}

long fibonacci(unsigned n) {
    if(n >= 2) {
        return fibonacci(n - 1 ) + fibonacci(n -2);
    }
    return n;
}


int main()
{
    functionA();
    fibonacci(46);
    return 0;
}`
