### ISSUE TITLE
addr2line: DWRAF error: section.debug_info is larger than its filesize

### ISSUE THREAD

**Issue by Lumm-8** [gperftools/gperftools#1409]
When I use pprof, I get an error "addr2line: DWRAF error: section.debug_info is larger than its filesize". Will this error affect the generated callgrind file?

**Comment by alk** [comment]
Couple things. First, yes it could affect some addr->function mappings. Impossible to say from just this warning. Second, we don't really support pprof version that comes with our package (perl version). Please use go version from github.com/google/pprof. It is far more advanced, but most imprortantly it is properly supported.
