### ISSUE TITLE
automake cross compilation cannot generate dynamic libraries

### ISSUE THREAD

**Issue by ayongsir** [gperftools/gperftools#1411]
I use gperftools for aarch64 system, when I use automake build gperftools and set --enable-shared，only static library can be generated.
but I use cmake build gperftools， both Static library and dynamic library can be generated.

**Comment by alk** [comment]
Please attach config.log. It'll have a number of details that is likely to help

**Comment by ayongsir** [comment]
> Please attach config.log. It'll have a number of details that is likely to help

Thank you very much. I have found the correct settings.
