### ISSUE TITLE
Error: symbol mmap64 is already defined

### ISSUE THREAD

**Issue by sephiroth-j** [gperftools/gperftools#1418]
I am getting a build error with version 2.11 at `src/low_level_alloc_unittest-mmap_hook.o`. No issues with v2.10.

**error log**
```
/usr/bin/g++-9 -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src  -I./src -DNO_TCMALLOC_SAMPLES -O2 -march=native -mtune=bdver4 -pipe -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC -DNO_TCMALLOC_SAMPLES -O2 -march=native -mtune=bdver4 -pipe -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC -MT src/low_level_alloc_unittest-mmap_hook.o -MD -MP -MF src/.deps/low_level_alloc_unittest-mmap_hook.Tpo -c -o src/low_level_alloc_unittest-mmap_hook.o `test -f 'src/mmap_hook.cc' || echo './'`src/mmap_hook.cc
{standard input}: Assembler messages:
{standard input}:244: Error: symbol `mmap64' is already defined
Makefile:5589: recipe for target 'src/low_level_alloc_unittest-mmap_hook.o' failed
make: *** [src/low_level_alloc_unittest-mmap_hook.o] Error 1
make: *** Waiting for unfinished jobs....
mv -f src/.deps/low_level_alloc_unittest-malloc_hook.Tpo src/.deps/low_level_alloc_unittest-malloc_hook.Po
```
[build-gperftools.log](https://github.com/gperftools/gperftools/files/12408019/build-gperftools.log)

**configure command**
```
./configure --enable-minimal
```

**Environment**
- SLES 12 SP5 x64
- GCC 9.3.1
gcc-9 (SUSE Linux) 9.3.1 20200406 [revision 6db837a5288ee3ca5ec504fbd5a765817e556ac2]

**Comment by alk** [comment]
Hi and thanks for bug report. Please attach config.log from your system. Somehow your system gets _FILE_OFFSET_BITS thingy which we don't expect.

**Comment by sephiroth-j** [comment]
Ah, yes, you are right. _FILE_OFFSET_BITS=64 is defined in our CFLAGS/CXXFLAGS. Probably a remnant from the pre-64-bit past.
[config-gperftools-2.11.log](https://github.com/gperftools/gperftools/files/12416361/config-gperftools-2.11.log)

**Comment by sephiroth-j** [comment]
No, the source code was not changed.

_FILE_OFFSET_BITS is now no longer set (not necessary with 64-bit anyway) and with that it could be compiled.
