### ISSUE TITLE
Asan doesn't catch basic FMR (Free Memory Read) 

### ISSUE THREAD

**Issue by naveendugar1010** [gperftools/gperftools#1419]
```
#include <iostream>
#include <set>
using namespace std;

void DeleteElements(set<int> &mp) {
  if (mp.empty())
    return;
  for (auto it: mp) {
    if (it%2) {
      mp.erase(it);
    }
  }
}
int main() {
  std::set<int> mp;
  for (int i = 0; i < 12; i++) {
    mp.insert(i);
  }
  DeleteElements(mp);
  for (auto& it: mp) {
    cout << it << "\n";
  }
}
```
> g++ map_erase.cpp -o asan.out -fsanitize=address -static-liblsan -g

Compiling the above code with address sanitizer (asan) should flag the FMR as erase() for std::set is not used correctly here.

Executing asan.out gives the below output:

> asan.out 
> 0
> 2
> 4
> 6
> 8
> 10

**Comment by alk** [comment]
You're filing this into wrong project.

**Comment by naveendugar1010** [comment]
Where should I file it?

Thanks
Naveen

**Comment by alk** [comment]
In your case asan comes with the compiler. File ticket there.
