### ISSUE TITLE
CMake has no equivalent for `--enable-libgcc-unwinder-by-default`

### ISSUE THREAD

**Issue by Lastique** [gperftools/gperftools#1420]
As the title says. gperftools 2.12.

**Comment by alk** [comment]
Well there are always defines and what not.

Isn't cmake for the people who enjoy passing arbitrary and cryptic -Dwhatevs ? ;)

**Comment by Lastique** [comment]
`-Dwhatevs` is a CMake variable `whatevs`. CMakeLists.txt must translate it to a C++ define for it to have effect.

You can pass C++ defines in `CFLAGS` or `CXXFLAGS` but that is not what I would call best practice. Defining random macros like this may result in an unsupported or plain invalid configuration. CMake provides syntax for explicit user-configurable build options, and you're already using it, just not for `--enable-libgcc-unwinder-by-default`.
