### ISSUE TITLE
configure.ac should enable C++17 if possible

### ISSUE THREAD

**Issue by Lastique** [gperftools/gperftools#1423]
As of 2.12.0, `configure.ac` only enables C++11 (see the `AX_CXX_COMPILE_STDCXX` directive). However, the library may use C++17 memory allocation operators, e.g. involving `std::align_val_t`. `configure.ac` should be updated to opportunistically enable C++17, when compiler supports it.

The current workaround is to pass `-std=gnu++1z` or `-std=gnu++17` in `CXXFLAGS` environment variable, however this is compiler-specific.

**Comment by alk** [comment]
We already enable align_val_t stuff (well, on gcc at least). No need to have entire code base upgraded to c++17.

Please, reopen if there is specific issue you're seeing.
