### ISSUE TITLE
crash in generic_fp backtracer (was: SIGSEGV in libunwind)

### ISSUE THREAD

**Issue by akseg73** [gperftools/gperftools#1426]
Downloaded the latest gperftools from github, built it configured it with libunwind-devel and also without it, in either 
case we get a SIGSEGV without making much effort.  Some have suggested using generic_fp_unsafe instead of liunwind
we will try to do that, although other cases suggest that generic_fp is 50X slower.

This was attempted on amazon linux 2.

Isnt this stuff supposed to work by now?  did we miss something? Any help is greatly appreciated.

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ffff5495ddf in access_mem () from /lib64/libunwind.so.8
[Current thread is 1 (Thread 0x7ffff335a700 (LWP 1031))]
Missing separate debuginfos, use: debuginfo-install glibc-2.26-63.amzn2.x86_64 libaio-0.3.109-13.amzn2.0.2.x86_64 libgcc-7.3.1-15.amzn2.x86_64 libstdc++-7.3.1-15.amzn2.x86_64 libunwind-1.2-2.amzn2.0.2.x86_64 libuuid-2.30.2-2.amzn2.0.11.x86_64 numactl-libs-2.0.9-7.amzn2.x86_64
(gdb) bt
#0  0x00007ffff5495ddf in access_mem () from /lib64/libunwind.so.8
#1  0x00007ffff5496af4 in _ULx86_64_step () from /lib64/libunwind.so.8
#2  0x00007ffff7bcce0a in GetStackTraceWithContext_libunwind (result=0x7ffff321ed08,
    max_depth=253, skip_count=<optimized out>, ucp=<optimized out>)
    at src/stacktrace_libunwind-inl.h:138
#3  0x00007ffff7bcd83a in GetStackTraceWithContext (result=0x7ffff321ed08, max_depth=253,
    skip_count=3, uc=0x7ffff321f580) at src/stacktrace.cc:358
#4  0x00007ffff7bca401 in CpuProfiler::prof_handler (signal_ucontext=<optimized out>,
    cpu_profiler=0x7ffff7dd3620, sig=<optimized out>) at src/profiler.cc:354
#5  0x00007ffff7bcae37 in ProfileHandler::SignalHandler (sig=27, sinfo=0x7ffff321f6b0,
    ucontext=0x7ffff321f580) at src/profile-handler.cc:549
#6  <signal handler called>

**Comment by akseg73** [comment]
utilizing generic_fp_unsafe also requires rebuilding the code with -fno-omit-frame-pointer. Don't know what performance issues that might cause.

**Comment by alk** [comment]
generic_fp won't be so much slower than libunwind. Libunwind is super heavy and relatively slow. (Few times slower than libgcc which uses same unwind info)

And in any case for cpu profiling case speed of backtrace grabbing doesn't matter. And yes generic_fp_unsafe will be super quick. But yes no-omit-f-p will affect your perf some.

As for what to do. Well libunwind is accessing some memory trying to capture stacktrace and crashes. I suggest you file ticket for them. My understanding is even if compiler produced wrong unwind info (which sadly happened in past so might happen again), they shouldn't crash. If you do file ticket there, please consider referencing it here as well (I try to follow state of things in general with them)

Also before you give them ticket, it is fair for your to try to get their latest version and test with that.

As for this specific ticket, I don't think there is anything we can do (we won't replace/rewrite libunwind).

**Comment by akseg73** [comment]
Thanks so much for the response, for starters we will attempt to utilize generic_fp_unsafe to see if it atleast works and provides us some useful data.

**Comment by alk** [comment]
My advise is to always start with regular "safe" generic_fp. It should be more than fast enough. Because crashes will be possible with unsafe depending what you link in and flags that are used to build stuff. Only resort to unsafe if you see actual performance issue with regular one.

**Comment by akseg73** [comment]
Will do.

**Comment by alk** [comment]
Go see recently updated wiki page https://github.com/gperftools/gperftools/wiki/gperftools'-stacktrace-capturing-methods-and-their-issues and let me know if any descriptions and/or wordings need improvements.

**Comment by akseg73** [comment]
As a side, we are not being disrespectful, on the contrary gperftools has been immensely beneficial to us and the community at large. Its one of the few tools of its kind which actually is so useful.

Thanks for providing the reference we will certainly go through it more carefully

**Comment by akseg73** [comment]
This is what happens when we utilize generic_fp:

This is how we run our command
env LD_PRELOAD=/usr/local/lib/libprofiler.so TCMALLOC_STACKTRACE_METHOD=generic_fp CPUPROFILE=/dbstore/buff.prof CPUPROFILE_FREQUENCY=1000000  <command>

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/src/cyclone-master/core/build/peachdb_server ./mymisc/cluster_config.info'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  (anonymous namespace)::stacktrace_generic_fp::capture<false, false> (
    result=result@entry=0x7fffffff4a48, max_depth=257, skip_count=0,
    initial_frame=<optimized out>, initial_pc=<optimized out>, sizes=0x0)
    at src/stacktrace_generic_fp-inl.h:189
189     src/stacktrace_generic_fp-inl.h: No such file or directory.
[Current thread is 1 (Thread 0x7ffff7fe2740 (LWP 1028))]
Missing separate debuginfos, use: debuginfo-install glibc-2.26-63.amzn2.x86_64 libaio-0.3.109-13.amzn2.0.2.x86_64 libgcc-7.3.1-15.amzn2.x86_64 libstdc++-7.3.1-15.amzn2.x86_64 libunwind-1.2-2.amzn2.0.2.x86_64 libuuid-2.30.2-2.amzn2.0.11.x86_64 numactl-libs-2.0.9-7.amzn2.x86_64
(gdb) bt
#0  (anonymous namespace)::stacktrace_generic_fp::capture<false, false> (
    result=result@entry=0x7fffffff4a48, max_depth=257, skip_count=0,
    initial_frame=<optimized out>, initial_pc=<optimized out>, sizes=0x0)
    at src/stacktrace_generic_fp-inl.h:189
#1  0x00007ffff7bcd5b3 in GetStackTraceWithContext_generic_fp (result=0x7fffffff4a48,
    max_depth=<optimized out>, skip_count=<optimized out>, ucp=<optimized out>)
    at src/stacktrace_generic_fp-inl.h:342
#2  0x00007ffff7bcd83a in GetStackTraceWithContext (result=0x7fffffff4a48, max_depth=253,
    skip_count=3, uc=0x7fffffff52c0) at src/stacktrace.cc:358
#3  0x00007ffff7bca401 in CpuProfiler::prof_handler (signal_ucontext=<optimized out>,
    cpu_profiler=0x7ffff7dd3620, sig=<optimized out>) at src/profiler.cc:354
#4  0x00007ffff7bcae37 in ProfileHandler::SignalHandler (sig=27, sinfo=0x7fffffff53f0,
    ucontext=0x7fffffff52c0) at src/profile-handler.cc:549
#5  <signal handler called>

**Comment by akseg73** [comment]
Do we have to rebuild gperftools with different flags for ./configure?

**Comment by alk** [comment]
Hm. Very odd. Must be then bug in safeness checks we do. Can you please disas the frame that crashed ? (it'll be stacktrace_generic_fp::capture<false, false> function)

**Comment by akseg73** [comment]
That is frame #0 listed above. What more information is needed? Would like local variables in that frame?

**Comment by alk** [comment]
Can you please disasm that function and paste it here. (your compiler is likely to produce version similar to mine but just in case. Plus I'll get exact location of the crash)

Ah, also can you paste all register values?

Just type "disas" in gdb. Then let it print all the asm. Then type "info reg". And paste here.

**Comment by akseg73** [comment]
We recreated the issue, core dump happens right away without even test starting up, included below the
stack are the other things you have suggested:

(aside: before building gperftools, we removed libunwind-devel and then just did make distclean; ./configure; make; make install, parameters to execute were the same as before which utilized generic_fp)


(gdb) bt
#0  (anonymous namespace)::stacktrace_generic_fp::capture<false, false> (
    result=result@entry=0x7fffffff4a48, max_depth=257, skip_count=0,
    initial_frame=<optimized out>, initial_pc=<optimized out>, sizes=0x0)
    at src/stacktrace_generic_fp-inl.h:189
#1  0x00007ffff7bcdd83 in GetStackTraceWithContext_generic_fp (result=0x7fffffff4a48,
    max_depth=<optimized out>, skip_count=<optimized out>, ucp=<optimized out>)
    at src/stacktrace_generic_fp-inl.h:342
#2  0x00007ffff7bce00a in GetStackTraceWithContext (result=0x7fffffff4a48, max_depth=253,
    skip_count=3, uc=0x7fffffff52c0) at src/stacktrace.cc:358
#3  0x00007ffff7bcb1b1 in CpuProfiler::prof_handler (signal_ucontext=<optimized out>,
    cpu_profiler=0x7ffff7dd35c0, sig=<optimized out>) at src/profiler.cc:354
#4  0x00007ffff7bcbbe7 in ProfileHandler::SignalHandler (sig=27, sinfo=0x7fffffff53f0,
    ucontext=0x7fffffff52c0) at src/profile-handler.cc:549
#5  <signal handler called>


(gdb) disas
Dump of assembler code for function (anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*):
   0x00007ffff7bcdc80 <+0>:     push   %rbp
   0x00007ffff7bcdc81 <+1>:     mov    %rsp,%rbp
   0x00007ffff7bcdc84 <+4>:     push   %r15
   0x00007ffff7bcdc86 <+6>:     push   %r14
   0x00007ffff7bcdc88 <+8>:     push   %r13
   0x00007ffff7bcdc8a <+10>:    push   %r12
   0x00007ffff7bcdc8c <+12>:    mov    %rdi,%r14
   0x00007ffff7bcdc8f <+15>:    push   %rbx
   0x00007ffff7bcdc90 <+16>:    lea    (%rsi,%rdx,1),%r13d
   0x00007ffff7bcdc94 <+20>:    mov    %rcx,%rbx
   0x00007ffff7bcdc97 <+23>:    sub    $0x8,%rsp
   0x00007ffff7bcdc9b <+27>:    test   %r8,%r8
   0x00007ffff7bcdc9e <+30>:    je     0x7ffff7bcdcd7 <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+87>
   0x00007ffff7bcdca0 <+32>:    xor    %r12d,%r12d
   0x00007ffff7bcdca3 <+35>:    test   %r13d,%r13d
   0x00007ffff7bcdca6 <+38>:    je     0x7ffff7bcdcc5 <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+69>
   0x00007ffff7bcdca8 <+40>:    mov    (%r8),%rax
   0x00007ffff7bcdcab <+43>:    mov    $0x1,%r12d
   0x00007ffff7bcdcb1 <+49>:    xor    %r15d,%r15d
   0x00007ffff7bcdcb4 <+52>:    mov    %rax,(%rdi)
   0x00007ffff7bcdcb7 <+55>:    test   $0xf,%bl
   0x00007ffff7bcdcba <+58>:    jne    0x7ffff7bcdcc5 <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+69>
   0x00007ffff7bcdcbc <+60>:    cmp    $0x3fff,%rbx
   0x00007ffff7bcdcc3 <+67>:    ja     0x7ffff7bcdcdf <(anonymous namespace)::stacktrace_generic_fp:---Type <return> to continue, or q <return> to quit---
:capture<false, false>(void**, int, int, void*, void* const*, int*)+95>
   0x00007ffff7bcdcc5 <+69>:    add    $0x8,%rsp
   0x00007ffff7bcdcc9 <+73>:    mov    %r12d,%eax
   0x00007ffff7bcdccc <+76>:    pop    %rbx
   0x00007ffff7bcdccd <+77>:    pop    %r12
   0x00007ffff7bcdccf <+79>:    pop    %r13
   0x00007ffff7bcdcd1 <+81>:    pop    %r14
   0x00007ffff7bcdcd3 <+83>:    pop    %r15
   0x00007ffff7bcdcd5 <+85>:    pop    %rbp
   0x00007ffff7bcdcd6 <+86>:    retq
   0x00007ffff7bcdcd7 <+87>:    mov    %edx,%r15d
   0x00007ffff7bcdcda <+90>:    xor    %r12d,%r12d
   0x00007ffff7bcdcdd <+93>:    jmp    0x7ffff7bcdcb7 <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+55>
   0x00007ffff7bcdcdf <+95>:    cmp    %r12d,%r13d
   0x00007ffff7bcdce2 <+98>:    mov    %rbp,%rsi
   0x00007ffff7bcdce5 <+101>:   jg     0x7ffff7bcdd31 <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+177>
   0x00007ffff7bcdce7 <+103>:   jmp    0x7ffff7bcdd3d <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+189>
=> 0x00007ffff7bcdce9 <+105>:   mov    0x8(%rbx),%rax
   0x00007ffff7bcdced <+109>:   test   %rax,%rax
   0x00007ffff7bcdcf0 <+112>:   je     0x7ffff7bcdd3d <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+189>
   0x00007ffff7bcdcf2 <+114>:   cmp    %r12d,%r15d
   0x00007ffff7bcdcf5 <+117>:   jg     0x7ffff7bcdd04 <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+132>
   0x00007ffff7bcdcf7 <+119>:   mov    %r12d,%edx
   0x00007ffff7bcdcfa <+122>:   sub    %r15d,%edx
---Type <return> to continue, or q <return> to quit---
   0x00007ffff7bcdcfd <+125>:   movslq %edx,%rdx
   0x00007ffff7bcdd00 <+128>:   mov    %rax,(%r14,%rdx,8)
   0x00007ffff7bcdd04 <+132>:   mov    (%rbx),%rax
   0x00007ffff7bcdd07 <+135>:   add    $0x1,%r12d
   0x00007ffff7bcdd0b <+139>:   cmp    $0x3fff,%rax
   0x00007ffff7bcdd11 <+145>:   jbe    0x7ffff7bcdd3d <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+189>
   0x00007ffff7bcdd13 <+147>:   mov    %rax,%rdx
   0x00007ffff7bcdd16 <+150>:   sub    %rbx,%rdx
   0x00007ffff7bcdd19 <+153>:   cmp    $0x20000,%rdx
   0x00007ffff7bcdd20 <+160>:   ja     0x7ffff7bcdd3d <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+189>
   0x00007ffff7bcdd22 <+162>:   test   $0xf,%al
   0x00007ffff7bcdd24 <+164>:   jne    0x7ffff7bcdd3d <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+189>
   0x00007ffff7bcdd26 <+166>:   cmp    %r12d,%r13d
   0x00007ffff7bcdd29 <+169>:   mov    %rbx,%rsi
   0x00007ffff7bcdd2c <+172>:   je     0x7ffff7bcdd3d <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+189>
   0x00007ffff7bcdd2e <+174>:   mov    %rax,%rbx
   0x00007ffff7bcdd31 <+177>:   mov    %rbx,%rdi
   0x00007ffff7bcdd34 <+180>:   callq  0x7ffff7bcd700 <(anonymous namespace)::stacktrace_generic_fp::CheckPageIsReadable(void*, void*)>
   0x00007ffff7bcdd39 <+185>:   test   %al,%al
   0x00007ffff7bcdd3b <+187>:   jne    0x7ffff7bcdce9 <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+105>
   0x00007ffff7bcdd3d <+189>:   sub    %r15d,%r12d
   0x00007ffff7bcdd40 <+192>:   jmp    0x7ffff7bcdcc5 <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+69>
End of assembler dump.


(gdb) info reg
rax            0x1      1
rbx            0x2b9ae71c0      11705151936
rcx            0x7ffff739cd79   140737341148537
rdx            0x1      1
rsi            0x1000   4096
rdi            0x0      0
rbp            0x7fffffff49d0   0x7fffffff49d0
rsp            0x7fffffff49a0   0x7fffffff49a0
r8             0x0      0
r9             0x0      0
r10            0x7fffffff5ea0   140737488314016
r11            0x0      0
r12            0x1      1
r13            0x101    257
r14            0x7fffffff4a48   140737488308808
r15            0x0      0
rip            0x7ffff7bcdce9   0x7ffff7bcdce9 <(anonymous namespace)::stacktrace_generic_fp::capture<false, false>(void**, int, int, void*, void* const*, int*)+105>
eflags         0x10202  [ IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
k0             0x0      0
k1             0x0      0
k2             0x0      0
k3             0x0      0
k4             0x0      0
k5             0x0      0
k6             0x0      0
k7             0x0      0

**Comment by alk** [comment]
looks like msync is wrong way to check whether address is readable. It doesn't handle PROT_NONE mappings. It could potentially explain libunwind crash. They at least in some architectures also do msync to "probe" address for being readable.

To double check, can you also add output of "info file" from gdb ?

**Comment by akseg73** [comment]
Thanks for your response, we will setup once again and recreate the issue, if there is any additional information you need please let us know, we have to set this up in the cloud.

**Comment by akseg73** [comment]
[info.file.txt.txt](https://github.com/gperftools/gperftools/files/12506066/info.file.txt.txt)

The file containing output from info file has been attached. Please let us know if there is anything else that is needed and any suggestions as to how we can make progress, right now we are getting a segfault without even running the tests, the product dies right at startup.

**Comment by alk** [comment]
I still haven't decided on the proper fix for this. But here is what will let you run profiler (apply with patch -p1):

```
diff --git a/src/stacktrace_generic_fp-inl.h b/src/stacktrace_generic_fp-inl.h
index e8bdf2f..14e6d48 100644
--- a/src/stacktrace_generic_fp-inl.h
+++ b/src/stacktrace_generic_fp-inl.h
@@ -119,7 +119,10 @@ static bool CheckPageIsReadable(void* ptr, void* checked_ptr) {
   // well us few other "trivial" calls crash.
   rc = syscall(SYS_msync, reinterpret_cast<void*>(addr), pagesize, MS_ASYNC);
 #else
-  rc = msync(reinterpret_cast<void*>(addr), pagesize, MS_ASYNC);
+  // rc = msync(reinterpret_cast<void*>(addr), pagesize, MS_ASYNC);
+  //
+  // DO NOT SUBMIT
+  rc = syscall(SYS_rt_sigprocmask, ~0, addr, 0, 8);
 #endif
 
   return (rc == 0);
diff --git a/src/tests/stacktrace_unittest.cc b/src/tests/stacktrace_unittest.cc
index 6f20ea1..855ba7b 100644
--- a/src/tests/stacktrace_unittest.cc
+++ b/src/tests/stacktrace_unittest.cc
@@ -193,10 +193,13 @@ int ATTRIBUTE_NOINLINE CaptureLeafUContext(void **stack, int stack_len) {
 
   // SignalHandler will run somewhere here, making sure we capture
   // backtrace from signal handler
+  uintptr_t save;
+  asm volatile ("mov %%rbp, %0; mov $0xaaaaaaa0, %%rbp" : "=r" (save));
   gst_args.ready = true;
   while (!gst_args.captured) {
     // do nothing
   }
+  asm volatile ("mov %0, %%rbp" : : "r" (save));
 
   rv = sigaction(SIGPROF, &old_sa, nullptr);
   CHECK(rv == 0);
```

Do note that whatever function that is triggering this condition will have "truncated" stacktrace, but at least you'll see that function in the profile.

**Comment by akseg73** [comment]
Thanks for the response, hopefully this will allow us to make some progress.

**Comment by akseg73** [comment]
We applied the patch and were able to finally run our test for about 30 minutes which we have never been able to do. In the past even when utilizing libunwind we would be lucky to be able to run for 5 minutes. We would have to try several time.

However, the data we have collected is not very useful as it is not allowing us to look into the functions which were hoping
to examine. The remaining numbers may be accurate or not, we can't tell, they certainly don't tally up with the shorter runs
we had earlier with libunwind.

We'll make sure that we are not making a mistake at our end.

**Comment by akseg73** [comment]
we are building everything with -fno-omit-frame-pointer.

**Comment by akseg73** [comment]
Please let us know if there is likely to be any fix for this in the near future. Currently we are struggling with some issues which would have been best diagnosed with gperftools.

**Comment by alk** [comment]
Patch above is the fix. I will submit (likely in a couple days) a much cleaner version but effect will be identical.

If whatever I posted above doesn't work for you, please let me know.

**Comment by akseg73** [comment]
That patch does not work the reason is that it effectively disables the statistics for all of the functions we want to
dig into. Please consult some of your colleagues to see if there is something else that might be more appealing.

So liunwind as well generic-fp are both running into seg faults for us. Its unfortunate that we are not able to
utilize this tool. What other option do we have.

**Comment by alk** [comment]
I sense misunderstanding. This ticket is "there is an avoidable crash in cpu profiler". I have a fix for that.

I have no magic means for unbreaking whatever functions you're trying to profile. That a) use frame pointer register for other needs (you said above you're going to build with frame pointers) b) lack unwind info. If I had to guess you're probably dealing with handcrafted asm codes (example of similar case I helped fix recently: https://github.com/libjpeg-turbo/libjpeg-turbo/pull/708)

Second, while there are no software means in existence today that can give you full backtraces, you're still getting somewhat useful profiles. Hits within those functions (but not their parents) are reflected in cpu profile you get today.

And third, there are somewhat limited but working hardware option for your case. Linux perf with LBR option allows hardware to track call stack for you. If you're able to get this working in your environment you'll get those backtraces. perf isn't so great when it comes to visualizing profiles and "massaging" them. But there are tools that with varying degrees of success make those perf profiles available for pprof (or other tools). I.e.: https://alkandratsenka.blogspot.com/2015/02/visualizing-perf-profiles-using-pprof.html (I am not sure if it works still) or https://github.com/google/perf_data_converter

**Comment by akseg73** [comment]
Are you saying that the most likely cause of these segfaults is 'asm codes' ,  if that is the case we can try our code with those asms disabled. Most of those asms are just accessing the lock for timing data anyway. So we can throw those away.

**Comment by akseg73** [comment]
Thanks a lot for your suggestion regarding asm interfering with our runs. We disabled all the 'asm's and now we do not see any seg faults with libunwind either. We have run it several times and it seems to work.

Thanks a lot, we would never be able to figure this out ourselves.

**Comment by alk** [comment]
More misunderstandings. Are you saying you get segfaults even with the patch above ?

As for what exactly gets in the way (well, assuming you don't get crashes with the patch) you'll see in the profile exactly what function(s) have truncated backtraces. Asm or no asm.

**Comment by akseg73** [comment]
NO, we are saying that once we disable 'asm' we do not get any segfaults (we did apply the patch you provided). The added benefit of disabling ams's is that we are now able to get all the stack details. Hope that clarifies it.

**Comment by alk** [comment]
Sorry, I am still confused. With just my patch, do you get any segfaults (truncated backtraces should be expected) ?

This is important because I need to know if my patch actually fixed the crash in your case (it should have fixed the crash).

**Comment by akseg73** [comment]
your patch fixes the seg faults
removing asm's allows us to see all the stack details.

the reason you are a little confused by our statements is that we are users of this tool and have superficial (if any) understanding of its workings, where as you understand the depths of this.

anyway we appreciate your help.

**Comment by akseg73** [comment]
One more data point, when utilizing the patch you provided we still get a seg fault below if we do not utilize generic_fp and the code was built without -fno_omit_frame_pointer. So it seems that for us we also have to build the code with -fno-omit-frame-pinter else we get segfaults.

(gdb) bt
#0  0x00007ffff56bc407 in ?? () from /lib64/libgcc_s.so.1
#1  0x00007ffff56bde52 in _Unwind_Backtrace () from /lib64/libgcc_s.so.1
#2  0x00007ffff7bcd93c in GetStackTraceWithContext_libgcc (result=<optimized out>,
    max_depth=<optimized out>, skip_count=<optimized out>, ucp=<optimized out>)
    at src/stacktrace_libgcc-inl.h:100
#3  0x00007ffff7bcdfda in GetStackTraceWithContext (result=0x7ffff3439d08, max_depth=253,
    skip_count=3, uc=0x7ffff343a580) at src/stacktrace.cc:358
#4  0x00007ffff7bcb171 in CpuProfiler::prof_handler (signal_ucontext=<optimized out>,
    cpu_profiler=0x7ffff7dd35c0, sig=<optimized out>) at src/profiler.cc:354
#5  0x00007ffff7bcbba7 in ProfileHandler::SignalHandler (sig=27, sinfo=0x7ffff343a6b0,
    ucontext=0x7ffff343a580) at src/profile-handler.cc:549
#6  <signal handler called>

**Comment by akseg73** [comment]
more data, we are now getting a seg fault even after building with -fno-omit-frame-pointer where the command line looks like this:
env LD_PRELOAD=/usr/local/lib/libprofiler.so CPUPROFILE=buff.prof CPUPROFILE_FREQUENCY=1000000 

In short, we don't really know for sure what is going on.

**Comment by alk** [comment]
Looking forward seeing more details. Here is what I know so far about your case:

a) there are some functions (possibly asm functions or possibly inline asm) that break or lack regular unwind info and that use RBP register to point to some unreadable area of memory

b) this causes libunwind to crash when they try to backtrace through this broken code

c) similar crash occurs with generic_fp method as shipped today

d) The fix above for fixes the crash but there is no way for us or anyone to get you backtraces through those affected function(s)

Specific details about crash(es) could tell me what exactly is going on. And I am happy to help, but as of now I am not aware of any specific issue in gperftools itself, other than generic_fp crash above (the issue(s) are only your setup/codebase). Feel free to post as many details as you feel comfortable. If some details are non-public, feel free to mail them to me directly.

**Comment by akseg73** [comment]
Thanks for your response. We did not take a very close look at the stack in the seg faults. When these occur are the stack frames precisely located at the offending code?  If so then we can analyze some of that code ourselves to determine what could be wrong. But next time we re-create the crash we will be happy to provide the details.

**Comment by alk** [comment]
Yes, assuming the crash is libunwind trying to capture backtrace, you'll see libunwind stack frames at the top, then gperftools cpu profiler, then signal trampoline, then function where SIGPROF signal occured and then either nothing (or garbage) or few more frames.

Based on previous evidence, this "leaf" function where signal occurred seems to be the damaged one. It is to be expected that gdb will also be unable to show stack frames below "bad" function. So bottom-most function that you could see on profile is likely to be bad one.
