### ISSUE TITLE
crash in tcmalloc_minimal on windows( RemoveInitialHooksAndCallInitializers() in malloc_hook.cc)

### ISSUE THREAD

**Issue by muliu** [gperftools/gperftools#1428]
Downloaded the latest gperftools 2.12 from github, built it configured it with Release-Override x86 on windows using VisualStudio 2022。

link libtcmalloc_minimal.lib in statically with a Console APP for test purpose.   The test app'code is very simple: 

#include <iostream>
#include <windows.h>

int main()
{
    printf("hello tcmalloc test. \n");

    char* p = new char[260];
    if (NULL != p)
    {
        ZeroMemory(p, 260);
        strcpy_s(p, 260, "123456");

        printf("p = %s\n", p);

        delete[] p;
        p = NULL;
    }

    getchar();
    return 0;
}
 
then Press F5 to debug it, a exception occur :
Exception thrown at 0x773FF5F3 (ntdll.dll) in tcm_s.exe: 0xC0000005: Access violation writing location 0x00000014.

the callstack is：
 	ntdll.dll!RtlpWaitOnCriticalSection()	Unknown
 	ntdll.dll!RtlpEnterCriticalSectionContended()	Unknown
 	ntdll.dll!_RtlEnterCriticalSection@4()	Unknown
 	[Inline Frame] tcm_s.exe!_Init_thread_lock() Line 146	C++
 	tcm_s.exe!_Init_thread_header(int * pOnce) Line 200	C++
	[Inline Frame] tcm_s.exe!?A0x240ceca3::RemoveInitialHooksAndCallInitializers() Line 132	C++
 	tcm_s.exe!`anonymous namespace'::InitialNewHook(const void * ptr, unsigned int size) Line 121	C++
 	[Inline Frame] tcm_s.exe!MallocHook::InvokeNewHookSlow(const void *) Line 314	C++
 	tcm_s.exe!MallocHook::InvokeNewHook(const void * p, unsigned int s) Line 133	C++
 	[Inline Frame] tcm_s.exe!tcmalloc::do_allocate_full(unsigned int) Line 1808	C++
 	tcm_s.exe!tcmalloc::allocate_full_cpp_throw_oom(unsigned int size) Line 1818	C++
 	[Inline Frame] tcm_s.exe!tcmalloc::dispatch_allocate_full(unsigned int) Line 1826	C++
 	[Inline Frame] tcm_s.exe!malloc_fast_path(unsigned int) Line 1881	C++
 	[Inline Frame] tcm_s.exe!tc_new(unsigned int) Line 2022	C++
 	[Inline Frame] tcm_s.exe!operator new(unsigned int) Line 45	C++
 	tcm_s.exe!__acrt_initialize_heap() Line 101	C++
 	tcm_s.exe!__acrt_execute_initializers(const __acrt_initializer * first, const __acrt_initializer * last) Line 25	C++
 	tcm_s.exe!__acrt_initialize() Line 259	C++
 	[External Code]	

![test code](https://github.com/gperftools/gperftools/assets/644615/2a9e0ea7-6414-4cf0-a1fa-e64e60e611e4)

![exception](https://github.com/gperftools/gperftools/assets/644615/0fee4e64-6628-4b6e-92ec-b054128b2a7a)

![exception 2](https://github.com/gperftools/gperftools/assets/644615/d5234024-e7e9-4f76-9130-59dc673e8f77)

**Comment by alk** [comment]
So I didn't reproduce your repro case, but I see the problem from backtraces you post. For that I uploaded fix. Please test latest master and update if the issue is gone.

**Comment by muliu** [comment]
**It works!**

Thanks for the fix!
