### ISSUE TITLE
build error:  src/base/sysinfo.cc:249:25: error: converting to 'std::tuple<bool, const char*, const char*>' from initializer list woul d use explicit constructor 

### ISSUE THREAD

**Issue by KeenH** [gperftools/gperftools#1432]
on linux, build failed. 

uname  -a
Linux host1 3.10.0-1160.99.1.el7.x86_64 #1 SMP Thu Aug 10 10:46:21 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

cd  gperftools-2.13, 
./configure 
make 

libtool: compile:  g++ -std=gnu++11 -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-
virtual -Wno-sign-compare -Wno-unused-result -fno-omit-frame-pointer -momit-leaf-frame-pointer -g -O2 -MT src/base/sysin
  .lo -MD -MP -MF src/base/.deps/sysinfo.Tpo -c src/base/sysinfo.cc  -fPIC -DPIC -o src/base/.libs/sysinfo.o
src/base/sysinfo.cc: In function 'std::tuple<bool, const char*, const char*> QueryHPCEnvironment()':
src/base/sysinfo.cc:230:37: error: converting to 'std::tuple<bool, const char*, const char*>' from initializer list woul
d use explicit constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements =
 {bool, const char (&)[7], char*&}; <template-parameter-2-2> = void; _Elements = {bool, const char*, const char*}]'
     return {false, ".rank-", envval };
                                     ^
src/base/sysinfo.cc:240:41: error: converting to 'std::tuple<bool, const char*, const char*>' from initializer list woul
d use explicit constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements =
 {bool, const char (&)[10], char*&}; <template-parameter-2-2> = void; _Elements = {bool, const char*, const char*}]'
       return {false, ".slurmid-", procid};
                                         ^
src/base/sysinfo.cc:243:25: error: converting to 'std::tuple<bool, const char*, const char*>' from initializer list woul
d use explicit constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements =
 {bool, const char (&)[1], const char (&)[1]}; <template-parameter-2-2> = void; _Elements = {bool, const char*, const ch
ar*}]'
     return {true, "", ""};
                         ^
src/base/sysinfo.cc:249:25: error: converting to 'std::tuple<bool, const char*, const char*>' from initializer list woul
d use explicit constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements =
 {bool, const char (&)[1], const char (&)[1]}; <template-parameter-2-2> = void; _Elements = {bool, const char*, const ch
ar*}]'
     return {true, "", ""};
                         ^
src/base/sysinfo.cc:255:36: error: converting to 'std::tuple<bool, const char*, const char*>' from initializer list woul
d use explicit constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements =
 {bool, const char (&)[7], char*&}; <template-parameter-2-2> = void; _Elements = {bool, const char*, const char*}]'
     return {false, ".rank-", envval};
                                    ^
src/base/sysinfo.cc:259:24: error: converting to 'std::tuple<bool, const char*, const char*>' from initializer list would use explicit constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements =                      = {bool, const char (&)[1], const char (&)[1]}; <template-parameter-2-2> = void; _Elements = {bool, const char*, const ch                      har*}]'
   return {false, "", ""};
                        ^
make: *** [src/base/sysinfo.lo] Error 1

**Comment by KeenH** [comment]
temp fix: 
src/base/sysinfo.cc:230:37:
- return {false, ".rank-", envval};
+ return std::make_tuple(false, ".rank-", envval);

**Comment by alk** [comment]
What gcc version you're building with? Can you attach config.log?

**Comment by alk** [comment]
To elaborate some. I am semi-regularly testing on centos 6. With devtools 7 installed (otherwise built-in gcc is way too old).

We're very thankful to Red Hat for shipping up-to-date tools for their generally not very new enterprise distros. We try to support those older Linux-en (even past rhat own support support schedule), but we _require_ somewhat up-to-date compiler versions.

Thus my question about your compiler version.

**Comment by lfxyl** [comment]
I encountered the same problem, this is my gcc version：

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/root/.iso_compiler/v2/gcc/x86_64-5.4/bin/../libexec/gcc/x86_64-linux-gnu/5.4.0/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../gcc-5.4.0/configure --prefix=/mnt/hdd/isocompiler/target-gcc-5.4 --enable-languages=c,c++ --disable-libsanitizer --with-gnu-as --with-gnu-ld --enable-threads=posix --with-pkgversion='ISO Compiler for Ubuntu 16.04' --enable-shared --enable-linker-build-ld --with-sysroot=/mnt/hdd/isocompiler/target-gcc-5.4/libc/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-multiarch --disable-werror --with-abi=m64 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 (ISO Compiler for Ubuntu 16.04)

**Comment by alk** [comment]
Okay, this should be fixed.

But do note that gcc 5 indeed has non-conformant std::tuple constructor. And there is only so much I can do with obsolete broken compilers.

So next release will be last where I'll test and support gcc 5.

Users of centos/rhel 7 are strongly encouraged to install and use devtools thingy. As for ubuntu 16, well, perhaps simply upgrade.
