### ISSUE TITLE
Failed to static link to my dynamic library with libtcmalloc_and_profiler.a

### ISSUE THREAD

**Issue by zhanglistar** [gperftools/gperftools#1441]
When I try to static link gperftools to my dynamic library, I got this error.
`ld.lld-16: error: relocation R_X86_64_TPOFF32 against thread_disable_counter cannot be used with -shared`
It seems that TLS variable cannot link with -shared, any advice?
Thanks.

**Comment by alk** [comment]
Yes, this is general elf-specific aspect.

.so libraries are built for dynamic linking and they're PIC (wiki. While .a libraries are for linking to main binary so they're classically non-pic (but increasingly different distros are defaulting to "PIE" a variant of PIC useful for binaries).

https://en.wikipedia.org/wiki/Position-independent_code has more details.

So just link .so with .so and you'll be fine.

Alternatively, you might be able to work around the issue by passing -fpic to both CXXFLAGS and LDFLAGS.
