### ISSUE TITLE
"generic_fp_unsafe" stacktrace method crashes (possibly due to omitted frame pointer in libc) while the previous "x86" method works

### ISSUE THREAD

**Issue by blahgeek** [gperftools/gperftools#1444]
Gperftools version: 2.12
OS version: Ubuntu 20.04
Arch: x86_64

While using the CPU profiler with "generic_fp_unsafe" stacktrace, it may crashes when trying to obtaining the stacktrace during some libc function (in my case, in `pthread_mutex_trylock` function). The reason is that `uc->uc_mcontext.gregs[REG_RBP]` is incorrect, possibly due to ommitted frame pointer in libc. (my own code, including gperftools, is compiled with fno-omit-frame-pointer though)

However, the previous "x86" backtrace method (tested in gperftools 2.7) does work in this case because apparently it does not uses the ucontext information.

So my questions are

- Is this (all code must be compiled with fno-omit-frame-pointer) the expected requirement for "generic_fp_unsafe" method? If so, it seems a too strict requirement, because most people cannot control system libraries
- Can we not use the ucontext info in "generic_fp_unsafe" method to solve this issue?
- Or, can we get the "x86" method back?

Thanks in advance!

**Comment by blahgeek** [comment]
> a) can you please elaborate why you choose "unsafe" backtracer? What happens if you simply use safe one ?

Because the safe one is too slow for us. We are using the profiler in production (with a low sampling rate) and want the overhead to be as small as possible.

> b) what do you mean when you say x86 backtracer "works"? Is it just not crashing or is it somehow getting you better/right backtraces when generic_fp (safe one) doesn't ?

Sorry I wasn't clear. The x86 backtracer does not crash, though the backtrace result is incomplete. But the generic_fp_unsafe method would crash. (Also, the safe one would not crash, which is expected)

---

I did more debugging and I think I have found the root cause:

The stack looks like this:

```
#0 GetStackTraceWithContext               <- gperftools is compiled with fno-omit-frame-pointer
#1 CpuProfiler::prof_handler
#2 ProfileHandler::SignalHandler
<signal handler called>                                  
#3 pthread_mutex_trylock from libc.so.6   <- libc.so is NOT compiled with fno-omit-frame-pointer
#4 foo                                    <- user program is compiled with fno-omit-frame-pointer
#5 bar
```

When the signal is triggered in some function that is not compiled with frame pointer (in this case, libc.so), the `rbp` value in the signal context (`uc->uc_mcontext.gregs[REG_RBP]`) is not the correct frame pointer. It's used as `initial_frame` [here](https://github.com/gperftools/gperftools/blob/64d64bee40811ae19cb119414bdd5e078094d8a7/src/stacktrace_generic_fp-inl.h#L171) and the backtracer crashed [here](https://github.com/gperftools/gperftools/blob/64d64bee40811ae19cb119414bdd5e078094d8a7/src/stacktrace_generic_fp-inl.h#L179).

The old "x86" backtracer doesn't crash because 1. it does not use the value from signal context as the initial frame 2. it would do basic sanity check while using each frame pointer from the stack.

So IMO the correct fix is that, in current `generic_fp` backtracer, we should also do [sanity checks](https://github.com/gperftools/gperftools/blob/master/src/stacktrace_generic_fp-inl.h#L196-L210) for the initial frame before using it.

**Comment by blahgeek** [comment]
I created an PR that can fix my issue: https://github.com/gperftools/gperftools/pull/1447

**Comment by alk** [comment]
Your patch LGTM. I took it. Thanks.

I still encourage you to back up your "safe is too slow" with numbers (and if you're able to post them here, please do).

My understanding is for production occasional activation of profiler signal handler each 10ms of compute, and profiler taking probably up to few micros of cpu, will still be negligible overhead. You're not constantly profiling after all. Plus if you do find overhead too large, you can always profile with smaller frequency and longer profiling duration.

And you'll be sleeping better knowing that backtraces are robust.
