### ISSUE TITLE
TCMALLOC_PAGE_FENCE does not take effect in gperftools-2.1.90 and above versions.

### ISSUE THREAD

**Issue by MiloMallo** [gperftools/gperftools#1454]
I set TCMALLOC_PAGE_FENCE to true, and added the --enable-frame-poin option in the compilation. However, it does not work.

> #ifdef HAVE_MMAP
    DEFINE_bool(malloc_page_fence,
            EnvToBool("TCMALLOC_PAGE_FENCE", true),
            "Enables putting of memory allocations at page boundaries "
            "with a guard page following the allocation (to catch buffer "
            "overruns right when they happen).");

**Comment by MiloMallo** [comment]
In versions higher than 2.1, there is no problem when using the compilation option -O2, but it does not work with -O0. However, for version 2.1, there is no problem with the compilation option -O0.

**Comment by MiloMallo** [comment]
I fixed it
![image](https://github.com/gperftools/gperftools/assets/15778994/257be8f6-cbef-4f4a-8201-f03ab1fe58f2)

**Comment by alk** [comment]
Thanks for the update. Will you post this as a patch (pull request works too)? If you can add unit test, it would be most awesome.

**Comment by MiloMallo** [comment]
This might not be a bug, as the memory allocated here has been aligned. For example, if I requested 10 bytes of memory, and the kMinAlign here is 16, after alignment, 16 bytes are actually allocated for the 10 bytes requested. Therefore, executing memcpy(a,b,16); will not cause an exception because 16 bytes were actually allocated, and it won't trigger a checker exception. Hence, there should be an optimization point here; the checker should check based on the actual size of the allocated memory.

**Comment by alk** [comment]
Closing then. I am still unsure what it was about. "does not take effect" is very unclear. Please reopen if you have anything to add.
