### ISSUE TITLE
More specifical information needed when warning

### ISSUE THREAD

**Issue by zhanglistar** [gperftools/gperftools#1457]
When doing this command, 
`pprof --svg /usr/lib/jvm/java-8-openjdk-amd64/bin/java /root/_3289640.0130.heap`
I got this, 
```
Some binary filenames not available. Symbolization may be incomplete.
Try setting PPROF_BINARY_PATH to the search path for local binaries.
```

Could you please print out the binary filenames more specifically? That will be helplful.

**Comment by alk** [comment]
Hi. perl pprof implementation that comes with our source is strongly deprecated. We don't support it. People should be using pprof from github.com/google/pprof

So, sorry, but I am closing this ticket as wont-fix.

**Comment by zhanglistar** [comment]
@alk No, it's go version.

**Comment by alk** [comment]
Hi. Then file ticket over there.
