### ISSUE TITLE
gperftools only profile heap memory usage of C/C++？

### ISSUE THREAD

**Issue by yr-wang-hit** [gperftools/gperftools#1463]
We have a numerical program with C++ and Fortran static library. When using gperftools heap profiler to understand which routine(s) occupy too much memory, it seems that memory allocated by fortran library not take into account. So if gperftools only profile C/C++ memory allocation and free? If there are any good choice to profile fortran library memory usage?

Thanks.

**Comment by alk** [comment]
Hi. It don't know anything about fortran, but we should be hooking regular OS allocation routines. If this fortran thingy is dynamically allocating memory somehow, it will probably end up calling down to malloc/free, then we'd hook it. If it doesn't, well, maybe it does mmap/sbrk directly? We should be hooking those too on GNU/Linux.

**Comment by alk** [comment]
please reopen if/when you're able to add more details.
