### ISSUE TITLE
Infinite recursion occurs when calling MallocExtension::instance() from a custom operator new

### ISSUE THREAD

**Issue by poljak181** [gperftools/gperftools#1472]
Hi!
I have encountered a problem that was discussed in these issues:

- https://github.com/gperftools/gperftools/issues/852
- https://github.com/gperftools/gperftools/issues/718

I have prepared a minimal example to reproduce it.
```cpp
#include <gperftools/tcmalloc.h>
#include <gperftools/malloc_extension.h>

void* operator new(size_t size)
{
    auto ptr = tc_malloc(size);
    auto sz = MallocExtension::instance()->GetAllocatedSize(ptr);
    // log size allocation ...
    return ptr;
}

void operator delete(void* p) _GLIBCXX_USE_NOEXCEPT
{
    tc_free(p);
}

int main()
{
    auto pi = new int;
    delete pi;
    return 0;
}
```
Compile it with:
```bash
clang++ -g main.cpp -Wl,-rpath,. -L. -ltcmalloc_minimal
```

Calling **MallocExtension::instance()** leads to calling **operator new**, which, in turn, leads to calling **MallocExtension::instance()**. This causes an infinite recursion.

I have tried two solutions:

1. Compiling the **tcmalloc_minimal** library with the linker option **-Bsymbolic**, which forces the library to use functions implemented inside itself (especially operator new). The problem with this solution is that I can't track memory allocations inside the tcmalloc library in this case.
You can add `add_link_options(-Wl,-Bsymbolic)` in **CMakeLists.txt** and rebuild the library.

2. Another approach proposed in issue 718. Using placement new fixes the problem. You can see a possible fix in this 
[placement_new.patch](https://github.com/gperftools/gperftools/files/13798180/placement_new.patch)

Which solution is the best?

**Comment by alk** [comment]
yes, it makes sense. I am frankly surprised we didn't do it earlier. Applying this shortly.

**Comment by alk** [comment]
Applied. Thanks.

Next time, please consider offering proper git patch so that I don't have to be formal author of your commit and risk forgetting to refer to your contribution in the NEWS file.
