### ISSUE TITLE
HEAPCHECK and HEAPPROFILE do not work successfully for fork sub-process

### ISSUE THREAD

**Issue by aitazhixin** [gperftools/gperftools#1488]
In my code, a main function forks two sub-processes using gperftools-2.13, has some problems as below:
**### 1,**
HEAPPROFILE for this program:
`HEAP_PROFILE_ALLOCATION_INTERVAL=2097152 HEAPPROFILE=perflog HEAPPROFILE_USE_PID=1 ./memory_assign`
The subprocess memory note will be covered:
`Starting tracking the heap`
`Dumping heap profile to perflog_505460.0001.heap (10 MB allocated cumulatively, 10 MB currently in use)`
`Dumping heap profile to perflog_505460.0001.heap (5 MB allocated cumulatively, 5 MB currently in use)`
`Dumping heap profile to perflog_505460.0002.heap (20 MB allocated cumulatively, 20 MB currently in use)`
`Dumping heap profile to perflog_505460.0002.heap (10 MB allocated cumulatively, 10 MB currently in use)`
`Dumping heap profile to perflog_505460.0003.heap (30 MB allocated cumulatively, 30 MB currently in use)`
`Dumping heap profile to perflog_505460.0003.heap (15 MB allocated cumulatively, 15 MB currently in use)`
`Dumping heap profile to perflog_505460.0004.heap (40 MB allocated cumulatively, 40 MB currently in use)`
`Dumping heap profile to perflog_505460.0004.heap (20 MB allocated cumulatively, 20 MB currently in use)`
`Dumping heap profile to perflog_505460.0005.heap (25 MB allocated cumulatively, 25 MB currently in use)`
`Dumping heap profile to perflog_505460.0005.heap (50 MB allocated cumulatively, 50 MB currently in use)`
`Dumping heap profile to perflog_505460.0001.heap (Exiting, 0 bytes in use)`
`Dumping heap profile to perflog_505460.0006.heap (Exiting, 50 MB in use)`
`Dumping heap profile to perflog_505460.0006.heap (Exiting, 25 MB in use)`

**How to save memory state for each subprocess?**

**### 2,**
HEAPCHECK cannot show sub-processes memory leak.
`HEAPCHECK=strict ./memory_assign`
output:
`WARNING: Perftools heap leak checker is active -- Performance may suffer`
`Have memory regions w/o callers: might report false leaks`
`No leaks found for check "_main_" (but no 100% guarantee that there aren't any): found 14 reachable heap objects of 73370 bytes`

**### code**
`int main(int argc, char** argv) {`
`    std::vector<std::thread> ths;`
**`    pid_t ten_pid = fork();`**
`    if (ten_pid == 0) {`
`        prctl(PR_SET_NAME, "ten");`
`        ths.emplace_back(ten_block);`
`    }`
`    else if (ten_pid > 0) {`
**`        pid_t five_pid = fork();`**
`        if (five_pid == 0) {`
`            prctl(PR_SET_NAME, "five");`
`            ths.emplace_back(five_block);`
`        }`
`    }`
`    while(true) {`
`        std::this_thread::sleep_for(std::chrono::milliseconds(20000));`
`        break;`
`    }`
`    for (auto& th : ths) {`
`        th.join();`
`    }`
`    return 0;`
`}`

`void ten_block() {`
`    int count = 5;`
`    while(count-- > 0) {`
**`        char* ptr = new char[10*block_size_k];`**
`        auto start = std::chrono::steady_clock::now();`
`        auto end = start;`
`        while(std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() < 100) {`
`            end = std::chrono::steady_clock::now();`
`        }`
**`        // delete [] ptr;`**
`        while(std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() < 1000) {`
`            end = std::chrono::steady_clock::now();`
`        }`
`    }`
`}`

`void five_block() {`
`    int count = 5;`
`    while(count-- > 0) {`
**`        char* ptr = new char[5*block_size_k];`**
`        auto start = std::chrono::steady_clock::now();`
`        auto end = start;`
`        while(std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() < 100) {`
`            end = std::chrono::steady_clock::now();`
`        }`
**`        // delete [] ptr;`**
`        while(std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() < 1000) {`
`            end = std::chrono::steady_clock::now();`
`        }`
`    }`
`}`

**Comment by alk** [comment]
We cannot magically detect process forking and "fork" the heap profiler (or checker) state. If you require something like that (but, really, forking and threading isn't good mix), you'll need to start heap {profiler,checker} manually in in those separate address spaces.
