### ISSUE TITLE
Transparent hugepages eating up a lot of memory

### ISSUE THREAD

**Issue by coder-saab001** [gperftools/gperftools#1494]
Running my application using gperftools's tcmalloc. Captured some data and got to know that a huge amount of memory is going towards the transparent hugepages
<img width="594" alt="image" src="https://github.com/gperftools/gperftools/assets/141615129/6187d4fd-6e01-46d9-8ee3-3b40a546827c">
The huge bump seen here is nothing but memory towards transparent hugepages.

Is there any way to limit it..

Kernel Version
5.10.205-2.el8

Transparent hugepages setting:
![image](https://github.com/gperftools/gperftools/assets/141615129/77cb9f0a-24da-4471-95bb-410ff3f9916f)

**Comment by alk** [comment]
Yes, your case is likely yet another "victim" of max_ptes_none setting. It's default is harmless.  We should do something to document it better. So please feel free to contribute documentation maybe.

/sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_none

Set it to 0.

**Comment by coder-saab001** [comment]
Thanks @alk for quick reaponse.
I had an older linux kernel (3.10.0-1160.76.1.el7). With following transparent hugepages settings:
![image (1)](https://github.com/gperftools/gperftools/assets/76659019/6e4bf500-2734-4aad-8b4c-ae3be87e7f30)
max_ptes_none is set to 511 here too.

But I am not able to see the same issue here. Things are working perfectly good here. What might be happening here??

**Comment by alk** [comment]
Apologies for delay. Yes, I think it is still "it".
