### ISSUE TITLE
How to get stats for large objects (i.e. > 256KB) 

### ISSUE THREAD

**Issue by alokkataria** [gperftools/gperftools#1497]
Today the MallocExtention::GetStats() implementation, even at level 2, returns information about memory allocated only for all size classes that are available and the page_heap free list information. From what I understand, If the application has done a lot of large object allocations (> 256KB) information about those allocations is not presented anywhere. Which makes accounting of all memory for an application very difficult.

Any ideas if there's a way to get that information ?

**Comment by alk** [comment]
Best way to get stats for in-use allocations is through sampling. It will work regardless of sizes.

If you want stats about freelists, then, yes, you'd need to add code to maintain histograms for larger spans.

**Comment by alokkataria** [comment]
I see, you mean we need to set TCMALLOC_SAMPLE_PARAMETER and get information using GetHeapSample, wasn't aware of this, let me try this out. Thanks !

**Comment by alk** [comment]
Closing with assumption of "resolved". Please, reopen with details if this is not the case.
