### ISSUE TITLE
Inquiry: Issue with pprof Usage

### ISSUE THREAD

**Issue by PengWei97** [gperftools/gperftools#1506]
Dear Maintainers of the gperftools Repository,

I am a user of the MOOSE framework and I have encountered some issues while using pprof for performance analysis. I would greatly appreciate your assistance in resolving them.

I have been running a simulation using a MOOSE program and attempting to analyze its performance with pprof. The workflow involves running the simulation to generate a series of performance analysis files named `run1_*.prof`, and then using the command `pprof run1.prof` to analyze one of these files. However, when I execute `pprof run1.prof`, I encounter the following error:

```
Using remote profile at run1.prof.
Use of uninitialized value $line in substitution (s///) at /home/pw-moose/miniforge/envs/moose/bin/pprof line 3326.
http://run1.prof/pprof/symbol doesn't exist
```

Could you please assist me in resolving this issue? I would greatly appreciate any guidance or insights you can provide.

Thank you very much for your assistance.

Best regards,
Wei

**Comment by alk** [comment]
Hi.

First, please use go pprof from github.com/google/pprof. Our version written in perl is unmaintained and deprecated.

Second, the way to use pprof in this case is first give it program then profile file. I.e. pprof <myprog> run1.prof

Have a nice day.
