### ISSUE TITLE
please  i am having  problems on my kali    can someone help me out

### ISSUE THREAD

**Issue by mt103vps** [gperftools/gperftools#1507]
configure.ac:16: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
configure.ac:16: You should run autoupdate.
m4/libtool.m4:100: AC_PROG_LIBTOOL is expanded from...
configure.ac:16: the top level
configure.ac:28: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:28: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:28: the top level
configure.ac:93: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:93: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
configure.ac:93: the top level
configure.ac:111: warning: The macro `AC_CONFIG_HEADER' is obsolete.
configure.ac:111: You should run autoupdate.
./lib/autoconf/status.m4:719: AC_CONFIG_HEADER is expanded from...
configure.ac:111: the top level
configure.ac:113: warning: AC_OUTPUT should be used without arguments.
configure.ac:113: You should run autoupdate.
Makefile.am:4: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/Makefile.am:6: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')

**Comment by alk** [comment]
Well, this is border-line rude. You're filing two identical tickets with no (or by far not enough) details. I understand this is not intentional, but please learn from this.

What is missing is what and how exactly it fails. What version you're trying to build and how. What you posted so far is just a set of warnings (odd warnings btw).

As for that autoconf and autoupdate thingy. Just take .tar.gz from releases which according to common practice among autotools projects includes already produced configure script.

**Comment by mt103vps** [comment]
i am sorry ok 



Building with autotools:

cd rtl-sdr/
autoreconf -i
./configure
make
sudo make install
sudo ldconfig

if run the autoreconf -i    command  it gives me the   warnings 
please how can fix these

**Comment by alk** [comment]
How our code is related to rtl-sdr? What kind of errors exactly are you getting? Are you simply complaining about warnings? If so, please list exact versions of autoconf, libtool and automake you have.

**Comment by mt103vps** [comment]
autoconf is already the newest version (2.71-3).
libtool is already the newest version (2.4.7-7)
automake is already the newest version (1:1.16.5-1.3).

**Comment by mt103vps** [comment]
$ autoreconf -i
configure.ac:16: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
configure.ac:16: You should run autoupdate.
m4/libtool.m4:100: AC_PROG_LIBTOOL is expanded from...
configure.ac:16: the top level
configure.ac:28: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:28: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:28: the top level
configure.ac:93: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:93: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
configure.ac:93: the top level
configure.ac:111: warning: The macro `AC_CONFIG_HEADER' is obsolete.
configure.ac:111: You should run autoupdate.
./lib/autoconf/status.m4:719: AC_CONFIG_HEADER is expanded from...
configure.ac:111: the top level
configure.ac:113: warning: AC_OUTPUT should be used without arguments.
configure.ac:113: You should run autoupdate.
Makefile.am:4: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/Makefile.am:6: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')

**Comment by mt103vps** [comment]
if run the autoreconf -i      
command it gives me the configure.ac warnings
please how can fix these

**Comment by mt103vps** [comment]
Should be completed without warnings.
i am using  kali-linux-2024.1 version
