### ISSUE TITLE
Global variable destruction order

### ISSUE THREAD

**Issue by yejw5** [gperftools/gperftools#1514]
We have encounter a crash in program exiting, with coredump stacktrace like this:

```
#0  tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) () from /app/mipilot/lib/libtcmalloc.so
#1  tcmalloc::ThreadCache::Scavenge() () from /app/mipilot/lib/libtcmalloc.so
#2  ProcessContext() () from /app/mipilot/lib/libados_apprt.so
#3  NodeLaunch::~NodeLaunch() ()
#4  main ()
```

Is it possible that some global/static variable of tcmalloc have been destroyed, like Static::central_cache()?

**Comment by alk** [comment]
We don't destroy anything (well, almost, we have couple places like in heap leak checker). It also Google-style policy (google-search for Google C++ style guide).

As for your crash, pretty much all crashes like this is some bug in user's code. That it crashes in tcmalloc bits doesn't really prove it is "us". (Of course we cannot 100% guarantee we have no crashing bugs, but it is super unlikely that we have)

As usual in such cases, consider running with various malloc debugging tools: asan, our "own" debugallocator, valgrind etc.
