### ISSUE TITLE
mmap_hook_test uses 15+GB of memory

### ISSUE THREAD

**Issue by yurivict** [gperftools/gperftools#1522]
mmap_hook_test kills the system because it keeps growing in memory, and tests have to be aborted.

(I tried to run tests to investigate the issue that you've reported, https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279560, but found this issue in the process.)

Version: 2.15
FreeBSD 14.1-STABLE stable/14-n267671-9a8a26aefb36

**Comment by alk** [comment]
Are you testing 2.15 release or master?

**Comment by yurivict** [comment]
I am testing 2.15

**Comment by alk** [comment]
So you want me what? To go back in time and fix 2.15 ? Please test master there are plenty of changes and we're close to doing 2.16 rc (and then 2.16 proper).

**Comment by alk** [comment]
Also how do I get that precise version string on FreeBSD? (with n267671 thingy posted above)

**Comment by yurivict** [comment]
I was testing using the FreeBSD port.
I'll retest using the latest master revision.

**Comment by yurivict** [comment]
This test failure doesn't exist in the latest master revision addf751.
