### ISSUE TITLE
from-ucontext stack trace tests fail on !frame-pointer backtracers on !Linux (was: stacktrace_unittest fails: CHECK_LE(ret_addr, range.end); fails)

### ISSUE THREAD

**Issue by yurivict** [gperftools/gperftools#1524]
```
(gdb) p ret_addr
$1 = (void *) 0x2c498a7b <thr_sighandler+315>
(gdb) p range.end
$2 = (const void *) 0x207756 <CaptureLeafUContext(void**, int)+902>
```

Version: 2.15
FreeBSD 14.1-STABLE stable/14-n267671-9a8a26aefb36

**Comment by yurivict** [comment]
This test still fails with the latest master revision https://github.com/gperftools/gperftools/commit/addf7514207db473a632e6dbff31cd0c4559b0f9.

**Comment by alk** [comment]
It actually works on my freebsd VM. Can you please a) test fresh checkout just in case b) post exact failure details that apply to master

**Comment by yurivict** [comment]
Yes, I can reproduce it with a fresh checkout of addf751

How to reproduce:
1. Apply [this patch](https://freebsd.org/~yuri/google-perftools.patch) to the port tree.
2. cd /usr/ports/devel/google-perftools
3. make test

**Comment by alk** [comment]
I am not a bsd person. Don't make me apply anything to ports or anything else "complex" BSD-wise. I can ssh and run usual unixy bits on FreeBSD VM. I think it is fair I stop here.

**Comment by yurivict** [comment]
Either some environment variables, or configure arguments matter.

I was able to create a UNIXy reproducer.

Just run [this](https://freebsd.org/~yuri/google-perftools-test-failure-reproducer.sh) shell script on a freshly cloned repo, and it should reproduce the problem.

**Comment by alk** [comment]
Somewhat simpler and more precise reproduction:

* get libunwind installed (as root): pkg info libunwind-20240221 
* then checkout master of gperftools
* `LDFLAGS="-L/usr/local/lib" CXXFLAGS="-O2 -isystem /usr/local/include" ./configure`
* `make stacktrace_unittest && ./stacktrace_unittest`

BTW, is there "normal" way to get /usr/local things automagically added to includes and libs ? Or is it some kind of principled way to make people's lives more hardcore?

**Comment by yurivict** [comment]
> BTW, is there "normal" way to get /usr/local things automagically added to includes and libs ? Or is it some kind of principled way to make people's lives more hardcore?

On BSDs there are 2 prefixes: /usr (for base) and /usr/local (for ports).
Only the first prefix is added automatically.
It would be strange to add both prefixes automatically, because there could be more prefixes in general. All of them can't be added.
It's also a bad idea to conflate them, like in Linux.

Sorry if this is inconvenient. This isn't done this way to inconvenience people.

**Comment by alk** [comment]
Lets consider this fixed. Tests will now pass. But I created https://github.com/gperftools/gperftools/issues/1526 to cover making things work correctly, rather than avoiding brokenness in test.
