### ISSUE TITLE
out-of-tree configure runs fail to detect working GetPC method (was: Issues when not configuring in top of source)

### ISSUE THREAD

**Issue by lindsayad** [gperftools/gperftools#1525]
My standard procedure is something like
```
mkdir build
cd build
../configure <some options>
make
make install
```
which allows me to have multiple builds with different configurations. This used to work with gperftools. However, after pulling today and doing a fresh configure and install, I was missing `libprofiler.so`. Going back to the configure step, I found this warning:
```
configure: WARNING: Could not find the PC.  Will not try to compile libprofiler...
```
which going into `config.log` appears to be because we assume that we are in the top of the source directory when configuring
```
| #include "src/getpc.h"
| int
| main (void)
| {
| GetPC({})
|   ;
|   return 0;
| }
```
It would be nice to be able to configure in other locations or if not wanting to support that, then erroring at the time of configuration and informing the user where they should run configure

**Comment by alk** [comment]
Thanks for the ticket, but what makes you think that failing to locate a working method of ucontext->pc mapping is due to non-source directory build? Have you tried to do in-source-dir build to confirm it "works" there ?

**Comment by alk** [comment]
Hm, but your observation is correct. Thanks for spotting and reporting it.

I personally don't do out-of-tree builds, but make distcheck always checks this. And yet of course if some features get disabled, it has no means to detect this.

So something to think about. How to make sure we end up with same number of tests when we do make distcheck

**Comment by lindsayad** [comment]
> Have you tried to do in-source-dir build to confirm it "works" there ?

Yes I did and it works well

**Comment by alk** [comment]
Fixed now. Thanks, again, for reporting the issue.

**Comment by lindsayad** [comment]
No problem. Thanks for the rapid fix!
