### ISSUE TITLE
tcmalloc_and_profiler removed

### ISSUE THREAD

**Issue by ct1n** [gperftools/gperftools#1528]
The tcmalloc_and_profiler target was removed in https://github.com/gperftools/gperftools/commit/9dfab2cdce5ec1ebb36e2a20e5031ef49cbe8087

Was this intentional? It seems it was quite used. The [conan recipe](https://github.com/conan-io/conan-center-index/blob/master/recipes/gperftools/all/conanfile.py) breaks because of this.

**Comment by alk** [comment]
It wasn't removed. Only cmake support for doing it (which we still don't right) was amputated. And specifically a huge number of tests were failing indicating possible and likely issues with .so-s and .a-s. Another related comment is here: https://github.com/gperftools/gperftools/issues/1518#issuecomment-2131325539

Again, cmake support was and is best-effort. I was thinking, lets merge it and give it chance to improve. Instead I get people jumping ahead and doing somewhat sophisticated stuff with it (judging by conan thing you're referring to). I.e. someone spent nontrivial effort, invested own time to create dependency that shouldn't be created. Makes me sad and unsure what to do.

So closing and assuming this is the answer. Question was "why". Answer is "it didn't work" (for the fullest extent of meaning of "work").

If you're one of those numerous people who somehow feel strongly about all things cmake, please consider implementing this missing support you want.
