### ISSUE TITLE
mmap failed, when offset is physical address

### ISSUE THREAD

**Issue by zero-zhaowei** [gperftools/gperftools#1530]
used tcmalloc lib with hisi32bit platform, i need mmap an address and offset param is physical address(0x9240a000), but mmap failed.

`static void* do_sys_mmap(long sysnr, void* start, size_t length, int prot, int flags, int fd, long offset)`， i think offset param type should be unsigned long .

signed type will lost Precision .

i changed long offset to unsigned ,mmap succeed.

**Comment by alk** [comment]
Hi. Thanks for the ticket but off_t type is signed. It is what it is. Also I don't know what platform is that you're referring to, but all modern linuxes should be doing mmap2 syscall (with offset divided by page size and thus avoiding limited precision of 32-bit off_t).

So perhaps you can elaborate some ?

**Comment by alk** [comment]
Ah, and of course, address and offset are different params. If you're saying that in order to mmap at high address you need to pass some unusually high offset, something isn't right.

**Comment by zero-zhaowei** [comment]
> Hi. Thanks for the ticket but off_t type is signed. It is what it is. Also I don't know what platform is that you're referring to, but all modern linuxes should be doing mmap2 syscall (with offset divided by page size and thus avoiding limited precision of 32-bit off_t).
> 
> So perhaps you can elaborate some ?

I need to use this tool on the ARM ，and Need to use different toolchains。from  Linux Programmer's Manual, this param is off_t, I think this type（off_t） will adapt to the toolchain， Can this type be applied for compatibility？

>If you're saying that in order to mmap at high address you need to pass some unusually high offset, something isn't right.

Yes, I did use it that way。

**Comment by alk** [comment]
off_t is 32- or 64- bits based on different factors. We cannot use this type (there are comments in this file).

In this place of code we need to be explicit. long is right type to use. It is of machine word width and signedness actually doesn't matter in this place as we simply pass it as-is.

**Comment by zero-zhaowei** [comment]
ok,thanks
