### ISSUE TITLE
Questions about ProfilerStart

### ISSUE THREAD

**Issue by cj2a7t** [gperftools/gperftools#1532]
Hi @alk

```
if (ProfilerStart(profile)) {
    /* start ITIMER_PROF timer */
    ProfilerRegisterThread();  // executed
} 
```

<img width="431" alt="image" src="https://github.com/gperftools/gperftools/assets/70355872/8ddb1260-2a0b-45c4-913d-6061a50d76f9">
Why is there always no profile data.

**Comment by alk** [comment]
We dump profile data usually when profiling stops or (usually rarer) gradually as internal cpu profiling hash table overflows. I.e. have profiling stop and you should see something.

**Comment by cj2a7t** [comment]
Thanks @alk,  need to ProfilerStop(), right?

**Comment by alk** [comment]
Make sure your program runs whatever you want to profile for at least few seconds. I advise at least 10-30 seconds to get at least somewhat decent profile precision. Then either stop profile or have you program exit normally.

**Comment by cj2a7t** [comment]
sure thanks

**Comment by cj2a7t** [comment]
Hi @alk  I would like to ask you another question. If lua is called in the nginx program I use, the result is as follows. How can I locate the specific lua file?
<img width="601" alt="image" src="https://github.com/gperftools/gperftools/assets/70355872/3f4ae306-7e2d-43a6-8cf6-6e5e7ddcd8bb">

**Comment by cj2a7t** [comment]
Hi @alk Do you have any suggestions?

**Comment by alk** [comment]
Not really. Regular lua is interpreter. So you'd be seeing profile of interpreter itself. If you're dealing with luajit or similar thing, you'd be getting complications both in getting backtraces and getting them symbolized via pprof. You may need some lua-specific profiler.

**Comment by cj2a7t** [comment]
<img width="656" alt="image" src="https://github.com/gperftools/gperftools/assets/70355872/e894f1ec-aedb-4245-9845-5f503ad234f0">
`use jit.off()`, Close Luajit.

**Comment by cj2a7t** [comment]
<img width="593" alt="image" src="https://github.com/gperftools/gperftools/assets/70355872/6fcebed8-f02b-4755-8de0-751edaf05493">
use jit.on()
