### ISSUE TITLE
Flag provided but not defined: -symbols

### ISSUE THREAD

**Issue by albertcaldas84** [gperftools/gperftools#1534]
Hello,

I'm trying to run ggperf on my app but after installing go and latest version of pprof I'm getting this when ggperf calls it:

```
Thread finding failed with -1 errno=14
Could not find thread stacks. Will likely report false leak positives.
Have memory regions w/o callers: might report false leaks
Leak check _main_ detected leaks of 666 bytes in 21 objects
The 3 largest leaks:
flag provided but not defined: -symbols
usage:

Produce output in the specified format.

   pprof <format> [options] [binary] <source> ...

```

Seems that latest pprof doesn't support --symbols? Any idea? Thanks a lot

**Comment by alk** [comment]
For next time please consider adding far more details.

For I see I can infer that you're trying to do heap checker. Something isn't working (we see it complains with errno nr. 14 (EFAULT on Linux)). Then gperftools attempts to symbolize some backtrace and somehow tries to invoke go pprof. go pprof isn't designed to do symbolization requests. We ship pprof-symbolize which is our old legacy perl version that understands --symbols flag. So something isn't right with your setup. But I'd need far more details to advise.
