### ISSUE TITLE
Receiving "Profiling timer expired" when using gperftools to profile

### ISSUE THREAD

**Issue by dentiny** [gperftools/gperftools#1535]
I receive "Profiling timer expired" error when I use gperftools to profile, which behaves the same as if no signal handler is registered.

My program looks like

A python driver program:
```
if __name__ == '__main__':
    glog.error("Enter into the program")

    # Set gperftools env for C++ process, not python, otherwise will be overwritten.
    env = os.environ.copy()
    assert "CPUPROFILE" in env

    # Code pointer within gperftools checks:
    # https://github.com/gperftools/gperftools/blob/825b6638cf76aecc5a540d3fa662d157760fc11e/src/base/sysinfo.cc
    env["CPUPROFILE_USE_PID"] = "true"

    proc = subprocess.Popen(
        ["bazel-bin//external_profiling/cpp_subprocess"],
        env=env)

    glog.error(proc.stdout)
    glog.error(proc.returncode)
```

Within the python process, I started a C++ process.
```
void DeadLoop1() {
  uint64_t start_time = env::EnvTime::Default()->NowSecondsWithSteadyClock();
  while (true) {
    uint64_t cur_time = env::EnvTime::Default()->NowSecondsWithSteadyClock();
    if (cur_time - start_time >= 10) {
      return;
    }
  }
}
int main(int argc, char** argv) {
  std::jthread([]() { DeadLoop1(); });
  // Another subprocess.
  const std::string kSubprocessBinary =
      "bazel-bin/experimental/external_profiling/cpp_subprocess";
  Process process;
  THROW_IF_ERROR(process.ForkExec(kSubprocessBinary, {kSubprocessBinary},
                                       /*envp=*/{}, /*pipe_mask=*/{}));
  ASSIGN_OR_THROW(int ret_code, process.Wait());
  CHECK_EQ(ret_code, 0);
  return 0;
}
```

Command:
```
LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc_and_profiler.so.4" CPUPROFILE=/tmp/cpu_profile.out HEAPPROFILE=/tmp/mem_profile.heap HEAP_PROFILE_TIME_INTERVAL=3 bazel-bin/experimental/external_profiling/python_driver
```

My understanding for profiling is:
- A timer is setup: https://linux.die.net/man/2/setitimer
- A `SIGPROF` signal handler is registered to perform stacktrace aggregation related work

The error that I get is: "Profiling timer expired" without further output (in the start of driver python program I print something out).
The error doesn't reproduce stably, I'm wondering
- If it's allowed to use gperftool for profiling in multi-process environment?
  + I doubt if it's an issue since it crashes right away, before my print out at the first line in `main` function
- If it's allowed to use CPU profiler and memory profiler at the same time via "libtcmalloc_and_profiler.so.4"?
  + I doubt it also, since the same setup sometimes works sometimes not

**Comment by alk** [comment]
Hi. For all your questions the answer is Yes. Bugs might still lurk somewhere, but it should work. That you're getting "profiling timer expired" implies that SIGPROF gets delivered but signal handler is reset to default. I can only guess why. Perhaps python does that ?

I'd recommend:

* consider setting LD_PRELOAD or CPUPROFILE only for C++ bits, so that python stuff doesn't get exposed to SIGPROF stuff.
* double check what process gets this error. Is that python thingy or C++.
* also maybe consider creating a smaller reproducer program so I can inspect myself

**Comment by dentiny** [comment]
Thanks @alk for the reply! 

Yes the error message implies the profiling timer is registered, but somehow the signal handler (which also resides in gperftool and supposed to be registered via LD_PRELOAD) misses.

> consider setting LD_PRELOAD or CPUPROFILE only for C++ bits, so that python stuff doesn't get exposed to SIGPROF stuff.

Yeah I agree, but the proj I'm working on is a generic execution plane, which could execute both python and C++; meanwhile a few C++ programs are actually launched via python subprocess.

> double check what process gets this error. Is that python thingy or C++.

TBH it's hard, because both profiling timer and signal handler are supposed to be registered before main;
For example, the "profiling timer expired" message appear before my first statement in python.

> also maybe consider creating a smaller reproducer program so I can inspect myself

Sure, I shorten the code snippet a bit; let me know if it reproduces on your end; but it somehow doesn't reproduce deterministically one my end.

Python driver program:
```
import os
import subprocess
import time

if __name__ == '__main__':
    env = os.environ.copy()
    assert "CPUPROFILE" in env
    proc = subprocess.Popen(
        ["bazel-bin/experimental/hjiang/external_profiling/cpp_subprocess"],
        env=env)
    t1.join()
    t2.join()
    glog.error(proc.stdout)
```
C++ subprocess program:
```
#include <iostream>
#include <thread>
#include <chrono>

static constexpr uint64_t kSecondsToNanos = 1000ULL * 1000ULL * 1000ULL;
int64_t NowNanosWithSteadyClock() {
  return std::chrono::duration_cast<std::chrono::nanoseconds>(
              std::chrono::system_clock::now().time_since_epoch())
      .count();
}
uint64_t NowSecondsWithSteadyClock() {
  return NowNanosWithSteadyClock() / kSecondsToNanos;
}

void DeadLoop3() {
  uint64_t start_time = NowSecondsWithSteadyClock();
  while (true) {
    uint64_t cur_time = NowSecondsWithSteadyClock();
    if (cur_time - start_time >= 10) {
      return;
    }
  }
}
void DeadLoop5() {
  uint64_t start_time = NowSecondsWithSteadyClock();
  while (true) {
    uint64_t cur_time = NowSecondsWithSteadyClock();
    if (cur_time - start_time >= 10) {
      return;
    }
  }
}

int main(int argc, char** argv) {
  std::jthread([]() { DeadLoop3(); });
  DeadLoop5();
  return 0;
}
```

**Comment by dentiny** [comment]
I think I know more about this issue.

It could be reproduced by only python script.
```
if __name__ == '__main__':
    glog.error("Enter into the program")

    # Set gperftools env for C++ process, not python, otherwise will be overwritten.
    env = os.environ.copy()
    assert "CPUPROFILE" in env

    # Code pointer within gperftools checks:
    # https://github.com/gperftools/gperftools/blob/825b6638cf76aecc5a540d3fa662d157760fc11e/src/base/sysinfo.cc
    env["CPUPROFILE_USE_PID"] = "true"

    proc = subprocess.Popen(
        ["bazel-bin//external_profiling/cpp_subprocess"],
        env=env)

    glog.error(proc.stdout)
    glog.error(proc.returncode)
```

Command:
```
LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libprofiler.so.0 /usr/lib/x86_64-linux-gnu/libtcmalloc.so.4" CPUPROFILE=/tmp/cpu_profile.out HEAPPROFILE=/tmp/mem_profile.heap HEAP_PROFILE_TIME_INTERVAL=3 strace -e trace=signal bazel-bin/experimental/external_profiling/python_driver
```

The issue is:
- Use `strace` to see `signal` syscall;
- There's `rt_sigaction(SIGPROF, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0` at python launch which override registered signal handler.

**Comment by alk** [comment]
okay then. This implies something isn't right with CPU profiling python interpreter. It doesn't look like your intention is to do that. (If it is, then go bother python folk or debug yourself why python might be resetting SIGPRIOF handler; I don't see any value for them doing it)
