### ISSUE TITLE
Advantages of using File backed Mapping

### ISSUE THREAD

**Issue by yash760** [gperftools/gperftools#1536]
I wanted to understand the advantages of using file backed mapping here. I believe we could all the things we do here by using MAP_ANONYMOUS also(because anyway we are unlinking the _**hugetlb_fd_**_ and using MAP_PRIVATE). 

Was wondering why we decided to go with this approach rather than the anonymous mmap or if we never think of using anonymous mapping. I searched around but couldn't find any relevant answers.

```
  result = mmap(0, size + extra, PROT_WRITE|PROT_READ,
                FLAGS_memfs_malloc_map_private ? MAP_PRIVATE : MAP_SHARED,
                hugetlb_fd_, hugetlb_base_);
```
Reference: https://github.com/gperftools/gperftools/blob/master/src/memfs_malloc.cc#L197

**Comment by yash760** [comment]
@alk are you aware on this?

**Comment by alk** [comment]
So I cannot give you a true historical perspective of why something was added. I can only say what I know.

First, please note that private mapping isn't the default. And, indeed, I see no reason to use private mapping. No idea why it was added.

As for shared mappings, there are plenty of uses for it. For example it can be used to cgroup accounting reasons (tmpfs/hugetlbfs/etc mount being accounted differently than process' memory). It can be used to tweak huge pages stuff (most typical usage). And it is not hard to imagine any kind of "special" memory being available via some kind of shared memory mount.

**Comment by alk** [comment]
Ah, I was just reminded about one thing. Private mapping of hugetlbfs does make sense and is actually somewhat helpful if/when someone uses fork (which everyone should avoid; there are better ways to do nearly everything)
