### ISSUE TITLE
CPU profiler doesn't produce file for std

### ISSUE THREAD

**Issue by dentiny** [gperftools/gperftools#1537]
I found when using python as the driver program with CPU profiler enabled with LD_PRELOAD, the profiler file will not be generated.

Example code to reproduce
```
if __name__ == '__main__':
    env = os.environ.copy()
    proc = subprocess.Popen(
        ["bazel-bin/external_profiling/cpp_subprocess"],
        env=env,
        # If remove the later two lines, the CPU profiler file will be generated without any problem.
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE)

    proc.wait()
```

Command to reproduce:
```
LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libprofiler.so.0" CPUPROFILESIGNAL=12 CPUPROFILE=/tmp/cpu_profile.out bazel-bin/experimental/external_profiling/python_driver
```

**Comment by alk** [comment]
It implies something isn't right with your environment variables. I'd suspect CPUPROFILESIGNAL.

https://github.com/gperftools/gperftools/blob/285908e8c7cfa98659127a23532c060f8dcbd148/src/profiler.cc#L199

Make sure you understand what is it that you want and debug it first without python driver.
