### ISSUE TITLE
Use LD_PRELOAD=“libtcmalloc.so” no profile.heap file

### ISSUE THREAD

**Issue by zhangdexin** [gperftools/gperftools#1542]
Becase I dev a so module, I canot recompile the main prog. I use LD_PRELOAD env do that. And point HEAPPROFILE env, but not the file gene.
And I use LD_DEBUG, the 'malloc' and 'free' symbols already bind the libtcmalloc.so.
I think use libtcmalloc to gene heap file if restricted by some compilation options.
Please help.

Tks

**Comment by alk** [comment]
It should work. Any more details you can offer will help. Is that latest released version? Master? Does that fail even on simplest program (i.e. no .so-s involved)?

**Comment by zhangdexin** [comment]
The simplest program can work.
Not lastest version, perhaps it is the master at two month ago.
Now I try the lastest version, and use gperftools, how open the log output, eg. error log for no gene heap file

**Comment by zhangdexin** [comment]
Oh, I am sorry. I’m sorry. 😂
I git clone the master code at two month ago.
simple program and simple program with so both can be work.

**Comment by alk** [comment]
Does that mean there is no bug? Can you please clarify very ***very*** verbosely?

**Comment by zhangdexin** [comment]
In my Huge project. It canot work. So I think it related with compile option.

**Comment by alk** [comment]
Well, we need to narrow it down somehow. How can this be affected by compile flags? You're saying same libtcmalloc.so works as expected with simple .so library, but fails with much bigger project ?

**Comment by zhangdexin** [comment]
Yeah, so I want to open the verbose log of libtcmalloc.so if it had.

**Comment by alk** [comment]
Sorry, I am struggling to understand your words. Are you saying you need help enabling more verbose logs ? (Set PERFTOOLS_VERBOSE=100 and you'll get plenty of log into stderr; hard to say if it'll help diagnose this case)

**Comment by alk** [comment]
Also, another thing worth trying just in case is some older released versions. Just to see if it is something introduced recently or not.

**Comment by zhangdexin** [comment]
Yeah, I need more info about that. And it can provide the detail for you.
I am going try it about PERFTOOLS_VERBOSE and then provide the log for you.

**Comment by zhangdexin** [comment]
It output like this：
```
Found hooked allocator at 7: 0x7efd7f168b2c <- 0x558df89d0176
Found hooked allocator at 7: 0x7efd7f168b2c <- 0x7efd608b0732
...
```
and ctrl + c can not stop prog.
1) Is the libtcmalloc generate the heap file at when recv SIGINT or main prog exit ?
2) If main prog install sigaction and it will filter the SIGINT, it causing thisbug?

**Comment by alk** [comment]
We don't intercept any signals by default.

There is optional HEAPPROFILESIGNAL environment variable that can be used to set up signal that triggers profile dumping.

Heap profiler files are created based on various metrics. See MaybeDumpProfileLocked in heap-profiler.cc and it's uses.

You can force heap profile dumping by invoking HeapProfilerDump (or HeapProfilerStop). See heap-profiler.h header that we ship.

We also have profile dumping trigger at normal program termination (see HeapProfileEndWriter), but I am not sure if this works for LD_PRELOAD-ed libtcmalloc

**Comment by zhangdexin** [comment]
I use HEAPPROFILESIGNAL it can work. I think I found the problem，HEAP_PROFILE_ALLOCATION_INTERVAL is 1G by default. My bigger prog no alloc 1G memory and no exit. My simple prog run a period of time and exit normal. So simple prog can generate file.
It is not a bug.
Tks.
