### ISSUE TITLE
How stat the “so” library memory allocation？

### ISSUE THREAD

**Issue by zhangdexin** [gperftools/gperftools#1548]
Hi, I want to stat my so library memory alloction, and the executable no recompile,  I only can recompile my so library with -ltcmalloc. But I gene heap profile the alloc is 0. So I want to stat my so library only, how do that?

**Comment by zhangdexin** [comment]
I sorry, I want to profile single so library not all app.

**Comment by alk** [comment]
You cannot profile single shared library. Put you can profile whole thing and filter down. See above.
