### ISSUE TITLE
is there any downsides for defining NO_TCMALLOC_SAMPLES?

### ISSUE THREAD

**Issue by lano1106** [gperftools/gperftools#1550]
it seems like defining NO_TCMALLOC_SAMPLES can make allocations be faster...

by always skipping over

```
  if (PREDICT_FALSE(!cache->TryRecordAllocationFast(allocated_size))) {
    return tcmalloc::dispatch_allocate_full<OOMHandler>(size);
  }
```

tbh, it is a bit fuzzy in my mind what the class Sampler is supposed to achieve...

I was never aware that some allocation were traced...

intuitively, no trace, no check at all to see if a recording is needed...
it seems like it is only good things and no downsides...

what am I missing?
is this documented anywhere?
what is the trade off to have no allocations never recorded?
(beside populating stats that I am not using)

**Comment by lano1106** [comment]
https://github.com/gperftools/gperftools/pull/1551

**Comment by alk** [comment]
If you don't need sampling, you can simply use "libtcmalloc_minimal". But if you want to have it disabled some other way, sure.

Also overhead introduced by sampling is carefuly built to be minimal. On fast-path it is just decrement and conditional jump (a little more but still fast on more risc-ful instruction sets). And yes it is very useful if you know how to use it. At Google all servers run with sampling enabled and ~any engineer can obtain this sample of heap. Showing where memory is spent right now. It can then  be used to investigate things like leaks and what not. Borg and other infrastructure also provides niceties around this. Like pre-mortem heap samples captured (usually) shortly prior to task getting OOMed and it has saved our ass countless times.

**Comment by lano1106** [comment]
ok thx for the info...

One valid use strategy in that case would be:

Use minimal version by default. If heap issues are suspected, start using the full version to have the allocator perform samples to help in the debugging

That assume of course that you know what the samples can do for you and how to use them...

Is there some documentation about how this data can be used?

**Comment by alk** [comment]
Documentation is another area where we could use more help. I don't think it is well documented. The raw usage can be seen here: https://github.com/gperftools/gperftools/blob/ae15d7a490eff0cd93fbbcfa89469f672e0ec7cd/src/tests/sampling_test.cc#L182

(inside Google there are well-known standard HTTP handlers to serve those; Go folk have caught some of that culture: https://pkg.go.dev/net/http/pprof@go1.23.0)
