### ISSUE TITLE
Multithreaded behaviour of MallocHook

### ISSUE THREAD

**Issue by mfranzreb** [gperftools/gperftools#1555]
I am using MallocHook for memory benchmarking of a multithreaded program. Currently, only the main thread adds the hooks at the beginning of the benchmark, and removes them at the end. Sometimes, a hook gets called after it was removed by the main thread.

The documentation at the top of "malloc_hook.h" states:
```
// Some of our malloc implementations can invoke the following hooks whenever
// memory is allocated or deallocated.  MallocHook is thread-safe, and things
// you do before calling AddFooHook(MyHook) are visible to any resulting calls
// to MyHook.  Hooks must be thread-safe.  If you write:
//
//   CHECK(MallocHook::AddNewHook(&MyNewHook));
//
// MyNewHook will be invoked in subsequent calls in the current thread, but
// there are no guarantees on when it might be invoked in other threads.
```

How can I ensure that when I add/remove a hook, all (de-)allocations are recorded/ignored from that point onwards? Is it possible to have a hook per thread?

**Comment by alk** [comment]
Yes, our implementation is deliberately simple and un-synchronized in this regard. If you need more, have one "perma hook" installed and implement own hooks facility with whatever extra synchronization on top (something along the lines of RCU comes to mind here).

We choose performance and our main use-case is hooks that are installed early (e.g. see heap checker) and don't get removed in practice.

**Comment by alk** [comment]
Have a per-thread flag "I am in the middle of the hook". We have not exactly this but similar here: https://github.com/gperftools/gperftools/blob/f46c141b4eaea3872c2bfc3974d1240ff16dd00b/src/memory_region_map.cc#L193

**Comment by alk** [comment]
In fact I did a similar tracking recently. You see code here: https://godbolt.org/z/nYYvG74d7 (although arguably in that case per-thread-ness wasn't necessary)

**Comment by mfranzreb** [comment]
Thank you for the tips!
