### ISSUE TITLE
What diff the tcmalloc with `https://github.com/google/tcmalloc` ?

### ISSUE THREAD

**Issue by zhangdexin** [gperftools/gperftools#1556]
`https://github.com/google/tcmalloc` also has tcmalloc, and I think gperftools's tcmalloc and google's tcmalloc is one thing.
But some code is still different.
Why not use submodule if the difference isn't huge?
What kind of development concept is it?

**Comment by alk** [comment]
We have common ancestry, but our code bases diverged a lot. Rest I'll leave for https://github.com/gperftools/gperftools/issues/1496 (and I think they have document somewhere stating things they did that we haven't).

See also some comments at https://github.com/gperftools/gperftools/issues/1549 for some subjective comments on what they are and aren't doing compared to us.
