### ISSUE TITLE
mmap_hook_test: src/tests/mmap_hook_test.cc:87: static void MMapHookTest::HandleMappingEvent(const tcmalloc::MappingEvent&): Assertion `evt.stack_depth == 1' failed.

### ISSUE THREAD

**Issue by vt-alt** [gperftools/gperftools#1558]
`make check` consistently fail on aarch64 architecture:
```
[00:02:40] FAIL: mmap_hook_test
[00:02:40] ====================
[00:02:40] 
[00:02:40] first mmap!
[00:02:40] Running main() from vendor/googletest/googletest/src/gtest_main.cc
[00:02:40] [==========] Running 4 tests from 1 test suite.
[00:02:40] [----------] Global test environment set-up.
[00:02:40] [----------] 4 tests from MMapHookTest
[00:02:40] [ RUN      ] MMapHookTest.MMap
[00:02:40] mmap_hook_test: src/tests/mmap_hook_test.cc:87: static void MMapHookTest::HandleMappingEvent(const tcmalloc::MappingEvent&): Assertion `evt.stack_depth == 1' failed.
[00:02:40] FAIL mmap_hook_test (exit status: 134)
[00:02:40] 
[00:02:40] ============================================================================
[00:02:40] Testsuite summary for gperftools 2.15.90
[00:02:40] ============================================================================
[00:02:40] # TOTAL: 54
[00:02:40] # PASS:  53
[00:02:40] # SKIP:  0
[00:02:40] # XFAIL: 0
[00:02:40] # FAIL:  1
[00:02:40] # XPASS: 0
[00:02:40] # ERROR: 0
```
Temporary build log https://git.altlinux.org/tasks/357738/build/200/aarch64/log

**Comment by vt-alt** [comment]
Other build logs with failure on aarch64, both have `make chack  || make recheck` construct:
https://git.altlinux.org/tasks/357742/build/100/aarch64/log
https://git.altlinux.org/tasks/357743/build/100/aarch64/log
So this is 100% repeatable failure and not probabilistic.

**Comment by alk** [comment]
In this case I require explicit reproduction instructions outside of whatever builder machine you have. Maybe docker thingy.

Why? Because I already faced some crazy stuff e.g. here: https://github.com/gperftools/gperftools/issues/1424

**Comment by vt-alt** [comment]
Yes these builds was with LTO, I just retested without LTO now but test failure is still there. New temporary log: https://git.altlinux.org/tasks/357746/build/100/aarch64/log

I will try to make reproducer in Docker later. Not sure it's possible for aarch64 though.

**Comment by vt-alt** [comment]
To reproduce in docker (other tests are failing too but I'm only interested in `mmap_hook_test`):
```
host$ docker run --rm -it --platform linux/arm64 arm64v8/alt:sisyphus
/# apt-get update -y
/# apt-get install rpm-build gcc-c++ libunwind-devel git -y
/# git clone https://github.com/gperftools/gperftools
/# cd gperftools
gperftools# ./autogen.sh
gperftools# ./configure --disable-static
gperftools# make -j20
gperftools# make check TESTS=mmap_hook_test VERBOSE=1
...
FAIL: mmap_hook_test
====================

first mmap!
Running main() from vendor/googletest/googletest/src/gtest_main.cc
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from MMapHookTest
[ RUN      ] MMapHookTest.MMap
mmap_hook_test: src/tests/mmap_hook_test.cc:87: static void MMapHookTest::HandleMappingEvent(const tcmalloc::MappingEvent&): Assertion `evt.stack_depth == 1' failed.
qemu: uncaught target signal 6 (Aborted) - core dumped
FAIL mmap_hook_test (exit status: 134)

```
This will require aarch64 host or qemu-user-aarch64 with binfmt installed.

**Comment by alk** [comment]
Thanks. Does that happen only on this "alt" thingy? With everything going on today, I don't have excuse not to be paranoid about binaries built by your compatriots. So I'd need extra safety measures on my end to run this.

In any case it is good to know that no extra "rpm builder whatever" tricks are necessary to reproduce. I.e. simple configure ; make check. I'll see if I can reproduce this on my stock arm64 machine.

**Comment by alk** [comment]
yes, it is reproducible on stock debian sid aarch64. Thanks for reporting the issue. I'll get it fixed asap.

**Comment by alk** [comment]
Actually this is reasonably interesting case. Not sure how I managed not to catch it earlier myself.

So mmap hook calls backtracing facility which calls libunwind, which initializes some it's internal bits which calls mmap. And for such recursion we have special provision to explicitly provide empty backtrace (to avoid recursion into backtracing bits). Issue is test itself is not expecting this and dies.

Thinking about this some, I think when I'll soon amputate heap checker, I'll also shoot mmap/sbrk hooks (and heap "profiling" feature that includes mmap events), then this becomes irrelevant.

So for now I am thinking we'll just make test more lenient

**Comment by vt-alt** [comment]
Thanks!
