### ISSUE TITLE
How tcmalloc allocator for STL？

### ISSUE THREAD

**Issue by zhangdexin** [gperftools/gperftools#1559]
I only want to use tcmalloc for my so，not all app(the process). 
So I thought tcmalloc use for a allocator like std::allocator.
And use like this:
```
class tcmallocAllocator {
// ...
};

std::vector<int, tcmallocAllocator<int>> vec;
```

**Comment by alk** [comment]
You will have to implement this yourself (and feel free to contribute it back). In order for this to happen, you'll need to implement an option that disables "overriding" of systems allocator. I.e. only have libtcmalloc to expose tc_malloc/tc_new/etc and not malloc/operator new/delete etc. That should be trivial, I think.

In addition to that if you want it to be loadable and unloadable as a .so, you'll likely face more complications. Thread-local storage model will likely need to be changed from init-exec to default. And you may need to implement some way(s) to unmap whatever memory tcmalloc has got from kernel, prior to unloading. I am not 100% sure how much work that might be, but it might end up not too bad to implement as well.

Closing on our end as "won't fix", but feel free to send us a pull request if/when this is ready to be discussed as a specific patch/pull request.

**Comment by zhangdexin** [comment]
I found the a adapter of STL_allocator and use it in memory_region_map.h and heap-checker.cc. They both use it like this:
```
  struct MyAllocator {
    static void *Allocate(size_t n) {
      return LowLevelAlloc::AllocWithArena(n, arena_);
    }
    static void Free(const void *p, size_t /* n */) {
      LowLevelAlloc::Free(const_cast<void*>(p));
    }
  };
```
So can I use `LowLevelAlloc` api for my so. and whether  the`LowLevelAlloc`  api has the thread cache feature or what different with use libtcmalloc.so by LD_PRELOAD?

**Comment by zhangdexin** [comment]
I found mimalloc has this function:
https://github.com/microsoft/mimalloc/blob/db3d8485d2f45a6f179d784f602f9eff4f60795c/include/mimalloc.h#L482

**Comment by alk** [comment]
1) No LowLevelAllocator thingy (as noted in it's relevant comment) isn't good general use allocator.

2) Yes, I was referring to something along this lines, except you'd be calling down to tc_new/tc_delete

I didn't get this reference to LD_PRELOAD you were referring to. Seems unrelated to your request to do STL allocator for loadable .so library.

**Comment by zhangdexin** [comment]
About 2, I have a trick. :)  If only `.so` link the libtcmalloc.so, the operator new/delete override not take effect. So the 
```
 struct MyAllocator {
    static void *Allocate(size_t n) {
    }
    static void Free(const void *p, size_t /* n */) {
    }
  };
```
Allocate func call tc_malloc/tc_new, the Free func call tc_free/tc_delete.

Is that okay？hahah

**Comment by zhangdexin** [comment]
I am not sure that operator new/delete override not take effect.
But only .so link the libtcmalloc.so **and** use dlopen call the .so, the operator new/delete override will not take effect.
