### ISSUE TITLE
[Question] Accidental core dump encountered when linking against to gperftools

### ISSUE THREAD

**Issue by clay4444** [gperftools/gperftools#1561]
I wrote a customer library which will be invoked by java through JNI, then I want to do a profiling to it, the code is below:

Findgperftools:
```
include(ExternalProject)

set(GPERFTOOLS_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/gperftools-install")

set(GPERFTOOLS_CONFIGURE_ARGS
    "AR=${CMAKE_AR}"
    "RANLIB=${CMAKE_RANLIB}"
    "CC=${CMAKE_C_COMPILER}"
    "CXX=${CMAKE_CXX_COMPILER}"
    "--disable-shared"
    "--enable-hidden-visibility"
    "--prefix=${GPERFTOOLS_PREFIX}"
    "CFLAGS=-fPIC"
    "CXXFLAGS=-fPIC")

ExternalProject_Add(
        gperftools
        GIT_REPOSITORY https://github.com/gperftools/gperftools.git
        GIT_TAG gperftools-2.15.90
        UPDATE_COMMAND "./autogen.sh"
        CONFIGURE_COMMAND ./configure --prefix=${GPERFTOOLS_CONFIGURE_ARGS}
        BUILD_COMMAND ""
        BUILD_IN_SOURCE true
        INSTALL_COMMAND $(MAKE) install
        INSTALL_DIR ${GPERFTOOLS_PREFIX}
)

ExternalProject_Get_Property(gperftools INSTALL_DIR)

set(GPERFTOOLS_INCLUDE_DIR ${INSTALL_DIR}/include)
message(STATUS "gperftools include dir: ${GPERFTOOLS_INCLUDE_DIR}")

set(GPERFTOOLS_LIBRARY ${INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}profiler${CMAKE_STATIC_LIBRARY_SUFFIX})
message(STATUS "gperftools static library: ${GPERFTOOLS_LIBRARY}")
```

My project CMakeLists.txt:

```
if(ENABLE_GPERFTOOLS)
  find_package(gperftools)
  if(NOT gperftools_FOUND)
    message(STATUS "gperftools not found!")
  endif()
  add_dependencies(customer_lib gperftools)

  add_definitions(-DENABLE_GPERFTOOLS)
  target_include_directories(customer_lib PRIVATE ${GPERFTOOLS_INCLUDE_DIRS})
  target_link_libraries(customer_lib PRIVATE ${GPERFTOOLS_LIBRARYS})
endif()
 ```

My Source code:

```
#ifdef ENABLE_GPERFTOOLS
  ProfilerStart("")
#endif

other code

#ifdef ENABLE_GPERFTOOLS
  ProfilerStop()
#endif
```

It works fine in the dev enviroment, by in the production env, it will core dump like this:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb5a84ea94f, pid=36567, tid=0x00007fb56d3ff700
#
# Problematic frame:
# C  [libgcc_s.so.1+0xf94f]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

the customer_lib runs in a distributed application and hundreds of processes will invoke it and some of it will faile. I can't enable core dump in the production env, but in the dev enviroment, I can't reproduce it .... So I actually want to make sure that I have introduced gperftools into my project in the wrong way?

**Comment by clay4444** [comment]
> I am by no means cmake expert, so cannot comment on cmake details, but this looks at high level right.
> 
> What might be happening though is a crash during capturing stack trace. Here we have some details documented: https://github.com/gperftools/gperftools/wiki/gperftools'-stacktrace-capturing-methods-and-their-issues
> 
> That crash happens inside libgcc_s.so hints it might be "it".
> 
> JVMs runtime code generation likely adds to the challenge here. I don't think it integrates with C++ exceptions (and by extension backtrace capturing) facility. So libgcc likely finds no unwind info for the stack frames for the code produced by JVM. And perhaps it is not robust for that.

Many thanks for your reply! I read this wiki, but most of the above contents are unfamiliar to me.... Are there any compile options I can try to solve this problem?

**Comment by alk** [comment]
There is chance it could help, yes. Closing for now assuming it was matter of question and (mostly) known issues with backtracing. Please, feel free to reopen if something else comes up here.

**Comment by clay4444** [comment]
> There is chance it could help, yes. Closing for now assuming it was matter of question and (mostly) known issues with backtracing. Please, feel free to reopen if something else comes up here.

It worked, Thank you so mush! @alk
