### ISSUE TITLE
[QUESTION] Hooks for per-thread memory profiling

### ISSUE THREAD

**Issue by HazyMrf** [gperftools/gperftools#1568]
I did setup such hooks to my tcmalloc:

```cpp
thread_local static ThreadHeapState* thread_state = nullptr;

struct ThreadHeapState : private boost::noncopyable {
    ThreadHeapState() {
    }

    std::size_t active_bytes() const noexcept {
        return _allocated_bytes - _deallocated_bytes;
    }
    
    static void NewHook(const void* ptr, size_t size) {
        if (thread_state) {
            std::size_t total_alloc = MallocExtension::instance()->GetEstimatedAllocatedSize(size);
            thread_state->_allocated_bytes += total_alloc;
        }
    }

    static void DeleteHook(const void* ptr) {
        if (thread_state) {
            std::size_t total_alloc = MallocExtension::instance()->GetAllocatedSize(ptr);
            thread_state->_deallocated_bytes += total_alloc;
        }
    }

private:
    std::size_t _allocated_bytes = 0;
    std::size_t _deallocated_bytes = 0;
};
```

I understand that hooks can cause performance degradation and that to profile per-thread memory I need all allocations and deallocations not to be shared between threads (e.g. if thread T1 allocated memory, T1 must deallocate it, not some other thread T2). Imagine I have the guarantee above, will my hooks be working all right then or `MallocExtension::instance()->GetEstimatedAllocatedSize(size);` and `MallocExtension::instance()->GetAllocatedSize(ptr);` aren't exactly what I need to use?

**Comment by HazyMrf** [comment]
It appeared after a few days of execution my tcmalloc tracked smth about 300GB of allocated bytes on some thread, while in fact I don't have that much memory to be used (according to `free -h`)

**Comment by HazyMrf** [comment]
And another question: what if I have allocations and deallocations in different threads, how do you recommend my to track per-thread allocations and deallocations? I thought about overriding global `new` to store `thread_id` in the first bytes, but it is already overridden by tcmalloc so idk what to do in such case

**Comment by alk** [comment]
The above looks roughly right. It doesn't show how you get your thread_state pointer initialized. whatever issues you have might be there.

As for storing extra stuff, yes, it is hard currently. You'd need some sort of extra map. Feel free to "steal" address_map we have if it is some sort of experiment or if license terms work for you.

Some day, we'll get stackable hooks which will somewhat help performance but will also enable you to add whatever data you need. I.e. like debugallocator does (which would be done on top of that hooks). But how soon I cannot promise.

**Comment by HazyMrf** [comment]
Thank you for such a quick response @alk . I do create thread_state pointer manually at the beginning of my threads and remove it in the end. I came up with a solution where I can overload `operator new` using `tc_new` and the same with delete, but my code crashes after a few seconds of execution. Is there any way you can tell me what am I doing wrong here?

```cpp
    
static constexpr std::size_t kHeader = alignof(std::max_align_t);

void* operator new(size_t size) {
    void* ptr = tc_new(size + kHeader);
    // save some metadata into `Header` bytes
    return static_cast<char*>(ptr) + kHeader;
}

void operator delete(void* ptr) noexcept {
    // Use metadata ...
    
    tc_delete(static_cast<char*>(ptr) - kHeader);
}

```
