### ISSUE TITLE
Frame-pointer based stacktrace produce inaccurate result when sampling at the function prologue and epilogue

### ISSUE THREAD

**Issue by blahgeek** [gperftools/gperftools#1571]
## How to reproduce

`test.cc`:

```c++
__attribute__((noinline)) void Bar() {
  int x = 0;
  while (x < 10) x++;
}
__attribute__((noinline)) void Foo() {
  Bar();
  asm("nop"::);
}
int main() {
  for (int i = 0 ; i < 1000000000 ; i ++) Foo();
  return 0;
}
```

Compiled with `clang++ -O0 -g test.cc` in x86-64.

Run the profiler with `env TCMALLOC_STACKTRACE_METHOD=generic_fp LD_PRELOAD=$PWD/libprofiler.so CPUPROFILE=out.prof CPUPROFILE_FREQUENCY=1000 ./a.out`

## Actual result

![2024-10-29_15-09](https://github.com/user-attachments/assets/fa52e5d1-7b47-416a-9880-38c36f9a020d)

## Expected result

`main` does not call `Bar`, so the profiling result should not contain that line.

## Cause analysis

Result of `pprof --disasm=Bar a.out out.prof`:

```
-------------------- /home/yikai/Code/gperftools/build/test.cc
    50     50     2: __attribute__((noinline)) void Bar() {
    48     48      401110: push   %rbp
     2      2      401111: mov    %rsp,%rbp
     .      .     3: int x = 0;
     .      .      401114: movl   $0x0,-0x4(%rbp)
   593    593     4: while (x < 10) x++;
     7      7      40111b: cmpl   $0xa,-0x4(%rbp)
   116    116      40111f: jge    401133 <Bar+0x23>
    94     94      401125: mov    -0x4(%rbp),%eax
    56     56      401128: add    $0x1,%eax
    13     13      40112b: mov    %eax,-0x4(%rbp)
   307    307      40112e: jmp    40111b <Bar+0xb>
    18     18     5: }
    17     17      401133: pop    %rbp
     1      1      401134: ret    
     .      .      401135: cs nopw 0x0(%rax,%rax,1)
     .      .      40113f:    nop
```

When the sampling is taken at the prologue and epilogue of `Bar` function (at `push   %rbp`, `mov    %rsp,%rbp`, or `ret`), the frame pointer is not set yet or already unset, so the return address based on the frame pointer would be incorrectly `main` instead of `Foo`. In the above example, that's a total of 48+2+1 samples.

**Comment by alk** [comment]
This is a known downside of the method. It is documented as well. https://github.com/gperftools/gperftools/wiki/gperftools'-stacktrace-capturing-methods-and-their-issues#frame-pointers

Some heuristics might be possible. Old x86 (i.e. legacy 32 bit) frame-pointers method had one. But it made sense in gcc 3.x era when gcc was much less eager to schedule instructions around prologue.

Closing as "wont fix". But feel free to dig around and propose alternatives.
