### ISSUE TITLE
Unable to build gperftools with _GLIBCXX_DEBUG flag

### ISSUE THREAD

**Issue by marcinols** [gperftools/gperftools#1573]
When building gperftools with CXXFLAGS that includes the -D_GLIBCXX_DEBUG flag, the compilation fails with this error:

> libtool: compile:  /opt/misc/gcc-13.3.0/bin/g++ -std=gnu++17 -DHAVE_CONFIG_H -I. -I./src -I./src -DNO_TCMALLOC_SAMPLES -DNO_HEAP_CHECK -DNDEBUG -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fsized-deallocation -fno-omit-frame-pointer -momit-leaf-frame-pointer -D_GLIBCXX_DEBUG -D_GLIBCXX_USE_CXX11_ABI=1 -O3 -std=c++23 -MT src/libtcmalloc_minimal_la-tcmalloc.lo -MD -MP -MF src/.deps/libtcmalloc_minimal_la-tcmalloc.Tpo -c src/tcmalloc.cc  -fPIC -DPIC -o src/libtcmalloc_minimal_la-tcmalloc.o
> In file included from src/central_freelist.h:43,
>                  from src/tcmalloc.cc:116:
> src/span.h: In member function 'std::__debug::set<tcmalloc::SpanPtrWithLength, tcmalloc::SpanBestFitLess, tcmalloc::STLPageHeapAllocator<tcmalloc::SpanPtrWithLength, void> >::iterator tcmalloc::Span::ExtractSpanSetIterator()':
> src/span.h:132:28: error: 'std::_Rb_tree_const_iterator<tcmalloc::SpanPtrWithLength>' is not an accessible base of 'iterator_type' {aka 'std::__debug::set<tcmalloc::SpanPtrWithLength, tcmalloc::SpanBestFitLess, tcmalloc::STLPageHeapAllocator<tcmalloc::SpanPtrWithLength, void> >::iterator'}
>   132 |   this_iter->\~iterator_type();
>       |   ~~~~~~~~~~~~~~~~~~~~~~~~~^~
> make[1]: *** [Makefile:5126: src/libtcmalloc_minimal_la-tcmalloc.lo] Error 1
>

**Comment by alk** [comment]
Thanks. Fixed.
