### ISSUE TITLE
Ask again, How to distinguish a Semgent Fault in tcmalloc is caused by a double free or write after free？

### ISSUE THREAD

**Issue by sonicgemini** [gperftools/gperftools#1577]
As many coredump stack info in our using, most is caused by or , there are mainly two kinds of stack:

in freelist
```
#0 tcmalloc::SLL_Next (t=0x0) at src/linked_list.h:45
#1 tcmalloc::SLL_PopRange (end=, start=, N=32, head=0x5562dca501a0)
at src/linked_list.h:88
```

in span
```
#0 0x0000ffffa4148594 in tcmalloc::CentralFreeList::FetchFromOneSpans(int, void**, void**) () from /usr/lib64/libtcmalloc.so.4
#1 0x0000ffffa414889c in tcmalloc::CentralFreeList::FetchFromOneSpansSafe(int, void**, void**) () from /usr/lib64/libtcmalloc.so.4
```

These two kind can be triggerd by adding thread running like samples below:
```cpp
// double free
{
    long *p = new long;
    std::cout << std::hex << (void*)p << "\n";
    delete p;

    delete p;

    long *p1 = new long;
    std::cout << std::hex << (void*)p1 << "\n";
    *p1 = 0xFFFFFFFFFFFFFFFF;

    int *p2 = new int;
    std::cout << std::hex << (void*)p2 << "\n";
    *p2 = 66;

    std::cout << "before allocate againt\n";
    long *d = new long;
    std::cout << std::hex << (void*)d << "\n";
    *d = 1.0;
}
```

```cpp
// write after free
{
    long *p = new long;
    std::cout << std::hex << (void*)p << "\n";

    long *p1 = p;

    delete p;

    std::cout << std::hex << (void*)p1 << "\n";
    *p1 = 0xFFFFFFFFFFFFFFFF;

    std::cout << "before 1st allo\n";
    int *p2 = new int;
    std::cout << std::hex << (void*)p2 << "\n";
    *p2 = 66;

    std::cout << "before 2nd allo\n";
    long *d = new long;
    std::cout << std::hex << (void*)d << "\n";
    *d = 1.0;
}
```

and broken freelist example:

```shell
(gdb) p tcmalloc::ThreadCache::threadlocal_data_.fast_path_heap.list_
$1 = {{
list_ = 0x0,
length_ = 0,
lowater_ = 0,
max_length_ = 1,
length_overages_ = 0,
size_ = 0
}, {
list_ = 0xffffffffffffffff,
length_ = 0,
lowater_ = 0,
max_length_ = 2,
length_overages_ = 0,
size_ = 8
}, 
```

My question is, **based on coredump stacks, how to distinguish it is caused by `double free` or `write after free` ?**

Since it is related to how to demining our biz code to find out the bug code, it is a huge project and we want a more concise way.

BTW, 
1. for one aspect, we change to ptmalloc and it do not coredump again so we guess it probably write after free (since double free in ptmalloc will be detected by tcache); but for another aspect, developer in C++ are more likely to write <double free> code rather than <write after free>;
2. I used ason version and it did not coredump again either.

**Comment by sonicgemini** [comment]
currently we analyzed these types:
1. double erase of stl container;
2. double free/delete(we seldom use delete/free directly);
3. singleton inner modification race scenario;
4. mutex miss use scenario; 

although some issue had been found out, but DEFINITELY they are not the issue we meet. The problem recurs about 1 time - 3 months, and I am looking for useful advice and thx.

**Comment by alk** [comment]
There is no fully reliable way to distinguish different kinds of memory management bugs. Not for production mallocs.

For asan/msan and our debug allocator you are likely able to get you something. But those too are not 100% bullet-proof. And some race-type bugs might get "hidden" by those too.

So that is as much help in your debugging as I can give you.
