### ISSUE TITLE
memset() works too slow

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#22]
Originally reported on Google Code with ID 19

```
What steps will reproduce the problem?
1. Run many times calloc and malloc (1024000 times)
Calloc() works more slower than malloc().
I think that memset() that used inside calloc() works too slow. 

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
google-perftools-0.91 compiled from sources with
gcc (GCC) 4.1.1 20070105 (Red Hat 4.1.1-51)
Linux 2.6.20-1.2319.fc5 i686 i686 i386 GNU/Linux

Please provide any additional information below.


```

Reported by `egor.abramov` on 2007-06-18 15:50:36

**Comment by 372046933** [comment]
Ten times slower than ptmalloc's `calloc`

**Comment by alk** [comment]
Wasn't aware of this ticket. Here is what I can tell you. What likely happens is that benchmark is ~bogus. That is, in this specific benchmark case, ptmalloc likely has optimization that "memory" freshly gotten from kernel is (correctly) assumed to be zeroed. But that calloc hits this case is in fact rare. Other than micro-benchmarks. it will only occur early during program startup and then ~all subsequent callocs will be returning "reused" memory which must be memset. And then libc's calloc will call memset same as us with same slowdown. I think jemalloc has (or used to have) similar optimization. IMHO it is not useful/not worth complexity.

**Comment by 372046933** [comment]
Thanks for your reply.
In fact, I have benchmarked `jemalloc` as well with the same program. This benchmark has warm up simulation. That is requesting 1MB,  10MB, 100MB, 1GB, 10GB from the allocator and `free` them first. After that, benchmark records time used by `calloc`, `malloc`, `posix_memalign` requesting 1MB, 10MB, etc.  using `ptmalloc`, `jemalloc` and `tcmalloc`. Overall, `tcmalloc` has the best performance except `calloc`. `jemalloc` and `ptmalloc` have similar `calloc` performance and both are orders of magnitude faster than `tcmalloc`

**Comment by alk** [comment]
If you just allocate and free using calloc and allocator has this specific optimization, then this is not "real" too. Because virtual memory pages behind this large area are not populated. If you touch this memory (say force-read every page), you will get more real outcomes.

But also do note that tcmalloc (and most others allocators) don't really work hard optimizing large allocations. Because they are relatively rare. It does matter to squeeze every cycle for common-ish 32 byte allocations as some programs allocate those hundreds of millions of times per second, but those 1+ meg allocations they can take microseconds or even more and it'll be fine.

**Comment by 372046933** [comment]
Thanks a million. I touched every byte in the `calloc` 1MB address space. `tcmalloc` is just a little slower than `ptmalloc`. But they are on the same order of magnitude now.
