### ISSUE TITLE
Disabling profiler because SIGPROF handler is already in use.

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#396]
Originally reported on Google Code with ID 393

```
I got this warning when I use profile on my virtual machine of “2.6.18-274.12.1.el5xen
#1 SMP Tue Nov 29 14:18:21 EST 2011 x86_64 x86_64 x86_64 GNU/Linux”.
But I didn't install SIGPROF handler myself, I debug my main and sigation()the SIGPROF,
I Got this:
$2 = {__sigaction_handler = {sa_handler = 0x37ec4d62c0 <profil_counter>, sa_sigaction
= 0x37ec4d62c0 <profil_counter>}, sa_mask = {__val = {18446744073709289215, 46909632806913,
140737488344672, 
      4131212846, 140737488345072, 240186842448, 46912498377520, 0, 4294967295, 240199406976,
46912498372608, 9830400, 4294967295, 140737488345336, 9924248, 0}}, sa_flags = 335544320,

  sa_restorer = 0x37ec4302d0 <__restore_rt>}

I do not install profil_counter myself, and why I got the warning? any help?

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Reported by `thunder54007` on 2012-01-11 12:15:53

**Comment by ubique** [comment]
Apparently I hit into the same issue. Some hours of debugging give me the answer - the reason in -pg flag to compiler. google-perftools sees that SIGPERF handler is not set to DFL or NUL and decides to not to install own handlers. And SIGPERF handlers are installed before main from glibc library if you building with -pg .

**Comment by alk** [comment]
Hi Dmitry.

Thanks for update. But I'm not sure what your intention is. Do you want us to fix anything? In this case there doesn't seem to be anything to fix.

**Comment by ubique** [comment]
My intention was to put a notice for someone who hit this problem in order to save his time for debugging. For sure there is nothing to fix in gperftools. Thank you for your attention!

**Comment by romdhann** [comment]
Hi,
I'm facing the same issue.
" Disabling profiler because signal 27 handler is already in use.
nFrames decoded: 300 (176x144 @ 1255.98 fps)
PROFILE: interrupts/evictions/bytes = 0/0/64"

**Comment by alk** [comment]
So you're not supposed to build your program for gcc profiling (i.e. no -p or -pg or stuff like that). Perhaps we should change the message to point this out more clearly.

**Comment by tomjaguarpaw** [comment]
> Perhaps we should change the message to point this out more clearly.

Yes please.  That would have saved me searching for this page.

**Comment by alk** [comment]
Agree. Good opportunity for someone to contribute little improvement.
