### ISSUE TITLE
I can not  get the result of txt,help me

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#417]
Originally reported on Google Code with ID 414
```

When i use pprof --text bin/bs prof.txt,error  be print:

Use of uninitialized value in substitution (s///) at /home/map/gprofiler/bin/pprof
line 3103.
Use of uninitialized value in concatenation (.) or string at /home/map/gprofiler/bin/pprof
line 3105.
Use of uninitialized value in concatenation (.) or string at /home/map/gprofiler/bin/pprof
line 3105.
Use of uninitialized value in substitution (s///) at /home/map/gprofiler/bin/pprof
line 3103.
Use of uninitialized value in concatenation (.) or string at /home/map/gprofiler/bin/pprof
line 3105.
Use of uninitialized value in concatenation (.) or string at /home/map/gprofiler/bin/pprof
line 3105.
Use of uninitialized value in sprintf at /home/map/gprofiler/bin/pprof line 3270.
Gathering CPU profile from http:///pprof/profile?seconds=30 for 30 seconds to
  /home/map/pprof/bs.1331008371.
Be patient...
Failed to get profile: curl -s --max-time 90 'http:///pprof/profile?seconds=30' > '/home/map/pprof/.tmp.bs.1331008371.':
No such file or directory
```

Reported by `chenhao@baidu.com` on 2012-03-06 05:24:54

**Comment by alk** [comment]
Closing stale ticket.

Also perl pprof implementation is deprecated in favor of github.com/google/pprof

**Comment by guowenyao** [comment]
I am facing this same problem, is there a fix for it yet?

**Comment by alk** [comment]
Consider opening new issue with all details. But as noted above, if you're seeing message about curling something, then profile you're referring to doesn't exit.

**Comment by laplasz** [comment]
> ```
> 
> Try using absolute paths. Also make sure the heap profile you are trying to use actually
> exists under the path you have provided. Otherwise it tries to look for a remote profile.
> ```
> 
> Reported by `chappedm` on 2012-12-26 22:34:01

the profiler file location was incorrect - by correcting it this error was gone.
