### ISSUE TITLE
configure should better handle lack of libunwind

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#528]
Originally reported on Google Code with ID 525

```
It would be very helpful if the ./configure script fail early if libunwind was not found,
rather than fail later in compilation.

It would be even nicer if ./configure would accept an option such as --with-libunwind=<path>
in case libunwind is not available. 
```

Reported by `oleg.alexandrov` on 2013-04-30 00:02:38

**Comment by peng-wang-cn** [comment]
For "./configure CPPFLAGS=-I/home/me/lunw/include LDFLAGS=-L/home/me/lunw/lib", CPPFLAGS will not work, bug CFLAGS will, because when configure script tests header files, it uses a .c file.
