### ISSUE TITLE
profiler pause/resume support

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#597]
Originally reported on Google Code with ID 594

```
I've been using a hacked-up version of gperftools where I added ProfilerPause() and
ProfilerResume(): https://gist.github.com/tmm1/8031600

My goal was to profile one specific section of code over a number of iterations, and
produce one profile at the end. With the existing API, each invocation of Start/Stop
would overwrite the previous profile. With Pause/Resume, most of my program can run
unimpaired since the profiler is only resumed in the codepath I'm profiling. The API
can also be used to exclude known hotspots (i.e. garbage collection) by pausing the
profiler around them.

The implementation is half baked, but it does work. If this sounds like a good idea
I can clean up the patch for inclusion.
```

Reported by `themastermind1` on 2013-12-18 23:36:46

**Comment by alk** [comment]
Ping, @tmm1

Do you still want to merge this ?

**Comment by tmm1** [comment]
Sure I think it would be useful to others.

**Comment by alk** [comment]
Thanks. Once your patch is ready to merge, just let me know. Gist referenced above looks good.

**Comment by chtlp** [comment]
Requesting this feature as well!

**Comment by nelson2005** [comment]
This would be very helpful.

**Comment by chengu-pony** [comment]
+1
I also need it.

**Comment by alk** [comment]
Well, in practice I'd simply get one single profile and then filter in or out. See --focus and --ignore/--hide in github.com/google/pprof.

I wouldn't bet on dynamically pausing / unpausing due to very nontrivial overheads of those. You probably don't want this.

Looks like original author of this improvement has lost interest. So closing then.
