### ISSUE TITLE
Heap profiler consumes a lot of memory

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#674]
Originally reported on Google Code with ID 671

```
Hello,

I am testing the heap profiler to track memory leak in my application.

It works well but when I activate the heap profiler on my runtime, the memory usage
of the app grows strongly (1 MB/sec) until my machine ends in OOM (over 15 GB RAM used).

I use the profiler like this (link with tcmalloc at runtime):

LD_PRELOAD=libtcmalloc.so.4.2.4 HEAPPROFILE=<path_to_output_files> <MyBinary> 

Thank you!
Chris
```

Reported by `lebars.christophe` on 2015-01-30 09:53:15

**Comment by xsphen** [comment]
pmap -X mypid print:
![image](https://user-images.githubusercontent.com/11701706/56285141-19827e00-6149-11e9-875e-eaac9d35359a.png)
fanally, MallocExtension::instance()->ReleaseFreeMemory(), and malloc_stats() print:
![image](https://user-images.githubusercontent.com/11701706/56285185-374fe300-6149-11e9-94dd-2910a2867732.png)

also, I am testing the heap profiler to track memory leak in my application.
and linked libtcmalloc.so , then i run it with the command below:
```bash
HEAPCHECK=normal \
HEAP_CHECK_RUN_UNDER_GDB=1 \
HEAP_CHECK_IDENTIFY_LEAKS=1 \
HEAP_CHECK_MAX_POINTER_OFFSET=-1  \
PERFTOOLS_UNITTEST=0 \
TCMALLOC_RELEASE_RATE=10 \
HEAP_PROFILE_INUSE_INTERVAL=52428800 \
TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD=32768 \
HEAPPROFILE=heapprof/heapprof \
HEAP_CHECK_IGNORE_GLOBAL_LIVE=0 \
HEAP_CHECK_IGNORE_THREAD_LIVE=0 \
HEAP_CHECK_MAX_LEAKS=0 \
TCMALLOC_TRACE=1 \
./diagent
```

and use a singnal SIGUSER2 to release and display tcmalloc memory usage,  (my application is runing  backgroud):

```C
void sigusr2(int signum) {
    MallocExtension::instance()->ReleaseFreeMemory();
    malloc_stats();
}
main() {
     signal(SIGUSR2, sigusr2);
}
```
is the 700mb  high address memory （which address is 0x7fdfc3160000） consume by  Heap profiler?
