### ISSUE TITLE
Like a teeter totter,run slowly because call ThreadCache::FetchFromCentralCache and ThreadCache::ReleaseToCentralCache frequently

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#678]
Originally reported on Google Code with ID 675
```
What steps will reproduce the problem?
1.create many sub threads until unclaimed_cache_space_ < 0,all threads call free(malloc(1)),and
sleep long time expect the first subthread .
2.the first subthread alloc many times then free for max_length_ = 8192
  state1:
  ThreadCache::size_=8,max_size_=64K
  ThreadCache::freelist[1] :length_ = 1,max_length_ = 8192,lowater_ = 1
3.alloc(8) ->
  state2:
  ThreadCache::size_=0,max_size_=64K
  ThreadCache::freelist[1] :length_ = 0,max_length_ = 8192,lowater_ = 0
4:alloc(8) -->
  state3:
  ThreadCache::size_=64K-8,max_size_=64K
  ThreadCache::freelist[1] :length_ = 8191,max_length_ = 8192,lowater_ = 0
  call
  ThreadCache::FetchFromCentralCache
  CentralFreeList::RemoveRange(spin lock of CentralFreeList) 
5:free
  state4:
  ThreadCache::size_=64K,max_size_=64K
  ThreadCache::freelist[1] :length_ = 8192,max_length_ = 8192,lowater_ = 8192
  call 
  ThreadCache::Scavenge
  ThreadCache::IncreaseCacheLimit(spin lock of heap)  
6:free -->state1
  call
  ThreadCache::ListTooLong
  ThreadCache::ReleaseToCentralCache  
  ThreadCache::PopRange
  CentralFreeList::InsertRange(spin lock of CentralFreeList) 
and 3,4,5,6,3,4...

What is the expected output? What do you see instead?
Because the list of malloc and free call many functions that wastes times and use spin
lock,once enter this scene,then run slowly although these cpu kernels are busy.

What version of the product are you using? On what operating system?
ver:gperftools-2.4
os:RHEL 6.5

Please provide any additional information below.
In the sence, policy of lowater and policy of unclaimed_cache_space are invalid.

void* ThreadCache::FetchFromCentralCache(size_t cl, size_t byte_size) {
  FreeList* list = &list_[cl];
  ASSERT(list->empty());
  const int batch_size = Static::sizemap()->num_objects_to_move(cl);

  const int num_to_move = min<int>(list->max_length(), batch_size);
  void *start, *end;
  int fetch_count = Static::central_cache()[cl].RemoveRange(
      &start, &end, num_to_move);

  ASSERT((start == NULL) == (fetch_count == 0));
  if (--fetch_count >= 0) {
    size_ += byte_size * fetch_count;
    list->PushRange(fetch_count, SLL_Next(start), end);
+   list->clear_lowwatermark();
  }

test code

#include "config_for_unittests.h"
#include <stdio.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>    // for sleep()
#endif
#include "base/logging.h"
#include <gperftools/malloc_extension.h>
#include "tests/testutil.h"   // for RunThread()
#include <sys/time.h>

static void AllocOnce(void);

static void AllocStuffId(int nId);

static void TestVgop(int nId);

static void FastOrSlow(int nId);

static void CycleAllocFree(int nCount, int nSize);

int main(int argc, char** argv) 
{
    AllocOnce();

    FastOrSlow(0);
    int nThCount = 600;
    RunManyThreadsWithId(AllocStuffId, nThCount, 1 << 20);
    return 0;
}

static void AllocStuffId(int nId)
{
    AllocOnce();

    if (0 != nId)
    {
        sleep(5 * 60);
    }
    else
    {
        sleep(2 * 60);
        TestVgop(nId + 1);
    }
}

static void TestVgop(int nId)
{
    int nCount = (1 + 8192) / 2 * 8192;
    int nSize = 6;
    void** objects = new void*[nCount];
    int i = 0;
    for (i = 0; i < nCount; i++) {
        objects[i] = malloc(nSize);
    }

    for (i = 0; i < nCount; i++) {
        free(objects[i]);
    }
    int nPackCount = 8039;
    for (i = 0; i < nPackCount; i++) {
        objects[i] = malloc(nSize);
    }
    FastOrSlow(nId);
    for (i = 0; i < nPackCount; i++) {
        free(objects[i]);
    }

    delete[] objects;
}

void FastOrSlow(int nId)
{
    timeval starttime, endtime;
    gettimeofday(&starttime, 0);
    int nCount = 30 * 64 * 1024;
    int nSize = 6;
    CycleAllocFree(nCount, nSize);

    gettimeofday(&endtime, 0);
    double timeuse = 1000000 * (endtime.tv_sec - starttime.tv_sec) + endtime.tv_usec
- starttime.tv_usec;
    timeuse /= 1000;
    printf("task id %d\ttime:%d ms\n",nId, int(timeuse));
}

void CycleAllocFree(int nCount, int nSize)
{
    for (int i = 0; i < nCount; i++)
    {
        void *p1 = malloc(nSize);
        void *p2 = malloc(nSize);
        free(p2);
        free(p1);
    }
}

void AllocOnce(void)
{
    free(malloc(1));
}

```

Reported by `fanzhenyong@163.com` on 2015-02-26 06:28:56

**Comment by alk** [comment]
Thanks a lot Tim. You're right.

I'll admit that I haven't spent enough time thinking about list size management heuristics and that your case helped me understand it better.

So it can be said that your specific test case issue is caused by increase of num_objects_to_move in 2.1 release. Specifically that in your case in FetchFromCentralCache num_objects_to_move and max_length are same and there is cap on max_length in the code to exact same 8k objects.

So for 8 byte objects we get situation that max_length grows to 8192 which is same as num_objects_to_move. So FetchFromCentralCache grows list size from 0 to 8192. Which leaves no space in list_headroom variable so subsequent free (or more specifically second free) overflows list again which causes call to ListToLong which reduces list size back to 0 (well 1).

So at very least we should avoid num_objects_to_move to be significantly less than 8k. Or we can grow that bound on max_length. CC-ing @zatrazz who was author of that performance commit that bumping num_objects_to_move.

But I think there is seemingly larger and more general issue any time when max_length is not at significantly larger than num_objects_to_move. For those cases some careful hysteresis looks like right idea. I'll need to think about this more.

Thanks a lot.

**Comment by timliim** [comment]
Alk,

You are very welcome!


> But I think there is seemingly larger and more general issue any
> time when max_length is not at significantly larger than
> num_objects_to_move.  For those cases some careful hysteresis looks
> like right idea.  I'll need to think about this more.

Amen!  Yes that's the idea.  And it's your decision as how to best fix
it, since you know how the stuff works better than I do,

Cheers,
Tim Taiwanese Liim

**Comment by timliim** [comment]
Alk,
By any chance do you have an ETA when a fix might be available?  Or as
a workaround before the official fix is available, do you think using
a smaller num_objects_to_move will help without much adverse effect?
Eg. in common.cc:SizeMap::NumMoveSize(size_t size) if I change this line
  // Use approx 64k transfers between thread and central caches.
  int num = static_cast<int>(64.0 * 1024.0 / size);
to
  int num = static_cast<int>(**48.0** * 1024.0 / size);

Do you think it do any bad thing as a workaround?  I think it will
alleviate the situation a lot, but I also want to make sure it does
not do bad things.

Thanks,
Tim Taiwanese Liim

**Comment by alk** [comment]
I cannot promise you any specific time of fix.

But I believe that most of problem is due to large num_objects_to_move. Which was bumped in 2.1 release and remains point of concern.

Your problem will likely go away if you lower this value by setting environment variable TCMALLOC_TRANSFER_NUM_OBJ. I.e.: https://github.com/gperftools/gperftools/blob/master/src/common.cc#L55

**Comment by timliim** [comment]
Alk,
Wonderful!  Will try out the env var TCMALLOC_TRANSFER_NUM_OBJ.
Tim Taiwanese Liim

**Comment by alk** [comment]
I've lowered default transfer batch to 512. It should fix this particular issue.

**Comment by timliim** [comment]
Alk,

Thanks a lot!

Tim



On 11/21/2015 10:25 PM, Aliaksey Kandratsenka (aka Aliaksei 
Kandratsenka) wrote:
>
> I've lowered default transfer batch to 512. It should fix this 
> particular issue.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gperftools/gperftools/issues/678#issuecomment-158704344>.
>


-- 
Tim "Taiwanese" Liim <tim.liim@alcatel-lucent.com>
HOH M-230F / 732.888.7152
=================================================================
I'm Taiwanese.  To be politically correct, people don't ask me
where I'm from; they just guess.  And the guess is almost always
wrong.  To take the guesswork out, I'll just tell you that
     I am Taiwanese, from Taiwan, a free & prosperous democracy,
     and the ONLY country on planet earth that is DENIED
     UN (United Nations) membership.
=================================================================
