### ISSUE TITLE
On Windows 8.1, system-alloc_unittest fails an assert

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#684]
Originally reported on Google Code with ID 681

```
What steps will reproduce the problem?
1. Using Visual studio 2013 community edition, compile x86 debug version
2. select system-alloc_unittest as startup project
3. run (F5) 

What is the expected output? What do you see instead?
Expected to see a PASS
instead the following assert
Assertion failed: success == TRUE, file c:\des\gperftools-2.4\src\windows\system-alloc.cc,
line 166

What version of the product are you using? On what operating system?
2.4, Windows 8.1

Please provide any additional information below.

This seems to be an attempt to call VirtualFree (inside TCMalloc_SystemRelease) again
with the same memory reference

(I think it may be due to how the freelist is handled)

```

Reported by `desb42` on 2015-04-12 10:15:11

**Comment by brunochampoux** [comment]
this is still happening in the master branch as of 9e5b1628737c67b4587f937164572774592978c4

the VirtualFree failure is compounded by the fast that `assert` can call `malloc` on Windows, causing a deadlock/hang when running `system-alloc_unittest`

**Comment by alk** [comment]
Yes, this is known limitation of current sysallocator api and what test is doing. Test is assuming it can release memory obtained from any sys allocator. Which is not the case in general and more so for windows for that specific test. But it is actually harmless test failure.
