### ISSUE TITLE
x86_64 trouble with libunwind

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#69]
Originally reported on Google Code with ID 66

```

Having read the INSTALL and README file, x86_64 seems to be difficult to
get working in a stable manner.

I tried all the libunwind, the -Wl,-fno-omit-frame-pointer,-leh_gcc, etc.
flags but it reliably crashes whenever I want to use the CPU or heap profiler.

Given the increasing popularity of x86_64 users (especially those who are
actually developers and require performance tuning of their applications),
can you please consider putting more effort into getting the x86_64
usability to a higher level?

Thanks a lot!



What version of the product are you using? On what operating system?

Ubuntu 08.04 x86_64.


```

Reported by `nowozin` on 2008-06-30 10:06:03

**Comment by lag1500** [comment]
> ```
> I've tried to use, instead, --enable-frame-pointer, but it's hard for me to get a
> libc and libc++ version built with these options so then my CPU profiles contain a
> lot of disconnected boxes and are pretty impossible to use.
> 
> ```
How do I find out whether my libc.so and libstdc++.so was built with --enable-frame-pointer?
Maybe it's a simple question, but I cann't find how...
objdump seems no helpful.
Thanks a lot!

**Comment by alk** [comment]
Closing as too much noise has accumulated here. Current status. Libunwind when build with right options (which is I think are right be default) has one issue. Which is dl_iterate_phdr thingy. It may only happen in cpu profiler (not stack traces captured by tcmalloc bits).

Great news is we now support "libgcc" backtrace capturing method with on newest linux systems is completely perfect.

With caveat that compilers do occasionally screw us up. Fan fact, about 5-ish years ago Google had to disable libunwind usage for all internal systems due to some clang failure to generate correct unwind info. Issue was fixed, verified and AFAIR google now runs with libunwind (but they have special patch to glibc to avoid trouble with dl_iterate_phdr stuff).

For the latest question here about how to check if libraries are built with frame pointers. Well, likely they aren't. No distro I know does that. But do actually verify, I am not aware of simple ways. I'd disassemble and then it is "obvious". But it require some experience with asm. so not easy.
