### ISSUE TITLE
Failed to build with lib musl

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#693]
Originally reported on Google Code with ID 690

```
What steps will reproduce the problem?
1. unpack source onto x86_64, musl based system
2. apply patch to define __off64_t
3. try to build

What is the expected output? What do you see instead?
Build fails instead of normal completition:
src/malloc_hook_mmap_linux.h: In function 'void* mmap(void*, size_t, int, int, int,
off_t)':
src/malloc_hook_mmap_linux.h:169:18: error: redefinition of 'void* mmap(void*, size_t,
int, int, int, off_t)'
 extern "C" void* mmap(void *start, size_t length, int prot, int flags,
                  ^
In file included from src/malloc_hook.cc:41:0:
src/malloc_hook_mmap_linux.h:155:18: error: 'void* mmap(void*, size_t, int, int, int,
__off64_t)' previously defined here
 extern "C" void* mmap64(void *start, size_t length, int prot, int flags,
                  ^
Makefile:4515: recipe for target 'src/libtcmalloc_minimal_internal_la-malloc_hook.lo'
failed
make: *** [src/libtcmalloc_minimal_internal_la-malloc_hook.lo] Error 1


What version of the product are you using? On what operating system?
Alpine linux 3.0
gcc 4.8.2
musl 1.1.4

Please provide any additional information below.
1. _off64_t is not defined, so I patched base/linux_syscall_support.h to define it
into off64_t
2. musl sys/mman.h is quite different from glibc, so I guess the problem of redifinition
comes from that fact.

I would appreciate for any advice how it could be fixed. Full configure & make logs
attached
```

Reported by `filipp.andronov` on 2015-05-15 17:59:04

<hr>
- _Attachment: [build.log](https://storage.googleapis.com/google-code-attachments/gperftools/issue-690/comment-0/build.log)_
- _Attachment: [10-define-off64-t.patch](https://storage.googleapis.com/google-code-attachments/gperftools/issue-690/comment-0/10-define-off64-t.patch)_

**Comment by ncopa** [comment]
gperftools (git master) with this patch:
````diff
diff --git a/src/base/linux_syscall_support.h b/src/base/linux_syscall_support.h
index 90add93..7f6f4a2 100644
--- a/src/base/linux_syscall_support.h
+++ b/src/base/linux_syscall_support.h
@@ -2166,9 +2166,9 @@ struct kernel_stat {
                          int,                     t, int,       p)
   #endif
   #if defined(__x86_64__)
-    /* Need to make sure __off64_t isn't truncated to 32-bits under x32.  */
+    /* Need to make sure off64_t isn't truncated to 32-bits under x32.  */
     LSS_INLINE void* LSS_NAME(mmap)(void *s, size_t l, int p, int f, int d,
-                                    __off64_t o) {
+                                    off64_t o) {
       LSS_BODY(6, void*, mmap, LSS_SYSCALL_ARG(s), LSS_SYSCALL_ARG(l),
                                LSS_SYSCALL_ARG(p), LSS_SYSCALL_ARG(f),
                                LSS_SYSCALL_ARG(d), (uint64_t)(o));
diff --git a/src/malloc_hook_mmap_linux.h b/src/malloc_hook_mmap_linux.h
index 0f531db..ec0c587 100755
--- a/src/malloc_hook_mmap_linux.h
+++ b/src/malloc_hook_mmap_linux.h
@@ -46,6 +46,10 @@
 #include <errno.h>
 #include "base/linux_syscall_support.h"
 
+#ifndef off64_t
+#define off64_t __off64_t
+#endif
+
 // The x86-32 case and the x86-64 case differ:
 // 32b has a mmap2() syscall, 64b does not.
 // 64b and 32b have different calling conventions for mmap().
@@ -56,7 +60,7 @@
 
 static inline void* do_mmap64(void *start, size_t length,
                               int prot, int flags,
-                              int fd, __off64_t offset) __THROW {
+                              int fd, off64_t offset) __THROW {
   return sys_mmap(start, length, prot, flags, fd, offset);
 }
 
@@ -67,7 +71,7 @@ static inline void* do_mmap64(void *start, size_t length,
 
 static inline void* do_mmap64(void *start, size_t length,
                               int prot, int flags,
-                              int fd, __off64_t offset) __THROW {
+                              int fd, off64_t offset) __THROW {
   void *result;
 
   // Try mmap2() unless it's not supported
@@ -137,9 +141,11 @@ static inline void* do_mmap64(void *start, size_t length,
 # undef mmap
 
 extern "C" {
+#ifndef mmap64
   void* mmap64(void *start, size_t length, int prot, int flags,
-               int fd, __off64_t offset  ) __THROW
+               int fd, off64_t offset  ) __THROW
     ATTRIBUTE_SECTION(malloc_hook);
+#endif
   void* mmap(void *start, size_t length,int prot, int flags,
              int fd, off_t offset) __THROW
     ATTRIBUTE_SECTION(malloc_hook);
@@ -152,8 +158,9 @@ extern "C" {
     ATTRIBUTE_SECTION(malloc_hook);
 }
 
+#ifndef mmap64
 extern "C" void* mmap64(void *start, size_t length, int prot, int flags,
-                        int fd, __off64_t offset) __THROW {
+                        int fd, off64_t offset) __THROW {
   MallocHook::InvokePreMmapHook(start, length, prot, flags, fd, offset);
   void *result;
   if (!MallocHook::InvokeMmapReplacement(
@@ -163,6 +170,7 @@ extern "C" void* mmap64(void *start, size_t length, int prot, int flags,
   MallocHook::InvokeMmapHook(result, start, length, prot, flags, fd, offset);
   return result;
 }
+#endif
 
 # if !defined(__USE_FILE_OFFSET64) || !defined(__REDIRECT_NTH)
 
@@ -202,7 +210,7 @@ extern "C" void* mremap(void* old_addr, size_t old_size, size_t new_size,
   return result;
 }
 
-#ifndef __UCLIBC__
+#if defined(__GLIBC__) && ! defined(__UCLIBC__)
 // libc's version:
 extern "C" void* __sbrk(ptrdiff_t increment);
 
````

The mmap64 ifdef is a hack due to musl libc does:
````C
#define mmap64 mmap
````
I think we should check in configure script if mmap64 is a real symbol or not.

Also, sbrk is [disabled](http://git.musl-libc.org/cgit/musl/commit/src/linux/sbrk.c?id=7a995fe706e519a4f55399776ef0df9596101f93) on musl libc.

**Comment by alk** [comment]
Hi, ncopa. I'm not sure I understand intention of your comment. Do you want me to consider merging your patch? Something else ? Can you please elaborate a bit more ?

**Comment by ncopa** [comment]
Sorry for being unclear.

I doubt that the patch can be applied as is. The intention is:
- show that it is possible to make gperftools build with musl
- show what kind of issues makes musl break
- discuss how those issues can/should be fixed.

As you see, it fails on `__off64_t` which is not defined in any standard (normally, things prefixed with `__` are only intended for internal use). There is `off_t` specified in posix, but I am not sure it can be used here. I think the `#ifndef off64_t` may be acceptable.

Second problem is that it tries to intercept mmap64. On musl libc there are no such symbol exported. Instead there is a `#define mmap64 mmap`, meaning that on musl libc, `mmap64` is the same thing as `mmap`.

We can not do `#ifdef __MUSL__` or similar because that is [not supported by design](http://wiki.musl-libc.org/wiki/FAQ#Q:_why_is_there_no_MUSL_macro_.3F), so we need to add some kind of configure test to detect if there are a mmap64 that is a function and not a macro.

We probably also need to have a configure test for __sbrk.

I can probably work on it but it would be nice to have some input or opinions on how you would like to solve those things.

Or do you prefer that I make a suggestion as a pull request and we take it from there?

**Comment by alk** [comment]
Feel free to work on this

* __off64_t thing is probably due to 32-bit or 64-bit off_t support in 32-bit glibc (and other older OS's libc). I think we can probably replace it with something concrete like int64_t

* regarding mmap64 it looks like bug worth reporting to musl authors. But working around it seems fine.

* regarding __sbrk, feel free to find some way to work around that. Ideally without having to disable sbrk support. The intention of __sbrk usage is, apparently, to be able to hook sbrk so that we can invoke sbrk hooks. And glibc provides this convenience, albeit in unportable way.

I'll be happy to review your patch as soon as it is ready.

**Comment by zatrazz** [comment]
__off64_t is exactly due the 32-bit/64-bit support in 32-bit glibc: for such ABI you have pread/pread64, for instance, where they differ in argument passing and might as well in kernel abi for syscall. For most 64-bit abi (exception the ILP32 ones, like x32 and mips64 n32) pread is an alias for pread64.

Same applies for mmap64, where it is defined iff _LARGEFILE64_SOURCE is set. Basically, for 64-bit abi it is an alias to mmap, however for some 32-bit abi it is a different implementation.

The diference with musl is it does not support the old 32-bit abi with sizeof(off_t) == 4 and then get rid of most of the incompatibility issue. And that is why it can simple redefine __off64_t to off_t.

The only problem is what happens if you build gperftools against musl and try to use with glibc linked binaries? Will this correctly intercepting old binaries that call the 32-bit variant off_t? 

I am fine defining that this is not explicit support, although it would be good to report this at runtime for user somehow.

**Comment by alk** [comment]
__off64 should be ok to simply replace it with int64_t I think.

Regarding bulding against musl and running with glibc. Is this (or vice versa) even possible ? I though it's not but will be happy to be told I'm wrong.

**Comment by ncopa** [comment]
why not replace `__off64_t` with `off64_t`, which seems to work on both glibc and musl?

musl libc does have limited ABI compatibility with glibc. For example, the closed-source adobe flash plugin, which is linked against glibc actually works in firefox built with musl.

But I don't think it makes any sense to do this when sources is available, so in the gperftools I don't think we need to worry about it at all.

**Comment by alk** [comment]
Status update:

ncopa's commit makes it build, _but_ dynamically linked musl does not support interposing malloc/free. I.e. musl's strdup will call musl's malloc and not interposed version. This makes it impossible to support musl in _any_ malloc implementation not just tcmalloc.

**Comment by superlbr** [comment]
Seems not solved yet,I just making a docker image and failed.

**Comment by superlbr** [comment]
when make
> In file included from src/malloc_hook_mmap_linux.h:47:0,
                 from src/malloc_hook.cc:678:
src/base/linux_syscall_support.h:2437:37: error: '__off64_t' has not been declared
                                     __off64_t o) {
                                     ^
In file included from src/malloc_hook.cc:678:0:
src/malloc_hook_mmap_linux.h:59:39: error: '__off64_t' has not been declared
                               int fd, __off64_t offset) __THROW {
                                       ^
src/malloc_hook_mmap_linux.h:155:24: error: '__off64_t' has not been declared
                int fd, __off64_t offset  ) __THROW
                        ^
In file included from ./src/base/commandlineflags.h:56:0,
                 from src/base/logging.h:49,
                 from src/malloc_hook.cc:50:
./src/base/basictypes.h:260:66: error: conflicting declaration of C function 'void* mmap(void*, size_t, int, int, int, int)'
 # define ATTRIBUTE_SECTION(name) __attribute__ ((section (#name)))
                                                                  ^
src/malloc_hook_mmap_linux.h:156:5: note: in expansion of macro 'ATTRIBUTE_SECTION'
     ATTRIBUTE_SECTION(malloc_hook);
     ^
In file included from src/malloc_hook.cc:41:0:
/usr/include/sys/mman.h:21:7: note: previous declaration 'void* mmap(void*, size_t, int, int, int, off_t)'
 void *mmap (void *, size_t, int, int, int, off_t);
       ^
In file included from ./src/base/commandlineflags.h:56:0,
                 from src/base/logging.h:49,
                 from src/malloc_hook.cc:50:
./src/base/basictypes.h:260:66: error: conflicting declaration of C function 'void* mmap(void*, size_t, int, int, int, off_t)'
 # define ATTRIBUTE_SECTION(name) __attribute__ ((section (#name)))
                                                                  ^
src/malloc_hook_mmap_linux.h:159:5: note: in expansion of macro 'ATTRIBUTE_SECTION'
     ATTRIBUTE_SECTION(malloc_hook);
     ^
In file included from src/malloc_hook.cc:41:0:
src/malloc_hook_mmap_linux.h:154:9: note: previous declaration 'void* mmap(void*, size_t, int, int, int, int)'
   void* mmap64(void *start, size_t length, int prot, int flags,
         ^
In file included from src/malloc_hook.cc:678:0:
src/malloc_hook_mmap_linux.h:170:33: error: '__off64_t' has not been declared
                         int fd, __off64_t offset) __THROW {
                                 ^
src/malloc_hook_mmap_linux.h: In function 'void* mmap(void*, size_t, int, int, int, off_t)':
src/malloc_hook_mmap_linux.h:184:43: error: conflicting declaration of C function 'void* mmap(void*, size_t, int, int, int, off_t)'
                       int fd, off_t offset) __THROW {
                                           ^
In file included from src/malloc_hook.cc:41:0:
src/malloc_hook_mmap_linux.h:169:18: note: previous declaration 'void* mmap(void*, size_t, int, int, int, int)'
 extern "C" void* mmap64(void *start, size_t length, int prot, int flags,
                  ^
Makefile:4731: recipe for target 'src/libtcmalloc_minimal_internal_la-malloc_hook.lo' failed
make: *** [src/libtcmalloc_minimal_internal_la-malloc_hook.lo] Error 1

**Comment by alk** [comment]
As noted above we do have patch that makes it compile. But that isn't making musl work 100% as noted above.

**Comment by ncopa** [comment]
Yes, just because it compiles does not mean that it works.

To make it actually work I think we have to intercept all functions that returns anything that should be `free`ed. Eg. we need to also intercept `strdup` and others. I think valgrind does that and valgrind works (sort of).

**Comment by alk** [comment]
I don't like the idea of replacing and re-implementing all libc functions that interact with malloc. It is waste of time for no benefit at all.

Also if musl authors don't care about supporting interposing malloc why should we care ?

**Comment by ncopa** [comment]
Its not that they don't care. Its just not that easy or maybe not even possible to do it right and musl will not hack around it. Even the glibc malloc interposition is [broken](http://tracker.ceph.com/issues/13522#note-23).

For musl libc devs it is all about correctness.

**Comment by alk** [comment]
Thanks for link above. I've replied to their ticket. And it actually has nothing to do with glibc malloc interposition which is working just fine.

Regarding whether musl is all about correctness or not, I'm not going to argue with that. What is a matter of fact however, is that musl doesn't support malloc interposition in shared library version (I think that for static library it might just work). And without them supporting it, there is little reason for us to try to support them.

**Comment by Soullivaneuh** [comment]
@alk It would be very great to have your lib working with Alpine, we need this to get Mongo working on it too. :+1: 

Thanks.

**Comment by acmorrow** [comment]
@Soullivaneuh - Just build mongodb without tcmalloc via the ```--allocator=system``` build parameter. That isn't a supported configuration, but, then again, neither is the one you are building. You will lose the performance advantages of tcmalloc. But if there is no way to interpose on musl's allocator (which seems like a serious bug), you never could have taken advantage anyway.

**Comment by alk** [comment]
Right. There is not much that we can do. Statically linked musl might work, but so far I have seen no reports of that working.

**Comment by eitijupaenoithoowohd** [comment]
More than two years. Have no working fixes. Blgat! :(

**Comment by alk** [comment]
You can help by contributing working commit. Doesn't look like musl will ever support replacing their malloc for dynamically linked musl. But statically linked musl might work. Or not, I need someone who cares to take a look and let us know.

Musl authors apparent hatred to everything GNU makes me unlikely care enough to look myself.

**Comment by eitijupaenoithoowohd** [comment]
@alk, thank you for answer. I'l try to do something to the best of my ability because musl is the better replacement of libc now.

**Comment by TBK** [comment]
Latest discussion regarding the subject on Musl's end - http://www.openwall.com/lists/musl/2018/04/10/2

**Comment by alk** [comment]
Thanks. So we close as won't fix then?

**Comment by alk** [comment]
Thinking about this little more, I think we can still offer faster operator new/delete for musl case. Musl will still offer it's own malloc/free, because we cannot safely replace those.

Again, don't expect me to contribute this work. Their attitude makes me avoid helping their cause. So I'll accept patches if someone offers something.

**Comment by superlbr** [comment]
three years, just a number 42...

**Comment by eitijupaenoithoowohd** [comment]
> Rich Felker from musl mailling list:
> Today I pushed changes which should make malloc
> replacement/interposition work reliably as long as you only use
> AS-safe functions. If you try this, please let us know how it turns
> out and if you run into any unexpected problems.

I hope the bugfixing process of musl is at the final state.

**Comment by alk** [comment]
Aha. That is good news. Async-signal-safe is a bit too strong and isn't quite 100% enough. But we'll be good in practice I think.

Other mallocs use pthread_mutex-es, which are not AS-safe (but probably good enough in practice). We don't. We use custom "spinlocks" (and futex-based sleeping). But we do use a bit of pthread facilities for thread local storage. Those are not AS-safe technically, but we're explicitly prepared to deal with recursive malloc calls from inside those. Well at least for creating pthread local storage key. So we'll likely be fine too.

Again, don't expect me to dedicate time for making it happen. But I'll be happy to review and merge patches (as long as said patches are good).

**Comment by alk** [comment]
gperftools has been working on musl for some time now. (heap checker unittest is currently failing and musl seem to have trouble with unwind info around signal trampolines but that is something to be investigated separately)
