### ISSUE TITLE
Configure test for -Wno-unused-result always returns "yes"

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#703]
Originally reported on Google Code with ID 700
```
What steps will reproduce the problem?
1. Find a gcc version that does not accept -Wno-unused-result
2. Run configure

What is the expected output? What do you see instead?

I expect that the output of configure will include
checking if the compiler supports -Wno-unused-result... no
but instead I see
checking if the compiler supports -Wno-unused-result... yes

What version of the product are you using? On what operating system?

I am on RHEL 6, using gcc 4.4.7 (Red Hat 4.4.7-11).  I am configuring gperftools-2.4
newly unpacked from the release tarball.

Please provide any additional information below.

I suspect that the "-Wno-error" flag is responsible.  This keeps the test from failing
due to the divide by zero error, but it also keeps the test from failing due to an
actual unexpected flag.  The return code of gcc is still 0.
```

Reported by `jsw.osu` on 2015-07-20 17:10:02

**Comment by jsw-fnal** [comment]
The build fails because gcc was given the -Wno-unused-results flag, which it does not understand.  If the check worked correctly, then the build would succeed.  I manually disabled the -Wno-unused-results flag, and the build succeeded.

**Comment by alk** [comment]
I think the intention of the check is "see if -Wno-unused-result breaks compilation". Basically at configure time we see if it makes compiler exit with error or not (with or without warnings).

So I'm really curious how build fails in your case. Are you using -Werror ?

**Comment by alk** [comment]
It looks like gcc does warning for unknown -Wno-XXX flags and error on -WXXX flags. I'm going to fix it by using positive flag in test.

But I'm really curious how this breaks your builds.

**Comment by alk** [comment]
Thanks for raising this again.
