### ISSUE TITLE
Hanging in ARCH_FORK with CPUPROFILE

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#704]
Originally reported on Google Code with ID 701
```
There are two ways I have been able to reproduce the problem.
The first method occurs at random, and in spans of time (running in release mode).
The second seems to occur every time I run internal tools linked against libprofiler
with gdb/cgdb.
I have been unable to generate a simplified reproducer that can be shared.

What steps will reproduce the problem?
1. compile code in debug mode, linked against libprofiler.so
2. run executable in cgdb
3. wait
4. interrupt execution and observe that:
    a. all but one thread are waiting in poll, or epoll, or pthread_cond_wait, or etc.
    b. one thread is stuck in a fork system call, on the ARCH_FORK line
    c. CPU is at 100%

What is the expected output? What do you see instead?
The program is expected to finish normally.
The program hangs 'forever' in a call to fork(). On the ARCH_FORK() macro with $rax
= -ERESTARTNOINTR

What version of the product are you using? On what operating system?
2.2.1 / 2.4
RHEL6

Please provide any additional information below.
I have a quick (non-complete) fix (attached) for this using pthread_atfork and pthread_sigmask
to block SIGPROF before a fork and then re-enable it afterwards. From my testing, this
always prevents the hanging issue.

I have communicated my fix with Developer Services at my job and they have indicated
that it would be preferred if this solution could be patched into the gperftools source
code.

While this is probably sufficient for the usecase at my job, it feels incomplete for
the purposes of patching into the gperftools codebase.

```

Reported by `Sam.J.Jaffe` on 2015-07-20 17:18:35

<hr>
 * *Attachment: hang in ARCH_FORK.png<br>![hang in ARCH_FORK.png](https://storage.googleapis.com/google-code-attachments/gperftools/issue-701/comment-0/hang in ARCH_FORK.png)*
 * *Attachment: [cpu_profiler_nohang.cpp](https://storage.googleapis.com/google-code-attachments/gperftools/issue-701/comment-0/cpu_profiler_nohang.cpp)*

**Comment by sjjaffe** [comment]
Thank you for exporting this to github.

Just wanted to touch base about this ticket. How is it progressing? Is there any other information you need from me?

**Comment by alk** [comment]
Right now I'm busy with other stuff.

My current theory is that this is indeed bug in RHEL6 that could be reproduced by doing fork when other threads actively burn cpu. If that is indeed the case than preventing cpuprofiler from installing SIGPROF handler early.

For now I advise you to workaround this issue by either:

* not running under RHEL6

* not linking to libprofiler. You can still profile by loading profiler via LD_PRELOAD

**Comment by sjjaffe** [comment]
Thanks for the update! 
Unfortunately, running on something other than RHEL6 is not possible, but I've already stopped linking against libprofiler except through my hacky workaround.

**Comment by sjjaffe** [comment]
Hello, just touching base to see if you've had the time to work on this yet. No worries if you haven't though.

Thanks

**Comment by alk** [comment]
We've now merged a patch that prevents profiler from installing signal prematurely.

But looks like your case is explicitly about issues during forking while profiling. If so, there is nothing we can do. Report the bug to RedHat or drop RHEL6.
