### ISSUE TITLE
problem with address length longer than 16 on 64 bits system

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#707]
Originally reported on Google Code with ID 704
```
What steps will reproduce the problem?
1. run pprof in interactive mode
2. command "list" which produces the assembly code
3. then I get:
Warning: address    b6ef6:	74 08                	je     b6f00 is longer than address
length 16 

What is the expected output? What do you see instead?
the assembly code of a subprogram


What version of the product are you using? On what operating system?
I am using gperftools 2.4 on a Ubuntu 14.04 64 bits
The compiler is g++-4.9.2

Please provide any additional information below.
I am attaching the program (prog2) that runs with no argument and the profile (profile.prof)

```

Reported by `karlaesva` on 2015-08-04 08:45:48

<hr>
 * *Attachment: [profile.prof](https://storage.googleapis.com/google-code-attachments/gperftools/issue-704/comment-0/profile.prof)*
 * *Attachment: [prog2](https://storage.googleapis.com/google-code-attachments/gperftools/issue-704/comment-0/prog2)*

**Comment by alk** [comment]
BTW perl pprof is now deprecated in favor of golang implementation at github.com/google/pprof

Keeping it open though, since I can't get golang implementation to disasm at all.

**Comment by alk** [comment]
Ok. Latest version of golang pprof has functional disasm (yay!). Closing the ticket.

**Comment by Alnek** [comment]
Hey guys from the past, and sorry for necro-posting =)

For anyone stuck on the Perl version of pprof: make sure `file` and `binutils` are installed. It seems the Perl version requires both of them.
