### ISSUE TITLE
How to install on OS X 10.10

### ISSUE THREAD

**Issue by JuKa87** [gperftools/gperftools#712]
This is not really on issue. I apologize for misusing the bug tracker. However, I could not find a better platform. The recommendations in INSTALL did no work for me. Which version should I use and what is the best way to install it?

**Comment by alk** [comment]
Getting .tar.gz release (e.g. https://github.com/gperftools/gperftools/releases/download/gperftools-2.4/gperftools-2.4.tar.gz) and doing plain ./configure && make && make install should work.

If this fails for any reason, I'm willing to help, but I'll need more details on how (and if) it doesn't work for you.

**Comment by JuKa87** [comment]
Switched to Instruments so its not relevant for me anymore. Thanks for offering help!
