### ISSUE TITLE
Mangled new and delete symbols possibly wrong for x64 in patch_functions.cc

### ISSUE THREAD

**Issue by myrsloik** [gperftools/gperftools#715]
By accident I noticed that x86 and x64 mangles its symbols differently. This means that there probably should be another set of symbols to match for 64 bit code in patch_functions.cc. 

Current code in patch_functions.cc:
const char kMangledNew[] = "??2@YAPAXI@Z";
const char kMangledNewArray[] = "??_U@YAPAXI@Z";
const char kMangledDelete[] = "??3@YAXPAX@Z";
const char kMangledDeleteArray[] = "??_V@YAXPAX@Z";
const char kMangledNewNothrow[] = "??2@YAPAXIABUnothrow_t@std@@@Z";
const char kMangledNewArrayNothrow[] = "??_U@YAPAXIABUnothrow_t@std@@@Z";
const char kMangledDeleteNothrow[] = "??3@YAXPAXABUnothrow_t@std@@@Z";
const char kMangledDeleteArrayNothrow[] = "??_V@YAXPAXABUnothrow_t@std@@@Z";

However for x64 the relevant parts of the get_mangled_names.cc+dumpbin output is:
008 00000000 SECT3  notype()    External | ??2@YAPEAX_K@Z (void * __cdecl operator new(unsigned __int64))
009 00000020 SECT3  notype()    External | ??3@YAXPEAX@Z (void __cdecl operator delete(void *))
00A 00000030 SECT3  notype()    External | ??_U@YAPEAX_K@Z (void * __cdecl operator new[](unsigned __int64))
00B 00000050 SECT3  notype()    External | ??_V@YAXPEAX@Z (void __cdecl operator delete[](void *))
00C 00000060 SECT3  notype()    External | ??2@YAPEAX_KAEBUnothrow_t@std@@@Z (void * __cdecl operator new(unsigned __int64, struct std::nothrow_t const &))
00D 00000080 SECT3  notype()    External | ??_U@YAPEAX_KAEBUnothrow_t@std@@@Z (void * __cdecl operator new[](unsigned __int64, struct std::nothrow_t const &))
00E 000000A0 SECT3  notype()    External | ??3@YAXPEAXAEBUnothrow_t@std@@@Z (void __cdecl operator delete(void *, struct std::nothrow_t const &))
00F 000000C0 SECT3  notype()    External | ??_V@YAXPEAXAEBUnothrow_t@std@@@Z (void __cdecl operator delete[](void *, struct std::nothrow_t const &))

Obviously these don't match. If this really is confirmed to be a bug I'll happily make a patch for it.

**Comment by alk** [comment]
Thanks a lot. Looking forward seeing patch from you for this or indication that it works without patching.

**Comment by alk** [comment]
Merged. Thanks.
