### ISSUE TITLE
VS2015 with WIN32_OVERRIDE_ALLOCATORS produces linker errors

### ISSUE THREAD

**Issue by myrsloik** [gperftools/gperftools#716]
I've used tcmalloc in my own project as a static library with WIN32_OVERRIDE_ALLOCATORS since I don't want to patch any other loaded modules. This worked just fine in VS2013 but when switching to VS2015 and two major issues appeared.

The first one is this compilation error when linking tcmalloc as a static library:
1>  Finished generating code
1>\* CIL library _(_ CIL module *) : warning LNK4078: multiple '.CRT' sections found with different attributes (C0400040)
1>libtcmalloc_minimal_mt.lib(override_functions.obj) : error LNK2005: _get_heap_handle already defined in libucrt.lib(heap_handle.obj)
1>libtcmalloc_minimal_mt.lib(override_functions.obj) : error LNK2005: _set_new_mode already defined in libucrt.lib(new_mode.obj)
1>......\Program Files\Python 3.5\Lib\site-packages\vapoursynth\VapourSynth.dll : fatal error LNK1169: one or more multiply defined symbols found

tcmalloc defines duplicate symbols now that VS2015 doesn't like. Forcing the linker to discard the tcmalloc symbols or commenting them out makes it link. However when running the resulting code it will usually result in an invalid pointer freed error from somewhere deep inside the C++ standard library. That's all I've been able to figure out so far.

**Comment by alk** [comment]
Thanks for reporting it. Looks weird indeed. I am by no means windows expert so have no idea while VS2015 complains.

It might be worth seeing if there is any linker flag that may disable this behavior.

**Comment by BengtGustafsson** [comment]
I just started with VS2015. I got some mysterious multiple defined symbols when Microsoft C++ extensions were disabled. C++/Language in settings.

I'm a bit confused by this post. Does tcmalloc work with VS2015 in general, except for some WIN32_OVERRIDE_ALLOCATORS trick you are doing?

**Comment by alk** [comment]
I think Chrome is doing some magic to MS c++ runtime and strips those symbols out. It might be worth checking exactly how they do it. I won't have time to do that myself in next few months.
