### ISSUE TITLE
CPU profiler check fail in ProfileData::Add()

### ISSUE THREAD

**Issue by romange** [gperftools/gperftools#721]
Check failed: depth > 0: ProfileData::Add depth <= 0
line gperf/src/profiledata.cc:267.

my environment - ubuntu linux 3.13.0-39-generic with 
gperftools-2.4.tar.gz configured with --enable-frame-pointers. no libunwind afaik.

**Comment by alk** [comment]
I will need more help to diagnose this. Abort in this case should produce core dump. I believe in default ubuntu setup that core will be piped to some service, so if not already disabled you'll need to disable it.

I.e. via: sudo sysctl.kernel_core_pattern=core

Then unable core dumps just in case: ulimit -c unlimited, then run your program and cause this crash. core file will be produced in current working directory of crashed process.

You can then extract backtrace from core file by:

$ gdb <your program> core

Then in gdb prompt:
> thread apply all bt

And paste output of that here. That should help understanding what happened.

**Comment by alk** [comment]
Also please try seeing if this patch helps:

```
diff --git a/src/profiler.cc b/src/profiler.cc
index b862ae6..f4f5990 100644
--- a/src/profiler.cc
+++ b/src/profiler.cc
@@ -360,7 +360,7 @@ void CpuProfiler::prof_handler(int sig, siginfo_t*, void* signal_ucontext,
                                          3, signal_ucontext);
 
     void **used_stack;
-    if (stack[1] == stack[0]) {
+    if (depth > 0 && stack[1] == stack[0]) {
       // in case of non-frame-pointer-based unwinding we will get
       // duplicate of PC in stack[1], which we don't want
       used_stack = stack + 1;
```

**Comment by romange** [comment]
It seems that the the patch helps.

Thanks!

On Mon, Sep 28, 2015 at 8:23 PM, Aliaksey Kandratsenka (aka Aliaksei
Kandratsenka) <notifications@github.com> wrote:

> Also please try seeing if this patch helps:
>
> diff --git a/src/profiler.cc b/src/profiler.cc
> index b862ae6..f4f5990 100644
> --- a/src/profiler.cc
> +++ b/src/profiler.cc
> @@ -360,7 +360,7 @@ void CpuProfiler::prof_handler(int sig, siginfo_t*, void* signal_ucontext,
>                                           3, signal_ucontext);
>
>      void **used_stack;
> -    if (stack[1] == stack[0]) {
> +    if (depth > 0 && stack[1] == stack[0]) {
>        // in case of non-frame-pointer-based unwinding we will get
>        // duplicate of PC in stack[1], which we don't want
>        used_stack = stack + 1;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gperftools/gperftools/issues/721#issuecomment-143811266>
> .
>



-- 
Best regards,
     Roman

**Comment by alk** [comment]
Fix now merged.
