### ISSUE TITLE
integer overflow in malloc sampling (currently harmless)

### ISSUE THREAD

**Issue by spotrh** [gperftools/gperftools#723]
tcmalloc.cc:do_malloc_pages contains this code:

  Length num_pages = tcmalloc::pages(size);
  size = num_pages << kPageShift;

This means that the size value can end up as zero if the allocation requst is close to ~(size_t)0.

The size value is only used in sampling mode:

  if ((FLAGS_tcmalloc_sample_parameter > 0) && heap->SampleAllocation(size)) {
    result = DoSampledAllocation(size);

tcmalloc currently never samples size-0 allocations, so heap->SampleAllocation(size) is always false in this case, and DoSampledAllocation is never called.

But this should still be fixed in case size-0 allocations are sampled one day and do_malloc_pages is not adjusted accordingly.

**Comment by fweimer** [comment]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1232705

**Comment by alk** [comment]
Indeed. Thanks for spotting it.
