### ISSUE TITLE
heap analysis for tcmalloc

### ISSUE THREAD

**Issue by gaurabpaul** [gperftools/gperftools#727]
this not an issue as such. are there ways to know the all the  allocations made from of the central heap and the thread cache. or we need some pointers on how to locate the central heap, the thread cache locations and all allocations made from them in a core file. 

we are thinking of writing gdb scripts in the lines similar to https://seanhn.wordpress.com/2011/03/30/heap-scripts-for-tcmalloc-with-gdbs-python-api/

**Comment by alk** [comment]
There are no APIs for that. It should be possible to script gdb to locate things in core file. If you do that, please consider contributing this back.

**Comment by gaurabpaul** [comment]
yes sure. we wanted to know the location of the central heap or main arena and from there how to reach the thread cache. is the central heap at a fixed location ?

**Comment by alk** [comment]
It's not very straightforward. I'll try to give you some pointers, but doing this thing will require you to understand intimate details tcmalloc. So you'll need to dive into the code in any case.

There are several data structures that represent freed memory and metadata.

PageMap stores mapping from logical pages (8k or 32k or 64k depending on config) to Span objects. Which store metadata for that chunk of memory.

Spans that are free are kept in pageheap. Pageheap and pagemap can be located via static_vars.h.

Every thread has ThreadCache that maintains free list per size class. There is global list of them headed at ThreadCache::thread_heaps_.

And there is also CentralFreeList object that maintains transfer caches and free lists per size class.

By analyzing all that data when program is stopped, you can in locate all free and allocated objects.
