### ISSUE TITLE
Running death test 15...FAILED

### ISSUE THREAD

**Issue by egberts** [gperftools/gperftools#728]
Downloaded gperftools-master.zip (that's commit 6627f9217d8897b297c6da038cfbcff6a3086cfa parent f985abc by Aliaksey Kandratsenka).

First try on CentOS 6.6 x86_64 using gcc-4.4.7-20120313 (Red hat 4.4.7-16) resulted in:

    ./autogen.sh
    ./configure
    ....
    checking unwind.h usability... yes
    checking unwind.h presence... yes
    ...
    checking libunwind.h usability... yes
    checking libunwind.h presence... yes
    checking for libunwind.h... yes
    checking for backtrace in -lunwind... yes
    checking for x86 without frame pointers... yes
    ...
    make
    ./debugallocation_test.sh
    $ ./debugallocation_test.sh
    Running death test 0...OK
    Running death test 1...OK
    Running death test 2...OK
    Running death test 3...OK
    Running death test 4...OK
    Running death test 5...OK
    Running death test 6...OK
    Running death test 7...OK
    Running death test 8...OK
    Running death test 9...OK
    Running death test 10...OK
    Running death test 11...OK
    Running death test 12...OK
    Running death test 13...OK
    Running death test 14...OK
    Running death test 15...FAILED
    Running death test 16...done with death tests
    Running non-death tests...Massive size passed to malloc: 18446744073709551615
    tcmalloc: large alloc 0 bytes == (nil) @  0x7fe0768237da 0x7fe076825ebc 0x7fe0768464f5 
        0x401211 0x400f52 0x3a5f01ed5d 0x400e59
    
    Passed 12 tests
    
    PASS
    OK
    Failed with 1 failures

Any idea where to start?

**Comment by egberts** [comment]
Strange.....

Problem got fixed once I exported `PPROF_PATH=/usr/bin/pprof` in the shell.

Now, all 16 death tests pass.

**Comment by zatrazz** [comment]
It is because the make check will set all the required environment variables to run the tests. To run some tests individually you will need to set some variables manually.

**Comment by alk** [comment]
I've merged fix that sets PPROF_PATH in shell file.
