### ISSUE TITLE
Leakage during Heap StackTrace construction for a deep-stack application

### ISSUE THREAD

**Issue by egberts** [gperftools/gperftools#729]
If your application has 16-function deep (or deeper) of a backtrace or more, then this one is for you.

When the stacktrace gets outputted into the STDERR file by application's `libtcmalloc` library, sometimes the stacktrace get truncated at 800 character per program address' worth of backtraces. Sometime, maybe 16 to 18 lines of stacktrace with the last line were truncated. If it gets truncated, this appears to be a live memory leak caused by gperftools. 

I fixed this by expanding the `kBufSize` in [heap-profile-table.cc:590](https://github.com/gperftools/gperftools/blob/master/src/heap-profile-table.cc#L590) by changing from the 10 value into an 11. :

    static const int kBufSize = 2<<11;

Rebuild and reinstall, then restart my app again. No more leak by gperftools. Of course, this leakage only occurs when doing formatting of backtraces requiring more than 2<<10 of string space.

**Comment by alk** [comment]
Can you please provide sample program ? I'm unable to see how size of that buffer may affect leaking.

**Comment by egberts** [comment]
Well, the sample is a production software using Bro.

But one should be able to recreate it by a small test C source code having some 50 functions, all with at least 24 characters each.

I should point out that the leakage is only occurring during the backtrace printing of its very deep stack.


Steve

**Comment by alk** [comment]
That's fine. But in order to help I'll need at a bit more details. What makes you think it's leaking ?

**Comment by alk** [comment]
Closing stale ticket.

Please reopen of you're able to provide more info.
