### ISSUE TITLE
g_last_loaded cause memory leak when closing application

### ISSUE THREAD

**Issue by yhchen** [gperftools/gperftools#730]
I found a memory leak report on application closed. the size is 12byte on x86 and 24byte on x64. then i find that it might cause by the var g_last_loaded. so i add code below : 

```C++
static std::set<HMODULE> *g_last_loaded;
//↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
class auto_free_last_loaded
{
public:
	auto_free_last_loaded() {}
	~auto_free_last_loaded() { if (g_last_loaded) { delete g_last_loaded; g_last_loaded = NULL; } }
}g_do_auto_free_last_loaded;	/* free g_last_loaded if exists */
//↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
```

the memory leak warming solved.

**Comment by zatrazz** [comment]
Could you elaborate why you think this is an issue with tcmalloc? Otherwise please close this report.

**Comment by alk** [comment]
g_last_loaded is part of gperftools' windows/patch_functions.cc. I'm slightly reluctant to patch this, since it's not really "a leak". There is no way to safely unload tcmalloc dll on windows anyways. So "leak" only happens at program exit and so is totally harmless.

**Comment by zatrazz** [comment]
Any special reason to dynamic allocate the std::set?

**Comment by yhchen** [comment]
```Any special reason to dynamic allocate the std::set?```
same question...

**Comment by yhchen** [comment]
···Any special reason to dynamic allocate the std::set?···
i also wonder why?

**Comment by alk** [comment]
On Wed, Oct 14, 2015 at 8:20 AM, Adhemerval Zanella <
notifications@github.com> wrote:

> Any special reason to dynamic allocate the std::set?
>

I believe it is because TCMallocGuard::TCMallocGuard() calls
ReplaceSystemAlloc early. Which calls PatchWindowsFunctions which calls
PatchModuleFunctions which uses this variable. So this variable may be
accessed before it is initialized (unless it's .data or .bss).
