### ISSUE TITLE
if EnumProcessModules is broken, patching hangs (was: Attention please,EnumProcessModules fail may cause infinite loop)

### ISSUE THREAD

**Issue by qq325895369** [gperftools/gperftools#733]
when i use tcmalloc,I found a fatal bug in function PatchAllModules,in my own project,link libtcmalloc,encountered a  dead loop problem, so I generated a full dmp file,after my analyzing,then i located here:
once EnumProcessModules fail,when next  time to execute PatchAllModules,if this api call successfully,will lead to double patching,then lead to dead loop finally！（perftools_free<1> jmp to perftools_free<0>,but perftools_free<0> jmp back to perftools_free<1>）

this bug often appears!!!   and you can reappear it by making the EnumProcessModules call fail manually
if not,you can get the dmp file here: http://pan.baidu.com/s/1kTAhEjd

i have made a pull request,attention please

sorry,my english is not good,can you get it? thanks

**Comment by alk** [comment]
Hi. Sorry for delay. I don't quite understand the problem. Why would EnumProcessModules fail?

Also why PatchAllModules is invoked several times?

**Comment by qq325895369** [comment]
@alk ,i have modified #ifndef WIN32, please merge.  EnumProcessModules fail,because api hook or system  module is corrupted

PatchAllModules  is invoked when new dll is loaded into process

**Comment by qq325895369** [comment]
@alk tcmalloc's patch is not thread safe,attention please! such as patch to malloc,free,etc.

**Comment by alk** [comment]
I still don't quite understand the problem. Can you please post little test program where problem can be clearly seen?

**Comment by qq325895369** [comment]
hi,@alk

EnumProcessModules is a windows api. if this api is patched by some application,and return false. then, when a new module load next time, PatchAllModules will be invoked again, and it call EnumProcessModules , if 

EnumProcessModules return true this time, this problem reappears!

i can't write a demo,beacuse this happens only when  EnumProcessModules fails first time  and succ next time. i have a dmp file, can  you download it?

**Comment by alk** [comment]
I am not eager to do defensive coding against someone breaking windows api. If that is "bug", then sorry but no, I won't take this patch.

**Comment by qq325895369** [comment]
also,if the system dll file is damaged, can result in this problem

the dmp file i uploaded, is  this case

**Comment by alk** [comment]
Closing the ticket as "won't fix". I see no reason to try to defensive-code around broken api. There are billions of various ways how someone can break some api(s) and there is no way we can guard against that.

So "broken api" -> "all bets are off".

**Comment by qq325895369** [comment]
another problem:
@alk tcmalloc's patch is not thread safe,attention please! such as patch to malloc,free,etc.
which version will fix this bug?

**Comment by alk** [comment]
Locking looks semi-plausible in this code. Can you elaborate where it is not thread safe ? Separate ticket and example program would be most helpful.

**Comment by qq325895369** [comment]
i have a crash dmp file.
when a thread is  execute free function,  another thread is patching free function,the head of this function is changed to be a  jmp instruction. when the first byte of the function is modified to be 0xe9,but the remaining operand is still unchanged, if thread switchs at this moment, then another thread will jmp to a invalid address, then crash..

**Comment by alk** [comment]
I'll need test program that hits this issue. Is it possible that you might be loading .dll that is linked to tcmalloc at runtime? That could explain why tcmalloc might be patching something when there is another thread running. If so, try linking tcmalloc to your main program, as supporting a case when tcmalloc suddenly needs to patch malloc/free in running process is impossible.
