### ISSUE TITLE
Tests fail when run in parallel

### ISSUE THREAD

**Issue by jrosenboom** [gperftools/gperftools#742]
Multiple tests are using the same TMPDIR, so running them in parallel with something like

    make check-TESTS -j8

will pretty reproducibly fail with an error like

```
FAIL: heap-profiler_debug_unittest.sh
=====================================

rm: cannot remove '/tmp/heap_profile_info': Directory not empty
mkdir: cannot create directory '/tmp/heap_profile_info': File exists
```

This affects e.g. Debian package builds, where the tests are run as part of the build process and people want to use parallel compilation for performance reason.

Is there a reason not to use a dedicated TMPDIR for each test?

**Comment by alk** [comment]
No reason. Feel free to patch this. Thanks for raising it.
