### ISSUE TITLE
sized deallocation changes broke compilation on OS X

### ISSUE THREAD

**Issue by acmorrow** [gperftools/gperftools#749]
In commit a9db0ae516c225543976280047b22b1e0ca08b93, the __attribute__((alias("tc_free_sized"))) was added, but it does not appear to build on OS X. I'm getting the following compiler error

```
libtcmalloc_minimal_internal_la-span.lo -MD -MP -MF src/.deps/libtcmalloc_minimal_internal_la-span.Tpo -c src/span.cc -o src/libtcmalloc_minimal_internal_la-span.o >/dev/null 2>&1
2 warnings generated.
src/tcmalloc.cc:1615:18: error: only weak aliases are supported on darwin
  __attribute__((alias("tc_free_sized")));
                 ^
src/tcmalloc.cc:1617:18: error: only weak aliases are supported on darwin
  __attribute__((alias("tc_free_sized")));
                 ^
```

**Comment by alk** [comment]
Thanks for reporting it. I think I'll ifdef this branch to known elf
platforms.

**Comment by ryanoneill** [comment]
Ran into the same issue on Yosemite (10.10.5) with Apple LLVM version 7.0.2 (clang-700.1.81)

Modifying the code to use the else path from
https://github.com/gperftools/gperftools/blob/master/src/tcmalloc.cc#L1608
allowed compilation to finish successfully.

**Comment by alk** [comment]
I've merged a fix yesterday. Thanks again for reporting it.
