### ISSUE TITLE
libtcamlloc couldn't get the backtrace on the arm

### ISSUE THREAD

**Issue by doudouOUC** [gperftools/gperftools#751]
hi,all:
I use my own tool-chains to comopile the gperftools，and use the libtcmalloc.so.4.2.6 on arm platform.
but I couldn't  get the backtrace using the  heap_profiler
version:
gperftools release 2.4
configure as follows
CC=$ourown CXX=xx CFLAGS+=" -g -fno-omit-frame-pointer " CPPFLAGS+=" -g -fno-omit-frame-pointer " CXXFLAGS+=" -g -fno-omit-frame-pointer " ./configure --host=arm-linux-gnueabi --build=arm-linux-gnueabi --enable-frame-pointers
I got the heap info like follows,we cant none backtrace!
>eap profile:      1:       16 [     1:       16] @ heapprofile
>     1:       16 [     1:       16] @
>
>MAPPED_LIBRARIES:
>00010000-00011000 r-xp 00000000 00:00 2446834     /tmp/link_tcmalloc
>00020000-00021000 r-xp 00000000 00:00 2446834     /tmp/link_tcmalloc
>00021000-00022000 rwxp 00001000 00:00 2446834     /tmp/link_tcmalloc
>01c87000-02588000 rwxp 00000000 00:00 0           [heap]
>b6998000-b6b68000 rwxp 00000000 00:00 0
>b6b68000-b6b7f000 r-xp 00000000 00:00 6827        /usr/lib/libpthread-2.20.so
......
  and then I use objdump -d and readelf -u  to to parse the libtcmalloc.so.4.2.6

objdump -d
>arm-eabi-objdump -d  .libs/libtcmalloc.so.4.2.6 >libtcmalloc.objdump

some objdump result sections as follows

>libs/libtcmalloc.so.4.2.6:     file format elf32-littlearm
>
>Disassembly of section .plt: 
>
>00038968 <_ZNSt8_Rb_treeIN15MemoryRegionMap6RegionES1_St9_IdentityIS1_ENS0_9RegionCmpE13STL_AllocatorIS1_NS0_11MyAllocatorEEE24_M_get_insert_unique_posERKS1_@plt-0x14>:
>   38968:       e52de004        push    {lr}            ; (str lr, [sp, #-4]!)
>   3896c:       e59fe004        ldr     lr, [pc, #4]    ; 38978 <_init+0x1c>
>   38970:       e08fe00e        add     lr, pc, lr
>   38974:       e5bef008        ldr     pc, [lr, #8]! 
>   38978:       00060688        .word   0x00060688
>
>0003897c <_ZNSt8_Rb_treeIN15MemoryRegionMap6RegionES1_St9_IdentityIS1_ENS0_9RegionCmpE13STL_AllocatorIS1_NS0_11MyAllocatorEEE24_M_get_insert_unique_posERKS1_@plt>:
>   3897c:       e28fc600        add     ip, pc, #0, 12
>   38980:       e28cca60        add     ip, ip, #96, 20 ; 0x60000
>   38984:       e5bcf688        ldr     pc, [ip, #1672]!        ; 0x688
>
>00038988 <_ZNSt3mapIPKvPKcSt4lessIS1_ESaISt4pairIKS1_S3_EEE11lower_boundERS7_@plt>:
>   38988:       e28fc600        add     ip, pc, #0, 12
>   3898c:       e28cca60        add     ip, ip, #96, 20 ; 0x60000
>   38990:       e5bcf680        ldr     pc, [ip, #1664]!        ; 0x680
>
>00038994 <_ZN8tcmalloc8PageHeap23SearchFreeAndLargeListsEj@plt>:
>   38994:       e28fc600        add     ip, pc, #0, 12
>   38998:       e28cca60        add     ip, ip, #96, 20 ; 0x60000
>   3899c:       e5bcf678        ldr     pc, [ip, #1656]!        ; 0x678
>
>000389a0 <getpagesize@plt>:
>   389a0:       e28fc600        add     ip, pc, #0, 12
>   389a4:       e28cca60        add     ip, ip, #96, 20 ; 0x60000
   389a8:       e5bcf670        ldr     pc, [ip, #1648]!        ; 0x670

readelf -u:

>arm-eabi-readelf -u .libs/libtcmalloc.so.4.2.6 >libtcmalloc.readelf

readelf result some sections as follows 

>Unwind table index '.ARM.exidx' at offset 0x8682c contains 750 entries:
>
>0x3d344 <deregister_tm_clones>: 0x80b0b0b0
>  Compact model index: 0
>  0xb0      finish
>  0xb0      finish
>  0xb0      finish                                                                                                                                                          
>
>0x3d3e0 <__do_global_dtors_aux>: @0x84388
>  Compact model index: 1
>  0xb1 0x08 pop {r3} 
>  0x84 0x00 pop {r14}
>  0xb0      finish
  0xb0      finish

As I knows, the ARM.exidx is used for unwinding the backtrace, but when we found the .arm.edidx lack a lot of instructions
eg:
from the objdump we found a lot functions point the instructions begin with 0x39
but from the readelf ,we found the the instructions begins with 0x3dxxx?!so where is the instructions that in 0x39xxx-0x3dxxx?
So,I have two questions.
First, Does the libtcmalloc.so support perfectly for arm platform?
Second, does the Arm.exidx useful for unwinding the backtrace?How can I get the full Arm.exidx? OR How can i get the full backtrace.

**Comment by alk** [comment]
We have asm frame-pointer-base ARM unwinder implementation, but it is known to be broken.

Libunwind unwinder mostly works (configure with --enable-libunwind). In my testing on arm I've found libunwind to occasionally crash.

There is also proposal for semi-portable frame-pointer based unwinder here: https://github.com/alk/gperftools/tree/wip-backtrace-via-gcc 

In my testing on arm I've found that it didn't work on gcc but it did work with clang.

**Comment by doudouOUC** [comment]
Thanks very much. We also found the logic of arm backtrace is something wrong,so we use the glibc backtrace logic code.

**Comment by zatrazz** [comment]
I tried to fix a similar issue for sanitizers on ARM [1] [2] and on my findings frame-pointer unwinder on ARM is broken due a set of constraints:

1. GCC and CLANG differs on which saved frame pointer value is saved on current frame pointer. This make it impossible without external information to walk on GCC-based stack frame due the fact we do not know which is the size of the allocated stack.
2. THUMB objects are broken on both compiler (-thumb), while as for 1. -marm only works for CLANG. 

These issues is leading me to send a patch to just disable the fast unwind options (the frame-pointer based on) on ARM for sanitizers.

[1] https://llvm.org/bugs/show_bug.cgi?id=22741
[2] https://llvm.org/bugs/show_bug.cgi?id=18505

**Comment by alk** [comment]
Fixed now with libgcc-based unwinder and working support of libunwind  (requires --enable-emergency-malloc)
