### ISSUE TITLE
Analyzing the Output

### ISSUE THREAD

**Issue by aleafboat** [gperftools/gperftools#753]
hi

today I tried to add sleep fucnton  for  30 seconds for testing  ，Why can't get the result 
zhe smartComputing cost is Zero

``` c++
int smartComputing(int a, int b)
 { 
    return a+b; 
    sleep(30);
 }; 
```

> pprof -text ./demo ./1.prof 
Total: 2204 samples
    1640  74.4%  74.4%     1640  74.4% consumeSomeCPUTime1
     563  25.5% 100.0%     1090  49.5% consumeSomeCPUTime2
       1   0.0% 100.0%     2203 100.0% stupidComputing
       0   0.0% 100.0%     2204 100.0% __libc_start_main
       0   0.0% 100.0%     2204 100.0% main
·

**Comment by alk** [comment]
Hi. I'm not sure what you expect to see.

Profiling is normally accounting cpu time spent. Not idle time (sleeping, blocked on locks, waiting for io, waiting for work etc).

If you really need to profile wall clock time there is a way to do that (see docs).

**Comment by aleafboat** [comment]
@alk  thanks 
sleep is my test
