### ISSUE TITLE
gperftools is not working for s390x machine

### ISSUE THREAD

**Issue by abcshravan** [gperftools/gperftools#761]
Why it is not supporting s390x? 
[root@svl gperftools-2.4]# make
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I./src  -I./src   -DNO_TCMALLOC_SAMPLES -pthread -DNDEBUG -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result   -g -O2 -MT src/libtcmalloc_minimal_la-tcmalloc.lo -MD -MP -MF src/.deps/libtcmalloc_minimal_la-tcmalloc.Tpo -c -o src/libtcmalloc_minimal_la-tcmalloc.lo `test -f 'src/tcmalloc.cc' || echo './'`src/tcmalloc.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -DNO_TCMALLOC_SAMPLES -pthread -DNDEBUG -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -g -O2 -MT src/libtcmalloc_minimal_la-tcmalloc.lo -MD -MP -MF src/.deps/libtcmalloc_minimal_la-tcmalloc.Tpo -c src/tcmalloc.cc  -fPIC -DPIC -o src/.libs/libtcmalloc_minimal_la-tcmalloc.o
In file included from src/tcmalloc.cc:117:0:
src/base/basictypes.h:361:5: error: #error Could not determine cache line length - unknown architecture
 #   error Could not determine cache line length - unknown architecture

**Comment by zatrazz** [comment]
IMHO the CACHELINE_ALIGNED is mainly an optimization hint and should not break build in an unknown configuration. I think instead of emitting an '#error" we should emit a warning and define as if !HAVE___ATTRIBUTE__.

**Comment by acmorrow** [comment]
I too would be happy to see out of the box s390x support for gperftools.

**Comment by alk** [comment]
There are still some places in the code that are not portable without too good reason. I've recently cleaned up some unnecessary stuff from spinlock. I believe in order to get tcmalloc_minimal working there is not much that needs to be supported. cacheline size should be easy to fix.

If someone provide a patch with s390x support I'd be happy to merge it.

**Comment by alk** [comment]
Alternatively, if there is some reasonably simple way I could run s390x cross-compiler on my box, I'll be happy to give it at least quick try.

**Comment by alk** [comment]
So in fact debian _does_ have s390x cross-compiler. So with some hacks I was able to build libtcmalloc_minimal.so.

With this patch:

diff --git a/src/base/basictypes.h b/src/base/basictypes.h
index 9c930a0..560d39a 100644
--- a/src/base/basictypes.h
+++ b/src/base/basictypes.h
@@ -357,6 +357,8 @@ class AssignAttributeStartEnd {
 # elif (defined(__aarch64__))
 #   define CACHELINE_ALIGNED __attribute__((aligned(64)))
     // implementation specific, Cortex-A53 and 57 should have 64 bytes
+# elif (defined(__s390x__))
+#   define CACHELINE_ALIGNED __attribute__((aligned(128)))
 # else
 #   error Could not determine cache line length - unknown architecture
 # endif
diff --git a/src/base/spinlock_linux-inl.h b/src/base/spinlock_linux-inl.h
index aadf62a..08ce245 100644
--- a/src/base/spinlock_linux-inl.h
+++ b/src/base/spinlock_linux-inl.h
@@ -51,12 +51,14 @@ static struct InitModule {
     int x = 0;
     // futexes are ints, so we can use them only when
     // that's the same size as the lockword_ in SpinLock.
+#ifdef __NR_futex
     have_futex = (sizeof (Atomic32) == sizeof (int) &&
                   sys_futex(&x, FUTEX_WAKE, 1, NULL, NULL, 0) >= 0);
     if (have_futex &&
         sys_futex(&x, FUTEX_WAKE | futex_private_flag, 1, NULL, NULL, 0) < 0) {
       futex_private_flag = 0;
     }
+#endif
   }
 } init_module;
 
@@ -77,11 +79,13 @@ void SpinLockDelay(volatile Atomic32 *w, int32 value, int loop) {
       tm.tv_nsec = 2000001;   // above 2ms so linux 2.4 doesn't spin
     }
     if (have_futex) {
+#ifdef __NR_futex
       tm.tv_nsec *= 16;  // increase the delay; we expect explicit wakeups
       sys_futex(reinterpret_cast<int *>(const_cast<Atomic32 *>(w)),
                 FUTEX_WAIT | futex_private_flag,
                 value, reinterpret_cast<struct kernel_timespec *>(&tm),
                 NULL, 0);
+#endif
     } else {
       nanosleep(&tm, NULL);
     }
@@ -90,11 +94,13 @@ void SpinLockDelay(volatile Atomic32 *w, int32 value, int loop) {
 }
 
 void SpinLockWake(volatile Atomic32 *w, bool all) {
+#ifdef __NR_futex
   if (have_futex) {
     sys_futex(reinterpret_cast<int *>(const_cast<Atomic32 *>(w)),
               FUTEX_WAKE | futex_private_flag, all? INT_MAX : 1,
               NULL, NULL, 0);
   }
+#endif
 }
 
 } // namespace internal

(by no means clean and 100% correct; I.e. i've cacheline size for s390 and forced 'bad' spinlock delay implementation)

So linux_syscall_support is totally lacking any knowledge of s390x. Which causes references to futex to fail. Also one low_level_alloc_unittest attempts to refer to unhooked mmap or something like that and fails to build. But at least make libtcmalloc_minimal.la build fine. With this command line:

$ ./configure --host=s390x-linux-gnu --enable-minimal --prefix=/root/s390gpt && make libtcmalloc_minimal.la -j8

So we should either have somebody knowledgeable in s390x contribute linux_syscall_support or just make our code less dependent on this unportable and, I believe, not really 100% needed thing.

**Comment by acmorrow** [comment]
I don't know enough about the background and rationale for why linux_syscall_support exists to know whether or not it is required, but it certainly does make things more complex. If removing it is a real possibility I'd be in favor.

**Comment by bryanpkc** [comment]
I have hacked linux_syscall_support.h for s390x and have started working on [a gperftools port for s390x](https://github.com/linux-on-ibm-z/gperftools). It builds and tcmalloc_minimal works, but since stack unwinding is busted, other things are not working. On s390x, we can use glibc's backtrace but it causes a deadlock (issue #614). So I am also trying to port libunwind to s390x.

I am not sure how important it is to support s390 (31-bit). Right now I am just making sure that 64-bit s390x works.

**Comment by alk** [comment]
Great. tcmalloc_minimal is already good achievement. And worth committing
by itself. So send us a patch please whenever you're ready.

Regarding libunwind support, expect some nontrivial amount if work.

I've made some work towards preventing deadlocks from backtrace. Exactly
with eye towards more portability. Here:
https://github.com/alk/gperftools/commits/wip-emergency-malloc-explicit

It is unlikely to help with CPU profiling since this case also involves
locking issues, but heap profiling and checker stuff should work fine.

**Comment by bryanpkc** [comment]
Excellent. After merging your branch into mine, "make check" now pass 47/47 on s390x. When do you plan to merge that code into master?

Porting libunwind is indeed non-trivial. That's not likely to get done soon.

**Comment by abcshravan** [comment]
Thanks alot its working for me too...

**Comment by alk** [comment]
This code needs a bit more work to handle elf-isms and other linux-isms. There is also some performance work pending. Since I want overhead of emergency malloc checks to be as small as possible.

I'll spend some more time on this next weekend.

**Comment by alk** [comment]
I've uploaded what looks like complete implementation of emergency malloc to https://github.com/alk/gperftools/tree/wip-emergency-malloc

I plan to merge it next week and do 2.5rc. Please review and test if you can. Thanks.

**Comment by alk** [comment]
I've also finished stacktrace capturing code via libgcc. Which is essentially same code path as backtrace, but it has advantage of not calling malloc. So it works even without emergency malloc.

The code is here: https://github.com/alk/gperftools/tree/wip-backtrace-via-gcc

**Comment by edelsohn** [comment]
@bryanpkc @alk Do you know anyone who would be interested to port libunwind to s390x if a financial bounty was offered?
