### ISSUE TITLE
`make check` hangs on Debian Sarge

### ISSUE THREAD

**Issue by bsilver8192** [gperftools/gperftools#763]
I created a Debian Sarge i386 (kernel 2.4.27, glibc 2.3.2) VM to test gperftools with linuxthreads. It hangs when running `make check`. I can't tell which test is hanging, but [here's the output](https://github.com/gperftools/gperftools/files/101423/make_check_output.txt).

I think not supporting a system this ancient is perfectly reasonable, so I would be fine if that's the answer. I only noticed the problem testing #762.

**Comment by zatrazz** [comment]
Linuxthreads is a defunct project, without proper support to POSIX and with a lot of issues; GLIBC 2.3.2 is no longer supported by a LONG time (it was released 13 years ago), and Linux 2.4 is not even in LTS. Why bother reporting it?

**Comment by bsilver8192** [comment]
The profiling code still has a lot of extra complication to support it (mainly its lack of POSIX compliance wrt how timers work between threads). If it's not supported any more, it seems like all that code should be removed to simplify it and avoid having if changes break it.

Four years ago (kind of a while now, but not all that long compared to how old linuxthreads is) in #409, somebody wanted changes to that code tested to make sure they didn't break it.

**Comment by zatrazz** [comment]
The profiling code indeed could use some cleanup, although I do noticed that another profiling projects (like perf) provide superior functionality, design and less limitations. So I wonder if this task really worth its time...

**Comment by alk** [comment]
I think profiling in general is still worth supporting.

Perf has some nice features but it still frequently sucks when dwarf unwinding is needed. And it's own profile viewing UI is still nearly useless.

Regarding supporting 2.4 kernel, I think it isn't worth keeping. I sometimes run tests on RHEL4 (which ships 2.6.9 kernel) and things seem to work there, but I doubt many folks really care about that old distro. Anything older than rhel4 is IMHO clearly useless.

So I'm closing this bug. Feel free to reopen if you disagree strongly.
