### ISSUE TITLE
IncreaseCacheLimitLocked() has a double next operation?

### ISSUE THREAD

**Issue by snaix** [gperftools/gperftools#764]
Hi
In ThreadCache::IncreaseCacheLimitLocked(), there is an double next_ operation:

  for (int i = 0; i < 10;
       ++i, **next_memory_steal_ = next_memory_steal_->next_**) {
    // Reached the end of the linked list.  Start at the beginning.
    if (next_memory_steal_ == NULL) {
      ASSERT(thread_heaps_ != NULL);
      next_memory_steal_ = thread_heaps_;
    }
    if (next_memory_steal_ == this ||
        next_memory_steal_->max_size_ <= kMinThreadCacheSize) {
      continue;
    }
    next_memory_steal_->max_size_ -= kStealAmount;
    max_size_ += kStealAmount;

**next_memory_steal_ = next_memory_steal_->next_;**
    return;
  }

Is it alright? to skip half of thread cache? or a bug?
and, is it necessary to loop with MIN(10, thread_heap_count_) but not 10 only?

**Comment by alk** [comment]
Regading skipping. It works fine in fact. Note how second "next"-ing is done right prior to returning and after successfully stealing.

Agree about MIN. It would be slight improvement. Feel free to send patch for that.
