### ISSUE TITLE
rpath of .so files when building in shared mode includes too many folders?

### ISSUE THREAD

**Issue by f18m** [gperftools/gperftools#768]
Hi,

Building gperftools in shared mode I noticed that the RPATH tag inside the resulting .so files seems to include a lot of folders (I guess all folders passed as linker search path via -L). For our use case, we need a single path, that we would like to set using LDFLAGS, to be present. Can we disable gperftools Makefile from placing all the paths passed as -L also as rpaths?

Thanks!

Francesco

**Comment by alk** [comment]
Hi Francesco. rpath is added not via -L line but either via:

a) LD_RUN_PATH environment variable

b) -Wl,rpath=XXX flag to gcc (which simply passes --rpath to ld)

c) libtool "major". Basically libtool is probably adding rpath from .la files of libraries you're linking to and it also automatically adds rpath if --prefix is not one of standard prefixes (i.e. not /usr or /usr/local).

You should inspect your particular case on exact cause of rpaths being added.

**Comment by alk** [comment]
Closing the ticket since it's not gperftools problem most likely.

Reopen if you have more details.
