### ISSUE TITLE
Is it possible to show each line annotated of a function I write myself in an individual file?

### ISSUE THREAD

**Issue by xibeisiber** [gperftools/gperftools#769]
Is it possible to show each line annotated of a function I write myself in an individual file?
That is I have main.cpp like this
main.cpp: for(i=0;i<n;i++) { **dofun**;}
**dofun**.cpp: void **dofun**() {line1; line2; line3; ...; line; }

I want to know which part in dofun.cpp costs the largest time.

I try to use "kcachegrind ls.callgrind" but it said function **dofun** has no cost of current selected type associated with any source line of this function in file '??' thus, no annotated source can be shown.

Thanks!

**Comment by alk** [comment]
pprof has --lines option that allows you to attribute profiling ticks to lines. Just be aware that in output of optimizing C/C++ compiler, instruction to line number mapping might be misleading.
