### ISSUE TITLE
A dead link in INSTALL

### ISSUE THREAD

**Issue by AndriyS73** [gperftools/gperftools#770]
Hi all,

A quote from INSTALL file:

> Alternately, you can use a more recent libunwind (e.g. 1.0.1) at the
> cost of adding a bit of boilerplate to your code.  For details, see
> http://groups.google.com/group/google-perftools/msg/2686d9f24ac4365f

However, following the link results in error 500 and google-perftools appears to be banned from google groups.
I suppose the link used to contain a solution for libunwind deadlock problem I'm facing now, so would it be possible to replace the link with an actual description of the code changes?

Thanks!
Andriy

**Comment by alk** [comment]
On Fri, Feb 19, 2016 at 8:44 AM, AndriyS73 <notifications@github.com> wrote:

> Hi all,
>
> A quote from INSTALL file:
>
> Alternately, you can use a more recent libunwind (e.g. 1.0.1) at the
> cost of adding a bit of boilerplate to your code. For details, see
> http://groups.google.com/group/google-perftools/msg/2686d9f24ac4365f
>
> However, following the link results in error 500 and google-perftools
> appears to be banned from google groups.
> I suppose the link used to contain a solution for libunwind deadlock
> problem I'm facing now, so would it be possible to replace the link with an
> actual description of the code changes?
>
> Thanks!
> Andriy
>

Thanks for reporting the issue, Andriy.

Regarding your issue I'm very curious about details. INSTALL file merely
suggests installing later version of libunwind, but it will not necessarily
be enough.

I think it'll be best if you open fresh ticket and post as much details as
you can. Particularly:

a) backtraces of all threads in your stuck application. I'll need to know
what is deadlocked

b) post exact version of libunwind and distro that you run on

b) post exact version of gpeftools that you're using

**Comment by AndriyS73** [comment]
Hi, 

So far, I didn't yet obtain the backtraces. I can only provide the distro versions at the time being.
> gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC)
> libunwind-1.1 (configured with default options)
> gperftools-2.4 (configure --enable-libunwind)

Thank you,
Andriy

**Comment by alk** [comment]
I am still hoping to get that link working again.

**Comment by alk** [comment]
I dropped link from install file. As for getting us archive access to gperftools, sadly it is not happening at all.

Some of gperftools ml archive can be retrieved from web archive (many thanks!). Latest version I see is here: https://web.archive.org/web/20120328080439/http://groups.google.com/group/google-perftools/topics
