### ISSUE TITLE
compile error with visual studio 2015

### ISSUE THREAD

**Issue by EnoroF** [gperftools/gperftools#773]
i am trying to compile tcmalloc with vs2015, but some error occurred. wheter i need to set some param?

tcmalloc.cc(196): error C2491: “FLAG__namespace_do_not_use_directly_use_DECLARE_int64_instead::FLAGS_tcmalloc_large_alloc_report_threshold”

error C3646: “PERFTOOLS_THROW”

**Comment by alk** [comment]
Thanks a lot for reporting it. Build issues are now fixed in 2.5rc2 that I just released.

Do keep in mind, however, that there are known issues with gperftools in vs2015.

**Comment by EnoroF** [comment]
thx a lot~

**Comment by acmorrow** [comment]
@alk Could you elaborate on what issues there are with VS2015? We have plans to upgrade to both gperftools 2.5 when it comes out, and are hoping to upgrade to VS2015 when it reaches some usable level of stability. If there are incompatibilities, I'd like to know what to expect.

**Comment by alk** [comment]
We might be at the end of the road with runtime patching of new/delete operators on VS2015. See ticket #719. Static operators new/delete, i.e. a-la chrome, overriding should still work.
