### ISSUE TITLE
Why does the physical memory increase continuously after free() is called

### ISSUE THREAD

**Issue by waiwai212** [gperftools/gperftools#774]
I'm testing tcmalloc and found a problem that bothering me for several days. Please help me.

Compile environment：
centos 6.4 for x64
glibc-2.12-1.107.el6.x86_64
glibc-devel-2.12-1.107.el6.x86_64
glibc-common-2.12-1.107.el6.x86_64
libstdc++-4.4.7-3.el6.x86_64
libstdc++-devel-4.4.7-3.el6.x86_64
gcc-c++-4.4.7-3.el6.x86_64

I compiled libunwind-1.1 and lastest gperftools using default configure, and compiled my test source as followed.

g++ -g -o test test.cpp -pthread -lstdc++  /usr/local/lib/libtcmalloc.a /usr/local/lib/libunwind.a

[test_src]$ cat test.cpp 
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <dlfcn.h>
#include <gperftools/heap-profiler.h>
#include <gperftools/malloc_extension.h>

#define MEM_SPEC_MAX 1000000
void *g_mem[MEM_SPEC_MAX]={0};

int main()
{
   int i = 0;
   for(i = 1; i< MEM_SPEC_MAX; i++)
   {
      g_mem[i] = malloc(rand()%1024);
   }
   
   // step 1
   printf("press any key  to free the memory");
   getchar();
   
   for(i = 1; i < MEM_SPEC_MAX; i++)
   {
       free(g_mem[i]);
       g_mem[i] = NULL;
   }
   
   printf("the used memory has free sucess, the process sm will go to sleep ......\n");
   // step 2
   getchar();
   while(1)
   {
      sleep(10);
   }

   return 0;
}

When the process is stop at step 1 after lots of malloc() called, the physical memory of test is 529m(RES). It's ok.
[root@localhost ~]# top
top - 03:48:35 up 16 min,  5 users,  load average: 0.00, 0.02, 0.04
Tasks: 108 total,   1 running, 107 sleeping,   0 stopped,   0 zombie
Cpu0  :  0.0%us,  0.7%sy,  0.0%ni, 99.3%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   1015480k total,   640880k used,   374600k free,      724k buffers
Swap:        0k total,        0k used,        0k free,    11236k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 2147 root      20   0  544m 529m 1276 S  0.0 53.4   0:01.38 test
 
 
When the process is stop at step 2 after free() called, the physical memory of test is reduced to 52m(RES). It's ok too.
[root@localhost ~]# top
top - 03:48:55 up 17 min,  5 users,  load average: 0.00, 0.01, 0.04
Tasks: 108 total,   1 running, 107 sleeping,   0 stopped,   0 zombie
Cpu0  :  0.0%us,  2.4%sy,  0.0%ni, 97.6%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   1015480k total,   151980k used,   863500k free,      740k buffers
Swap:        0k total,        0k used,        0k free,    11232k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 2147 root      20   0  544m  52m 1276 S  0.0  5.3   0:02.04 test 
 
 
 
When the process is endless loop, the physical memory increase continuously. After 4 minutes the physical memory is 247m(RES).
[root@localhost ~]# top
top - 03:52:32 up 20 min,  5 users,  load average: 0.00, 0.00, 0.01
Tasks: 108 total,   1 running, 107 sleeping,   0 stopped,   0 zombie
Cpu0  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   1015480k total,   351452k used,   664028k free,      780k buffers
Swap:        0k total,        0k used,        0k free,    11240k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 2147 root      20   0  544m 247m 1276 S  0.0 24.9   0:02.04 test 
 

That bother me, why the physical memory increase continuously but the process do nothing.

**Comment by waiwai212** [comment]
PS：
When I disable THP the problem is resolved, but I don't know why.
# echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled
# echo never > /sys/kernel/mm/redhat_transparent_hugepage/defrag

**Comment by alk** [comment]
Hi. BTW github has extensive documentation on their markdown flavor which allows you to format source code is readable way.

**Comment by alk** [comment]
Try capturing /proc/<pid>/smaps and /proc/meminfo while you're seeing this increase. It seems to be related to rhel-6-specific transparent hugepages implementation.

**Comment by alk** [comment]
Closing issue as there are no evidence of leak of any kind.
