### ISSUE TITLE
CPUPROFILE_FREQUENCY=1 is illegal

### ISSUE THREAD

**Issue by jonashaag** [gperftools/gperftools#777]
[Here](https://github.com/gperftools/gperftools/blob/5ce42e535d6b3bf6c5e41ceb9cf876a70a7e3318/src/profile-handler.cc#L496) the `setitimer` usec argument is calculated using `CPUPROFILE_FREQUENCY/1,000,000`. However, it must be in range [0, 1,000,000).

`CPUPROFILE_FREQUENCY` should either be an error or the second `setitimer` field (`tv_sec`) should be used to additionally represent seconds.

**Comment by alk** [comment]
Thanks a lot for pointing this out.

**Comment by hkimura** [comment]
Hi,
I have been using this bug as a feature to completely disable gperftools dynamically.
I remember we discussed how setitimer in a large NUMA machine could hurt performance even when the program does not enable gperftools at all. I'm all for fixing the bug, but could you provide an alternative way of completely disabling the setitimer in library loading? Such as a new env variable?

**Comment by alk** [comment]
Hi, Hideaki. Simply not enabling CPUPROFILE should be enough now. I.e. after https://github.com/gperftools/gperftools/pull/762 is merged.

**Comment by hkimura** [comment]
That's nice. Sorry didn't know about #762 already addressing it.
Thanks!
