### ISSUE TITLE
Seg fault seen when running gRPC C++ tests under profiler

### ISSUE THREAD

**Issue by vjpai** [gperftools/gperftools#778]
Hello there,
When debugging a lingering segv-flake in gRPC C++ tests, we found that our stack traces had the profiler near the top. Disabling the profiler allowed the test to pass successfully and consistently. These are tests run on our gRPC Jenkins testing infrastructure (GCE, x86-64, 16 core, Ubuntu 15.10, gcc-5.2; I can provide other information as needed). Does this look like the known problems regarding x86-64 stack unwinding? Is there a way to bypass or minimize this problem? Here's two stack traces attached.

Thanks for your help!

[bt1.txt](https://github.com/gperftools/gperftools/files/168060/bt1.txt)
[bt2.txt](https://github.com/gperftools/gperftools/files/168061/bt2.txt)

**Comment by alk** [comment]
Thanks for reporting this issue. Under assumption that libunwind is getting confused by lack of unwind info in memcpy_chk function I've created small program to try to reproduce this case.

```
#define _FORTIFY_SOURCE 3
#include <stdlib.h>
#include <sys/types.h>
#include <string.h>

void iteration(void *a, void *b, int l)
{
	char buf[4];
	memset(buf, 0, sizeof(buf));
	memcpy(buf, b, l);
	memcpy(a, buf, 4);
}

typedef void (*iteration_ptr)(void *, void *, int);

volatile iteration_ptr ip = iteration;

int main(void)
{
	int a = 0, b;
	for (long long i = 1LL << 32; i > 0; i--) {
		ip(&a, &b, 4);
		ip(&b, &a, 4);
	}
	return 0;
}
```

It indeed exercises same functions that are present at the top of crash in your case. But neither on my Debian unstable, nor on freshly installed ubuntu 15.10 docker image, I'm not able to reproduce the problem.

Is it possible that your testing infrastructure wasn't updated to latest glibc and/or libunwind? If so then try updating them to latest versions. Maybe ubuntu folks already fixed this crash.

If it still doesn't work, then I think I'll need more detailed instructions on how to reproduce this crash.

**Comment by vjpai** [comment]
I'll try to upgrade all the libraries and see if the problem goes away. Thanks for the input; I'll follow up soon.

**Comment by vjpai** [comment]
I'll close this up for now. We are upgrading our testing infrastructure and will report back when our upgrades are complete.
