### ISSUE TITLE
some strange problem

### ISSUE THREAD

**Issue by nuptxxp** [gperftools/gperftools#782]
1.  when i use pprof display a heap profile, some strange info puzzles me ,
like that:
addr2line: invalid option -- i
Usage: addr2line [option(s)] [addr(s)]
 Convert addresses into line number/file name pairs.
 If no addresses are specified on the command line, they will be read from stdin
 The options are:
  -b --target=<bfdname>  Set the binary file format
  -e --exe=<executable>  Set the input file name (default is a.out)
  -s --basenames         Strip directory names
  -f --functions         Show function names
  -C --demangle[={none,auto,gnu,lucid,arm,hp,edg,gnu-v3,java,gnat,compaq}]
                         Demangle function names
     --demangler=<dso:function>
                         Set dso and demangler function
  -h --help              Display this information
  -v --version           Display the program's version

2.  i see https://google-perftools.googlecode.com/svn/trunk/doc/heapprofile.html, 
i use pprof --base=/tmp/profile.0004.heap gfs_master /tmp/profile.0100.heap
but it doesn't work

pls help,thx

**Comment by alk** [comment]
You're likely using super-old version of addr2line. What kind of OS you're using ? And what addr2line --version says?

**Comment by nuptxxp** [comment]
yes, it's too old to run, now no errors when i use pprof,
the second question, could you tell me why?
thx

**Comment by alk** [comment]
Why what ? Can you please elaborate ?

**Comment by nuptxxp** [comment]
ah, i found why, some problem caused by myself
thx anyway ^_^

**Comment by AngelHeart** [comment]
I have the same problem.
What did you do to fix this?
And yes, I'm using an old linux too.
