### ISSUE TITLE
Incorrect memory size from Heap Profiler

### ISSUE THREAD

**Issue by wengan-li** [gperftools/gperftools#783]
Hi there,

I have a very strange problem when I profiling Xerces-C++ parsing a hugh XML document (~1.6 GB). pprof report it took 171,361,115,084 (~159.59 GB) bytes to process.
But it is 20,226,330,624 (~18.83 GB) if I just simply get the usage from virtual memory.
Also I am monitoring by using 'top' command at the same time and I am sure that the 'top' is much more correct.
It will be a acceptable value if I parsing a smaller document.
Am I mess up with Heap Profiler ?

My platform
> VMware ESXI Version 5.1.0 Build 799733
> Intel Xeon CPU E5-2620 2.00GHz x 2
> 180 GB RAM
> Ubuntu 14.04.3 LTS (Kernel: 3.13.0-46-generic)
> GCC 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

Tools
> Xerces-C++ 3.1.2
> gperftools-2.5
> libunwind-1.2-rc1

GCC flag for compiling tools
> -Ofast

Thx.

**Comment by alk** [comment]
Hi. Heap profiler actually counts aggregate malloc sizes. I.e. not how much allocations are in use but sum of all malloc requests.

With that I'm closing the ticket. Feel free to reopen if you think something is broken.

**Comment by wengan-li** [comment]
I understand Heap profiler focus on the malloc sizes.
So I am trying to limit the range of profiling to get a approximation size of in use memory which use for parsing process.

In some cases (like documents with size of 2KB, 8KB , even 50KB), the virtual memory was reported it took zero byte (or 4096 byte if I forced it to print out some message) for parsing. It is an unacceptable value.
Therefore the approximate size from Heap profiler is much more acceptable than the virtual memory.

So you think it is possible that Xerces was malloced ~159.59 GB for processing in that case, even it was keeping the size approximate ~18.83 GB ? Because I am thinking if it malloc so much memory, I should able to see some obvious consuming in 'top'. Or it can do it without any sign ?

Then any option I can use to have a approximation size of in use memory ?
I am thinking is it possible to use '--inuse_space' option and dump the information before-and-after the parsing process, but not after the exit of program ?

**Comment by wengan-li** [comment]
After a thought and experiment, I need to say, heap profiler is really able to profiling for getting an approximation size of in-use memory. And it works well than I thought.

The concept is focus on how to play with '--base' and HeapProfilerDump.
In my case of profiling the memory representation of a parser, the code should looks like this:
```
function profiling_parsing_memory(xml_path)
{
  HeapProfilerStart(...);

  // Dump heap information BEFORE parsing, e.g. 'profile.0010.heap'
  HeapProfilerDump(...);     

  someTool.parse(xml_path);

  // Dump heap information AFTER parsing, e.g. 'profile.0030.heap'
  HeapProfilerDump(...);     

  HeapProfilerStop();
}
```

And then use this command to generate the report:
```
pprof --text --base=profile.0010.heap your_program
  --inuse_space --show_bytes profile.0030.heap
```
The output shows the approximation size of in-use memory which is used for the memory representation to store any parsed data.

I say it is an approximation size, because I can't guarantee this value don't contain any memory which is not used for the representation. This is depend on which parser is used. So in theory, the size reported by pprof should be the in-use memory for holding the memory representation (In my case, it is a DOM tree).

And the value is quite acceptable. Here is some memory usage from my cases which profiling from virtual memory and heap profiler. And the unit of values is byte.

| Dataset | Data Size | Virtual Memory | Heap Profiler |
| :---: | :---: | :---: | :---: |
| address.xml | 15,608 | 223,408,128 | 221,108,794 | 
| standard.xml | 113,794 | 922,910,720 | 989,211,483 | 
| psd7003.xml | 700,052 | 9,303,494,656 | 9,867,166,829 | 
| dblp.xml | 1,579,613 | 20,226,330,624 | 24,445,881,023 |

Although I still don't understand the reason of 171,361,115,084 (~159.59 GB), but still I had solve my problem.

**Comment by alk** [comment]
Hi again.

heap profiler is showing you _aggregate_ size of malloced memory.

If you need to know what is currently live and where it was allocated, you
should look at heap sampling feature. It is actually much cheaper. For
example of how you can use it, see sampling_test.cc and it's use of
GetHeapSample.

**Comment by wengan-li** [comment]
Hi,

Thank you for your suggestion, and I have taken a look the 'sampling_test.cc'.
It is really much better way to have the information that I want.

But after some of my test, one of my testing parser (RapidXML) is unable to fit in this feature. It seem the heap profiler can't 'catch' the information of the function ( like doParsing() ) I want. This cause the pporf unable to show in the report. The function doParsing() is like this:
```
function doParsing
{
  GetHeapSample( ... )
  GetHeapGrowthStacks( ... )

  // parser_do_parsing()

  GetHeapSample( ... )
  GetHeapGrowthStacks( ... )
}
```

I found out doParsing() will show in report if parse a document with size >~ 68 KB. And it should use about 199,778 byte if using my method above to get it.

I have turn off the optimization in compiler. And I use 'TCMALLOC_SAMPLE_PARAMETER=8' try to get anything if possible.

I don't know how to growth the heap stack and still get the value of in-use memory of parser correctly. I have tried this way with option '--base'. But still unable to have the in-use memory of the parser.
```
function doParsing
{
  malloc( 5MB )

  GetHeapSample( ... )
  GetHeapGrowthStacks( ... )

  // parser_do_parsing()

  GetHeapSample( ... )
  GetHeapGrowthStacks( ... )

  free()
}
```

Did I do anything wrong again ?

**Comment by alk** [comment]
There seems to be continued misunderstanding about what you're trying to achieve.

heap sampling will tell you roughly which objects are in use by program at the time when sample is taken. And heap profiler will tell you which pieces of code allocated (and possibly freed) how much memory. The numbers from those two methods will differ greatly.
