### ISSUE TITLE
Pprof does not recognize symbols from libraries loaded with dlopen

### ISSUE THREAD

**Issue by jperalta-i** [gperftools/gperftools#787]
Hi,
I have an application that loads with DLopen an external library that I want to profile with libprofiler. However, the output in pprof only shows addresses, which I cannot correlate back with the source code and/or names of functions. What am I doing wrong? Is this a limitation?
For functions coming from normally linked libraries, the symbols are there.

Example:
      51   4.6%   4.6%       51   4.6% 0x00002aaaace757b2
      32   2.9%   7.5%       32   2.9% 0x00002aaaace7bf14
      29   2.6%  10.1%       29   2.6% 0x00002aaaac6625a8
      23   2.1%  12.2%       23   2.1% 0x00002aaaace7bf1b
      22   2.0%  14.1%       22   2.0% 0x00002aaaace74083
      21   1.9%  16.0%       21   1.9% __GI_memcpy
      20   1.8%  17.8%       36   3.2% __GI___libc_longjmp
      19   1.7%  19.5%       19   1.7% 0x00002aaaace7bf0b
      17   1.5%  21.1%       17   1.5% 0x00002aaaace74086
      16   1.4%  22.5%       16   1.4% 0x00002aaaace83ce3
      15   1.4%  23.9%       15   1.4% 0x00002aaaac6624f5
      15   1.4%  25.2%       15   1.4% __GI_memcmp
      15   1.4%  26.6%       16   1.4% _int_malloc

Thank you in advance.

**Comment by alk** [comment]
Yes. You're hitting fundamental limitation of pprof format (both legacy and protobuf).

Your best chance to get decent output is to either:

a) drop dlclose in your codle

b) finish profiling before unloading your dynamically loadable modules

I'm cc-ing current pprof maintainer in case he want's to chime in. @rauls5382

**Comment by alk** [comment]
I guess it is time to close this as wont fix. As noted above it is fundamental limitation of both our profiling formats that it is not possible to represent unloading of modules.

Your options are:

a) don't not dlclose anything

b) switch to perf (which format is just stream of events, both samples and modules loading/unloading events; so it should be capable of supporting modules)
