### ISSUE TITLE
pprof only displays addresses on OS X

### ISSUE THREAD

**Issue by tenderlove** [gperftools/gperftools#791]
Hi,

I'm trying to profile Ruby internals using gperftools on OS X (El Capitan), but pprof is only displaying addresses rather than function names.  I installed gperftools via homebrew, and I'm using version 2.4.

pprof output looks like this:

```
[aaron@TC ruby (anon_ic)]$ pprof ./ruby out.prof --text
Using local file ./ruby.
Using local file out.prof.
Total: 166 samples
      52  31.3%  31.3%       52  31.3% 0x00000001041595af
       6   3.6%  34.9%        6   3.6% 0x00000001041595ab
       3   1.8%  36.7%        3   1.8% 0x000000010415859a
       3   1.8%  38.6%        3   1.8% 0x00000001041585a3
       3   1.8%  40.4%        3   1.8% 0x0000000104159fab
       3   1.8%  42.2%        3   1.8% 0x0000000104177e9c
       3   1.8%  44.0%        3   1.8% 0x00007fff94982343
       2   1.2%  45.2%        2   1.2% 0x00000001041594b0
```

I'm not sure how to debug this, and I'd appreciate any help I can get.  Thank you!

**Comment by tenderlove** [comment]
I forgot to mention, I'm manually enabling and disabling profiling via `ProfilerStart` and `ProfilerStop`, but I still get addresses even when I use the `CPUPROFILE` environment variable.

Also, strangely I get one function name at the end of the output:

```
       0   0.0% 100.0%        1  11.1% 0x00007fc35388dbef
       0   0.0% 100.0%        1  11.1% 0x00007fc35399169f
       0   0.0% 100.0%        1  11.1% 0x00007fff5ddb044f
       0   0.0% 100.0%        7  77.8% 0x00007fff89bdf5ac
       0   0.0% 100.0%        7  77.8% __mh_execute_header
```

**Comment by alk** [comment]
Hi Aaron.

Try building very latest version. Some osx-specific fix was merged
recently. Your another option is to try official pprof tool from
github.com/google/pprof. We're deprecating perl pprof tool in gperftools.

**Comment by tenderlove** [comment]
@alk thanks!  I'm having some build problems on master:

```
[aaron@TC gperftools (master)]$ make
/bin/sh ./libtool  --tag=CXX   --mode=link g++ -DNO_TCMALLOC_SAMPLES -D_THREAD_SAFE  -DNDEBUG -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation   -g -O2 -version-info 7:0:3 -no-undefined   -o libtcmalloc_minimal.la -rpath /usr/local/Cellar/gperftools/master/lib src/libtcmalloc_minimal_la-tcmalloc.lo    libtcmalloc_minimal_internal.la 
libtool: link: g++ -dynamiclib  -o .libs/libtcmalloc_minimal.4.dylib  src/.libs/libtcmalloc_minimal_la-tcmalloc.o   -Wl,-force_load,./.libs/libtcmalloc_minimal_internal.a   -g -O2   -install_name  /usr/local/Cellar/gperftools/master/lib/libtcmalloc_minimal.4.dylib -compatibility_version 8 -current_version 8.0 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "operator delete(void*, unsigned long)", referenced from:
      TCMallocImplementation::~TCMallocImplementation() in libtcmalloc_minimal_la-tcmalloc.o
      SbrkSysAllocator::~SbrkSysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-system-alloc.o)
      MmapSysAllocator::~MmapSysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-system-alloc.o)
      DevMemSysAllocator::~DevMemSysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-system-alloc.o)
      DefaultSysAllocator::~DefaultSysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-system-alloc.o)
      SysAllocator::~SysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-malloc_extension.o)
      MallocExtension::~MallocExtension() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-malloc_extension.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Searching leads me to [possibly an llvm bug](https://llvm.org/bugs/show_bug.cgi?id=22951), but it's hard for me to believe.  Have you seen this error before?

I just build using autogen.sh and `./configure --disable-dependency-tracking --prefix=/usr/local/Cellar/gperftools/master`.

Thanks for the help!

**Comment by alk** [comment]
I haven't seen such issues. But I am not apple person. So thanks for
reporting it.

The bug you linked to indeed seems related.

This is something to do with sized delete (which we do support, but
disabled by default). So try passing --enable-sized-delete to configure.

Also for your specific case you simply need to copy pprof out of recent
source.

**Comment by tenderlove** [comment]
Hi @alk!  Thanks for the response.  I couldn't get `--enable-sized-delete` or `--disable-sized-delete` to have any impact on the build.  Homebrew has a formula for installing gperftools on OS X, so I looked at [what they do](https://raw.githubusercontent.com/Homebrew/formula-patches/master/gperftools/revert-sized-delete-aliases.patch), which is essentially to revert 782165fa7f2c49d6a67c2415626a1f215cc21ac2.  That's probably not The Right Solution™, but it does get me past the build failures.  Thanks!

**Comment by alk** [comment]
Thanks Aaron! Indeed there seem to be some issues w.r.t. sized delete and later clangen. Which I'll address shortly.

Can we close original ticket now? I.e. I am expecting upstream (golang-based) pprof to fix your issue. Let me know if that is still not the case.

**Comment by ben-albrecht** [comment]
Hello @alk, I am experiencing a similar problem on OS X with a gperftools version compiled from master ([eb474c9 ](https://github.com/gperftools/gperftools/commit/eb474c995eadef3edb47bc081f09693228832794)). I'm trying to profile a Chapel program, but am observing the address bug for simple C programs as well.

Would appreciate any tips on how to figure this out.

**Comment by rauls5382** [comment]
FWIW I checked in some fixes into the standalone [pprof](http://github.com/google/pprof) to deal with symbolization on OS X. If you still see symbolization failures using that version of pprof please open an issue against pprof.

**Comment by alk** [comment]
Thanks, Raul.

It seems to be time to close the ticket. I.e. perl pprof is deprecated and standalone pprof is reported to work on OSX.
