### ISSUE TITLE
GCCs atomic ops should be automatically preferred over hand-rolled per-architecture ones

### ISSUE THREAD

**Issue by acmorrow** [gperftools/gperftools#797]
In src/base/atomicops.h, there is an #ifdef ladder for including the backing implementation for atomics. There are two problems with it:
- The GCC atomics are only preferred if you both manually request them, by explicitly defining TCMALLOC_PREFER_GCC_ATOMICS and have a new enough compiler. There is almost no reason to prefer the hand-rolled versions if the GCC atomics are available. The logic here should be reversed to use the GCC atomics by default if available based on a compiler version check, and fall back to per-architecture implementations only if a new enough GCC is not available. There could be a flag like TCMALLOC_NO_GCC_ATOMICS to force that choice if needed.
- The other problem is that even if you define TCMALL_PREFER_GCC_ATOMICS, it doesn't work with clang, since clang identifies as GCC 4.2, and the GCC version check fails. The check should be updated to account for clang as well.

I also have a question about TCMALLOC_PREFER_GCC_ATOMICS. Is it necessary only when building tcmalloc? Or is it required when including tcmalloc headers as well? Another way of putting the question: is the atomicops.h header part of the public interface of tcmalloc?

**Comment by acmorrow** [comment]
@alk - Any thoughts on this? I'm happy to put together a PR for it if you think it makes sense.

**Comment by alk** [comment]
He Andrew. atomicops.h is not public interface.

My only tiny bit of concern about this idea is that in past I've heard that some versions of gcc had quite crappy atopic ops implementation. But perhaps this is not concern anymore.

IMHO existing atomic ops work and there is no pressing need to change them.

**Comment by acmorrow** [comment]
Thanks, for clarifying about atomicops being internal only. That was my belief, but I wanted to be sure.

I think your concern about old GCC is fair, but I would like to see TCMALLOC_PREFER_GCC_ATOMICS work correctly with clang, which it currently doesn't.

**Comment by alk** [comment]
Interesting. Thanks for letting me know. I was not aware that clang builds fail on TCMALLOC_PREFER_GCC_ATOMICS.

**Comment by acmorrow** [comment]
@alk - Well, it doesn't exactly fail to build when using clang with TCMALLOC_PREFER_GCC_ATOMICS. The issue is that TCMALLOC_PREFER_GCC_ATOMICS isn't honored when using clang, because the GCC version check sees clang as GCC 4.2, so it ignores the request to use the GCC atomics. So it still builds, but just not with the atomics you intended.

**Comment by acmorrow** [comment]
@alk - Thanks for adding the fixup for clang, that is much appreciated. I still think there is a lot of value in standardizing on the GCC __atomic implementation when available. Those interfaces are direct analogues of the standard atomic operation APIs of C11 and C++11, and thus are aligned with the memory model of these languages going forward. By making this implementation the default, it ensures that the semantics of the gperftools atomics API in the `subtle` namespace can be correctly expressed given the semantics of the language memory model. It also allows compilers that aware of the specific target to potentially capitalize on new instructions as newer ISAs are rolled out, without the difficulty of maintaining several separate (and possibly subtly broken) hand-rolled assembly implementations. Finally, it is possible that the hand-rolled versions actually provide *stronger* ordering guarantees as implemented than are strictly required by the claimed semantics of the functions in `subtle`, and thus could mask real concurrency bugs that using the intended weaker ordering guarantees might reveal. While I generally agree with the principle of not changing things that are known to work, I think in this case it is important to change over, since it is too important to know if the GCC atomics *don't* actually work, and the only way to find that out is by making them the default and addressing any fallout.

**Comment by rauls5382** [comment]
If you're going to change the default implementation, wouldn't it be better to use the standard C11/C++11 atomics? I expect those to be the preferred solution for atomics moving forward.

**Comment by acmorrow** [comment]
@rauls5382 - Yes, but I don't think gperftools should be limited to C++11. It wouldn't be a problem for my usage, but probably would be for others.

I think the best order would be:
- C++11 std::atomic API, if available
- GCC/clang __atomic API, if available (or Win32 API/intrinsics)
- Per-architecture hand-rolled assembly, to eventually be phased out.

So, I'd still start making the __atomic API implementation the default, as that implementation is already written. A C++11 option could be added later.

**Comment by rauls5382** [comment]
I agree with your proposed order, but I think that if defaults are to be changed, it is better to do that only once.

**Comment by alk** [comment]
On Thu, Sep 22, 2016 at 8:25 AM, Andrew C. Morrow <notifications@github.com>
wrote:

> @rauls5382 <https://github.com/rauls5382> - Yes, but I don't think
> gperftools should be limited to C++11. It wouldn't be a problem for my
> usage, but probably would be for others.
>

I was thinking about c++11 recently. As long as we support rhel6 and, say,
visual studio 2013, that would be fine. Looks like rhel6 ships gcc 4.4 with
only few bits of c++11: https://gcc.gnu.org/gcc-4.4/cxx0x_status.html
atomics is mentioned as supported. But we'll need to check if this is
decent implementation.

As far as atomics, my thinking is not touching this stuff unless we need
(which doesn't seem to be the case) and until c++11 is widespread and all
implementations are great.

**Comment by acmorrow** [comment]
I think the C++11 part of this discussion is a bit of a misdirection. Mostly, I don't care whether the implementation is C++11 atomics or GCC __atomic. Either is fine, really, though C++11 is probably better. What is much more important though is that gperftools eventually migrate away from hand-rolled assembly over to an implementation that is aligned with the C11/C++11 memory model.

The `PREFER` feature is a good start. I also see the merit to the argument that there isn't anything forcing a change, right now, and I understand taking the conservative approach for something like a memory allocator. But I also think there is merit to getting more exposure and testing for the GCC __atomics based implementations. If compiler quality-of-implementation is a concern, how about a compromise: only prefer the __atomics implementation by default if using the as-of-today newest stable versions of GCC or clang (GCC 6.2 or clang 3.9)?

**Comment by alk** [comment]
Looking at this some more, looks like red hat is shipping later gcc as part of their "devtoolset" software collection that works on centos/rhel 6. And interestingly, binaries compiled with such gcc (even 5.2) work on stock centos 6. So, looks like switching to c++ 11 might be possible.

**Comment by alk** [comment]
we now run with c++11 atomics exclusively.
