### ISSUE TITLE
Using heap checker with external memory pool

### ISSUE THREAD

**Issue by unaiur** [gperftools/gperftools#803]
I'm trying to use the gperftools heap checker with DPDK packet buffers.

DPDK is an library that allocates packet buffers in an specially mapped memory that a network card can access directly using DMA. Therefore, I can't use tcmalloc to allocate them.

I'm trying to invoke MallocHook::InvokeNewHook & MallocHook::InvokeDeleteHook when allocating and releasing packet buffers but they are undefined inline functions. Also, the slow variants are private members of MallocHook class.

How this API is supposed to work? Can you make public the Slow variants?

**Comment by alk** [comment]
By design of this api, you're not supposed to call malloc hooks yourself. What are you trying to achieve?

**Comment by alk** [comment]
Actually looking at ticket subject, it looks like you want heap checker to "check" your dma-ful memory allocator. But it is not capable of that.

What exactly you want it to check?

I think you probably want to look at asan api instead. I.e. so that you can integrate your custom malloc with it.

**Comment by unaiur** [comment]
Yes. I want to track memory allocations from a custom allocator.

**Comment by alk** [comment]
Hm. What kind of tracking is that? Can you please elaborate ? Have you looked at asan ?
