### ISSUE TITLE
[QNX6] Memory is never return to the system.

### ISSUE THREAD

**Issue by stayprivate** [gperftools/gperftools#805]
I'm trying gperftools on QNX6 and pretty much every is ok but the large_heap_fragmentation unittest is a fail.  Of importance can't use sbrk, got to use mmap, which is fine in principle.   My investigation shows that munmap is never invoked, hence memory is never return to the OS.  In fact in the code I could not find a reference to were this would happen.

Comments in other issues suggest that this is by design, but that seems odd.

Any pointers ?

**Comment by alk** [comment]
Code checks if MADV_DONTNEED or MADV_FREE is defined. And it is possible that QNX simply does not have them.

I.e. tcmalloc can only return memory back to OS via MADV_DONTNEED or MADV_FREE.

**Comment by alk** [comment]
And btw thanks a lot for working in more porting. I am looking forward seeing your patch.

**Comment by virtualritz** [comment]
Is there an update on this?
I.e. do we know if it is possible to release memory on QNX via either MADV_DONTNEED or MADV_FREE?

**Comment by alk** [comment]
You can now build with -DFREE_MMAP_PROT_NONE and it's work. See https://github.com/gperftools/gperftools/commit/003775aa816cb3fe01215455825245089d423a7c
