### ISSUE TITLE
Changing the default alignment of tcmalloc to 64byte

### ISSUE THREAD

**Issue by dormaayan** [gperftools/gperftools#808]
We try to change the default alignment of tcmalloc to 32/64 byte alignment.
We tried a naive implementation in which we simply call to tc_memalign instead from malloc.
But, we discovered that due to the fragmentation restrictions on tcmalloc, on sizes larger than 128, the library return to the original alignment (16 byte) , at this code : 

 int AlignmentForSize(size_t size) {
      int alignment = kAlignment;
      if (size > kMaxSize) {
        // Cap alignment at kPageSize for large sizes.
        alignment = kPageSize;
      } **else if (size >= 128) {
        // Space wasted due to alignment is at most 1/8, i.e., 12.5%.
        alignment = (1 << LgFloor(size)) / 8;
      }** else if (size >= 16) {
        // We need an alignment of at least 16 bytes to satisfy
        // requirements for some SSE types.
        alignment = 16;
      }
      // Maximum alignment allowed is page size alignment.
      if (alignment > kPageSize) {
        alignment = kPageSize;
      }
      CHECK_CONDITION(size < 16 || alignment >= 16);
      CHECK_CONDITION((alignment & (alignment - 1)) == 0);
      return alignment;
    }

we tried to remove that condition but we get much more problems, we also tried to change the following parameter : kAlignment and kABaseClasses but we face more problem.

Do you see any convenient way to change the alignment of the library ?

**Comment by alk** [comment]
Hi. There are indeed several places that depend on exact number of size classes etc.

But it should be still be possible to hack everything for 64 bytes alignment. I.e. just keeping hacking until it works:)

**Comment by alk** [comment]
Closing as stale. Please reopen if/when you have anything specific to add.
