### ISSUE TITLE
Segmentation fault in tcmalloc - calloc

### ISSUE THREAD

**Issue by mesibo** [gperftools/gperftools#810]
We often get Segmentation fault after program ran for couple of hours. Below is the backtrace.

Do let me know if you need more info. 
Thanks

Program terminated with signal 11, Segmentation fault.
#0  0x00007f3097010e67 in tcmalloc::CentralFreeList::FetchFromOneSpans(int, void**, void**) () from /lib64/libtcmalloc.so.4
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-19.2.el7.x86_64 glibc-2.17-55.el7.x86_64 gperftools-libs-2.4-7.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.11.3-49.el7.x86_64 libcom_err-1.42.9-4.el7.x86_64 libcurl-7.29.0-19.el7.x86_64 libgcc-4.8.2-16.el7.x86_64 libidn-1.28-3.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 libssh2-1.4.3-8.el7.x86_64 libstdc++-4.8.2-16.el7.x86_64 libunwind-1.1-5.el7_2.2.x86_64 mariadb-libs-5.5.37-1.el7_0.x86_64 nspr-4.10.2-4.el7.x86_64 nss-3.15.4-6.el7.x86_64 nss-softokn-freebl-3.15.4-2.el7.x86_64 nss-util-3.15.4-2.el7.x86_64 openldap-2.4.39-3.el7.x86_64 openssl-libs-1.0.1e-34.el7_0.3.x86_64 pcre-8.32-12.el7.x86_64 xz-libs-5.1.2-8alpha.el7.x86_64 zlib-1.2.7-13.el7.x86_64
(gdb) bt
#0  0x00007f3097010e67 in tcmalloc::CentralFreeList::FetchFromOneSpans(int, void**, void**) () from /lib64/libtcmalloc.so.4
#1  0x00007f309701112a in tcmalloc::CentralFreeList::FetchFromOneSpansSafe(int, void**, void**) () from /lib64/libtcmalloc.so.4
#2  0x00007f30970111dd in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
#3  0x00007f3097014235 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned long, unsigned long) () from /lib64/libtcmalloc.so.4
#4  0x00007f309702331b in tc_calloc () from /lib64/libtcmalloc.so.4
#5  0x00000000004290dd in tm_calloc_internal (size=128, nmemb=<optimized out>) at malloc.cpp:95
#6  tm_calloc (nmemb=<optimized out>, size=120) at malloc.cpp:102

tm_calloc__internal is just a wrapper around tc_calloc, following is the code
void* tm_calloc_internal(size_t nmemb, size_t size) {
#ifdef USE_TCMALLOC
        return tc_calloc(nmemb, size);
#else
        return scalable_calloc(nmemb, size);
#endif
}

**Comment by alk** [comment]
There are no known heap corruption bugs in gperftools. Bugs like that are usually bugs in the program. Have you tried running it under asan or something like that ?

**Comment by mesibo** [comment]
Possible, however we don't get this issue if we use regular malloc or scalable malloc. However this issue pops up when using tcmalloc and hence we think the problem lies in tcmalloc. Is there anything we can do to isolate the issue?

**Comment by mesibo** [comment]
Additionally, I have also rebuild code with asan and it also SEGV in tcmalloc. ASAN doesn't report any other issue prior to it. 

ASAN:SIGSEGV
=================================================================
==28930== ERROR: AddressSanitizer: SEGV on unknown address 0x00000078aa55 (pc 0x7ff663da2e67 sp 0x7ff6662378d0 bp 0x00000078aa55 T16777215)
AddressSanitizer can not provide additional info.
    #0 0x7ff663da2e66 (/usr/lib64/libtcmalloc.so.4.2.6+0x23e66)
    #1 0x7ff663da3129 (/usr/lib64/libtcmalloc.so.4.2.6+0x24129)
    #2 0x7ff663da31dc (/usr/lib64/libtcmalloc.so.4.2.6+0x241dc)
    #3 0x7ff663da6234 (/usr/lib64/libtcmalloc.so.4.2.6+0x27234)
    #4 0x7ff663db531a (/usr/lib64/libtcmalloc.so.4.2.6+0x3631a)
    #5 0x4370ac (/mycore/bin/cm+0x4370ac)
    #6 0x40a17a (/mycore/bin/cm+0x40a17a)
    #7 0x411877 (/mycore/bin/cm+0x411877)
    #8 0x416829 (/mycore/bin/cm+0x416829)
    #9 0x41740d (/mycore/bin/cm+0x41740d)
    #10 0x417aa7 (/mycore/bin/cm+0x417aa7)
    #11 0x427f3a (/mycore/bin/cm+0x427f3a)
    #12 0x7ff665f78df2 (/usr/lib64/libpthread-2.17.so+0x7df2)
    #13 0x7ff65fec13dc (/usr/lib64/libc-2.17.so+0xf63dc)

**Comment by alk** [comment]
Looks like you haven't built tcmalloc with asan support which is why it is unable to help. But in general asan and tcmalloc are not supposed to be used together. When building with asan you're supposed to use default malloc (which asan takes over).

And yes it is possible that buggy program crashes with one memory allocator and works with another. I.e. since addresses that are handed out by different mallocs are different.
