### ISSUE TITLE
Segmentation fault in SLL_Pop

### ISSUE THREAD

**Issue by oathupdate** [gperftools/gperftools#811]
#0  SLL_Pop (size=32) at src/linked_list.h:59
#1  Pop (size=32) at src/thread_cache.h:212
#2  Allocate (size=32) at src/thread_cache.h:371
#3  do_malloc_small (size=32) at src/tcmalloc.cc:1193
#4  do_malloc (size=32) at src/tcmalloc.cc:1200
#5  cpp_alloc (size=32) at src/tcmalloc.cc:1543
#6  tc_new_nothrow (size=32) at src/tcmalloc.cc:1690
#7  0x00007f4062f818e8 in RSHTTPPaser::VerifyHttpResponse (this=0x7f405ab45102, pBuffer=
    0x5ed2000 "HTTP/1.1 200 OK\r\nServer: Apache-Coyote/1.1\r\nContent-Type: text/html;charset=utf-8\r\nTransfer-Encoding: chunked\r\nDate: Mon, 18 Jul 2016 01:18:40 GMT\r\n\r\n2000\r\n\r\n<style type=\"text/css\">\r\n<!--\r\na {\r\n\tfont-"..., BufferSize=<value optimized out>, pProcessed=0x7f405ab452d8, bEndSession=152, pExpect=0x7f405ab451b8) at http_parser.cpp:798
#8  0x00007f4062f8a23b in RSWebConnection::ProcessResp (this=0x4954000, pBuf=
    0x2f86000 "\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t"..., BufSize=9000, pSockAPI=0x241c1b0, pH=1467979919, psslH=<value optimized out>) at session.cpp:1926
#9  0x00007f4062f94c62 in RSRProxy::WebSessionSocketCallback (pSockAPI=0x241c1b0, pMsg=0x7f405ab45840) at rproxy.cpp:2112
#10 0x00007f4063e268ce in SocketSession::SendSockMessage (this=0x2a59b20, msg_type=<value optimized out>, data=
    0x2f86000 "\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t"..., data_size=9000) at sock_Engine3.cpp:1033
#11 0x00007f4063e2e003 in SocketSession::OnRecv (this=0x2a59b20, bRead=<value optimized out>) at sock_Engine3.cpp:1349
#12 0x00007f4063e33c2b in SocketWorkThread::Execute (this=0x24bd340) at sock_Engine3.cpp:2228
#13 0x00007f4068e7d6de in util_Thread::ThreadProc (lpParameter=0x24bd358) at util_thread.cpp:219
#14 0x00007f406882caa1 in start_thread () from /lib64/libpthread.so.0
#15 0x00007f40678c5aad in clone () from /lib64/libc.so.6

**Comment by oathupdate** [comment]
version:  gperftools-2.4.90
OS: Centos 6.4
@alk

**Comment by alk** [comment]
Have you tried running your program under thread-sanitizer, address-sanitizer and/or debug malloc ? So far I have no reason to believe that this is caused by program bug(s). Such as double free or writing to freed memory , etc.

**Comment by oathupdate** [comment]
@alk 
I thought isn`t related to  double free or writing to freed memory
because the core dump code is 
PRS_WEB_CHUNK p = new RS_WEB_CHUNK;

**Comment by alk** [comment]
Any of them may damage the heap, so that one of subsequent operations (such as malloc) crashes.

**Comment by oathupdate** [comment]
@alk thanks
