### ISSUE TITLE
how to filter the system functions ?

### ISSUE THREAD

**Issue by chuanhuayang** [gperftools/gperftools#814]
Hi, alk
When i use the pprof tool to analysis the dump file of cpu-profiler,heap-checker,heap-profiler, there are too many system functions there so that i can't fouce on my own bussiness function.
I know pprof have some options like -focus, -ignore, but it just can ignore one function once.
so ,i want to know how to filter system function convenient？

**Comment by rauls5382** [comment]
The pprof -hide and -show options allow you to restrict which functions to include in the report.

If you can match the functions of interest with a regex (eg the substring foo) , pprof -show=foo should do.

**Comment by alk** [comment]
Thanks, Raul. Yes for this case you'll likely want --hide to drop unnecessary functions while keeping overall information intact.
