### ISSUE TITLE
Why the two test results on the same program of cpu-profiler are so different?

### ISSUE THREAD

**Issue by chuanhuayang** [gperftools/gperftools#816]
I have do two times tests on the same program using cpu-profiler，but the result of the percentage of some functions are very different，why?
because the percentage is obtain by the statistical result,so it should be stable, but not different so much

**Comment by alk** [comment]
There are two possibilities. One is that your program run is too short. And the other is that some thread's are sampled more often than other. See CPUPROFILE_PER_THREAD_TIMERS feature for that.

**Comment by chuanhuayang** [comment]
Thanks very much, By the way, I do not see the settings for this environment variable in the gperftools2.5 document. Where is the latest document?

**Comment by chuanhuayang** [comment]
I found the pprof tool in  gperftools2.5 download from github  doesn't support --show and -hide option，but these option appeared in the pprof project's document, is the pprof tool in gperftools is just a subset of the project pprof ?

**Comment by alk** [comment]
On Tue, Aug 16, 2016 at 1:26 AM, chuanhuayang <notifications@github.com>
wrote:

> I found the pprof tool in gperftools2.5 download from github doesn't
> support --show and -hide option，but these option appeared in the pprof
> project's document, is the pprof tool in gperftools is just a subset of the
> project pprof ?
>

pprof is gperftools is old deprecated perl-based script. pprof in
github.com/google/pprof is new all-round-awesome implementation.

**Comment by alk** [comment]
Closing the ticket then.
