### ISSUE TITLE
coredump when delete resource

### ISSUE THREAD

**Issue by cloudusers** [gperftools/gperftools#818]
run sometimes will coredump when ctrl+C

**Comment by cloudusers** [comment]
[core_test.cpp.txt](https://github.com/gperftools/gperftools/files/421680/core_test.cpp.txt)
[PackageExtractor.cpp.txt](https://github.com/gperftools/gperftools/files/421681/PackageExtractor.cpp.txt)
[PackageExtractor.h.txt](https://github.com/gperftools/gperftools/files/421682/PackageExtractor.h.txt)
[singleton.h.txt](https://github.com/gperftools/gperftools/files/421679/singleton.h.txt)

![stack](https://cloud.githubusercontent.com/assets/16657639/17723191/bc29c9b2-646a-11e6-845d-54ce55be0029.jpg)

**Comment by cloudusers** [comment]
sometimes crash, sometimes ok

**Comment by cloudusers** [comment]
forgot update singleton.h, use this file pls
[singleton.h.txt](https://github.com/gperftools/gperftools/files/421693/singleton.h.txt)

**Comment by cloudusers** [comment]
is stack resource has been released when atexit happened ?

**Comment by alk** [comment]
Such reports are usually bugs in the program. Try address sanitizer or thread sanitizer or valgrind or debug tcmalloc (link to libtcmalloc_debug). Closing for now. Please reopen if you have more evidence of possible regression in tcmalloc.
