### ISSUE TITLE
libgcc stack-trace capturing should not be used with profiler (was: gperftools-2.5 + legacy python 2.7.5 + self built gcc-4.6.2 make check failure (profiler_unittest.sh))

### ISSUE THREAD

**Issue by truatpasteurdotfr** [gperftools/gperftools#825]
make check fails on my old CentOS-5 x86_64 desktop with the attached 
test-suite.log...
[test-suite.log.txt](https://github.com/gperftools/gperftools/files/439837/test-suite.log.txt)

**Comment by alk** [comment]
Attach your config.log please. I think you're likely configured without libunwind and we're automatically choosing libgcc and it isn't safe to use from cpu profiler signal handler.

**Comment by truatpasteurdotfr** [comment]
you are right on spot :P
[config.log.txt](https://github.com/gperftools/gperftools/files/441370/config.log.txt)

**Comment by alk** [comment]
Indeed, libgcc is used. It is not safe to use for profiling. But if you don't use profiling, it should work fine. So just ignore this make check failure.

**Comment by alk** [comment]
Notably very latest OSes now make it safe and actually best & perfect to use libgcc instead of other means. And configure doesn't bark at libgcc anymore (even though some people are likely to use not recent enough OSes and have trouble).

Anyways. Closing.
