### ISSUE TITLE
Difficulty obtaining realtime per thread profile

### ISSUE THREAD

**Issue by limaoscarjuliet** [gperftools/gperftools#826]
(Running latest gperftools from git locally built on the machine I'm running).

First, big thank you for maintaining gperftools. While perf is pretty darn good, I could not get it to produce any realtime profile (the sched events being disabled in kernel does not help much either). So gperftools to the rescue!

I'm trying to create a per-thread realtime profile for a basic C application. I'm either getting:
- a non-realtime profile for all threads (sleep, dbaccess or other I/O not visible as process is asleep), 
- realtime profile (sleeps, I/O visible) but main thread only.

In this config I'm getting the realtime profile from main thread only. The CPUPROFILE_PER_THREAD_TIMERS does not seem to have an effect.

export LD_PRELOAD=/usr/local/lib/libprofiler.so.0
export CPUPROFILE=a.out.prof
export CPUPROFILESIGNAL=12
export CPUPROFILE_FREQUENCY=100
export CPUPROFILE_REALTIME=1
export CPUPROFILE_TIMER_SIGNAL=34 # override SIGALRM used in REALTIME mode
# export CPUPROFILE_PER_THREAD_TIMERS=1

./a.out &
export LD_PRELOAD=

**Comment by alk** [comment]
Indeed, wall clock profiler is only able to profile one thread. per-thread timers mode should help, but you'll need to register threads as they're created. See https://github.com/alk/gperf-all-threads for one way to automagically register threads. See also issue #708

**Comment by alk** [comment]
Scrubbing. So indeed, when you give it CPUPROFILE_TIMER_SIGNAL you force it into per-thread mode. And that mode requires you yo register threads or use that gperf-all-threads thingy mentioned above. So either don't do custom signal number or do the other thing. I think as far this specific question we're done here.

Please, do reopen if there is anything to add or fix.
