### ISSUE TITLE
heap-profiler tests fail

### ISSUE THREAD

**Issue by GitMensch** [gperftools/gperftools#828]
I've got the 2.4 release from https://launchpad.net/ubuntu/+archive/primary/+files/google-perftools_2.4.orig.tar.gz (tried with a version from repo but wasn't able to run `autogen.sh` without errors), then run `./configure && make check`.

Result:

```
============================================================================
Testsuite summary for gperftools 2.4
============================================================================
# TOTAL: 47
# PASS:  45
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to google-perftools@googlegroups.com
============================================================================
```

From another issue I've got the idea to retry with `--enable-frame-pointer` but this option is not known i the configure script.

[test-suite.zip](https://github.com/gperftools/gperftools/files/455277/test-suite.zip)
[config.log.txt](https://github.com/gperftools/gperftools/files/455279/config.log.txt)

**Comment by alk** [comment]
Please re-test with 2.5. Bug against old version is not relevant.

**Comment by GitMensch** [comment]
Rechecked with master (2016-09-25T03:56:22).

The results are the same: 

    FAIL: heap-profiler_unittest.sh
    FAIL: heap-profiler_debug_unittest.sh

[test-suite-screen-capture.log.txt](https://github.com/gperftools/gperftools/files/493091/test-suite-screen-capture.log.txt)
[config.log.txt](https://github.com/gperftools/gperftools/files/493092/config.log.txt)

**Comment by alk** [comment]
Something is weird with your awk or shell. Looking at specific test that fails, I see that pprof outputs correct text. Also feeding this output to same command on my box I get correct behavior (exit 1 is executed by awk).

Do you by any chance have shell that is not bash or weird awk? What sh --version and awk --version give?

**Comment by alk** [comment]
BTW I just tested gperftools-2.5.tar.gz on centos 5 docker container and it passed those tests.

**Comment by sd-x** [comment]
I see these two tests failing for slightly different reasons.  My failure output from test-suite.log is
```
--- Test failed for Allocate: didn't account for 90% of executable memory
--- Program output:
[...snip...]
--- pprof output:
Using local file [...]/gperftools-2.7.90/.libs/lt-heap-profiler_unittest.
Using local file /tmp/heap-profiler_unittest.a5nhc2/test_17027.1548.heap.
Total: 36.6 MB
    36.6 100.0% 100.0%     36.6 100.0% _ZL8Allocateiii.constprop.23
     0.0   0.0% 100.0%     36.6 100.0% __libc_start_main
     0.0   0.0% 100.0%     36.6 100.0% _start
     0.0   0.0% 100.0%     36.6 100.0% main
---
```

So the `awk` script in heap-profiler_unittest.sh/VerifyMemFunction doesn't find `^Allocate$`.  My gcc is 7.3.0.  When I hack heap-profiler_unittest.sh to search for "_ZL8Allocate.*" instead of just 'Allocate' the test passes, but I don't think that's really the right fix.

**Comment by GitMensch** [comment]
> What sh --version and awk --version give?

I'm quite sure that was whatever shipped with SLES9. the configure script found `ac_cv_prog_AWK=gawk` so I hope that the testsuite also uses that by `AWK`... But it does neither output the version of it nor of `SHELL='/bin/sh'`, it might be useful to do so.

**Comment by alk** [comment]
This is odd. Either c++filt isn't working right on your box or isn't available or pprof isn't doing right thing.

So what OS we're talking about here? SLES9 if this is not mistake is from 2006 according to wikipedia.

**Comment by GitMensch** [comment]
> So what OS we're talking about here? SLES9 if this is not mistake is from 2006 according to wikipedia.

According to GitHub, this issue is from 2016. I don't have access to that system (which may still runs).

The last question of @alk was, what the outputs of `$AWK --version` and `$SHELL --version` are - and I answered that I don't know but would suggest to present that either in config.log or testsuite.log, so if that question should ever arise it would be easy to check that.
