### ISSUE TITLE
heap-check cause program hangs

### ISSUE THREAD

**Issue by darjun** [gperftools/gperftools#830]
On my RetHat, I link my program with tcmalloc and set environment HEAPCHECK=normal to run it. As a result, the program hangs. I use pstack to find reasons. I found it locks on dl_iterate_phdr, as described in 64-BIT ISSUES in the doc.

How can I do or is there any way to walkaround? thx.

my system info:
uname -r
2.6.32.-358.el6.x86_64

lsb_release -a
LSB Version:          :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:       RedHatEnterpriseServer
Description:           Red Hat Enterprise Linux Server release 6.4 (Santiago)
Release:                 6.4
Codename:            Santiago

**Comment by alk** [comment]
Make sure you have latest gperftools and then try running with TCMALLOC_STACKTRACE_METHOD=libgcc environment variable. This should make heap checker work.

**Comment by darjun** [comment]
Sorry for feeding back so late. But adding TCMALLOC_STACKTRACE_METHOD=libgcc does not improve my situation. The program still hangs on start-up.

**Comment by darjun** [comment]
In addtion, the traceback is:
#0  0x0000003bf220e054 in __lll_lock_wait () from /lib64/libpthread.so.0                                                                                                                 
#1  0x0000003bf22093a3 in _L_lock_892 () from /lib64/libpthread.so.0
#2  0x0000003bf2209287 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x0000003bf1f25c8b in dl_iterate_phdr () from /lib64/libc.so.6
#4  0x00007fe21b480d63 in _Unwind_Find_FDE () from /usr/local/gcc/lib64/libgcc_s.so.1
#5  0x00007fe21b47d956 in uw_frame_state_for () from /usr/local/gcc/lib64/libgcc_s.so.1
#6  0x00007fe21b47ea30 in uw_init_context_1 () from /usr/local/gcc/lib64/libgcc_s.so.1
#7  0x00007fe21b47f2a8 in _Unwind_Backtrace () from /usr/local/gcc/lib64/libgcc_s.so.1
#8  0x00007fe21c0ede7a in ?? () from /home/lidajun/ldjdev/main/dev/server/thirdpart/lib/libprofiler.so.0
#9  0x00007fe21c0ee232 in ?? () from /home/lidajun/ldjdev/main/dev/server/thirdpart/lib/libprofiler.so.0
#10 0x00007fe21c0eb519 in ?? () from /home/lidajun/ldjdev/main/dev/server/thirdpart/lib/libprofiler.so.0
#11 0x00007fe21c0ec0ab in ProfileHandler::SignalHandler(int, siginfo*, void*) () from /home/lidajun/ldjdev/main/dev/server/thirdpart/lib/libprofiler.so.0
#12 <signal handler called>
#13 0x0000003bf2209281 in pthread_mutex_lock () from /lib64/libpthread.so.0
#14 0x0000003bf1f25c8b in dl_iterate_phdr () from /lib64/libc.so.6
#15 0x00007fe21b480d63 in _Unwind_Find_FDE () from /usr/local/gcc/lib64/libgcc_s.so.1
#16 0x00007fe21b47d956 in uw_frame_state_for () from /usr/local/gcc/lib64/libgcc_s.so.1
#17 0x00007fe21b47f2d8 in _Unwind_Backtrace () from /usr/local/gcc/lib64/libgcc_s.so.1
#18 0x00007fe21c0edeca in ?? () from /home/lidajun/ldjdev/main/dev/server/thirdpart/lib/libprofiler.so.0
#19 0x00007fe21c0ee2c6 in ?? () from /home/lidajun/ldjdev/main/dev/server/thirdpart/lib/libprofiler.so.0
#20 0x00007fe21be9f078 in MallocHook_GetCallerStackTrace () from /home/lidajun/ldjdev/main/dev/server/thirdpart/lib/libtcmalloc.so.4
#21 0x00007fe21be92180 in NewHook(void const*, unsigned long) () from /home/lidajun/ldjdev/main/dev/server/thirdpart/lib/libtcmalloc.so.4
#22 0x00007fe21be9ebe6 in MallocHook::InvokeNewHookSlow(void const*, unsigned long) () from /home/lidajun/ldjdev/main/dev/server/thirdpart/lib/libtcmalloc.so.4
#23 0x00007fe21beac244 in tc_newarray () from /home/lidajun/ldjdev/main/dev/server/thirdpart/lib/libtcmalloc.so.4
#24 0x0000000001472ea9 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) ()
#25 0x0000000001473b5b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_M_clone(std::allocator<char> const&, unsigned long) ()
#26 0x0000000001473c00 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long) ()
#27 0x0000000001473ff6 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(unsigned long, char) ()
#28 0x000000000115bb33 in google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ()
#29 0x000000000118d5e3 in google::protobuf::FieldDescriptorProto::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) ()
#30 0x000000000118e6b5 in google::protobuf::DescriptorProto::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) ()
#31 0x0000000001193a77 in google::protobuf::FileDescriptorProto::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) ()
#32 0x000000000115aac6 in google::protobuf::MessageLite::ParseFromArray(void const*, int) ()
#33 0x000000000119719a in google::protobuf::EncodedDescriptorDatabase::Add(void const*, int) ()
#34 0x0000000001161469 in google::protobuf::DescriptorPool::InternalAddGeneratedFile(void const*, int) ()
#35 0x00000000012af86e in GtReq::protobuf_AddDesc_GtReq_2eproto() ()
#36 0x00000000014906e6 in __do_global_ctors_aux ()
#37 0x000000000044dca8 in _init ()
#38 0x0000000007f4a1c8 in ?? ()
#39 0x0000000001490665 in __libc_csu_init ()
#40 0x0000003bf1e1ec70 in __libc_start_main () from /lib64/libc.so.6
#41 0x000000000044fed1 in _start ()

it seems that it is the intializationg of protobuf cause the problem.

**Comment by alk** [comment]
TCMALLOC_STACKTRACE_METHOD=libgcc does not work with cpu profiler. Your program is running with both cpu profiler enabed and heap profiler enabled.

If you need to run with both, then the only really safe option is using frame pointers. If you need to run just cpu profiler, then frame pointers or libunwind should work. With libunwind having chance of deadlocking. If you need just heap profiler, then all stack tracing options should work. But IMHO libgcc should be more reliable than libunwind.

**Comment by darjun** [comment]
Em, yeah, now it works. Thanks for detailed explanation.
