### ISSUE TITLE
test result should be gathered in a log file

### ISSUE THREAD

**Issue by GitMensch** [gperftools/gperftools#832]
Used master (2016-09-25T03:56:22):

    make check

results in

~~~
============================================
2 of 47 tests failed
Please report to gperftools@googlegroups.com
============================================
~~~

But I see no log file at all. Most projects auto-create a testsuite.log with the important parts of configure.log and the testsuite results. Does gperftools has this already and I'm just not seeing it?

The message above just says "report", not "how", and I didn't found a reference how to do so in `README` or `INSTALL` - again: do I miss something here?

The 2.4 release produced a nice summary and test-suite.log ?!?

~~~
============================================================================
Testsuite summary for gperftools 2.4
============================================================================
# TOTAL: 47
# PASS:  45
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to google-perftools@googlegroups.com
============================================================================
~~~

**Comment by alk** [comment]
I just tested gperftools-2.5.tar.gz from releases page and it creates all logs as expected
