### ISSUE TITLE
Does tcmalloc support FIBER in windows?

### ISSUE THREAD

**Issue by Ragnarokbp** [gperftools/gperftools#835]
Recently, I wrote multithreading app using Fibers. It seems that tcmalloc doesn't support ::SwitchToFiber or any context switch like this in ThreadCache. Is that true? 
If so, could anyone help me find some high performance allocators that support fiber?

**Comment by alk** [comment]
I think it will likely just work. Have tried?

**Comment by Ragnarokbp** [comment]
Thanks for reply. It happens to crash in ThreadCache::FreeList::PushRange within a fiber several times, but I cannot find a stable situation to reproduce it. Maybe it's caused by the bug in my multi-thread code. I'll check it again.
