### ISSUE TITLE
In README.md  "NOTE: CPU profiling doesn't work after fork"... it's not resovled？？？？

### ISSUE THREAD

**Issue by anonymalias** [gperftools/gperftools#836]
IN README.md, has a description, as follow:
“
NOTE: CPU profiling doesn't work after fork (unless you immediately
      do an exec()-like call afterwards).  Furthermore, if you do
      fork, and the child calls exit(), it may corrupt the profile
      data.  You can use _exit() to work around this.  We hope to have
      a fix for both problems in the next release of perftools
      (hopefully perftools 1.2).
”

but in the gperftools-2.5/doc/cpuprofile.html, has a description, as follow:
"
If your program forks, the children will also be profiled (since they inherit the same CPUPROFILE setting). Each process is profiled separately; to distinguish the child profiles from the parent profile and from each other, all children will have their process-id appended to the CPUPROFILE name.
"

**Comment by alk** [comment]
Some of that stuff was indeed fixed, especially for programs that fork and exec.
