### ISSUE TITLE
Regression introduced in 2.4: freeing became much slower for a large number of small memory blocks

### ISSUE THREAD

**Issue by yurivict** [gperftools/gperftools#839]
The below testcase allocating 10GB in small blocks runs in about 5 seconds with version 2.3, and in hundreds of seconds with version 2.4. Freeing became much slower. Debugger always stops on ```madvise``` function. Spotted on FreeBSD 11 amd64. May or may not be FreeBSD specific.

```
#include <string.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>

#define SZ_BLK 4000
#define NUM_BLK 2500000

main() {
  void **pp = malloc(NUM_BLK*sizeof(void*));
  int i;
  printf("allocating ...\n");
  for (i = 0; i < NUM_BLK; i++) {
    pp[i] = malloc(SZ_BLK);
    memset(pp[i], 1, SZ_BLK);
  }
  printf("done allocating\n");
  printf("freeing ...\n");
  for (i = 0; i < NUM_BLK; i++) {
    free(pp[i]);
  }
  free(pp);
  printf("done freeing\n");
}
```

**Comment by alk** [comment]
Hi. Yes, this is side effect of aggressive decommit mode. If you're
frequently allocating/freeing large blocks of memory, it will hurt
performance. You can disable it for your program by either setting property
via extension api tcmalloc.aggressive_memory_decommit or by
TCMALLOC_AGGRESSIVE_DECOMMIT environment variable.

**Comment by yurivict** [comment]
The problem I see with this is that this is a typical behavior of many programs. They allocate a lot of not-so-large blocks (4k in this case), and then get hurt during deallocation. I am sure many programs got affected, maybe not that acutely, it's just that people don't pay much attention to performance in general and this goes unnoticed.

**Comment by alk** [comment]
I disagree about typical and many. Most programs do keep reasonably stable working set size and thus don't suffer much from this problem. Keep in mind that in order for "decommit" to happen, you either need to have page span worth of small objects (where "small" is everything less than 256k), or large free.

Perhaps, indeed, this affects BSD more than Linux. I'll be ok merging patch that makes it aggressive decommit default to be "off" on BSD systems.

**Comment by yurivict** [comment]
On Arch Linux, the same case with half NUM_BLK (1250000), allocating 5GB, runs in 2.4 sec with the default allocator, and it runs in 25 sec with gperftools allocator. This isn't a reasonable difference, so linux is also strongly affected.

IMO, "decommit" uses too aggressive algorithm on all systems causing such performance degradation. It should be adjusted for conditions.

Also, serial allocation of same-sized blocks can't be considered a special case for any block size. There should be no significant performance degradation when switching to gperftools.

**Comment by alk** [comment]
Thanks a lot for being persistent on this. In fact most of the issue is not your test program, but much suboptimal behavior of aggressive decommit that used to decommit combined page heap span after merging. So when you get larger and larger free span as you're freeing your stuff, it passes larger and larger region to MADV_FREE or MADV_DONTNEED and that clearly hurts. I will fix it shortly.

**Comment by alk** [comment]
Please take a look at this commit: https://github.com/alk/gperftools/commit/290efe66517c5a1b8dcb2f2b6384d05f0cd9f0e8 and let me know what you think.

While it doesn't address your whole issue that we're now doing more of those commit/decommit operations, it seems to be slowing down your test program by only a bit. So, given that typical programs hit this quite more rarely, I believe we're good to keep this mode as default.

**Comment by alk** [comment]
Here is timings I get when adding 4 loops to your program (to make it run a bit longer) with various modes after the fix. I also enabled MADV_FREE to see if it is any better (and was disappointed):

big:~/src/test$ \time sh -c 'LD_PRELOAD=$HOME/gpt/lib/libtcmalloc_minimal.so TCMALLOC_AGGRESSIVE_DECOMMIT=t ./aggressive-decommit-exerciser '
allocating ...
done allocating
freeing ...
done freeing
allocating ...
done allocating
freeing ...
done freeing
allocating ...
done allocating
freeing ...
done freeing
allocating ...
done allocating
freeing ...
done freeing
3.30user 8.72system 0:12.03elapsed 99%CPU (0avgtext+0avgdata 10064996maxresident)k
0inputs+0outputs (0major+10014915minor)pagefaults 0swaps

big:~/src/test$ \time sh -c 'LD_PRELOAD=$HOME/gpt/lib/libtcmalloc_minimal.so TCMALLOC_AGGRESSIVE_DECOMMIT=f ./aggressive-decommit-exerciser '
allocating ...
done allocating
freeing ...
done freeing
allocating ...
done allocating
freeing ...
done freeing
allocating ...
done allocating
freeing ...
done freeing
allocating ...
done allocating
freeing ...
done freeing
3.13user 2.24system 0:05.38elapsed 99%CPU (0avgtext+0avgdata 10065204maxresident)k
0inputs+0outputs (0major+2953215minor)pagefaults 0swaps

big:~/src/test$ \time sh -c 'LD_PRELOAD=$HOME/gpt/lib/libtcmalloc_minimal.so TCMALLOC_DISABLE_MEMORY_RELEASE=t ./aggressive-decommit-exerciser '
allocating ...
done allocating
freeing ...
done freeing
allocating ...
done allocating
freeing ...
done freeing
allocating ...
done allocating
freeing ...
done freeing
allocating ...
done allocating
freeing ...
done freeing
3.36user 1.88system 0:05.25elapsed 99%CPU (0avgtext+0avgdata 10065348maxresident)k
0inputs+0outputs (0major+2515821minor)pagefaults 0swaps

big:~/src/test$ \time ./aggressive-decommit-exerciser
allocating ...
done allocating
freeing ...
done freeing
allocating ...
done allocating
freeing ...
done freeing
allocating ...
done allocating
freeing ...
done freeing
allocating ...
done allocating
freeing ...
done freeing
2.97user 7.38system 0:10.35elapsed 99%CPU (0avgtext+0avgdata 9825236maxresident)k
0inputs+0outputs (0major+9809534minor)pagefaults 0swaps

So no decommit is more than 2x faster in this (arguably worst) case with tcmalloc. But it still compares well compared to glibc. (only 12sec vs 10 sec in glibc).

**Comment by yurivict** [comment]
I retested with your version on FreeBSD.
The user times:
* with your commit: ~1050 ms
* google-perftools-2.3: ~1050 ms
* google-perftools-2.5: over 4 minutes
* with the OS-supplied malloc: ~1250 ms

So the time is about the same as in 2.3 and better than with the OS allocator.

Thank you for fixing it!

**Comment by alk** [comment]
Thanks. Can you also test with completely disabled releasing of memory ? On
GNU/Linux it was 2x faster.

**Comment by yurivict** [comment]
Without freeing on FreeBSD.

with your commit: ~800 ms
google-perftools-2.3: ~800 ms
google-perftools-2.5: ~850 ms
with the OS-supplied malloc: ~1070 ms

Without freeing it mostly tests mmap speed, not perftools itself though.

**Comment by alk** [comment]
Perhaps there is misunderstanding, when I referring to "without freeing" I was referring to running with TCMALLOC_DISABLE_MEMORY_RELEASE=t

**Comment by yurivict** [comment]
With TCMALLOC_DISABLE_MEMORY_RELEASE=t:

with your commit: ~1010 ms
google-perftools-2.3: ~1050 ms
google-perftools-2.5: ~1045 ms

**Comment by alk** [comment]
Thanks. This probably means that freebsd does have quick madv_free.
