### ISSUE TITLE
Can't not add code with "new" function

### ISSUE THREAD

**Issue by lchkeepit** [gperftools/gperftools#840]
In my project, I need to change Tc and When I want to add code like "int *t = new int;" in thread_cache.h.Then Tc throws serious exceptions. Besides, the error message changes and is not always the same.
I guess that this issue happens because of some lock. But I don't get confirmation now.

Thanks for help!

**Comment by lchkeepit** [comment]
I think I figure out the reason. "new" function has already been hooked.

**Comment by alk** [comment]
Yes, calling operator new from inside operator new can't work.
