### ISSUE TITLE
Strict aliasing optimization issue

### ISSUE THREAD

**Issue by jlquinn** [gperftools/gperftools#846]
Hi all,

We're using tcmalloc in our project.  I noticed a strict-aliasing issue when compiling tcmalloc:

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../gperftools-src -I./src -I../gperftools-src/src -DNO_TCMALLOC_SAMPLES -DNO_TCMALLOC_SAMPLES -pthread -DNDEBUG -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -DNO_FRAME_POINTER -DTCMALLOC_FOR_DEBUGALLOCATION -g -O2 -MT src/libtcmalloc_minimal_debug_la-debugallocation.lo -MD -MP -MF src/.deps/libtcmalloc_minimal_debug_la-debugallocation.Tpo -c ../gperftools-src/src/debugallocation.cc  -fPIC -DPIC -o src/.libs/libtcmalloc_minimal_debug_la-debugallocation.o
../gperftools-src/src/debugallocation.cc: In function ‘void<unnamed>::google_init_module_debugallocation()’:
../gperftools-src/src/debugallocation.cc:1046: warning: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
../gperftools-src/src/tcmalloc.cc:579: warning: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
../gperftools-src/src/tcmalloc.cc:579: warning: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
../gperftools-src/src/gperftools/malloc_extension.h:90: warning: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
../gperftools-src/src/debugallocation.cc:1150: warning: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
../gperftools-src/src/debugallocation.cc:1150: warning: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
../gperftools-src/src/debugallocation.cc:1150: note: initialized from here

This is Centos 6, x86_64, gcc 4.4.7.  We run autogen.sh and then configure with --enable-minimal.
It looks like you need -fno-strict-aliasing to prevent potential optimization-related bugs.  I haven't hit an actual bug I could attribute to tcmalloc, but something may be lurking.

**Comment by alk** [comment]
I believe this is bogus warnings. All other compilers are ok with that. And my centos 6 VM with 4.4.7 is giving aliasing warnings placement new calls in system-alloc.cc InitSystemAllocators. While I am not language lawyer those calls seem totally fine as far as I can see.

Please reopen if you have good reasons to think that those warnings are valid.
