### ISSUE TITLE
Troubleshooting malloc bottlenecks

### ISSUE THREAD

**Issue by kellabyte** [gperftools/gperftools#847]
I would appreciate some help troubleshooting what may be my bottleneck in memory allocation. I'm using tcmalloc to try and reduce some contention I may be seeing in malloc calls.

I have a HTTP service that supports load balancing via `SO_REUSEPORT` in multi-process and multi-threaded configurations. Currently the `1 thread per 20 processes` model does `6.3M requests/second` but the `20 threads per 1 process` does only `3.2M requests/second`. I'm trying to figure out why because my in-process memory pools are on a per-thread basis so they shouldn't be competing on memory allocation.

Here are my results and `perf top` output of the 2 different configurations.

If I run 20 haywire processes using `tcmalloc` haywire reaches `6.3 million requests/second`. 
```
killall hello_world; for i in `seq 20`; do LD_PRELOAD="./lib/gperftools/.libs/libtcmalloc.so" ./build/hello_world --balancer reuseport & done

perf top
   7.42%  hello_world              [.] http_request_buffer_pin
   6.94%  hello_world              [.] http_request_buffer_reassign_pin
   6.63%  hello_world              [.] http_parser_execute
   6.23%  libtcmalloc.so.4.3.0     [.] tc_deletearray_nothrow
   4.94%  hello_world              [.] http_request_buffer_locate
   3.60%  libtcmalloc.so.4.3.0     [.] tc_malloc
   2.77%  libtcmalloc.so.4.3.0     [.] tc_calloc
   2.33%  [kernel]                 [k] native_queued_spin_lock_slowpath
   2.31%  [kernel]                 [k] tcp_sendmsg
   1.76%  [kernel]                 [k] _raw_spin_lock_bh
   1.41%  hello_world              [.] http_request_on_message_complete
   1.34%  hello_world              [.] set_header
   1.22%  [kernel]                 [k] copy_user_enhanced_fast_string
   1.20%  hello_world              [.] create_response_buffer
```

Expanding `http_parser_execute`
```
   6.84%  hello_world                   [.] http_request_buffer_pin          ▒
   6.59%  hello_world                   [.] http_parser_execute              ▒
   6.21%  hello_world                   [.] http_request_buffer_reassign_pin ▒
   6.08%  libtcmalloc_minimal.so.4.3.0  [.] tc_deletearray_nothrow           ▒
   4.47%  hello_world                   [.] http_request_buffer_locate       ▒
   3.62%  libtcmalloc_minimal.so.4.3.0  [.] tc_malloc                        ▒
   2.26%  [kernel]                      [k] tcp_sendmsg                      ▒
   1.82%  [kernel]                      [k] _raw_spin_lock_bh                ▒
   1.44%  hello_world                   [.] http_request_on_message_complete ▒
   1.21%  hello_world                   [.] create_response_buffer           ▒
   1.08%  hello_world                   [.] hw_route_compare_method          ▒
   0.93%  [kernel]                      [k] __srcu_read_lock                 ▒
   0.76%  libtcmalloc_minimal.so.4.3.0  [.] tc_realloc                       ▒
   0.73%  hello_world                   [.] free_http_request
```

If I run 1 process but 20 threads somewhere they are competing on something and only reach `3.2 million requests/second`.

```
LD_PRELOAD="./lib/gperftools/.libs/libtcmalloc.so" ./build/hello_world --threads 20 --balancer reuseport

perf top
  10.68%  hello_world           [.] http_parser_execute
   6.61%  libtcmalloc.so.4.3.0  [.] tc_deletearray_nothrow
   5.05%  hello_world           [.] http_request_buffer_pin
   4.70%  hello_world           [.] http_request_buffer_reassign_pin
   4.46%  libtcmalloc.so.4.3.0  [.] tc_malloc
   3.82%  libc-2.21.so          [.] 0x00000000001452a0
   3.26%  hello_world           [.] http_request_buffer_locate
   2.78%  libtcmalloc.so.4.3.0  [.] tc_calloc
   2.41%  hello_world           [.] uv_write2
   2.30%  libc-2.21.so          [.] 0x000000000014d86c
   2.13%  libc-2.21.so          [.] 0x000000000014d6b0
   1.77%  [kernel]              [k] native_queued_spin_lock_slowpath
   1.58%  libc-2.21.so          [.] strlen
   1.44%  hello_world           [.] http_request_on_message_complete
```

Expanding `http_parser_execute`.
```
   6.65%  libtcmalloc_minimal.so.4.3.0  [.] tc_deletearray_nothrow           ▒
   5.28%  hello_world                   [.] http_request_buffer_pin          ▒
   4.60%  hello_world                   [.] http_request_buffer_reassign_pin ▒
   4.47%  libtcmalloc_minimal.so.4.3.0  [.] tc_malloc                        ▒
   3.27%  libc-2.21.so                  [.] 0x00000000001452a0               ▒
   3.26%  hello_world                   [.] http_request_buffer_locate       ▒
   2.71%  libtcmalloc_minimal.so.4.3.0  [.] tc_calloc                        ▒
   2.12%  libc-2.21.so                  [.] 0x000000000014d86c               ▒
   2.07%  libc-2.21.so                  [.] 0x000000000014d6b0               ▒
   1.95%  hello_world                   [.] uv_write2                        ▒
   1.53%  hello_world                   [.] http_request_on_message_complete ▒
   1.44%  [kernel]                      [k] tcp_sendmsg                      ▒
   1.39%  hello_world                   [.] get_cached_request
```

Is it safe to say `tc_deletearray_nothrow()` is having a larger impact in the multi-threaded configuration? What could be causing this? I'm trying to think of what malloc functions that may be causing this and I know we call `realloc()` quite a bit in `http_request_buffer` such as [here](https://github.com/haywire/haywire/blob/reuseport/src/haywire/http_request_buffers.c#L131).

Any help interpreting these results would be greatly appreciated!

**Comment by alk** [comment]
You might be hitting tcmalloc slow-path more often with worker 20 threads. Consider raising thread cache limit via TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES environment variable. Default of just 32 megs might be too small.

**Comment by dimitrik-fr** [comment]
Curiously, I'm observing both `tc_deletearray_nothrow` and `tc_malloc` reported by "perf" on MySQL workload (using tcmalloc). TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES increased to 256MB, may it be still not enough ? how to know when it's "good enough" ? ;-))

any ideas are welcome !

Rgds, -Dimitri

**Comment by dimitrik-fr** [comment]
UPDATE : I can also see "CentralFreeList::FetchFromOneSpace.." reported, maybe this can point on something ?

NOTE : there is a clear `tcmalloc` scalability issue in the workload I'm observing.. -- if I replace `tcmalloc` by `jemalloc`, I'm directly getting 50-75% gain in overall performance. But I want to stay with `tcmalloc` as it has much more better memory management, so I absolutely need to find the way to fix this scalability issue ;-))

however, seems like `tcmalloc` I'm using is not the latest one (coming from system RPMs gpertools-2.6), I'll try with 2.8 as well and see if it'll be any batter..

Rgds, -Dimitri
