### ISSUE TITLE
Support OS X debugging info in .dSYM and flat .dwarf files

### ISSUE THREAD

**Issue by andlabs** [gperftools/gperftools#850]
OS X's linker does not seem to provide a way to store debug information embedded in the binary; instead, you use `dsymutil` to generate a `.dSYM` folder that contains the debug information. There is also a flat file version of these `.dSYM` folders, with extension `.dwarf`, generated with `dsymutil -f`.

Right now pprof does not support getting symbols from these files:

```
Pietros-MacBook-Pro:benchmark pietro$ pprof ./b b.prof 
Using local file ./b.
Using local file b.prof.
Welcome to pprof!  For help, type 'help'.
(pprof) top5
Total: 4005 samples
     113   2.8%   2.8%      113   2.8% 0x00000001011cb460
     100   2.5%   5.3%      100   2.5% 0x00000001011cb1cd
      91   2.3%   7.6%       91   2.3% 0x00000001011cb9bb
      82   2.0%   9.6%       82   2.0% 0x00000001011cb15d
      79   2.0%  11.6%       79   2.0% 0x00000001011cb745
(pprof) Pietros-MacBook-Pro:benchmark pietro$ ls -d b*
b		b.dwarf		benchmark.c	benchmark.o
b.dSYM		b.prof		benchmark.h
```

If you Google right now, you'll see suggestions to use `-Wl,-no_pie` to disable OS X's ASLR and get symbols back. However, that's all it does; `list _symbolName` results in

```
no filename found in _symbolName<00000001000011b0>
```

I'm not sure if OS X provides a library you can use for this or if you have to parse the flat file yourself; either way it boils down to a Mach-O binary with a custom format.

Tested against both 2.5 and master as installed from Homebrew on OS X 10.11.

Thanks!

**Comment by alk** [comment]
perl version of pprof is much deprecated. Please test and report bug (if any) against golang version at github.com/google/pprof
