### ISSUE TITLE
Early call of operator new() in MallocExtension initialization

### ISSUE THREAD

**Issue by perfhunter** [gperftools/gperftools#852]
Hi, 
I am working on a custom memory monitoring library that intercepts dynamic management routines and I experience some inconveniences to handle recent gperftools implementation. The problem is that I need to call malloc_usable_size() from my malloc/free/etc. hooks and I have realized that gperftools' tc_malloc_size() uses operator new() to initialize MallocExtension instance on a first invocation. This leads my library to infinite recursion loop. Right now I need some dirty tricks to handle this particular case and I am not happy with this. I perfectly understand the idea behind the possibility of implementing custom malloc extensions, but I have a few implementation questions:
1) IMHO, a call of generic operator new() from tc_malloc_size() is not a good idea in general. Why don't you just reserve some static memory and initialize it using placement new()? Since MallocExtension is basically a singleton, I see no need for dynamic memory allocation there.
2) The method MallocExtension::Register() sets the pointer to custom malloc extension implementation without deleting the original one. While it's not a big issue, formally this is the memory leak which may be triggered by some software.

Also I would like to vote for exposing the public API that calculates the size class for a given object size. The reason for doing this is that I can use this API in my malloc() and sized operator delete() hooks. This should significantly reduce the overhead from calculating the size of allocated memory region by a given pointer - this is not a cheap operation in tcmalloc as opposed to glibc's ptmalloc. What do you think about it?

Thanks,
Andrey

**Comment by alk** [comment]
Hi. Have you considered using malloc hooks rather than overriding memory allocator? I don't think we can explicitly support "easy" overriding of malloc. While placement new for that particular allocation is easy to do, there is no guarantee that we won't do it elsewhere.

As for API for calculating effective size, yes, that is good idea. In fact Google-internal copy of tcmalloc has simi-recently gained support for nallocx call originally introduced by jemalloc. Let me look at porting it right now.

**Comment by perfhunter** [comment]
Hi Aliaksey,

Yes, I considered to use malloc hooks, but  I have two reason not to do
this:
1) I do not like to introduce any specific TCmalloc dependencies, right now
my tool works perfectly at least with glibc malloc, tcmalloc and jemalloc
2) If I use memory hooks, I am not able to track very early memory
allocations that made before my hooks are initialized, and I am not happy
with this. Right now my tool is implemented as LD_PRELOAD'ed shared
library, so malloc override is quite natural way to to intercept _all_
memory allocations.

Best regards,
Andrey


17 дек. 2016 г. 21:31 пользователь "Aliaksey Kandratsenka (aka Aliaksei
Kandratsenka)" <notifications@github.com> написал:

**Comment by alk** [comment]
Thinking about this some, if you contribute that change for placement new-ing MallocExtension, I'll be happy to take it.

**Comment by alk** [comment]
Here is commit that adds nallocx: https://github.com/alk/gperftools/commit/b8f9d0d44f94177d34b069180618b7d002e85b69

I haven't extensively tested it yet, but it seems to be doing the right thing. Please test and review. And let me know what you think.

**Comment by perfhunter** [comment]
Ok, I will get back to this issue after my vacation.

Best regards and happy holidays,
Andrey

18 дек. 2016 г. 18:34 пользователь "Aliaksey Kandratsenka (aka Aliaksei
Kandratsenka)" <notifications@github.com> написал:
