### ISSUE TITLE
Memory usage slightly higher in the move from 2.4 to 2.5

### ISSUE THREAD

**Issue by SamSaffron** [gperftools/gperftools#853]
I have recently been experimenting with various allocators to try to find the best fit for Ruby. 

tcmalloc really shines, lockless appears to outperform tcmalloc but memory on tcmalloc is king and is now better than all other allocators including jemalloc which used to lead in this department. 

The benchmark is here: 

https://github.com/SamSaffron/allocator_bench

I noticed a slight memory regression in the move from 2.4 to 2.5. I understand allocators are series of tradeoffs, so this is not per-se a bug, but maybe worth looking into?

**Comment by alk** [comment]
Thanks a lot for reporting this. I will definitely take advantage of your benchmark.
