### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by acmorrow** [gperftools/gperftools#854]
It seems a like a number of good things have landed since March (Sierra, s390x, strict alignment, etc.). Is it time to get a 2.6 out? Are there any other open issues or PRs that should try to get merged first?

**Comment by alk** [comment]
Yes, and also windows improvements are good enough for new release too. I would like to land few important performance bits that few people (including me) made to Google version of tcmalloc. Expect RC during holiday season.

**Comment by acmorrow** [comment]
I think it would be good to see https://github.com/gperftools/gperftools/pull/785 merged before another release, if possible, so I've pinged the submitter.

**Comment by alk** [comment]
Apologies for delays. I've tagged 2.6 release candidate. And we still have time to sneak in few more changes.

**Comment by yurivict** [comment]
Release already happened, this can be closed.

**Comment by acmorrow** [comment]
Done.
