### ISSUE TITLE
How to profile java program on mac OSX?

### ISSUE THREAD

**Issue by dongeforever** [gperftools/gperftools#860]
Hi:
   I make the source code, and get *.dylib. 
   Can i use it as on Linux env as follows:
   export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/lib
   export LD_PRELOAD=/usr/local/lib/libtcmalloc_and_profiler.dylib
   export HEAPPROFILE=/tmp/test.log

   But it does not work.

   Have i got something wrong?
  And how to profile java program on mac OSX?

**Comment by dongeforever** [comment]
@alk @gaffo could you help me please? I have spent a lot of time in it now.

**Comment by alk** [comment]
Java has own set of profilers. cpu profiler bundled with gperftools is not useful for java.

**Comment by hujianxin** [comment]
@dongeforever java有一些自己的profilers，免费强大的visualvm，付费的yourkit, jprofiler，都非常好

**Comment by dongeforever** [comment]
@hujianxin @alk  I want to profile the off-heap memory, normal tools like visualvm  cannot handle this. Maybe i can try  yourkit and jprofiler.

**Comment by alk** [comment]
If you need heap profiler, then just follow regular instructions.

**Comment by dongeforever** [comment]
ok. I will try it on Linux instead of Mac.

**Comment by wl4g** [comment]
need disabled MacOS SIP，see: https://support.intego.com/hc/en-us/articles/115003523252-How-to-Disable-System-Integrity-Protection-SIP
