### ISSUE TITLE
Feature Request: log out of memory conditions

### ISSUE THREAD

**Issue by f18m** [gperftools/gperftools#861]
Hi,

I'm using tcmalloc in a multithreaded daemon process that does a lot of memory allocations. This process needs to run on a variety of hardware and in some cases on hardware that just does not have enough memory. In such case my process crashes (almost in no place there is a check for malloc() returning NULL) and that's fine for me. 
However, **it would be very useful to have out-of-memory events logged somewhere**; I have a logging framework built into such process but it is a C++ framework that may (perhaps inadvertently) try to allocate memory. For this reason, I don't want/can use that for logging an out-of-memory condition.

Options I can think of are:
1) use syslog() API to log a message, I need to test if this works when memory is over
2) use open()/write() POSIX calls (I'm on Linux) to write a message to /dev/kmsg (this requires root privileges)

Maybe there is something smarter that can be done. However I guess this could be useful also to other people using tcmalloc.... what do you think?

Thanks!

**Comment by alk** [comment]
Hi. Look at set_new_handler and tc_set_new_mode, you can do whatever you
want on out of memory conditions.

**Comment by f18m** [comment]
Hi alk,
sorry for the delay. 
Indeed I found the MallocHook::AddNewHook() function which I guess is the equivalent of the set_new_handler and tc_set_new_mode functions you cited.

I copy and paste here my solution to the problem, in case it can be useful to others as well:

`
void MyGetProcessName(char* output, size_t len)
{
	// in case of failure:
	output[0] = '\0';

	int status_fd = open("/proc/self/status", O_RDONLY);
	if (status_fd == -1)
		return;

	char buf[1024];
	int num_read = read(status_fd, buf, sizeof(buf));
	if (num_read <= 0)
	{
		close(status_fd);
		return;
	}

	buf[num_read] = 0;

	static const char ProcName[] = "Name:";
	char *proc_name = strstr(buf, ProcName);
	if (!proc_name)
	{
		close(status_fd);
		return;
	}

	char *proc_name_value = proc_name + sizeof(ProcName);
	char *proc_name_value_end = strstr(proc_name_value, "\n");
	if (!proc_name_value_end)
	{
		close(status_fd);
		return;
	}

	// mark the newline as end of process name:
	*proc_name_value_end = '\0';

	// skip any blank before the process name:
	char* curr = proc_name_value;
	for (; curr < proc_name_value_end; curr++)
		if (isprint(*curr) && *curr != ' ')
			break;

	// copy into output buffer
	if (curr < proc_name_value_end)
		strncpy(output, curr, len);

	close(status_fd);
}


void MyOutOfMemoryHook(const void* ptr, size_t size)
{
	if (UNLIKELY(ptr == NULL))
	{
		// this function gets called AFTER tcmalloc normal operation.
		// Thus if we get a NULL pointer here, it means that allocation has failed.

		char thread_name[16], process_name[16];

		// get process name
		MyGetProcessName(process_name, 16);
		process_name[15] = '\0';

		// get thread name
		prctl(PR_GET_NAME, thread_name, 0, 0, 0);
		thread_name[15] = '\0';


		char long_msg[128];
		size_t long_msg_len = 0;
		size_t max_len = sizeof(long_msg)/sizeof(char) - 1;

		const char *msg;
		size_t msg_len;

		/*
		 * Try to format a useful message for the user:
		 * NOTE: snprintf() will NOT allocate memory, just use the one we provide:
		 */
		int ret_len = snprintf(long_msg, max_len, "%s (%s): Allocation of %zu bytes failed: out of memory\n", process_name, thread_name, size);
		if (ret_len < max_len)
		{
			// snprintf() succeeded, print the long more-informative message:
			msg = long_msg;
			msg_len = ret_len;
		}
		else
		{
			msg = "Allocation failed: out of memory\n";
			msg_len = strlen(msg);
		}

		// Print this event in the kernel log that is shown by dmesg:
		int fd = open("/dev/kmsg", O_RDWR);
		if (fd > 0)
		{
			write(fd, msg, msg_len);
			close(fd);
		}
		//else: note that the open() will fail if this code is not running with superprivileges (root).. skip and continue

		// Print on stderr:
		write(STDERR_FILENO, msg, msg_len);

		// Print via syslog:
		// this triggers some memory allocations... let's try anyway:
		openlog(thread_name, LOG_PID, LOG_LOCAL1);
		syslog(LOG_CRIT, msg, msg_len);
		closelog();
	}
}

// inside main():
	MallocHook::AddNewHook(&MyOutOfMemoryHook);
`


Thanks!

**Comment by alk** [comment]
This is much suboptimal. New hooks do slow down program by a lot.

What I suggested was entirely different approach. You can set "new mode" via tc_set_new_mode, which will cause malloc/free use same OOM handling as operator new() throw(). I.e. in case of oom it will invoke new_handler (see std::set_new_handler), where you can do whatever you want. That will not affect performance of malloc at all, since critical path will remain fast and simple.

**Comment by f18m** [comment]
Thanks, for the pointer! This is very useful to know. 
I modified slightly my code to this form (in case it is useful to others):

`
tc_set_new_mode(1 /* 1 = calls to malloc will behave like calls to new, and the std_new_handler will be invoked on failure.*/);
std::set_new_handler(MyOutOfMemoryStdHook);
`
