### ISSUE TITLE
why "common.cc : static const int32 kDefaultTransferNumObjecs = 512;"?

### ISSUE THREAD

**Issue by bedragon** [gperftools/gperftools#862]
common.cc : static const int32 kDefaultTransferNumObjecs = 512;

why "kDefaultTransferNumObjecs = 512"???

**Comment by alk** [comment]
Elevating it helps on some benchmarks. But I recently got evidence that it
hurts some other benchmarks badly enough. So we'll likely revert back to
old value of 32 very soon.

But why you're asking? Do you have some other workloads where it hurts?

**Comment by bedragon** [comment]
Thanks answer my question，I learn tcmalloc source code. I found it to be different, in different versions。so，Its value depends on your experience？

**Comment by alk** [comment]
Some benchmarking and some wild guessing.
