### ISSUE TITLE
How to fill freed memory for debugging?

### ISSUE THREAD

**Issue by f18m** [gperftools/gperftools#866]
Hi,
I'm trying to debug some memory issue in a software using tcmalloc. 
My suspect is that a pointer to a freed memory block is used after free.
I know about the HEAP_PROFILE mode but I don't think it can be used for debugging, such issues right?

I would like to have something like what Microsoft provides: 
 https://msdn.microsoft.com/en-us/library/974tc9t1.aspx 
for debug builds, i.e. being able to:
1) Mark Freed blocks with 0xDD
2) Mark New blocks with 0xCD

While #2 is pretty easy using MallocHook::AddNewHook(), #1 is not because the function that I can provide to MallocHook::AddDeleteHook()  only takes 1 argument (the pointer) not the size of the memory block. Is there an easy way to have the freed memory block size in a delete hook function?

Thanks,
Francesco

**Comment by f18m** [comment]
Hi sorry for the noise, I found I can do:

 MallocExtension::instance()->GetAllocatedSize(ptr)

to get the size of a pointer. Is this correct?

**Comment by alk** [comment]
No need to create two ticket for this :)

Also do keep in mind that installing hook will slow down your malloc a lot. There is already tcmalloc_debugmalloc.so available that does this and much more, so I'd recommend it instead of manually filling the memory.

**Comment by f18m** [comment]
Hi alk,

what does tcmalloc_debugmalloc.so  do?
Is it documented somewhere? 
Where should I look to? I looked at the code and found the DebugAllocate() function that however seems to "just" do malloc tracing, isn't it? I found nothing like new/freed memory filling... 

Thanks!

**Comment by alk** [comment]
On Mon, Jan 23, 2017 at 11:06 AM, f18m <notifications@github.com> wrote:

> Hi alk,
>
> what does tcmalloc_debugmalloc.so do?
> Is it documented somewhere?
> Where should I look to? I looked at the code and found the DebugAllocate()
> function that however seems to "just" do malloc tracing, isn't it? I found
> nothing like new/freed memory filling...
>

Check numerous flags and code at:
https://github.com/gperftools/gperftools/blob/master/src/debugallocation.cc

It is used by linking or preloading debugmalloc instead of regular
tcmalloc. Then debugmalloc will automagically do all the checks for you.

**Comment by f18m** [comment]
Ok, thanks. I verified that linking the libtcmalloc_debug.so indeed I get newly-allocated memory filled with 0xAB and deleted memory gets filled with 0xCD... thanks, I'm closing this ticket.
