### ISSUE TITLE
cpu-profile hang up with cout on arm linux

### ISSUE THREAD

**Issue by barrypp** [gperftools/gperftools#871]
gcc : 4.4.1
Linux : 4.1.6
GPerfTools : 2.5

test program :

	int main()
	{
		int a;
		a = 0;
		while(1)
		{
			//printf("%d\n",a++);
			cout<<a++<<endl;
			usleep(10e3);
		}
		return 0;
	 }

env:
export CPUPROFILE=./T.prof
export CPUPROFILE_FREQUENCY=1000

problem:
the test program should continue run and output, but it will hang up randomly and at the same time this program will use 100% cpu which it should not.

if we comment 'cout...' and uncomment 'printf...', this program will not hang up.
if we use ofstream instead of cout, problem is same.

**Comment by alk** [comment]
You need libunwind. Profiling with other stack unwinding methods is unsafe.

**Comment by barrypp** [comment]
thanks, I will try it tomorrow.

**Comment by barrypp** [comment]
libunwind cross build fail.

the error is 
hidden symbol '__sync_fetch_and_add_4'

**Comment by barrypp** [comment]
I  use 32bit linux arm. Do I really need libunwind ?

**Comment by alk** [comment]
Yes, stack-frame-pointer-based unwinding on arm is quite broken. Libunwind (or if you're truly desperate libgcc) -based unwinding is the only working method.
