### ISSUE TITLE
CPUPROFILE_FREQUENCY not working

### ISSUE THREAD

**Issue by SuFredyTing** [gperftools/gperftools#874]
PROFILE: interrupts/evictions/bytes = 0/0/64

After I set CPUPROFILE_FREQUENCY=1000000， the interrupts also are 0. I don,t know environment variable not working?

**Comment by alk** [comment]
Most likely your program run time is too small. But also such ridiculously high profiling frequency has no chance of working too.

**Comment by SuFredyTing** [comment]
Yes, you are right. Thanks for your answer.
