### ISSUE TITLE
Link problem with clang++ 3.8 on Linux and gperftools 2.5 with -stdlib=libc++

### ISSUE THREAD

**Issue by ronaaron** [gperftools/gperftools#876]
In order to get C++ throw/catch working correctly, I've had to switch to using the libc++ instead of libstdc++ in my application.

However, I used to be able to link with tcmalloc, and now I get a bunch of errors.

First, I did a clean rebuild of tcmalloc with the configure line:
`./configure LIBS=-lc++ CC=clang CXX=clang++ CXFLAGS="-stdlib=libc++"`

This compiled fine.  I took that libtcmalloc.a and linked with my application, and it looks like tcmalloc is trying to get libstdc++ functions.  I tried libtcmalloc as well as -minimal:
`.../libtcmalloc.a(libtcmalloc_minimal_internal_la-malloc_extension.o): In function `void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag)':
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/basic_string.tcc:223: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'`

Everything links and runs fine if I just don't link with tcmalloc.

**Comment by acmorrow** [comment]
Shouldn't that be `CXXFLAGS=-stdlib=libc++`? You seem to be missing an `X`. Did you verify that `-stdlib=libc++` was on the compile line for each TU in tcmalloc?

**Comment by ronaaron** [comment]
Yes, you are correct.  Sorry for the noise!
