### ISSUE TITLE
Issues with building TCMalloc for iOS

### ISSUE THREAD

**Issue by michaeleiselsc** [gperftools/gperftools#877]
Hi, I'm trying to build TCMalloc for iOS, and I thought I'd reach out since I saw you had a blog post mentioning you'd integrated into an iOS project. I've tried building for my iPhone 7 with "./configure --host=aarch64-apple-darwin", but when I include the .dylib file in my project, I get the error "file was built for x86_64 which is not the architecture being linked (arm64)". I tried then running make with this configuration as 'make CFLAGS="-arch arm64" LDFLAGS="-arch arm64"', but then I get errors like "/usr/include/sys/cdefs.h:707:2: error: Unsupported architecture". Any ideas?

**Comment by alk** [comment]
This is weird indeed. First, if ios works in any capacity, it'll have to be --enable-minimal. Second, attach ./config.log file from both attempts and lets see what it tells us.
