### ISSUE TITLE
How to link a program against tcmalloc_minimal with mingw-w64?

### ISSUE THREAD

**Issue by mdimura** [gperftools/gperftools#878]
On linux I just compile and link my program like this: `g++ -O2 -o test main.cpp -ltcmalloc_minimal` and it works, which I know since it prints messages like this:

> tcmalloc: large alloc 8589934592 bytes == 0x21e0000 @

Now I am trying to accomplish the same thing using minw-w64 cross-compilation.

> x86_64-w64-mingw32-g++ -O2 -o test.exe main.cpp -ltcmalloc_minimal

And when I start the `test.exe > out.txt 2>&1` on windows, I do not get any messages from tcmalloc and program starts just fine even if I remove libtcmalloc_minimal.dll. Dependency walker also does not show anything about tcmalloc.
I use the cross-build environment from Arch linux, which works wonderfull and provides the [mingw-w64-gperftools](https://aur.archlinux.org/packages/mingw-w64-gperftools/) package, which also seems to build and install fine (I get the libtcmalloc_minimal-4.dll, libtcmalloc_minimal.a libtcmalloc_minimal.dll.a).
I also tried using extra parameters:

> x86_64-w64-mingw32-g++ -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free  -o test.exe main.cpp -ltcmalloc_minimal

Does not help. Could not find anything that would work in internet either.

How do I link a program against tcmalloc using mingw?

Here is the source that I am compiling:
**main.cpp:**
```
#include <vector>
#include <iostream>
#include <numeric>
int main()
{
  std::vector<double> vec;
  vec.resize(1024L*1024L*1024L,10.0);
  std::cout<<long(std::accumulate(vec.begin(),vec.end(),0.0))<<std::endl;
  return 0;
}
```

**Comment by alk** [comment]
Try pulling some tcmalloc-specific symbol. Adding this to ldflags  -Wl,--require-defined=tc_malloc may do the trick. If you're linking to .dll, you way want to try -Wl,--no-as-needed.

**Comment by Burning-Daylight** [comment]
@alk Thank you for your answer! 
Building with
```
x86_64-w64-mingw32-g++ -O2 -o test.exe main.cpp -Wl,--no-as-needed -ltcmalloc_minimal
```
Does not seem to change anything, tcmalloc_minimal is ignored.

If I build with
```
x86_64-w64-mingw32-g++ -O2 -o test.exe main.cpp -Wl,--require-defined=tc_malloc -ltcmalloc_minimal
```
or
```
x86_64-w64-mingw32-g++ -O2 -o test.exe main.cpp  -Wl,--require-defined=tc_malloc -Wl,--no-as-needed -ltcmalloc_minimal
```
it starts complaining if libtcmalloc_minimal.dll is missing, which is good, but when I provide the dll, the program freezes and the does not seem to do anything - no cpu usage, only 1.2 MB of RAM.

**Comment by Burning-Daylight** [comment]
I also tried using gdb to debug the program, but it does not even seem get to the main():

> C:\>gdb test.exe
> GNU gdb (GDB) 7.11.1
> Copyright (C) 2016 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-w64-mingw32".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from test.exe...done.
> (gdb) break main
> Breakpoint 1 at 0x4015c3: file main.cpp, line 7.
> (gdb) next
> The program is not being run.
> (gdb) start
> Temporary breakpoint 2 at 0x4015c3: file main.cpp, line 7.
> Starting program: C:\test.exe
> [New Thread 5732.0xe88]
> [New Thread 5732.0x57c]
> [New Thread 5732.0xc80]
> [New Thread 5732.0x318]
> [Thread 5732.0x57c exited with code 0]
> [Thread 5732.0x318 exited with code 0]
> [Thread 5732.0xc80 exited with code 0]
>

**Comment by edubart** [comment]
I am having the same issue, is tcmalloc expected to work with mingw-w64?

**Comment by alk** [comment]
Yes, mingw-w64 is supposed to work. I am testing it myself periodically (with mingw64 as shipped by Debian).

**Comment by Burning-Daylight** [comment]
@alk what are the compiler/linker arguments that you use?

**Comment by alk** [comment]
So I just downloaded .tar.gz of gperftools 2.5, unpacked and did:

$ ./configure --host=x86_64-w64-mingw32

$ make -j8

(There is warning that somehow behaves as error on patching code so I needed to change int to unsigned here https://github.com/gperftools/gperftools/blob/master/src/windows/mini_disassembler_types.h#L191)

then

$ x86_64-w64-mingw32-g++ -O2 -Wall -o malloc_bench.exe benchmark/run_benchmark.c benchmark/malloc_bench.cc -Wl,--require-defined=tc_malloc -L.libs -ltcmalloc_minimal

then copy libtcmalloc_minimal-4.dll, libstdc++-6.dll and libgcc_s_seh-1.dll to current directory and then

$ wine64 ./malloc_bench.exe 

works

**Comment by edubart** [comment]
@alk The exactly same steps does not work in ArchLinux, must be something with ArchLinux  environment. Just one diference is that I need to copy libwinpthread-1.dll too, this make me think that the thread model used by mingw-w64 by default on archlinux is not the same as yours, maybe thats the cause. Also the gcc version:

$ x86_64-w64-mingw32-g++ --version
x86_64-w64-mingw32-g++ (GCC) 6.3.1 20170109

**Comment by alk** [comment]
thread model: posix I think is a potential problem. Interestingly, on debian there are two sets of mingw compilers one with win32 and another with posix. I'll see if I can do something quickly about that.

**Comment by alk** [comment]
Yes, mingw with pthreads as a c++11 threading option is a problem. We currently cause tcmalloc to use that pthread for stuff such as pthread_key_{create,get,set,delete} (instead of tiny implementations on top of win32 api). And that stuff apparently doesn't work when used early or perhaps it depends on malloc in a way that we cannot support. I am not sure how to even debug that.

Ideally, we won't be using pthread even if mingw supports it. But the issue is we're using types such us pthread_t or pthread_key_t and win32 layer needs to define those types. Which is not possible if mingw insists on it's own definitions.

Right solution I think would be to have custom types perftools_pthread_t and perftools_phread_key_t in addition to existing perftools_XXX functions, so that win32 layer can define those to use native win32 threads without overlapping with mingw types.

If you can contribute that change I'll gladly take it. For now using mingw with win32 c++ threads is the only option that works.
