### ISSUE TITLE
Crash on GHC Haskell compiler - Attempt to free invalid pointer

### ISSUE THREAD

**Issue by xavier83** [gperftools/gperftools#879]
Description:
I am trying to compile https://github.com/Peaker/lamdu using stack and experiencing a crash. related https://github.com/lamdu/lamdu/issues/51

package versions:
* gperftools-2.5
ghc-8.0.2(stack)
* produced the following log.

```
...
[ 7 of 129] Compiling Lamdu.Sugar.Names.NameGen ( Lamdu/Sugar/Names/NameGen.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/lamdu/lamdu-tmp/Lamdu/Sugar/Names/NameGen.o )
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x2862d20

-- While building package Lamdu-0.1 using:
.../.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build lib:Lamdu exe:lamdu --ghc-options " -ddump-hi -ddump-to-file"
Process exited with code: ExitFailure (-6)
```

Steps to reproduce:
compile lamdu on archlinux.

**Comment by zatrazz** [comment]
Did you sort out an issue with lamdu/ghc?

**Comment by xavier83** [comment]
there is a similar _closed_ issue on https://github.com/commercialhaskell/stack/issues/2926 tracking it but since **ghc** being a _compiler_, didn't put the blame on it too soon 😅. If you think it is a downstream issue, please feel free to close it. Thanks.
