### ISSUE TITLE
API/ABI changes review for gperftools

### ISSUE THREAD

**Issue by lvc** [gperftools/gperftools#882]
The review of API/ABI changes for gperftools since 1.10 version: https://abi-laboratory.pro/tracker/timeline/gperftools/

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker. Hope it will be helpful for users and maintainers of the library.

![gperftools-1](https://cloud.githubusercontent.com/assets/1517837/25325331/212ced7c-28dc-11e7-8602-e96b321096e7.png)
![gperftools-2](https://cloud.githubusercontent.com/assets/1517837/25325336/24f58086-28dc-11e7-81ae-941812bc9ecf.png)

## Environment
* Linux x86_64
* GCC 4.9
* gperftools 1.10 and higher

**Comment by alk** [comment]
Thanks a lot!
