### ISSUE TITLE
Windows platform, compilation and runtime issues

### ISSUE THREAD

**Issue by babylon73** [gperftools/gperftools#884]
Hi,

Experimenting under Win10 x64, using Visual Studio 2015 Update 3. Reporting a couple of facts that, may be, can be fixed quickly and easily:

**1.** Last repository state that seems to be more or less functional for Windows is this:
https://github.com/gperftools/gperftools/tree/b0abefd93834d9d9c7ffaae2d23bd48ed8e96477.
**All but two projects can be compiled** (low_level_alloc_unittest and tcmalloc_minimal_unittest-static report unresolved externals (tcmalloc::EnterStacktraceScope() and tcmalloc::LeaveStacktraceScope()), **all unit tests are passed in release, however, nothing works in debug - tcmalloc_minimal_unittest simply crashes in debug).**

**2.** tcmalloc_minimal_unittest can't be compiled since nallocx integration:
tcmalloc_unittest.obj : error LNK2019: unresolved external symbol _memalign referenced in function "void __cdecl testing::TestNAllocXAlignment(void)"

I have stopped on the pre-nallocx integration point that seems to be more or less compilable and functional, however, it would be great to have the stuff solid for all the integration states.

Also, I'm not sure whether crashes in Debug are expected or not... would be nice to have it functional in Debug also.

Thank you.

**Comment by alk** [comment]
Fix for second issue will soon be pushed. As for not working in debug mode, it seems unfixable. I.e. as we found in issue #719, visual studio compiler is now directly adding operator new/operator delete implementations in every module. And we cannot find them and thus cannot patch. So debug implementation adds some extra validation stuff which of course fails.

Which also means that performance is going to be at least slightly screwed as there is extra call for operator new/delete which we're otherwise explicitly trying to avoid.

**Comment by babylon73** [comment]
Hi Aliaksey,

Debug - understood.

NAllocX issue - great, waiting for the fix.

And what about the low_level_alloc_unittest and tcmalloc_minimal_unittest-static projects compilation? Both these projects report unresolved externals (tcmalloc::EnterStacktraceScope() and tcmalloc::LeaveStacktraceScope()) when trying to compile.

Thank you.

**Comment by alk** [comment]
Also fixed. See this branch: https://github.com/alk/gperftools/tree/wip-fast-path-malloc-proposal (but undo last commit, I won't push it)

**Comment by alk** [comment]
Please check 2.6rc release that I just made. Should have all fixed with exception of debug mode issues.

**Comment by volviq** [comment]
Using VS2015 I cannot just right click the solution and expect the build to run through. Instead it seems I need to find out the dependencies myself. Is this adressed in any bug yet?

**Comment by babylon73** [comment]
Preamble patcher, as I understand, is very linux-specific, it is not supposed to be built for Windows.

Dependencies - it's not that hard to prettify the dependencies, IMHO. Other than that it builds pretty smoothly.

**Alk:** Had no chance to try 2.6rc2 out yet, it's on my agenda, will report here as soon as possible.

**Comment by babylon73** [comment]
**Alk: tried 2.6rc2 out, two projects are still non-compilable (regardless fake_stacktrace_scope.cc addition).**

1>------ Build started: Project: low_level_alloc_unittest, Configuration: Unicode Release x64 ------
2>------ Build started: Project: tcmalloc_minimal_unittest-static, Configuration: Unicode Release x64 ------
1>  fake_stacktrace_scope.cc
1>...\gperftools\gperftools-master\src\base/basictypes.h(34): fatal error C1083: Cannot open include file: 'config.h': No such file or directory
2>  fake_stacktrace_scope.cc
2>...\gperftools\gperftools-master\src\base/basictypes.h(34): fatal error C1083: Cannot open include file: 'config.h': No such file or directory
========== Build: 0 succeeded, 2 failed, 19 up-to-date, 0 skipped ==========

**Comment by alk** [comment]
What kind of dependencies you needed to add ? I am not aware of any issues where manually adding dependencies was needed.

**Comment by babylon73** [comment]
Alk

False alarm. Additional include directories are to be specified on per-file (rather than on per-project) basis, so I coild fix the compilation (missing 'config.h').

2.6rc2 seems to work fine, unit tests are passed.

The only remark is these warnings during compilation:
...\src\tcmalloc.cc(1266): warning C4141: 'inline': used more than once (compiling source file ..\..\src\windows\patch_functions.cc)
...\src\tcmalloc.cc(1296): warning C4141: 'inline': used more than once (compiling source file ..\..\src\windows\patch_functions.cc)
...\src\tcmalloc.cc(1305): warning C4141: 'inline': used more than once (compiling source file ..\..\src\windows\patch_functions.cc)
...\src\tcmalloc.cc(1341): warning C4141: 'inline': used more than once (compiling source file ..\..\src\windows\patch_functions.cc)
...\src\tcmalloc.cc(1399): warning C4141: 'inline': used more than once (compiling source file ..\..\src\windows\patch_functions.cc)
...\src\tcmalloc.cc(1434): warning C4141: 'inline': used more than once (compiling source file ..\..\src\windows\patch_functions.cc)
...\src\tcmalloc.cc(1479): warning C4141: 'inline': used more than once (compiling source file ..\..\src\windows\patch_functions.cc)
...\src\tcmalloc.cc(1678): warning C4141: 'inline': used more than once (compiling source file ..\..\src\windows\patch_functions.cc)
...\src\tcmalloc.cc(1717): warning C4141: 'inline': used more than once (compiling source file ..\..\src\windows\patch_functions.cc)

**Comment by alk** [comment]
Works for me for VS2015 community edition and VS2017 community edition.

**Comment by alk** [comment]
And yes those warnings are "expected" even if imperfect a bit. Side effect of ATTRIBUTE_ALWAYS_INLINE
