### ISSUE TITLE
SIZE_MAX not defined on Debian 7 wheezy

### ISSUE THREAD

**Issue by mkj** [gperftools/gperftools#887]
https://github.com/gperftools/gperftools/blob/master/src/sampler.cc#L79 uses SIZE_MAX to define its own MAX_SSIZE, but SIZE_MAX isn't defined in glibc 2.13

It should work fine just using SSIZE_MAX directly, which is defined in POSIX?
http://pubs.opengroup.org/onlinepubs/7908799/xsh/limits.h.html

**Comment by mkj** [comment]
Looking a bit more I think something else is going on.  For reference it's g++ (Debian 4.7.2-5)

Adding -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS as mentioned in https://github.com/google/leveldb/pull/448 seems to fix the build.

**Comment by alk** [comment]
Thanks for reporting it. Yes, indeed, I haven't tested on older GNU/Linux-en. And indeed it fails to compile. I'll fix before 2.6 is out.

**Comment by alk** [comment]
stdint.h is the header that we need.

**Comment by mkj** [comment]
stdint.h is already included via src/sampler.h, but it seems the c99 spec says that c++ should not provide contents of stdint.h without `-D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS` 


https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52764#c1 is the gcc bug, fixed in 4.8.

A comment from llvm (not what I'm using, but informative): 
https://llvm.org/svn/llvm-project/cfe/trunk/lib/Headers/stdint.h
```
// C99 7.18.3 Limits of other integer types
//
//  Footnote 219, 220: C++ implementations should define these macros only when
//  __STDC_LIMIT_MACROS is defined before <stdint.h> is included.
//
//  Footnote 222: C++ implementations should define these macros only when
//  __STDC_CONSTANT_MACROS is defined before <stdint.h> is included.
```

**Comment by alk** [comment]
Thanks. Yes I found it too after posting my last comment. Will fix this Saturday.

**Comment by alk** [comment]
Fixed now. And I am creating tar.gz for 2.6rc3. Thanks again for finding and reporting it.
