### ISSUE TITLE
Heapcheck missing symbols (cannot find pprof)

### ISSUE THREAD

**Issue by fvisin** [gperftools/gperftools#888]
Heapcheck cannot load the symbols and returns this message:
> *** WARNING: Cannot convert addresses to symbols in output below.
> *** Reason: Cannot run 'pprof' (is PPROF_PATH set correctly?)
Note that `pprof` is in the `PATH` and I can run it from the command line.

I am running HEAPCHECK as `LD_PRELOAD="/usr/lib/libtcmalloc.so.4" HEAPCHECK=normal python run.py`, the full resulting log is [here](https://gist.github.com/fvisin/5bdee9bbb1a2d99540a9a0c5c02cf4df).

I tried setting `PPROF_PATH` to the path to the directory that contains pprof and the path to pprof itself with no success. I also tried to set `PPROF_BINARY_PATH`. What is the intended setting for these two environment variables? How can I make sure heapcheck finds the symbols?

Finally, can you explain what is the meaning of this warning and how to make sure heapcheck is working correctly?
> Have memory regions w/o callers: might report false leaks

**Comment by alk** [comment]
PPROF_PATH should point to pprof binary. if it doesn't work, check that pprof --help gives you anything. Also consider testing pprof binary from github.com/google/pprof as perl pprof bundled with gperftools is strongly deprecated.

**Comment by fvisin** [comment]
I confirm that `pprof --help` worked correctly. Also, I was using perl pprof because strangely the one in github.com/google/pprof was not able to read the profile files when run manually as suggested in the error message. 

I solved my bug in the meanwhile and I do not have an easy way to revert the code and investigate the issue with heapcheck at the moment, so I will close the issue for now. Thank you for your answer!

**Comment by slippedtisk** [comment]
Hi - I'm having this issue now running the heap checker against MariaDB on CentOS 7.7.1908 with a fresh install of gperftools 2.6.1-1. pprof is in the path, in /usr/bin/pprof, and runs correctly, and I have tried setting PPROF_PATH to both "/usr/bin/" and "/usr/bin/pprof" in the service definition with the same result:

```
Sep  9 14:02:01 MariaDB-10-4-13-G0-C-163 sh: The 4 largest leaks:
Sep  9 14:02:01 MariaDB-10-4-13-G0-C-163 sh: *** WARNING: Cannot convert addresses to symbols in output below.
Sep  9 14:02:01 MariaDB-10-4-13-G0-C-163 sh: *** Reason: Cannot find 'pprof' (is PPROF_PATH set correctly?)
Sep  9 14:02:01 MariaDB-10-4-13-G0-C-163 sh: *** If you cannot fix this, try running pprof directly.
Sep  9 14:02:01 MariaDB-10-4-13-G0-C-163 sh: Leak of 32 bytes in 1 objects allocated from:

```
