### ISSUE TITLE
[suggestion] Add more internal page size values

### ISSUE THREAD

**Issue by yurivict** [gperftools/gperftools#900]
I observed that for a very large app the top memory consumption went down ~5% when --with-tcmalloc-pagesize=64 was set.

Maybe it makes sense to add more values, like 128 kB, 256 kB, so that users can try and see for themselves if this benefits them? This should be a very simple change anyway.

**Comment by alk** [comment]
Yes, if you can contribute that, it would be great.

**Comment by yurivict** [comment]
https://github.com/gperftools/gperftools/pull/906

**Comment by alk** [comment]
fixed now
