### ISSUE TITLE
madvise(ADV_FREE) isn't called in a large allocation situation

### ISSUE THREAD

**Issue by yurivict** [gperftools/gperftools#903]
My program allocates 12GB in 4kB blocks. Then it releases all of them.
Memory use returned through the pertools interface drops, but madvise is not called on that large memory.
Repeating allocation/deallocation cycle shows the same behavior.

madvise is called on some smaller blocks in the beginning, just not on the large blocks.
As a result, OS thinks that all this memory is in use and other programs may fail with out-of-memory problem.

perftools-2.5.93
FreeBSD 11

testcase.c: I watch madvice calls through the DTrace probe and only see small ones. It doesn't call madvise on the whole 10GB.

```
#include <string.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>

#define SZ_BLK 4500
#define NUM_BLK 2500000

main() {
  void **pp = malloc(NUM_BLK*sizeof(void*));
  int i;
  for (;;) {
    printf("allocating ...\n");
    for (i = 0; i < NUM_BLK; i++) {
      pp[i] = malloc(SZ_BLK);
      memset(pp[i], 1, SZ_BLK);
    }
    printf("done allocating\n");
    printf("freeing ...\n");
    for (i = 0; i < NUM_BLK; i++) {
      free(pp[i]);
    }
    printf("done freeing\n");
  }
  free(pp);
}
```

Several cycles worth of allocations/deallocations only called madvise on these small blocks (arg1=size):
```
  7  69746                    madvise:entry uid= 1001 gid= 1001 pid=41788 execname=mem-perftools arg0=0x6fd90000 arg1=0x12000 arg2=0x5
  7  69746                    madvise:entry uid= 1001 gid= 1001 pid=41788 execname=mem-perftools arg0=0x180816000 arg1=0x9de000 arg2=0x5

  4  69746                    madvise:entry uid= 1001 gid= 1001 pid=41788 execname=mem-perftools arg0=0x6fd78000 arg1=0x12000 arg2=0x5
  4  69746                    madvise:entry uid= 1001 gid= 1001 pid=41788 execname=mem-perftools arg0=0x100816000 arg1=0x9ea000 arg2=0x5
  4  69746                    madvise:entry uid= 1001 gid= 1001 pid=41788 execname=mem-perftools arg0=0x4a9ce000 arg1=0x6000 arg2=0x5
  4  69746                    madvise:entry uid= 1001 gid= 1001 pid=41788 execname=mem-perftools arg0=0x280816000 arg1=0x16fe000 arg2=0x5

  5  69746                    madvise:entry uid= 1001 gid= 1001 pid=41788 execname=mem-perftools arg0=0x2e1004000 arg1=0x12000 arg2=0x5
  5  69746                    madvise:entry uid= 1001 gid= 1001 pid=41788 execname=mem-perftools arg0=0x180816000 arg1=0x9e4000 arg2=0x5

  1  69746                    madvise:entry uid= 1001 gid= 1001 pid=41788 execname=mem-perftools arg0=0xf3afc000 arg1=0xc000 arg2=0x5
  1  69746                    madvise:entry uid= 1001 gid= 1001 pid=41788 execname=mem-perftools arg0=0x2e1004000 arg1=0x12000 arg2=0x5
  1  69746                    madvise:entry uid= 1001 gid= 1001 pid=41788 execname=mem-perftools arg0=0x100816000 arg1=0x9ea000 arg2=0x5
```

And in my real-world app that allocates 12GB madvise isn't called at all during alloc/dealloc cycles.

**Comment by alk** [comment]
I am not sure if something is broken here. This could be "normal" memory releasing heuristics at work. Some applications benefit from more aggressive freeing, some get penalized by that. In 2.6 we've disabled aggressive freeing that was enabled by default before. This is because some higher-profile apps (some tensorflow benchmarks) got substantially slower with aggressive decommit.

There are two way you can tune tcmalloc in this case. First is setting higher value of TCMALLOC_RELEASE_RATE environment variable. Second is re-enabling aggressive decommit via TCMALLOC_AGGRESSIVE_DECOMMIT

If you have some specific reasons to believe that you're facing some bug, please provide test program.

**Comment by yurivict** [comment]
Aliaksey, thank you for your explanation.

Actually, ```MallocExtension::instance()->ReleaseFreeMemory();``` does decommit memory on demand. Plus there are TCMALLOC_RELEASE_RATE and TCMALLOC_AGGRESSIVE_DECOMMIT as you mentioned.
