### ISSUE TITLE
heap profile is empty even though I use HeapProfileStart() and GetHeapProfile() to get full info

### ISSUE THREAD

**Issue by tanglianggithub** [gperftools/gperftools#916]
I do it for 30 seconds using HeapProfileStart() and GetHeapProfile() 
no heap profile info found.

![image](https://user-images.githubusercontent.com/3445470/29199328-6f6d9598-7e7e-11e7-8fcb-d22f7bae4168.png)

os: centos6.2

output info:
https://docs.google.com/document/d/1MKgYYD4HDhAj03Fl4TzKyLqgsKTImN3ki-A9rSxn_uE/edit?usp=sharing

set PERFTOOLS_VERBOSE=99 and gperftools output:

![image](https://user-images.githubusercontent.com/3445470/29256738-399fd8fa-80df-11e7-875d-b693f2c65cbd.png)

press cntl + c, output:
![image](https://user-images.githubusercontent.com/3445470/29257532-72be84aa-80e5-11e7-87d5-58f31e3cd498.png)

**Comment by alk** [comment]
We'll need small test program to figure this out.

**Comment by tanglianggithub** [comment]
LD_PRELOAD  works, but link tcmalloc failed.
output as follows:

**env PERFTOOLS_VERBOSE=99 LD_PRELOAD=./lib/libtcmalloc.so.4 TCMALLOC_STACKTRACE_METHOD_VERBOSE=true ./bin/server start**
Chosen stacktrace method is libgcc
Supported methods:
* libgcc
* x86

<GoogleModuleObject> constructing: atomicops_x86
<GoogleModuleObject> constructing: libpthread_initialized_setter
RemoveNewHook(0x7f220709f3b0)
RemovePreMmapHook(0x7f220709e9f0)
RemovePreSbrkHook(0x7f220709edc0)
<GoogleModuleObject> constructing: heapprofiler
<GoogleModuleObject> constructing: malloc_extension_init
<GoogleModuleObject> constructing: memfs_malloc
<GoogleModuleObject> constructing: init_start
<GoogleModuleObject> constructing: init_start
Chosen stacktrace method is libgcc
Supported methods:
* libgcc
* x86

<GoogleModuleObject> constructing: atomicops_x86
<GoogleModuleObject> constructing: libpthread_initialized_setter
RemoveNewHook(0x7f71e02103b0)
RemovePreMmapHook(0x7f71e020f9f0)
RemovePreSbrkHook(0x7f71e020fdc0)
<GoogleModuleObject> constructing: heapprofiler
<GoogleModuleObject> constructing: malloc_extension_init
<GoogleModuleObject> constructing: memfs_malloc
<GoogleModuleObject> constructing: init_start
<GoogleModuleObject> constructing: init_start
<GoogleModuleObject> destroying: init_start
<GoogleModuleObject> destroying: init_start
<GoogleModuleObject> destroying: memfs_malloc
<GoogleModuleObject> destroying: malloc_extension_init
<GoogleModuleObject> destroying: heapprofiler
<GoogleModuleObject> destroying: libpthread_initialized_setter
<GoogleModuleObject> destroying: atomicops_x86
<GoogleModuleObject> destroying: stacktrace_init_default_stack_impl
<GoogleModuleObject> destroying: init_start
<GoogleModuleObject> destroying: init_start
<GoogleModuleObject> destroying: memfs_malloc
<GoogleModuleObject> destroying: malloc_extension_init
<GoogleModuleObject> destroying: heapprofiler
<GoogleModuleObject> destroying: libpthread_initialized_setter
<GoogleModuleObject> destroying: atomicops_x86
<GoogleModuleObject> destroying: stacktrace_init_default_stack_impl
Chosen stacktrace method is libgcc
Supported methods:
* libgcc
* x86

<GoogleModuleObject> constructing: atomicops_x86
<GoogleModuleObject> constructing: libpthread_initialized_setter
RemoveNewHook(0x7faa364e23b0)
RemovePreMmapHook(0x7faa364e19f0)
RemovePreSbrkHook(0x7faa364e1dc0)
<GoogleModuleObject> constructing: heapprofiler
<GoogleModuleObject> constructing: malloc_extension_init
<GoogleModuleObject> constructing: memfs_malloc
<GoogleModuleObject> constructing: init_start
<GoogleModuleObject> constructing: init_start
Chosen stacktrace method is libgcc
Supported methods:
* libgcc
* x86

<GoogleModuleObject> constructing: atomicops_x86
<GoogleModuleObject> constructing: libpthread_initialized_setter
RemoveNewHook(0x7fec35c323b0)
RemovePreMmapHook(0x7fec35c319f0)
RemovePreSbrkHook(0x7fec35c31dc0)
<GoogleModuleObject> constructing: heapprofiler
<GoogleModuleObject> constructing: malloc_extension_init
<GoogleModuleObject> constructing: memfs_malloc
<GoogleModuleObject> constructing: init_start
<GoogleModuleObject> constructing: init_start
Chosen stacktrace method is libgcc
Supported methods:
* libgcc
* x86

<GoogleModuleObject> constructing: atomicops_x86
<GoogleModuleObject> constructing: libpthread_initialized_setter
RemoveNewHook(0x7fbb5250e3b0)
RemovePreMmapHook(0x7fbb5250d9f0)
RemovePreSbrkHook(0x7fbb5250ddc0)
<GoogleModuleObject> constructing: heapprofiler
<GoogleModuleObject> constructing: malloc_extension_init
<GoogleModuleObject> constructing: memfs_malloc
<GoogleModuleObject> constructing: init_start
<GoogleModuleObject> constructing: init_start
<GoogleModuleObject> constructing: atomicops_x86
<GoogleModuleObject> constructing: stacktrace_init_default_stack_impl
Chosen stacktrace method is libunwind
Supported methods:
* libgcc
* libunwind
* x86

<GoogleModuleObject> constructing: profile_main
RemoveNewHook(0x7f002502d3b0)
RemovePreMmapHook(0x7f002502c9f0)
RemovePreSbrkHook(0x7f002502cdc0)
<GoogleModuleObject> constructing: stacktrace_init_default_stack_impl
Chosen stacktrace method is libgcc
Supported methods:
* libgcc
* x86

<GoogleModuleObject> constructing: atomicops_x86
<GoogleModuleObject> constructing: libpthread_initialized_setter
<GoogleModuleObject> constructing: heapprofiler
<GoogleModuleObject> constructing: malloc_extension_init
<GoogleModuleObject> constructing: memfs_malloc
<GoogleModuleObject> constructing: init_start
<GoogleModuleObject> constructing: init_start


**env PERFTOOLS_VERBOSE=99 TCMALLOC_STACKTRACE_METHOD_VERBOSE=true ./bin/server start**
<GoogleModuleObject> constructing: atomicops_x86
<GoogleModuleObject> constructing: stacktrace_init_default_stack_impl
Chosen stacktrace method is libgcc
Supported methods:
* libgcc
* x86

<GoogleModuleObject> constructing: profile_main
<GoogleModuleObject> constructing: stacktrace_init_default_stack_impl
Chosen stacktrace method is libgcc
Supported methods:
* libgcc
* x86

<GoogleModuleObject> constructing: atomicops_x86
<GoogleModuleObject> constructing: libpthread_initialized_setter
RemoveNewHook(0x7fd1647733b0)
RemovePreMmapHook(0x7fd1647729f0)
RemovePreSbrkHook(0x7fd164772dc0)
<GoogleModuleObject> constructing: heapprofiler
<GoogleModuleObject> constructing: malloc_extension_init
<GoogleModuleObject> constructing: memfs_malloc
<GoogleModuleObject> constructing: init_start
<GoogleModuleObject> constructing: init_start

no LD_PREALOAD:
![image](https://user-images.githubusercontent.com/3445470/50535043-2ff7d000-0b80-11e9-86b7-c405cbfb4d1e.png)

has LD_PRELOAD:
![image](https://user-images.githubusercontent.com/3445470/50535059-73ead500-0b80-11e9-97c2-93dc83c67723.png)

**Comment by han-ccc** [comment]
did you slove this problem？seems I met this two，got an empty heap profile. But I havn't try frame pointers, the program is too large.
