### ISSUE TITLE
HEAPCHECK have to be set or program is aborted

### ISSUE THREAD

**Issue by omron93** [gperftools/gperftools#917]
Hi,
when I run program (mongodb) using tcmalloc it requires to have HEAPCHECK variable set.

Otherwise it ends with
```
Can not start so late. You have to enable heap checking with HEAPCHECK=<mode>.
Aborted (core dumped)
```

program starts normally if HEAPCHECK is set to something. Even empty variable works...

Error occurs only on s390x. @alk Where could be a problem please?

Using rpm gperftools-libs-2.6.1-1.fc27.s390x build from http://pkgs.fedoraproject.org/rpms/gperftools/blob/master/f/gperftools.spec#_74

**Comment by omron93** [comment]
It happens only with gperftools 2.6.1. With 2.5 it is working fine.

**Comment by alk** [comment]
This is extremely weird. The code is supposed to disable heap checker few lines above that crash on "regular" setup. It seems possible that perhaps mongodb is setting up HEAPCHECK to something.

Can grab core and print FLAGS_heap_check for me?

Also are you LD_PRELOAD-ing tcmalloc or is it natively linked to mongodb?

**Comment by omron93** [comment]
>This is extremely weird. The code is supposed to disable heap checker few lines above that crash on "regular" setup. It seems possible that perhaps mongodb is setting up HEAPCHECK to something.

Sorry for my long inactivity. I've returned to this problem today and I can't reproduce it. After rebuild of gperftools (no gperftools change) I can't reproduce this error.
So problem was probably in gcc or some different build tool.

This issue can be closed from my POV.

> Also are you LD_PRELOAD-ing tcmalloc or is it natively linked to mongodb?

MongoDB uses natively linked tcmalloc.
