### ISSUE TITLE
Can't get java stack frame when trace off-heap memory

### ISSUE THREAD

**Issue by louxiu** [gperftools/gperftools#919]
1. Problem: The java stack frame is missed(run program with `XX:+PreserveFramePointer`) when profile heap, but it can be got using `perf-java-flames`
![pprof_missing](https://user-images.githubusercontent.com/925154/29485338-04e70534-8503-11e7-9a41-7356c9f910f4.png)
The java part is missing in above pprof picture.[original pprof svg file](https://www.dropbox.com/s/mts7raidvtvk69q/204f2e60_leak.new.pprof-test.svg?dl=0), [original heap data file](https://www.dropbox.com/s/kuxun69w0ip1epp/cfdaccce_pprof.0001.new.heap?dl=0)
![perf_keeped](https://user-images.githubusercontent.com/925154/29485343-07d0ce74-8503-11e7-8b5d-f3295243e9fb.png)
The java part is kept in above perf picture.[original perf svg file](https://www.dropbox.com/s/uoxp35mr5b4huuz/4ca716ea_flamegraph-171024.svg?dl=0), [original perf data file](https://www.dropbox.com/s/yf247xa3my5l0qx/224d42c8_perf-171024.data?dl=0)
2. Reproduce: 
`java -XX:+PreserveFramePointer -jar pprof-test.jar`
[The simple maven project](https://www.dropbox.com/s/h0mukr3syb10tuv/pproftest.tar.gz?dl=0)
[The jar file for convient](https://www.dropbox.com/s/ln7ut35me3a2rla/pprof-test.jar?dl=0)

3. Versions: java version "1.8.0_111",  gperftools-2.6.1, libunwind-1.2.1 and lastest pprof (`go get github.com/google/pprof`)
Though I installed and `ldconfig` libunwind, but when `./configure` in gperftools I got `configure: WARNING: No frame pointers and no libunwind. Using experimental backtrace capturing via libgcc. Expect crashy cpu profiler.` So I `--enable-frame-pointer`, then it seems ok.
 4. Env:  `Linux  3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by louxiu** [comment]
@aalexand maybe interested in this.

**Comment by alk** [comment]
The issue is that gperftools format for profiles does not support JIT-ted code. It will be a bit of a major project to support, which is unlikely to happen any time soon.

**Comment by ceeaspb** [comment]
@louxiu if seeing the interpreter frames is needed then likely your best option at the moment for java is the new heap profiler in async-profiler . 

Else tracing with perf/ebpf + uprobe on malloc should capture the full stack but without detail on what is executing in the interpreter frames.

**Comment by louxiu** [comment]
@ceeaspb Thanks, I will check it. ;-)

**Comment by louxiu** [comment]
Hi @alk , have been started to working on this? If you haven't started, I would like to share my work. 😃 

![jit](https://user-images.githubusercontent.com/925154/37555050-7b2b1c3a-2a1c-11e8-8eef-110fde9bd282.png)

**Comment by alk** [comment]
I have not and still do not have any plans. Before you start anything, make sure to target latest format of pprof tools (now separate from gperftools at github.com/google/pprof).

**Comment by louxiu** [comment]
I'm not quite sure that I solved the problem using the right way. I make a [pull request](https://github.com/gperftools/gperftools/pull/966) based on current gperftools pprof. Could you check that first before I start to work on pprof at github.com/google/pprof.

**Comment by alk** [comment]
On high level this change looks plausible. But, yes, I won't be merging it into perl pprof. It really belongs to new golang-based pprof.

**Comment by alk** [comment]
See discussion on the pull request. If this is all about pprof, then it should go to github.com/google/pprof
