### ISSUE TITLE
what's the significance of kBaseClasses of tcmalloc in common.h (want 64byte align)?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [gperftools/gperftools#920]
I'm trying to change the alignment of all malloc calls etc. to always give 32byte (AVX) or 64byte (AVX2) aligned addresses.

Intuitively I see that "kMinAlign" needs to be changed to 32 or 64 byte respectively.

However I see that kBaseClasses changes between the 8byte and 16byte alignment mode.. what should I make it equal to for 32byte or 64byte align?

**Comment by alk** [comment]
I don't see kBaseClasses in the code.

**Comment by devshgraphicsprogramming** [comment]
I'm ever so sorry, I have no idea how I caught that (maybe an old revision).

Anyhow, if I were to use this with AVX, setting malloc's default and minimum alignment to 32byte would be achieved through setting kAlignment and kMinAlign to 32 ?

I'm asking because I'm curious as to the specific behaviour of 'int AlignmentForSize(size_t size)'
as it contains "} else if (size >= 128) {" in the else-if statement chain.
From what I see if I pass 'size' in range [128,256) I will get an alignment of 16 always...

**Comment by alk** [comment]
Yes, you will need to adjust this code as well to ensure alignment >= 32.

But please consider c++17 aligned new feature instead. We've recently added support for it and performance should be on par with regular allocation. You will only need to declare proper alignment for your types and compiler will automagically use aligned new for those.

**Comment by devshgraphicsprogramming** [comment]
Yes, but when my most recent C++ STD lib can only be C++11 I should adjust that code?

**Comment by alk** [comment]
Possibly. But not necessarily. All types that need larger alignment will have size naturally aligned to that alignment too. So your size requests will be 32, 64, 96, etc bytes and those are already aligned to 32 bytes due to implementation details.
