### ISSUE TITLE
2.6.1 build failure use vs2010: 'log2': identifier not found

### ISSUE THREAD

**Issue by RonsonNamek** [gperftools/gperftools#924]
I'm trying to compile libtcmalloc_minimal 2.6.1 in vs2010, but i get the error:(error C3861: 'log2': identifier not found).even through i modified log2(q) into log(q)/log(2.0) in sample.cc and it works, but i don't know whether this make the performance reduced.I view the history of sample.cc and find that before 2.6rc, it use fastlog2 instead.so i'm confused what's the best in vs2010? log(q)/log(2.0) or revert sample.cc to use fastlog2?

**Comment by alk** [comment]
Thanks for report. I am not sure we care much about vs2010 anymore. This code is not performance-sensitive. So your alternative solution will get you somewhere. I will accept the patch if you send it.

**Comment by alk** [comment]
As for today we don't support vs2010 (need c++11). Cleaning this up.
