### ISSUE TITLE
no output is generated after executing the code

### ISSUE THREAD

**Issue by amsword** [gperftools/gperftools#926]
I follow this process to install the gperftools: https://github.com/linux-on-ibm-z/docs/wiki/Building-gperftools on ubuntu 14.04. Then I wrote a small c++ program like this:

```c++
#include <iostream>

int func2() {
    int r = 0;
    for (int j = 0; j < 100090; j++) {
         r +=j;
    }
    return r;
}
int abc_func(int x) {
    double s = 0;
    for (int i = 0; i < 10000; i++) {
        s += func2();
    }
    std::cout << s << "\n";
    return x;
}

int main() {
    ::abc_func(2);
    return 0;
}
```

Then, i built it by
```shell
g++ a.cpp -lprofiler
```
After that, when i run the following, it does not generate any output file, named prof.out.
```shell
CPUPROFILE=prof.out ./a.out
```

Is there anything I can check to debug why the output file of prof.out is not generated? 

When I type pprof, it outputs help information. Meanwhile, the file of libprofiler.so, libprofiler.so.0,   libprofiler.so.0.4.14 are also under /usr/bin/. So i thought the tool should be correctly installed.

**Comment by dashesy** [comment]
Try with this:

    LD_PRELOAD=/usr/lib/libprofiler.so CPUPROFILE=prof.out ./a.out

**Comment by amsword** [comment]
It works. Thanks Ehsan.

**Comment by alk** [comment]
Yes, linking libprofiler is not enough. You need to set CPUPROFILE for it to work.

**Comment by cirosantilli** [comment]
Or you can build with `-Wl,--no-as-needed,-lprofiler,--as-needed`, see also: https://stackoverflow.com/questions/46949407/gperftools-profile-file-not-dumped#comment81826459_47022660

**Comment by themightyoarfish** [comment]
I can only get output if i add the `LD_PRELOAD` trick, but that should not be required, should it? Just linking `-lprofiler` and setting `CPUPROFILE` does nothing for me.
