### ISSUE TITLE
Huge performance degradation in tcmalloc when disabling c++11 ABI

### ISSUE THREAD

**Issue by rsmantini** [gperftools/gperftools#933]
Hi,
I've compiled gperftools-2.6.1 with gcc 6.3.0 disabling c++11 ABI "CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0" and saw a performance degradation of around 40% in my application comparing with gperftools-2.0. 
If I do not disable the ABI the newer version is around 5% faster.
Is this expected? 
Is it safe to use tcmalloc compiled with c++11 ABI if my program is compiled without it?
Thanks,
Mantini

**Comment by alk** [comment]
I think the issue is that when you override CXXFLAGS this way, you also remove -O2 optimization flag. There should be no difference of performance at all w.r.t this define.
