### ISSUE TITLE
pprof can't translate function address to name-line when executable is stripped?

### ISSUE THREAD

**Issue by jianpanlanyue** [gperftools/gperftools#934]
As we know, in Linux, executable  will usally be stripped into a "stripped-exe" and a "debug-symbol" file when issued. Then if we need to debug it after it's issued, we should firstly install the "debug-symbol" rpm, then go on , like gdb does.

  But, with pprof, when i have already installed the "debug-symbol" file, pprof can't use it to translate function address into function name. ("pprof  stripped-exe  heap.profile"  or  "pprof  --add_lib=debug-symbol  stripped-exe  heap.profile" bothly can not show function name and line...). 

  Actually, after debug-symbol installed, command "gdb stripped-exe" can work well and read the symbol correctly,  so how can pprof find and use the "debug-symbol" when a debug-version-executable is splitted?

**Comment by alk** [comment]
Please forward this to github.com/google/pprof. Perl version of pprof we still have in gperftools is deprecated.
