### ISSUE TITLE
dead lock caused by tcmalloc

### ISSUE THREAD

**Issue by linxiaocong** [gperftools/gperftools#941]
[root@split-05 /data/home/willkozheng]# gstack 23557
Thread 9 (Thread 0x7f4b4f14e700 (LWP 23558)):
#0  0x0000000000b54d4b in sys_futex (v3=0, a2=0x0, t=0x7f4b4a75bb00, v=2, o=128, a=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>) at ./src/base/linux_syscall_support.h:2461
#1  base::internal::SpinLockDelay (w=w@entry=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>, value=2, loop=loop@entry=37583) at ./src/base/spinlock_linux-inl.h:84
#2  0x0000000000b54c6f in SpinLock::SlowLock (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>) at src/base/spinlock.cc:119
#3  0x0000000000b4d21a in Lock (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>) at src/base/spinlock.h:71
#4  tcmalloc::CentralFreeList::RemoveRange (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>, start=start@entry=0x7f4b4a75bbd0, end=end@entry=0x7f4b4a75bbd8, N=154) at src/central_freelist.cc:248
#5  0x0000000000b53ec3 in tcmalloc::ThreadCache::FetchFromCentralCache (this=this@entry=0xbfa51c0, cl=cl@entry=3, byte_size=byte_size@entry=32) at src/thread_cache.cc:126
#6  0x0000000000b65423 in Allocate (cl=3, size=32, this=0xbfa51c0) at src/thread_cache.h:362
#7  do_malloc_small (size=<optimized out>, heap=0xbfa51c0) at src/tcmalloc.cc:1259
#8  do_malloc (size=size@entry=32) at src/tcmalloc.cc:1266
#9  cpp_alloc (nothrow=false, size=size@entry=32) at src/tcmalloc.cc:1604
#10 tc_new (size=size@entry=32) at src/tcmalloc.cc:1740

Thread 8 (Thread 0x7f4b4f94f700 (LWP 23559)):
#0  0x0000000000b54d4b in sys_futex (v3=0, a2=0x0, t=0x7f4b4a77dab0, v=2, o=128, a=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>) at ./src/base/linux_syscall_support.h:2461
#1  base::internal::SpinLockDelay (w=w@entry=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>, value=2, loop=loop@entry=37612) at ./src/base/spinlock_linux-inl.h:84
#2  0x0000000000b54c6f in SpinLock::SlowLock (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>) at src/base/spinlock.cc:119
#3  0x0000000000b4d21a in Lock (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>) at src/base/spinlock.h:71
#4  tcmalloc::CentralFreeList::RemoveRange (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>, start=start@entry=0x7f4b4a77db80, end=end@entry=0x7f4b4a77db88, N=225) at src/central_freelist.cc:248
#5  0x0000000000b53ec3 in tcmalloc::ThreadCache::FetchFromCentralCache (this=this@entry=0xbfa4940, cl=cl@entry=3, byte_size=byte_size@entry=32) at src/thread_cache.cc:126
#6  0x0000000000b65423 in Allocate (cl=3, size=32, this=0xbfa4940) at src/thread_cache.h:362
#7  do_malloc_small (size=<optimized out>, heap=0xbfa4940) at src/tcmalloc.cc:1259
#8  do_malloc (size=size@entry=32) at src/tcmalloc.cc:1266
#9  cpp_alloc (nothrow=false, size=size@entry=32) at src/tcmalloc.cc:1604
#10 tc_new (size=size@entry=32) at src/tcmalloc.cc:1740
#11 0x0000000000806c62 in allocate (this=<optimized out>, __n=2) at /usr/include/c++/4.8.2/ext/new_allocator.h:104
#12 _M_allocate (this=<optimized out>, __n=2) at /usr/include/c++/4.8.2/bits/stl_vector.h:168
#13 _M_allocate_and_copy<std::move_iterator<net::QuicFrame*> > (this=<optimized out>, __last=..., __first=..., __n=2) at /usr/include/c++/4.8.2/bits/stl_vector.h:1138
#14 reserve (__n=2, this=0x1de2e830) at /usr/include/c++/4.8.2/bits/vector.tcc:75

Thread 7 (Thread 0x7f4b4e94d700 (LWP 23560)):
#0  0x0000000000b54d4b in sys_futex (v3=0, a2=0x0, t=0x7f4b4a7189c0, v=2, o=128, a=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>) at ./src/base/linux_syscall_support.h:2461
#1  base::internal::SpinLockDelay (w=w@entry=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>, value=2, loop=loop@entry=37505) at ./src/base/spinlock_linux-inl.h:84
#2  0x0000000000b54c6f in SpinLock::SlowLock (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>) at src/base/spinlock.cc:119
#3  0x0000000000b4d21a in Lock (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>) at src/base/spinlock.h:71
#4  tcmalloc::CentralFreeList::RemoveRange (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>, start=start@entry=0x7f4b4a718a90, end=end@entry=0x7f4b4a718a98, N=148) at src/central_freelist.cc:248
#5  0x0000000000b53ec3 in tcmalloc::ThreadCache::FetchFromCentralCache (this=this@entry=0xbfa5a40, cl=cl@entry=3, byte_size=byte_size@entry=32) at src/thread_cache.cc:126
#6  0x0000000000b65423 in Allocate (cl=3, size=32, this=0xbfa5a40) at src/thread_cache.h:362
#7  do_malloc_small (size=<optimized out>, heap=0xbfa5a40) at src/tcmalloc.cc:1259
#8  do_malloc (size=29) at src/tcmalloc.cc:1266
#9  cpp_alloc (nothrow=false, size=29) at src/tcmalloc.cc:1604
#10 tc_new (size=29) at src/tcmalloc.cc:1740

**Comment by linxiaocong** [comment]
Hi, we found that there may be dead lock issue inside tcmalloc. Please have a check, thx!

**Comment by alk** [comment]
Thanks for report. We need a lot more information to diagnose this further.

What version of tcmalloc is that?

Also what makes you think it is deadlock? (We've had a case where very slow performance was mis-reported as deadlock).

Your initial posting had stacks of 2 processes. Does it mean there is some fork involved?

**Comment by alk** [comment]
Aha, found this:

Thread 6 (Thread 0x7f4b4e14c700 (LWP 23561)): 
#0 0x0000000000b54d4b in sys_futex (v3=0, a2=0x0, t=0x7f4b44a6bf70, v=2, o=128, a=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>) at ./src/base/linux_syscall_support.h:2461 
#1 base::internal::SpinLockDelay (w=w@entry=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>, value=2, loop=loop@entry=38229) at ./src/base/spinlock_linux-inl.h:84 
#2 0x0000000000b54c6f in SpinLock::SlowLock (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>) at src/base/spinlock.cc:119 
#3 0x0000000000b4d21a in Lock (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>) at src/base/spinlock.h:71 
#4 tcmalloc::CentralFreeList::RemoveRange (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>, start=start@entry=0x7f4b44a6c040, end=end@entry=0x7f4b44a6c048, N=209) at src/central_freelist.cc:248 
#5 0x0000000000b53ec3 in tcmalloc::ThreadCache::FetchFromCentralCache (this=this@entry=0xbfa62c0, cl=cl@entry=3, byte_size=byte_size@entry=32) at src/thread_cache.cc:126 
#6 0x0000000000b65423 in Allocate (cl=3, size=32, this=0xbfa62c0) at src/thread_cache.h:362 
#7 do_malloc_small (size=<optimized out>, heap=0xbfa62c0) at src/tcmalloc.cc:1259 
#8 do_malloc (size=27) at src/tcmalloc.cc:1266 
#9 cpp_alloc (nothrow=false, size=27) at src/tcmalloc.cc:1604 
#10 tc_new (size=27) at src/tcmalloc.cc:1740 
#11 0x00007f4b51cc4c69 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) () from /lib64/libstdc++.so.6 
#12 0x0000000000650713 in _S_construct<char*> (__a=..., __end=<optimized out>, __beg=0x7f4b44a6c0d0 "11") at /usr/include/c++/4.8.2/bits/basic_string.tcc:138 
#13 _S_construct_aux<char*> (__a=..., __end=<optimized out>, __beg=0x7f4b44a6c0d0 "11") at /usr/include/c++/4.8.2/bits/basic_string.h:1725 
#14 _S_construct<char*> (__a=..., __end=<optimized out>, __beg=0x7f4b44a6c0d0 "11") at /usr/include/c++/4.8.2/bits/basic_string.h:1746 
#15 basic_string<char*> (__a=..., __end=<optimized out>, __beg=0x7f4b44a6c0d0 "11", this=0x7f4b44a6c240) at /usr/include/c++/4.8.2/bits/basic_string.tcc:229 
#16 __gnu_cxx::__to_xstring<std::string, char> (__convf=<optimized out>, __n=__n@entry=16, __fmt=__fmt@entry=0xbd6168 "%d") at /usr/include/c++/4.8.2/ext/string_conversions.h:99 
#17 0x00000000007845bf in to_string (__val=11) at /usr/include/c++/4.8.2/bits/basic_string.h:2866 
#18 handle_sig (signo=11) at /data/charlielin/GBN_proj/branches/node/main.cpp:124 
#19 <signal handler called> 
#20 tcmalloc::CentralFreeList::FetchFromOneSpans (this=this@entry=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>, N=N@entry=209, start=start@entry=0x7f4b44a6cbe0, end=end@entry=0x7f4b44a6cbe8) at src/central_freelist.cc:301 
#21 0x0000000000b4d0ca in tcmalloc::CentralFreeList::FetchFromOneSpansSafe (this=this@entry=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>, N=N@entry=209, start=start@entry=0x7f4b44a6cbe0, end=0x7f4b44a6cbe8) at src/central_freelist.cc:282 
#22 0x0000000000b4d16f in tcmalloc::CentralFreeList::RemoveRange (this=0x9eac3c0 <tcmalloc::Static::central_cache_+3648>, start=start@entry=0x7f4b44a6cbe0, end=end@entry=0x7f4b44a6cbe8, N=209) at src/central_freelist.cc:264 
#23 0x0000000000b53ec3 in tcmalloc::ThreadCache::FetchFromCentralCache (this=this@entry=0xbfa62c0, cl=cl@entry=3, byte_size=byte_size@entry=32) at src/thread_cache.cc:126 
#24 0x0000000000b65423 in Allocate (cl=3, size=32, this=0xbfa62c0) at src/thread_cache.h:362 
#25 do_malloc_small (size=<optimized out>, heap=0xbfa62c0) at src/tcmalloc.cc:1259 
#26 do_malloc (size=29) at src/tcmalloc.cc:1266 
#27 cpp_alloc (nothrow=false, size=29) at src/tcmalloc.cc:1604 
#28 tc_new (size=29) at src/tcmalloc.cc:1740 
#29 0x00007f4b51cc4c69 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) () from /lib64/libstdc++.so.6 
#30 0x00007f4b51cc6521 in char* std::string::_S_construct<char const*>(char const*, char const*, std::allocator<char> const&, std::forward_iterator_tag) () from /lib64/libstdc++.so.6 
#31 0x00007f4b51cc65dd in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned long, std::allocator<char> const&) () from /lib64/libstdc++.so.6 
#32 0x00000000007e5d42 in SetValue<unsigned int> (v=@0x7f4b44a6cfb8: 0, tag=1414812233, this=0x7f4b44a6ce30) at /data/willkozheng/GBN_proj/branches/lib_node_quic/proto-quic/src/net/../net/quic/core/crypto/crypto_handshake_message.h:46 
#33 net::QuicFixedUint32::ToHandshakeMessage (this=this@entry=0x1d6181b0, out=out@entry=0x7f4b44a6ce30) at /data/willkozheng/GBN_proj/branches/lib_node_quic/proto-quic/src/net/quic/core/quic_config.cc:156 
#34 0x00000000007e642f in ToHandshakeMessage (out=0x7f4b44a6ce30, this=0x1d6181b0) at /data/willkozheng/GBN_proj/branches/lib_node_quic/proto-quic/src/net/quic/core/quic_config.cc:622 
#35 net::QuicConfig::ToHandshakeMessage (this=0x1d618048, out=out@entry=0x7f4b44a6ce30) at /data/willkozheng/GBN_proj/branches/lib_node_quic/proto-quic/src/net/quic/core/quic_config.cc:622 
#36 0x00000000007f6b36 in net::QuicCryptoClientStream::DoSendCHLO (this=this@entry=0x1c205200, cached=cached@entry=0x21360be0) at /data/willkozheng/GBN_proj/branches/lib_node_quic/proto-quic/src/net/quic/core/quic_crypto_client_stream.cc:294 
#37 0x00000000007f77c3 in net::QuicCryptoClientStream::DoHandshakeLoop (this=this@entry=0x1c205200, in=in@entry=0x0) at /data/willkozheng/GBN_proj/branches/lib_node_quic/proto-quic/src/net/quic/core/quic_crypto_client_stream.cc:209 
#38 0x00000000007f79c5 in net::QuicCryptoClientStream::CryptoConnect (this=0x1c205200) at /data/willkozheng/GBN_proj/branches/lib_node_quic/proto-quic/src/net/quic/core/quic_crypto_client_stream.cc:148 
#39 0x00000000007c8ce4 in GBN::NodeQuicClientSession::CryptoConnect (this=0x1d618000) at /data/willkozheng/GBN_proj/branches/lib_node_quic/node_quic_client_session.cpp:82 
#40 0x00000000007c66c4 in GBN::NodeQuicClient::StartConnect (this=this@entry=0x1d5f6518) at /data/willkozheng/GBN_proj/branches/lib_node_quic/node_quic_client.cpp:204 
#41 0x00000000007c7e06 in GBN::NodeQuicClient::Connect (this=0x1d5f6518) at /data/willkozheng/GBN_proj/branches/lib_node_quic/node_quic_client.cpp:368 
#42 0x0000000000759b61 in GBN::InterconnectionSharePipeClient::Initializ (this=this@entry=0x1e3468a0) at /data/charlielin/GBN_proj/branches/node/interconnection_share_pipe_client.cpp:244 
#43 0x000000000075fe5d in GBN::service_routine (para=0x1e3468a0) at /data/charlielin/GBN_proj/branches/node/interconnection_share_pipe_client_handler_interface.cpp:93 
#44 0x0000000000b17a6d in std::function<void* (void*)>::operator()(void*) const (this=this@entry=0x1b35e910, __args
#0=0x1e3468a0) at /usr/include/c++/4.8.2/functional:2471 
#45 0x0000000000b1772d in CoRoutiner::Run (this=this@entry=0x1b35e900) at co_routine_pool.cpp:56 
#46 0x0000000000b179b0 in CoRoutinePoolRoutineFn (arg=0x1b35e900) at co_routine_pool.cpp:11 
#47 0x0000000000b143c3 in CoRoutineFunc (co=0x1d60c400) at co_routine.cpp:440 
#48 0x0000000000000000 in ?? ()

Your program is doing non-signal-safe calls while inside signal handler. What specifically happens where is you're getting signal while inside malloc holding lock. Then your signal handler calls malloc again and tries to get same lock which is of course taken and you get deadlock.

So this is your own bug and not malloc's.

**Comment by linxiaocong** [comment]
Got it! Thanks very much for your reply!
