### ISSUE TITLE
stacktrace.h and -lprofiler fails on OS X

### ISSUE THREAD

**Issue by krlmlr** [gperftools/gperftools#948]
I'm using functions from `<gperftools/stacktrace.h>` (and `"getpc.h"`) to regularly capture stack traces myself. I currently can't use `ProfilerStart()` and `ProfilerStop()`, because I need not only the frequency of each stack trace, but also the order of appearance (r-prof/gprofiler#18). Using `-lprofiler` seems to be sufficient on Ubuntu, but not on OS X. To reproduce, compile the following `test.cpp` file:

```
// clang test.cpp -lprofiler
// gcc test.cpp -lprofiler
#include <gperftools/stacktrace.h>

int main() {
  GetStackTraceWithContext(0, 0, 0, 0);
  return 0;
}
```

On OS X, I'm [seeing](https://travis-ci.org/r-prof/gprofiler/jobs/321992479#L474-L480):

```
Error: package or namespace load failed for ‘gprofiler’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/Rtmp9E4hvH/Rinst182d22434e6c/gprofiler/libs/gprofiler.so':
  dlopen(/private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/Rtmp9E4hvH/Rinst182d22434e6c/gprofiler/libs/gprofiler.so, 6): Symbol not found: __Z24GetStackTraceWithContextPPviiPKv
  Referenced from: /private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/Rtmp9E4hvH/Rinst182d22434e6c/gprofiler/libs/gprofiler.so
  Expected in: flat namespace
 in /private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/Rtmp9E4hvH/Rinst182d22434e6c/gprofiler/libs/gprofiler.so
```

Compiling with `-ltcmalloc` resolves the issue. I wonder if this is expected. If not, happy to contribute.

On that note, perhaps `GetPC()` could be made available through `-lprofiler`, too? Or perhaps you'd support writing samples directly to file, without aggregation?

**Comment by alk** [comment]
Interesting. Actually I was thinking about dropping this API completely. 

As for why it doesn't work on OSX, have no idea. I am not osx person.

Note that Abseil has some form of this API too (evolved from same original code), but probably also internal and not necessarily well-supported across various platforms.

Why not simply use backtrace() ? It should work in most cases (except if you're calling it from inside malloc or from inside signal handler).

**Comment by krlmlr** [comment]
I'm calling it from a `SIGPROF` handler...

Thanks for pointing me to Abseil, I need to check that out. At the moment I'm comfortable with `-ltcmalloc`, but obviosly not if you decide to make that API private ;-)

To add some context: I'm working on a project that aims at providing unified stack traces for R code that calls into native code. Each stack trace contains R functions when in R, and then seamlessly switches to native functions. R comes with a sampling profiler, I'm daisy-chaining it with gperftools's profiler and combine stack traces when profiling has finished. Initially I thought I could use `ProfilerStart()` with a filter, but I discovered (much too late) that gperftools doesn't write the samples to disk in the order of appearance. I decided to manually collect stack traces and writing to disk, because I wanted this to work with stable versions of gperftools. I borrowed relevant code from gperftools, see [feature branch](https://github.com/r-prof/gprofiler/tree/f-%236-combine)).

Please advise.

**Comment by alk** [comment]
I guess you should consider forking code of out gperftools. I still plan to do major API and ABI cleanup and making gperftools 3.0, but not immediately soon.

I just looked at abseil and they seemingly decided against releasing libunwind-ful stacktrace capturing.

So feel free to depend on gperftools for now, but when we do 3.0, you'll need to fork stacktrace capturing code out of our code. Or maybe by that time abseil will have polished stack trace facility.  It might be worth asking at  abseil-io@googlegroups.com.

If you want to contribute some simple change to libprofiler to support your use-case in interim, I'll take it.

**Comment by krlmlr** [comment]
Thanks for the heads-up.

I looked at the dependencies for the `libgoogle-perftools4` package on my Ubuntu system, it seems that only C/C++ standard libraries are required, and `libunwind`. This is a good thing, I can fork out the code if necessary and only require libunwind.

I'm creating a shared library that is linked with `libtcmalloc` (`-ltcmalloc`) to work around the original issue. Will loading my shared library enable tcmalloc? I haven't found an opt-out seitch in the [documentation](http://gperftools.github.io/gperftools/tcmalloc.html), and the docs also suggest to not enable tcmalloc in a running process. Please advise.

**Comment by krlmlr** [comment]
I'm seeing errors when loading `-ltcmalloc` through a shared library:

```
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x55e5eaabd6f0 
```

I'll submit a PR that adds `GetStackTraceWithContext()` and friends to the list of exported symbols.

**Comment by krlmlr** [comment]
In master now, not tagged yet (https://github.com/gperftools/gperftools/issues/1187).
