### ISSUE TITLE
Using tcmalloc sigbus on x86_64 RHEL 7.4

### ISSUE THREAD

**Issue by ghost** [gperftools/gperftools#949]
Hi,

We faced a random core dump with the below trace on RHEL7.4 OS, x86_64 platform. gperftools-2.4-8.el7.x86_64 is installed on the server. Application is trying to allocate memory using malloc(inside trace_malloc),  getting below stack trace. 

Program terminated with signal 7, Bus error.
#0  0x00007f4b2c40bdfd in tcmalloc::CentralFreeList::FetchFromOneSpans(int, void**, void**) () from /lib64/libtcmalloc.so.4
#1  0x00007f4b2c40c0aa in tcmalloc::CentralFreeList::FetchFromOneSpansSafe(int, void**, void**) () from /lib64/libtcmalloc.so.4
#2  0x00007f4b2c40c15d in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
#3  0x00007f4b2c40f1b5 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned long, unsigned long) () from /lib64/libtcmalloc.so.4
#4  0x00007f4b2c41dc9b in tc_malloc () from /lib64/libtcmalloc.so.4
#5  0x00007f4b225f7f41 in trace_malloc (x=<optimized out>)

**Comment by alk** [comment]
This is almost 100% certainly some bug in your program. Writing into freed memory could corrupt central free list which can then crash inside tcmalloc. Consider running your program under valgrind or asan.
