### ISSUE TITLE
gperftools 2.6.3 build failure at OS X 10.11.6 (El Capitan) with clang-703.0.31 (Apple LLVM version 7.3.0)

### ISSUE THREAD

**Issue by alexeyserbin** [gperftools/gperftools#954]
I hit an issue with building gperftools 2.6.3 at OS X 10.11.6:                  
                                                                                
/bin/sh ./libtool  --tag=CXX   --mode=link g++ -DNO_TCMALLOC_SAMPLES -D_THREAD_SAFE  -DNDEBUG -Wall
-Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation    -g -fno-omit-frame-pointer -O2   -stdlib=libc++ -version-info 9:1:5 -no-undefined  -stdlib=libc++ -o libtcmalloc_minimal.la -rpath /Users/aserbin/Projects/kudu/thirdparty/installed/uninstrumented/lib src/libtcmalloc_minimal_la-tcmalloc.lo    libtcmalloc_minimal_internal.la -lc++ -lc++abi
libtool: link: g++ -dynamiclib  -o .libs/libtcmalloc_minimal.4.dylib  src/.libs/libtcmalloc_minimal_la-tcmalloc.o   -Wl,-force_load,./.libs/libtcmalloc_minimal_internal.a  -lc++ -lc++abi  -g -O2 -stdlib=libc++ -stdlib=libc++   -install_name  /Users/aserbin/Projects/kudu/thirdparty/installed/uninstrumented/lib/libtcmalloc_minimal.4.dylib -compatibility_version 10 -current_version 10.1 -Wl,-single_module
Undefined symbols for architecture x86_64:                                      
  "operator delete(void*, unsigned long)", referenced from:                     
      TCMallocImplementation::~TCMallocImplementation() in libtcmalloc_minimal_la-tcmalloc.o
      SbrkSysAllocator::~SbrkSysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-system-alloc.o)
      MmapSysAllocator::~MmapSysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-system-alloc.o)
      DevMemSysAllocator::~DevMemSysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-system-alloc.o)
      DefaultSysAllocator::~DefaultSysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-system-alloc.o)
      __GLOBAL__sub_I_symbolize.cc in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-symbolize.o)
      SysAllocator::~SysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-malloc_extension.o)

The configure script was run with the following essential flags:
  --enable-frame-pointers
  --enable-heap-checker
  --with-pic

Some information about the system:

$ sw_vers
ProductName:  Mac OS X
ProductVersion: 10.11.6
BuildVersion: 15G1611

$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

While digging in and compiling the test that the configure scripts uses to determine whether -fsized-deallocation is supported by the host compiler, I found some surprises; see below.

test.cc
`#include <new>

int main () {                                                                   
  (::operator delete)(0, 256);
  return 0;
}`

As it turned out, the configure scripts runs the test with '-02' flag, and in my case it produces no errors:

$ c++ -fsized-deallocation -O2 test.cc
$ echo $?
0

Even with -01 it passes:
$ c++ -fsized-deallocation -O1 test.cc
$ echo $?
0

However, if compiled without optimizations and built-in function replacement (actually, either one suffices):

dhcp-10-16-1-175:tmp$ g++ -fsized-deallocation -O0 -fno-builtin test.cc
Undefined symbols for architecture x86_64:
  "operator delete(void*, unsigned long)", referenced from:
      _main in test-c91491.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation) 

$ echo $?                                                                       
1

Also, the AC_COMPILE_IFELSE used by configure.ac for that test, but the error comes from the linkage phase.  Maybe, it's worth replacing it with AC_LINK_IFELSE?

Overall, the zipped patch that un-breaks the build of gperftools-2.6.3 on my laptop is attached.
[gperftools-sized-alloc-build-fix.diff.zip](https://github.com/gperftools/gperftools/files/1683260/gperftools-sized-alloc-build-fix.diff.zip)

**Comment by alk** [comment]
Thanks for report. Very "nice" finding (and not nice for apple screwing us more).

I am a bit reluctant to have -fno-builtin added to flags for testing compiler features. There is chance that we'll be dealing with compiler that doesn't know -fno-builtin but does have features we're testing for.

I like idea of AC_LINK_IFELSE. And we can change test for operator delete to ensure that compiler doesn't optimize it away. I.e. like this:

`
int main () {
  static void (* volatile ptr)(void *, size_t) = ::operator delete;
  (*ptr)(0, 256);
  return 0;
}
`

Can you please try something like that on your system? E.g. https://godbolt.org/g/N6qVGG

**Comment by alexeyserbin** [comment]
Adding -O0 is enough, actually.  I added both -O0 and -fno-builtin 'just in case' while playing with that test.

Yep, the new test works better in my case.  I guess it prevents the compiler from making corresponding optimizations.  The code at https://godbolt.org/g/N6qVGG fails to compile (as expected) for all optimization levels -O{0,1,2,3,s}.  Below is the output for -O0 and -O2, plus the output from 'c++ --version':

$ c++ -fsized-deallocation -O0 test1.cc
Undefined symbols for architecture x86_64:
  "operator delete(void*, unsigned long)", referenced from:
      main::ptr in test1-188497.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

$ c++ -fsized-deallocation -O2 test1.cc
Undefined symbols for architecture x86_64:
  "operator delete(void*, unsigned long)", referenced from:
      main::ptr in test1-8f1c91.o
ld: symbol(s) not found for architecture x86_64

$ c++ --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by alk** [comment]
Should be fixed. Please let me know if not.
