### ISSUE TITLE
Add warning when profiling position independent executables

### ISSUE THREAD

**Issue by Timmmm** [gperftools/gperftools#955]
On OSX executables are compiled as PIE by default (you can check with `otool -hv <exe>` on OSX). This basically doesn't work at all since all the addresses end up wrong and you just get a load of `<Unknown>`'s.

**Comment by alk** [comment]
Are you 100% sure PIE executables don't work? AFAIK they do. At least on GNU/Linux.

**Comment by Timmmm** [comment]
Actually no, well I think it might not in some cases but it is actually due to [this bug in pprof](https://github.com/google/pprof/issues/311).
