### ISSUE TITLE
Doesn't work if statically linked

### ISSUE THREAD

**Issue by r0bertz** [gperftools/gperftools#961]
Here is what I added to SConstruct:

    if GetOption('tcmalloc'):
      env.Append(CCFLAGS=['-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', '-fno-builtin-free'])
      if should_link_static():
        env.Append(LINKFLAGS=['-Wl,--eh-frame-hdr'])
        env.Append(LIBS=[File('/usr/lib/libtcmalloc_and_profiler.a'),
            File('/usr/lib/x86_64-linux-gnu/libunwind.a'),
            File('/usr/lib/x86_64-linux-gnu/liblzma.a')])
      else:
        env.Append(LIBS=['tcmalloc_and_profiler'])

If dynamically linked, it works. Not if statically linked.

I found this article http://www.awenius.de/blog/2014/10/02/the-tcmalloc-heap-profiler-does-not-work-when-tcmalloc-is-statically-linked/

I called IsHeapProfilerRunning() in main() as suggested in the article. Then it worked.

Did I do anything wrong? Thank you!

**Comment by alk** [comment]
Yes, this is a bit of known issue. Another workaround is using linker's --undefined flag. E.g. something like: -Wl,--undefined=IsHeapProfilerRunning
