### ISSUE TITLE
About Libunwind

### ISSUE THREAD

**Issue by urhue** [gperftools/gperftools#964]
I have a question about libunwind when use cross compiling.
I use debian testing x64 and export host as x86_64-w64-mingw32.
Then a few question about the libunwind appeared in my mind.
Do I need libunwind under this condition? Or the parameter "enable-frame-pointers"?
Should I also compile libunwind with cross compiling?
Anyone who can help me?

**Comment by alk** [comment]
Windows builds use windows-specific api to capture backtraces. So we don't use libunwind on windows.

**Comment by urhue** [comment]
@alk
Is the parameter "enable-frame-pointers" not used on windows, too?

Thanks

**Comment by alk** [comment]
Not used.
