### ISSUE TITLE
Crash in SLL_Next seg fault!

### ISSUE THREAD

**Issue by bkannadassan** [gperftools/gperftools#967]
Hi All! 

   We have a crash in SLL_Next

#0  SLL_Next (t=0x0) at ../src/linked_list.h:45
#1  SLL_PopRange (end=<synthetic pointer>, start=<synthetic pointer>, N=32, head=0x7dcfce0) at ../src/linked_list.h:88
#2  PopRange (end=<synthetic pointer>, start=<synthetic pointer>, N=32, this=0x7dcfce0) at ../src/thread_cache.h:238
#3  tcmalloc::ThreadCache::ReleaseToCentralCache (this=this@entry=0x7dcfc40, src=src@entry=0x7dcfce0, cl=<optimized out>, N=N@entry=32) at ../src/thread_cache.cc:200
#4  0x00000000019d6dfc in tcmalloc::ThreadCache::ListTooLong (this=0x7dcfc40, list=0x7dcfce0, cl=<optimized out>) at ../src/thread_cache.cc:158
#5  0x00000000021f4605 in deallocate (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.8.2/ext/new_allocator.h:110
#6  _M_destroy (__a=..., this=<optimized out>) at /usr/include/c++/4.8.2/bits/basic_string.tcc:449
#7  std::string::_Rep::_M_dispose (this=<optimized out>, __a=...) at /usr/include/c++/4.8.2/bits/basic_string.h:249

Have an interesting observation when printing the cache list from the core.. Instead of +40 its -40 and it ends up crashing trying to pop 42 elements.

List Index 5 <==> Total List Element -40 {Cache 0x7dcfc40}
$4123 = (int *) 0x8b9bac0
$4124 = (int *) 0x8b9bb00
$4125 = (int *) 0x8b9bb40
$4126 = (int *) 0x8b9bb80
$4127 = (int *) 0x8b9bbc0
$4128 = (int *) 0x8b9bc00
$4129 = (int *) 0x8b9bc40
$4130 = (int *) 0x8b9bc80
$4131 = (int *) 0x8b9bcc0
$4132 = (int *) 0x8b9bd00
$4133 = (int *) 0x8b9bd40
$4134 = (int *) 0x8b9bd80
$4135 = (int *) 0x8b9bdc0
$4136 = (int *) 0x8b9be00
$4137 = (int *) 0x8b9be40
$4138 = (int *) 0x8b9be80
$4139 = (int *) 0x8b9bec0
$4140 = (int *) 0x8b9bf00
$4141 = (int *) 0x8b9bf40
$4142 = (int *) 0x8b9bf80
$4143 = (int *) 0x8b9bfc0
$4144 = (int *) 0x0

Please let me know if I am missing something ?. Is this because of app corruption ? It doesn't look like..

rgds
Balaji Kamal Kannadassan

**Comment by alk** [comment]
Double free could cause such kind of underflow.
