### ISSUE TITLE
There is no symbols output for macOS High Sieera!

### ISSUE THREAD

**Issue by wumuzi520** [gperftools/gperftools#968]
* Exe command like this:

HEAP_PROFILE_ALLOCATION_INTERVAL=5120000 HEAPPROFILE=/tmp/heapprof DYLD_INSERT_LIBRARIES="/usr/local/lib/libtcmalloc.dylib:/usr/local/lib/libprofiler.dylib" ./test_tcmalloc

* Output like this:

pprof --lines --text ./test_tcmalloc /tmp/heapprof.0001.heap
Using local file ./test_tcmalloc.
Using local file /tmp/heapprof.0001.heap.
Total: 4.9 MB
     4.9 100.0% 100.0%      4.9 100.0% 0x00007fff60ffa201 ?
     0.0   0.0% 100.0%      4.9  99.9% 0x000000010351fd96 ?
     0.0   0.0% 100.0%      0.0   0.1% 0x00000001035201e9 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x000000010352032b ?
     0.0   0.0% 100.0%      4.9  99.9% 0x0000000103520335 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x00000001035203cc ?
     0.0   0.0% 100.0%      0.0   0.0% 0x0000000103521b72 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x0000000103521b8e ?
     0.0   0.0% 100.0%      0.0   0.0% 0x0000000103521c6f ?
     0.0   0.0% 100.0%      0.0   0.1% 0x0000000103522780 ?
     0.0   0.0% 100.0%      0.0   0.1% 0x0000000103522a20 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x000000010d46c1d1 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x000000010d46c3d3 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x000000010d46d548 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x000000010d472238 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x000000010d47c2a5 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x000000010d47c339 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x000000010d47d16f ?
     0.0   0.0% 100.0%      0.0   0.0% 0x000000010d481a09 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x000000010d481c39 ?
     0.0   0.0% 100.0%      0.0   0.1% 0x00007fff5ee90f27 ?
     0.0   0.0% 100.0%      0.0   0.1% 0x00007fff5ee9cdd9 ?
     0.0   0.0% 100.0%      0.0   0.1% 0x00007fff5ee9d2eb ?
     0.0   0.0% 100.0%      0.0   0.0% 0x00007fff5eec8b24 ?
     0.0   0.0% 100.0%      4.9  99.9% 0x00007fff5eed9627 ?
     0.0   0.0% 100.0%      4.9  99.9% 0x00007fff60e52114 ?
     0.0   0.0% 100.0%      0.0   0.1% 0x00007fff60edf97b ?
     0.0   0.0% 100.0%      0.0   0.1% 0x00007fff60edff59 ?
     0.0   0.0% 100.0%      0.0   0.1% 0x00007fff60ee06bc ?
     0.0   0.0% 100.0%      0.0   0.1% 0x00007fff60ef4373 ?
     0.0   0.0% 100.0%      4.9 100.0% 0x00007fff60ff950a ?
     0.0   0.0% 100.0%      0.0   0.0% 0x00007fff610d2eff ?
     0.0   0.0% 100.0%      0.0   0.1% 0x00007fff610dcc5c ?
     0.0   0.0% 100.0%      0.0   0.1% 0x00007fff610dd56c ?
     0.0   0.0% 100.0%      0.0   0.1% 0x00007fff610dd6c0 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x00007fff610dd958 ?
     0.0   0.0% 100.0%      0.0   0.0% 0x00007fff610dd9bd ?
     0.0   0.0% 100.0%      0.0   0.0% ProfileHandler::Init ?
     0.0   0.0% 100.0%      0.0   0.0% ProfileHandlerGetState ?
     0.0   0.0% 100.0%      4.9  99.9% __mh_execute_header ?

**Comment by alk** [comment]
Report this to github.com/google/pprof. perf pprof shipped in gpertftools is deprecated. I am closing it here.
