### ISSUE TITLE
2.6.90: tcmalloc_debug_unittest failed on i386

### ISSUE THREAD

**Issue by wzssyqa** [gperftools/gperftools#969]
https://buildd.debian.org/status/package.php?p=google-perftools&suite=experimental
https://buildd.debian.org/status/fetch.php?pkg=google-perftools&arch=i386&ver=2.6.90-0.1~exp&stamp=1521635434&raw=0

I upload the new 2.7rc to Debian, and tcmalloc_debug_unittest on i386.

**Comment by alk** [comment]
I think it should be fixed now. Thanks for reporting. Please let me know if it works now.

**Comment by wzssyqa** [comment]
Yes, it has been fixed now. thanks.

It still ftbfs on some not very import architectures:
https://buildd.debian.org/status/package.php?p=google-perftools

If you have interest on them, you can have a look.
